m3db/m3

src/msg/consumer/config.go, src/msg/consumer/consumer.go, src/msg/consumer/options.go, src/msg/consumer/types.go
Without a timeout this can potentially block forever.
The producer and consumer can potentially dead lock trying to send/receive messages:
Producer -> msg -> Consumer. Consumer is not attempting to read since it's trying to ACK.
Consumer -> ack -> Producer. Producer is not attempting to read since it might be stuck trying to get a lock on the connection.
For backwards compatibility this defaults to 0. We should set it to a sane default (5s) in the future.
NONE. timeout is off by default.
```
NONE
```
=> Add a configurable write timeout for consumer ACKs

docs/operational_guide/resource_limits.md, src/cmd/services/m3dbnode/config/config_test.go, src/cmd/services/m3dbnode/config/limits.go
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
=> [documentation] Add documentation for disk read bytes per second limit

src/dbnode/integration/disk_flush_helpers.go, src/dbnode/integration/disk_snapshot_test.go, src/dbnode/integration/fs_commitlog_snapshot_mixed_mode_read_write_prop_test.go, src/dbnode/integration/large_tiles_test.go, src/dbnode/storage/database.go, src/dbnode/storage/shard.go
Both writing empty TSDB snapshots and tracking of empty snapshots on disk is unnecessary. Each snapshot run is tagged w/ a unique UUID and a snapshot run will complete and write the UUID to a metadata file on disk regardless of whether in-mem TSDB data exists or not. The cleanup manager will remove all but the latest snapshot UUID meaning that it will cleanup stale snapshots without the need for writing an empty TSDB snapshot to disk. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] No empty TSDB snapshots

src/query/api/v1/handler/prom/prom.go, src/query/api/v1/handler/prom/read.go, src/query/api/v1/handler/prom/read_instant.go, src/query/storage/prometheus/prometheus_storage.go, src/query/storage/prometheus/prometheus_storage_test.go
Fixes an issue seen when query endpoints do not add a metadata to the query context. This was erroring before, warns now instead; added a test for the entire path.
=> [query] Additional testing on Prometheus engine path

src/query/storage/m3/storage.go, src/query/ts/m3db/types.go
A single query context can have multiple fetch operations (e.g. `foo{status="a"} - bar{status="b"}`). To distinguish between compressed series by query, we need to include the query in the `InspectSeries` arguments.
```release-note
```
```documentation-note
```
=> [query] - Include FetchQuery in InspectSeries arguments

src/cmd/services/m3dbnode/config/config_test.go, src/dbnode/client/aggregate_results_accumulator_consistency_test.go, src/dbnode/client/client_mock.go, src/dbnode/client/config.go, src/dbnode/client/fetch_tagged_results_accumulator_consistency_prop_test.go, src/dbnode/client/fetch_tagged_results_accumulator_consistency_test.go, src/dbnode/client/fetch_tagged_results_accumulator_merge_test.go, src/dbnode/client/options.go, src/dbnode/client/session.go, src/dbnode/client/session_fetch_test.go, src/dbnode/client/types.go, src/dbnode/client/write_state.go, src/dbnode/client/write_test.go, src/dbnode/integration/fetch_tagged_quorum_test.go, src/dbnode/integration/index_multiple_node_high_concurrency_test.go, src/dbnode/topology/consistency_level.go, src/x/sync/pooled_worker_pool.go, src/x/sync/pooled_worker_pool_test.go
Allows for writes to leaving shards to count towards consistency and adds read consistency level unstrict all. Combined these settings allow for clusters under stress to perform a node join without removing the availability of the leaving node. Since this can cause issues where writes made to unavailable nodes count towards consistency the read unstrict all consistency level is made available so you can attempt always to try to read from all replicas. This means you won't optimistically short-circuit once reading from majority of nodes (with unstrict majority) and will always give the cluster a chance to read from all replicas (so if a write during a node join with write to a leaving shard that count towards consistency leaves a write on two nodes …
=> [coordinator] Configurable writes to leaving shards count towards consistency, add read level unstrict all

src/dbnode/storage/block/lease.go, src/dbnode/storage/block/lease_test.go
`LeaseManager.UpdateOpenLeases(...)` was preventing concurrent calls at global granularity (see the NB in the removed comment). This changes it to the smallest granularity possible (namespace + shard + block start) to allow concurrent operations.
Such change would prevent possible collisions between `shard.AggregateTiles()` background running and manual invocations, and `shardColdFlush.Done()`.
Also, this would open up the possibility of concurrent aggregation in `shard.AggregateTiles()` in future.
NONE
NONE
=> [dbnode] Fix granularity of LeaseManager.UpdateOpenLeases

src/dbnode/storage/database.go, src/dbnode/storage/types.go
I had by mistake declared `GetNamespaceFn` to return the private `databaseNamespace` which makes using it form other packages problematic. Replacing return type with the public `storage.Namespace`interface.
NONE
NONE
=> [dbnode] GetNamespaceFn returns public Namespace interface

src/msg/consumer/options.go, src/msg/producer/writer/options.go
This changes both the Producer sending new messages and the Consumer
sending ack messages.
5s is a safer default to prevent infinite blocking if the TCP connection
is not currently available for writing (i.e the buffer is full).
Yes. The default write timeouts change from unbounded to 5s.
No
=> Default m3msg write timeouts to 5 seconds

src/dbnode/storage/bootstrap/bootstrap_mock.go, src/dbnode/storage/bootstrap/cache.go, src/dbnode/storage/bootstrap/types.go
Fixes #
```release-note
```
```documentation-note
```
=> [dbnode] Ensure that bootstrap.Cache is always passed by reference

src/cmd/services/m3coordinator/downsample/id_pool_types.go, src/cmd/services/m3coordinator/downsample/options.go, src/x/serialize/decoder_fast.go, src/x/serialize/decoder_test.go, src/x/serialize/metric_tags_iterator.go
Adds a faster path for extracting a single tag from encoded tags that does not require pooling overhead.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Extract tag value from encoded tags without pooling required

src/query/storage/m3/dynamic_cluster.go, src/query/storage/m3/dynamic_cluster_test.go
This PR implements dynamicCluster to support fetching ClusterNamespaces
from etcd dynamically instead of pulling from static config. Notably,
this does not wire up the implementation for use in the coordinator yet.
That change is pending the addition of a flag to namespace metadata
to notify the coordinator that the namespace is ready for use.
Builds off https://github.com/m3db/m3/pull/2701
```release-note
```
```documentation-note
```
=> [query] Add implementation for dynamically fetching ClusterNamespaces

src/cmd/tools/read_data_files/main/main.go
Adds annotation as an output to `read_data_files` tool.
```release-note
NONE
```
```documentation-note
NONE
```
=> [tools] output annotation in read_data_files

src/dbnode/encoding/tile/series_block_iterator.go, src/dbnode/encoding/tile/types.go, src/dbnode/persist/fs/cross_block_reader.go, src/dbnode/storage/shard.go
Removes the reasons behind 99% of allocations incurred during `AggregateTiles`:
- boxing of minHeap entries to `interface {}` when going through `heap` API
- leftover unnecessary conversion of `ident.BytesID` to `ident.ID` 
NONE
NONE
=> [dbnode] Reduce allocations in AggregateTiles

src/x/sync/pooled_worker_pool.go, src/x/sync/pooled_worker_pool_test.go
The underlying buffered pools and queue selection (shards) weren't deterministic in this test, this changes it to be deterministic and make sure that the enqueues that are meant to timeout always will.
```release-note
NONE
```
```documentation-note
NONE
```
=> [test] Fix TestPooledWorkerPoolGoWithTimeout flaking

src/dbnode/storage/index.go, src/dbnode/storage/index_test.go
This allows to extend reverse index retention only up, so that if there are multiple calls to `nsIndex.SetExtendedRetentionPeriod`, the one with the longest period will win.
NONE
NONE
=> [dbnode] Only extend reverse index retention up

src/cmd/services/m3query/config/config.go, src/query/api/v1/handler/prometheus/remote/write.go, src/query/api/v1/handler/prometheus/remote/write_test.go, src/query/api/v1/options/handler.go
Adds a configuration option `storeMetricsType` to allow enabling/disabling store of metrics type into the annotation.
NONE
NONE
=> [coordinator] Add config option to control storing of metrics type

src/aggregator/server/server.go, src/cmd/services/m3aggregator/main/main.go, src/cmd/services/m3coordinator/main/main.go, src/cmd/services/m3dbnode/config/config.go, src/cmd/services/m3dbnode/config/config_test.go, src/cmd/services/m3dbnode/main/main.go, src/dbnode/server/server.go, src/query/server/query.go, src/x/debug/config/config.go
This allows users with a different main method to still enable the
runtime profiles.
Also adding the blocking profile.
NONE
NONE
=> Enable runtime profiles inside server run methods

src/m3ninx/index/segment/fst/fst_mock.go, src/m3ninx/index/segment/fst/segment.go, src/m3ninx/index/segment/fst/types.go
Removing dead code from FST segment that was no longer used. All reads should be through segment reader.
```release-note
NONE
```
```documentation-note
NONE
```
=> [m3ninx] Remove dead code from FST segment

integrations/systemd/m3dbnode.service
Having `RestartSec=10s` makes systemd wait for 10s before starting the
service back up after it already exited. This does not appear to be the
original intention of it. As we want m3dbnode started as soon as
possible once it stopped on error.
This was intended to be `TimeoutStopSec` which would have waited for 10s
before forcibly SIGKILLing the process. Without it specified the
default is given by `DefaultTimeoutStopSec` which is usually `90s`.
Remove the RestartSec, which would mean it would only wait 100ms before
starting the process after it exited with non-zero status. Do not add
`TimeoutStopSec` so the kill behavior is not changed. If someone wants
it, they can add that option.
**Does this PR introduce a user-facing and/or backwards incompatible …
=> Remove RestartSec from m3dbnode.service example

src/dbnode/encoding/types.go, src/dbnode/persist/fs/mmap_util.go, src/dbnode/persist/fs/msgpack/decoder.go, src/dbnode/persist/fs/msgpack/decoder_test.go
1. On incomplete data index file, it fixes error message from potentially misleading `decode index entry encountered checksum mismatch` to a more accurate `decode index entry encountered error: EOF` (or any other actual error encountered while reading/decoding the file).
2. On whole file checksum mismatch, it includes the file name (which helps to see both file type and block) into the error message and removes the misleading word `summaries` from it (this is generic code not related to summaries, and it is also used eg. for bloom filter checksumming).
NONE …
=> [dbnode] Improve error messages on corrupt files

src/cmd/services/m3coordinator/ingest/write.go, src/cmd/services/m3query/config/config.go, src/query/server/query.go
Raising the default writer worker pool and adding configurability and metrics for the worker pool.
This also removes `(*downsamplerAndWriter).writeWithOptions` which has a large stack options struct passed to it that may be causing the stack to split often:
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Expand and add metrics + configurability of downsample and ingest worker pool

src/cmd/services/m3dbnode/config/fs.go, src/dbnode/config/m3dbnode-all-config.yml
This PR brings flush ratelimit into 2020. The existing config is far too conservative and might actually cause harm - any decently-powered machine could potentially OOM before it can write out a snapshot @ 12MiB/s.
1000 mbps is still only 125mb/s, but a much more reasonable baseline for modern VMs/machines.
```release-note
```
```documentation-note
```
=> [dbnode] Bump default filesystem persist rate limit

src/dbnode/integration/peers_bootstrap_index_test.go, src/dbnode/storage/bootstrap/bootstrap_mock.go, src/dbnode/storage/bootstrap/bootstrapper/peers/source.go, src/dbnode/storage/bootstrap/cache.go, src/dbnode/storage/bootstrap/types.go
The info files cache becomes stale after the peers bootstrapper fetches/persists TSDB blocks streamed from peers. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Evict info files cache before index bootstrap in peers bootstrapper

src/dbnode/namespace/convert_test.go, src/dbnode/namespace/options.go, src/dbnode/persist/fs/files_test.go, src/dbnode/persist/fs/retriever_options.go, src/dbnode/persist/fs/seek_manager_test.go, src/dbnode/storage/bootstrap/bootstrapper/peers/source.go, src/dbnode/storage/bootstrap/bootstrapper/peers/source_data_test.go, src/query/api/v1/handler/database/create_test.go, src/query/api/v1/handler/namespace/add_test.go
Fixes #
```release-note
```
```documentation-note
```
=> [dbnode] Set default cache on retrieve to false, prepare testing with cache none

src/aggregator/aggregator/follower_flush_mgr.go, src/aggregator/aggregator/follower_flush_mgr_test.go
Recently we started using status endpoint to track health of aggregator leaders and followers.
We noticed that some followers are occasionally in a state of `canLead == false` when the last flush time recorded by leader is zero. Specifically, it was noticed for forwarded metrics at 10 minute resolution.
According to the leader flush manager code, this is possible when a new metric at some resolution appears for the very first time for a given shard (a new list is created). But since leader persists flush times for all resolution widows in the same batch, if some resolution window is brand new, its last flush time in etcd is zero.
Follower does not handle the zero value of last flush time and reports `canLead == false` even when it can legitimately takeover leadership.
When follower …
=> [aggregator] Handle follower canLead() for not yet flushed windows

src/cmd/tools/read_index_segments/main/main.go
Allows identification of each block being processed by the read_index_segments tool.
```release-note
NONE
```
```documentation-note
NONE
```
=> [read_index_segments] Add log that outlines which segment being processed

src/dbnode/namespace/staging.go, src/query/api/v1/handler/namespace/ready.go, src/query/api/v1/handler/namespace/ready_test.go, src/query/storage/m3/cluster.go, src/query/storage/m3/cluster_test.go, src/query/storage/m3/dynamic_cluster.go, src/query/storage/m3/dynamic_cluster_test.go
Previously, non-ready namespaces could not be marked as ready without using the `force` flag due to the coordinator ignoring the non-ready namespace when it was initially discovered. This PR ensures that non-ready namespaces are not discarded on discovery so that the coordinator can associate the appropriate dbnode session with the namespace. With the session in place, the coordinator can gracefully check the dbnode for the namespace availablility and set the namespace as ready for writes if the dbnode check is successful.
```release-note
``` …
=> Add non-ready namespaces to Clusters interface and use in /namespace/ready endpoint

src/cmd/tools/read_index_segments/main/main.go
Allows read_segment_files to be run in a pure validation mode and run concurrently (by default num CPUs / 2).
```release-note
NONE
```
```documentation-note
NONE
```
=> [tools] Add concurrent read_segment_files validation option

src/query/api/v1/handler/prom/read.go, src/query/api/v1/handler/prom/read_instant.go
Return additional warnings in `/query` and `/query_range` endpoints. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Return additional warnings in /query{,_range} endpoints

.buildkite/pipeline.yml, Makefile, docker-compose.yml, docker/m3aggregator/Dockerfile, docker/m3collector/Dockerfile, docker/m3coordinator/Dockerfile, docker/m3dbnode/Dockerfile, docker/m3dbnode/Dockerfile-setcap, docker/m3query/Dockerfile
I've landed all fixes to pass build/tests back in September, this PR switches build to use 1.14, so we don't introduce any more regressions.
Fixes #2540
```release-note
```
```documentation-note
Upgrade to Go 1.14
```
=> Bump go to 1.14

src/aggregator/aggregator/election_mgr.go, src/aggregator/aggregator/election_mgr_test.go
This fixes an annoying behavior, where campaign manager will always have a delay of $campaignCheckInterval, even if the process has crashed/restarted and lease hasn't expired yet. It also makes other tests that rely on non-mocked-out campaign manager much slower than they need to be.
The initialization delay also exposed some racy behavior in campaign manager tests. Fixing everything and reducing sleeps sped them up by quite a bit:
```
~# go test  github.com/m3db/m3/src/aggregator/aggregator  -tags integration  -count 1
ok  	github.com/m3db/m3/src/aggregator/aggregator	12.460s
```
vs
```
ok  	github.com/m3db/m3/src/aggregator/aggregator	34.935s
```
Fixes #
**Does this PR introduce a user-facing and/or backwards …
=> [aggregator] Process campaign state without waiting for first campaign check interval

src/query/graphite/native/builtin_functions.go
Fixes flaky coverage calculations
```release-note
```
```documentation-note
```
=> Update ci-scripts to correct coverage tracking

src/cluster/client/etcd/client.go, src/cluster/client/etcd/config_test.go, src/cluster/client/etcd/options.go, src/cluster/client/etcd/options_test.go, src/cluster/client/etcd/types.go
All of the services depend on timely data from KV and default etcd keepalive settings are far too relaxed, and can cause outages due to 5-10 minute latency, before dead connections are closed and retried.
Also, we are not setting DialTimeout (probably because pre-3.4 it would cause client to block, but now it's optional), and not using keepalives if no streams are currently active, which is a good idea in watch-happy code.
```release-note
```
```documentation-note
```
=> [etcd] Set reasonable cluster connection/sync settings by default

.golangci.yml
Keeping the new line required before a return linter would require a large fraction of the code base to need updating. 
The perceived benefit of always an empty line does not seem worth the changes required to each file. Also it is purely stylistic and doesn't seem to avoid types of errors.
```release-note
NONE
```
```documentation-note
NONE
```
=> [lint] Disable nlreturn linter

src/dbnode/integration/large_tiles_test.go
Had accidentally uncommented a `Skip` on a flaky test while checking it locally. Reverting.
NONE
NONE
=> [dbnode] Resurrect flaky test skip

src/cmd/services/m3dbnode/config/config.go, src/cmd/services/m3dbnode/main/main_index_test.go, src/cmd/services/m3dbnode/main/main_test.go, src/dbnode/config/m3dbnode-local-etcd-proto.yml, src/dbnode/config/m3dbnode-local-etcd.yml, src/dbnode/server/server.go, src/query/server/query.go
Default HostID and Discovery config for a minimal configuration file for default DB node which ends up being:
```
coordinator: {}
db: {}
```
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Default HostID and Discovery config for minimal config

src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/options.go
A lot of metrics have the "namespace" label on them, so we default to using a M3 prefixed namespace label here. This makes sure most rules will use the default rule namespace rather than whatever is specified by the "namespace" label on the metric itself.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Set default namespace tag to avoid colliding with commonly used "namespace" label

src/dbnode/integration/disk_cleanup_deletes_inactive_directories_test.go, src/dbnode/integration/disk_cleanup_helpers.go, src/dbnode/integration/integration.go, src/dbnode/integration/setup.go, src/dbnode/persist/fs/index_claims_manager.go, src/dbnode/persist/fs/index_claims_manager_test.go, src/dbnode/persist/fs/migration/migration_test.go, src/dbnode/server/server.go, src/dbnode/storage/bootstrap/bootstrapper/fs/source_data_test.go, src/dbnode/storage/bootstrap/bootstrapper/peers/peers_test.go, src/dbnode/storage/bootstrap/bootstrapper/peers/source_data_test.go, src/dbnode/storage/bootstrap/bootstrapper/peers/source_index_test.go, src/dbnode/storage/util.go
This ensures callers can't incorrectly create two instances of the index claims manager, which will help avoid refactors where for some reason the index claim manager is not incorrectly shared.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add validation to ensure index claims is singleton

go.mod, go.sum, src/cluster/kv/etcd/store_test.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/msg/integration/integration_test.go
Improves runtime of top 3 slowest tests:
```
ok  	github.com/m3db/m3/src/cmd/services/m3coordinator/downsample	167.544s
ok  	github.com/m3db/m3/src/cmd/services/m3coordinator/downsample	19.045s
ok  	github.com/m3db/m3/src/msg/integration	54.265s
ok  	github.com/m3db/m3/src/msg/integration	13.191s
ok  	github.com/m3db/m3/src/cluster/kv/etcd	36.037s
ok  	github.com/m3db/m3/src/cluster/kv/etcd	13.441s
```
Had to switch to goleak as leaktest doesn't support parallel tests - should probably switch everywhere, but out of scope.
```release-note
``` …
=> Improve some slow tests

site/content/docs/how_to/cluster_hard_way.md, site/content/docs/how_to/kubernetes.md, site/content/docs/how_to/query.md, site/content/docs/how_to/use_as_tsdb.md, site/content/docs/operational_guide/mapping_rollup.md, site/content/docs/operational_guide/multiple_m3db_clusters.md, site/content/docs/operational_guide/namespace_configuration.md, site/content/docs/quickstart/_index.md
This PR makes documentation reflect the preferred path for creating and configuring namespaces.
```release-note
```
```documentation-note
```
=> [docs] Update documentation for dynamic namespace configuration in Coordinator

src/m3ninx/index/segment/builder/multi_segments_builder.go, src/m3ninx/index/segment/builder/multi_segments_builder_test.go
Need to order index segments added to multi segments builder in descending order by size to ensure optimal compactions. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Order index segments in multi segments builder in descending order

src/cluster/placement/algo/sharded_test.go, src/cluster/shard/shard.go, src/cluster/shard/shard_benchmark_test.go, src/cluster/shard/shard_test.go
Pretty much all Shards() API calls in use are either `.All()` or `.Shard()/Contains()`, and `.All()` always re-sorts the backing map to produce a sorted list of shards.
m3dbnode doesn't use it heavily, as it manages routing via it's own shardset wrapper. However, m3aggregator does - and it does it over a contended lock - even though it usually is 5 to 30-40 shards, it gets really expensive fast, especially if it has to be done multiple times for staged placements/diffing.
This change trades slower init via `NewShards()` and `.Add()` (the latter is barely used) for much faster `.All()` calls.
While the slowdown in less frequent calls is 1-5x, the speedup is at least an order of magnitude.
```
name                                    old time/op    new …
```
=> [cluster] Store shards in sorted form

.buildkite/docs-docker-compose.yml, site/content/docs/how_to/kubernetes.md
Temporarily removes links to operator to be able to pass the master build and regenerate documents and the operator site itself; will be readded after it's working.
=> [docs] Update buildkite doc path

src/aggregator/integration/integration.go, src/aggregator/integration/setup.go
After #2855 (and #2867 fix) the agg startup is much faster, so there's no need for long waits everywhere. This pr updates the integration setup to actually aggressively check aggregator state.
```release-note
```
```documentation-note
```
=> [aggregator] Reduce delays in integration tests

site/content/how_to/other/tsdb.md, site/content/how_to/use_as_tsdb.md, site/content/m3db/architecture/commitlogs.md, site/content/operational_guide/namespace_configuration.md, site/static/about/index.html, site/static/index.html
Fixes #
```release-note
```
```documentation-note
```
=> [docs] Small changes to website/docs

CHANGELOG.md, site/content/operational_guide/resource_limits.md
Fixes #
```release-note
```
```documentation-note
```
=> [changelog] v1.0.0 changelog update

scripts/docker-integration-tests/prometheus/m3coordinator.yml, scripts/docker-integration-tests/prometheus/test.sh, src/cmd/services/m3query/config/config.go, src/query/server/query.go
Adds lookback duration to come from config for PromQL engine.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Add lookback duration from query config

src/cmd/tools/dtest/docker/harness/query_api_test.go, src/query/api/v1/handler/prometheus/native/read_common.go
Fixes `m3query/api/v1/{query,query_range}` returning 500 on invalid query string. Plus additional tests
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix /m3query returning 500 on invalid query argument

go.mod, go.sum, src/cmd/services/m3dbnode/config/config.go, src/cmd/services/m3dbnode/config/config_test.go, src/dbnode/server/server.go, src/m3ninx/index/segment/fst/regexp/regexp.go
Adds ability to configure regexp DFA and FSA limits.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add configurability for regexp DFA and FSA limits

src/aggregator/aggregation/gauge.go, src/aggregator/aggregation/gauge_test.go
We've observed `-math.MaxFloat64` values for `Max` R2 gauge aggregations in some cases that appears to be caused by zero/non-`Update`'d `aggregation.Gauge` values.
This changes `Gauge` to properly handle zero values and not produce sentinel values as part of e.g. `Max()` and `Min()`.
No.
No.
=> [aggregator] Use NaN instead of math.MaxFloat64 and add sentinel guards

src/aggregator/aggregation/gauge.go, src/aggregator/aggregation/gauge_test.go
Following up on #2929, return NaN instead of zeroes so we can disambiguate the two. We also discard NaN if configured in [src/aggregator/aggregator/gauge_elem_gen.go:467](https://sourcegraph.com/github.com/m3db/m3@afda2712be42b40c577dfd61ff6ffb2a7121e722/-/blob/src/aggregator/aggregator/gauge_elem_gen.go#L467).
No.
No.
=> [aggregator] Return NaN instead of 0 for NaN gauge values

src/dbnode/persist/fs/merger.go, src/dbnode/persist/types.go, src/dbnode/storage/namespace.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go
Expose a `DocRef()` method on db namespace. Also update the `OnFlushNewSeriesEvent` to add a `SeriesMetadata` type that supports multiple representations of underlying series metadata and memory life times. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add DocRef() to NS and multiple series metadata types 

src/aggregator/client/queue.go
There are cases when, during a placement change of aggregator service, the client fails to write to an instance.
On the managed platform instance ID and instance endpoint look very different: it's impossible to tell the instance ID from the endpoint without taking a look at placement details. Add instance ID to the error log message.
```release-note
NONE
```
```documentation-note
NONE
```
=> [aggregator/client] Include instance ID in write errors

src/dbnode/storage/namespace.go, src/dbnode/storage/namespace_test.go, src/dbnode/storage/options.go, src/dbnode/storage/shard.go, src/dbnode/storage/shard_test.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go
Integrate ns cold flusher into tile aggregations. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Integrate ns cold flusher into tile aggregation.

src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go
Expose `FetchWideEntry` on a higher level interface.
NONE
NONE
=> [dbnode] Widen exposure of namespace method

scripts/docker-integration-tests/prometheus/docker-compose.yml, scripts/docker-integration-tests/prometheus/test.sh, scripts/docker-integration-tests/simple_v2_batch_apis/test.sh
Swap metric `prometheus_remote_storage_succeeded_samples_total` with `prometheus_remote_storage_samples_total`. The former metric was [removed in v2.23 release of Prometheus](https://github.com/prometheus/prometheus/blame/26d89b4b0776fe4cd5a3656dfa520f119a375273/CHANGELOG.md#L5), which broke `docker-integration-tests`.
```release-note
NONE
```
```documentation-note
NONE
```
=> [tests] Fix deprecated Prometheus metric in docker-integration-tests

src/cmd/services/m3coordinator/downsample/id_pool_types.go, src/cmd/services/m3coordinator/downsample/tags.go, src/dbnode/encoding/iterators.go, src/dbnode/persist/fs/commitlog/reader.go, src/dbnode/persist/fs/retriever.go, src/dbnode/persist/fs/write.go, src/dbnode/persist/types.go, src/dbnode/storage/cluster/database.go, src/dbnode/storage/fs_merge_with_mem.go, src/dbnode/storage/namespace.go, src/dbnode/storage/shard.go, src/dbnode/storage/shard_test.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go, src/x/ident/bytes_id.go, src/x/ident/tag_iterator.go
=> [lint] Update instances of Reuseable -> Reusable

src/dbnode/integration/disk_coldflush_test.go, src/dbnode/integration/index_helpers.go, src/dbnode/integration/index_single_node_high_concurrency_test.go, src/dbnode/integration/options.go, src/dbnode/integration/wide_query_test.go
```release-note
```
```documentation-note
```
=> [integration] Expose TestIndexWrite methods

scripts/comparator/README.md
Just a quick diagram for comparator readme.
```release-note
NONE
```
```documentation-note
NONE
```
=> [comparator] Add diagram to comparator readme

src/dbnode/client/options.go, src/dbnode/network/server/tchannelthrift/cluster/server.go, src/dbnode/network/server/tchannelthrift/node/server.go
Fixes data races in integration tests with TChannel channel construction since it modifies channel options in place.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Fix integration code under race with TChannel channel options mutation issue

src/dbnode/storage/database.go, src/dbnode/storage/database_test.go, src/dbnode/storage/namespace.go, src/dbnode/storage/namespace_test.go, src/dbnode/storage/options.go, src/dbnode/storage/shard.go, src/dbnode/storage/shard_test.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go
Adds a few parameters.
NONE
NONE
=> [dbnode] Additional params for Aggregator

src/cluster/placement/placement_mock.go, src/cluster/placement/staged_placement.go, src/cluster/placement/staged_placement_test.go, src/cluster/placement/staged_placement_watcher_test.go, src/cluster/placement/types.go
Add plumbing, so staged placement watcher users can get the actual underlying KV value version for active placement from the underlying staged placement set.
```release-note
```
```documentation-note
```
=> [cluster] Expose underlying staged placement version

src/aggregator/client/tcp_client.go, src/aggregator/client/tcp_client_test.go
Builds on top of #2964 and #2963 to allow users to get internal placement status, so it's easier to expose data useful for debugging.
```release-note
```
```documentation-note
```
=> [aggregator] Add ActivePlacement method to TCP client

src/cluster/client/etcd/client.go, src/cluster/client/etcd/client_test.go, src/cluster/client/etcd/types.go
Expose underlying etcd clients so their state can be inspected, endpoints synced from external source/trigger, etc.
The existing cluster Client interface is far too limiting, even if it's built with etcd in mind.
```release-note
```
```documentation-note
```
=> [etcd] Expose cached etcd clients in cluster etcd config service

src/cluster/placement/staged_placement.go, src/cluster/placement/staged_placement_test.go
Fixes deadlock introduced in #2963: `Version()` could cause a deadlock, if an expire cycle was triggered on a `ActiveStagedPlacement()` call.
Root cause is that I've used a lock - that is also kinda acting as a refcounter and is not meant to be used for this case - to access a variable that was safe to read concurrently. 
The added test always deadlocks on master.
```release-note
```
```documentation-note
```
=> [cluster] Fix deadlock in new ActiveStagedPlacement method

src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/metrics/aggregation/type.go, src/metrics/aggregation/types_options_test.go
In a previous change we added support for graphite ingestion through the prometheus remote write endpoints. As a part of this we added support to extend the graphite path with the aggregation type.. This PR makes sure that the aggregation type matches with the exact graphite names rather than the internal M3 aggregation types
```release-note
The graphite aggregation option on mapping rules now writes metrics with graphite compatible paths, so will be different from prior to this release.
```
```documentation-note
NONE
```
=> [coordinator] add graphite names to aggregation types

site/static/about/index.html, site/static/community/index.html, site/static/index.html
This PR fixes some broken links to `og:meta` tags on static pages.
Signed-off-by: ChrisChinchilla <chris@chronosphere.io>
=> [SITE] Fix broken og meta tags on static pages

src/cluster/etcd/watchmanager/manager.go, src/cluster/etcd/watchmanager/manager_test.go
WatchManager relies on implicit etcdclient behavior that on any error the returned `watchCh` is successfully closed. 
However it is not true in all cases[*], and is causing rare but total watch failures.
This PR forces watch recreation not only on `ErrCompacted`, but also on server-side events like leader loss, server-initiated cancel and fixes a resource leak, where we weren't cancelling the provided context.
[*] don't know yet why is it not failing all the time
```release-note
```
```documentation-note
```
=> [cluster] Fix watch resource leak/hang

src/cmd/tools/read_data_files/main/main.go
Adds benchmarking support to `read_data_files` utility. There are two benchmarking modes:
- read series only (do not decode the datapoints)
- read series and decode the datapoints
It was already useful for me for measuring improvement of https://github.com/m3db/m3/pull/2827#issuecomment-739335010 and I believe there will be more use cases in future.
Sample output:
```
> read_data_files -b 1596009600000000000 -p ~/testdata/m3db -s 4 -v 0 -B datapoints
Running time: 460.262013ms
7315 series read
(15893.12 series/second)
3852592 datapoints decoded
(8370432.26 datapoints/second)
```
NONE
**Does this PR require updating code package or …
=> [tools] Add benchmarking support to read_data_files

src/aggregator/aggregator/forwarded_writer.go, src/aggregator/aggregator/forwarded_writer_test.go
M3 Aggregator was panicking on shutdown as Flush() and Close() are called concurrently. It no longer resets the internal fields to nil, but that's never been necessary.
```release-note
```
```documentation-note
```
=> [aggregator] Fix panic on shutdown in ForwardedWriter

src/x/net/http/client.go
This commit adds a new field, `Proxy`, to `HTTPClientOptions` that will be used to configure the corresponding `Proxy` field in the transport of the client that is created from the options. This allows the caller to use the standard library's built-in support for connecting to a target via proxy.
N/A
```release-note
NONE
```
```documentation-note
NONE
```
=> [x/net/http] Add Proxy field to HTTPClientOptions

src/dbnode/persist/fs/index_claims_manager.go, src/dbnode/persist/fs/index_claims_manager_test.go, src/dbnode/storage/bootstrap/bootstrapper/fs/source.go, src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
Skip out of retention index segments during bootstrap. This can happen if the edge of the requested ranges is already out of retention by the time we start bootstrapping index data. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Skip out of retention index segments during bootstrap.

site/content/operator/api.md
Updates k8s doc references to most recent minor version.
NONE
NONE
=> Update k8s doc references

src/cmd/services/m3coordinator/downsample/options.go, src/query/server/query.go
Enables clients to specify custom rule stores, and provides this custom rule store to the downsampler.
NONE
NONE
NONE
=> [m3coordinator] Allow downsampler to configure custom rule store

src/cluster/client/etcd/client.go, src/cluster/etcd/watchmanager/manager.go, src/cluster/etcd/watchmanager/manager_test.go, src/cluster/etcd/watchmanager/options.go, src/cluster/etcd/watchmanager/types.go, src/cluster/kv/etcd/store.go, src/cluster/kv/etcd/store_test.go, src/cluster/services/heartbeat/etcd/store.go
This PR fixes occasional complete watch hangs if etcd cluster loses the leader node and/or is unavailable for some period of time.
```release-note
```
```documentation-note
```
=> [cluster] Close etcd watches completely before recreating

src/cmd/services/m3dbnode/config/config.go, src/cmd/services/m3dbnode/config/config_test.go, src/dbnode/server/server.go
Adds the ability to force enable cold writes from config.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add ability to force enable cold writes from config

site/content/quickstart/docker.md
Either by a merge conflict or missing something #2795 introduced a rendering issue to the quickstart, this PR fixes it.
=> [DOCS] Quick fix to broken code tabs on quickstart

src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/options.go
AugmentM3Tags will augment the metric type to aggregated metrics
to be used within the filter for rules. If enabled, for example,
your filter can specify '__m3_type__:gauge' to filter by gauges.
This is particularly useful for Graphite metrics today.
Furthermore, the option is automatically enabled if static rules are
used and any filter contain an __m3_type__ tag.
```release-note
Adds a new config value: `coordinator.downsample.augmentM3Tags`
to augment the metric to aggregated metrics to be used within the filter for rules.
```
NONE
=> [coordinator] Allow clients to pass in augmentM3Tags as a config

src/dbnode/client/errors.go, src/dbnode/client/fetch_tagged_results_accumulator.go, src/dbnode/client/fetch_tagged_results_accumulator_merge_test.go
Updates `fetchTaggedResultAccumulator` to emit `consistencyResultError` instead of generic `fmt.Errorf()`. This should make it easier to distinguish the error type from the outside, using `client.IsConsistencyResultError()`.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Emit consistencyResultError from fetchTaggedResultAccumulator

site/config/_default/config.toml, site/content/includes/quickstart-common-steps.md, site/content/quickstart/docker.md, site/layouts/shortcodes/docker-version.html
@gediminasgu pointed out a handful of small API changes that I wasn't aware of, and this the quickstart fell out of date.
It also looks like #2795 override some changes from @nate as I single sourced some steps in that PR that went against git history so weren't really noticed in reviewing that PR.
Also after recommendation this PR sets a specific Docker version instead of using `latest`, and I have started adding config variables for the current versions of various releases, so it can be updated in one place.
=> [DOCS] Fix new API paths and add Docker version

src/dbnode/integration/serve.go, src/dbnode/integration/setup.go
Allows more flexible `TestSetup` configuration for integration tests.
NONE
NONE
=> [dbnode] Add server.StorageOptions to TestSetup

src/cmd/services/m3coordinator/downsample/options.go, src/query/server/query.go
Pass along instrument options into custom rule store fn
NONE
NONE
=> [coordinator] Pass along instrument options into custom rule store fn

src/aggregator/client/conn_options.go, src/aggregator/client/payload.go, src/aggregator/client/ref_count.go, src/aggregator/client/writer.go, src/metrics/encoding/protobuf/aggregated_encoder.go, src/metrics/encoding/protobuf/buffer.go, src/metrics/encoding/protobuf/buffer_test.go, src/metrics/encoding/protobuf/unaggregated_encoder.go
Reorder some fields of per-connection/per-queue structs:
```
/Users/vytenis/gocode/m3/src/metrics/encoding/protobuf/buffer.go:30:13: struct with 40 pointer bytes could be 24
/Users/vytenis/gocode/m3/src/aggregator/client/conn_options.go:117:24: struct with 120 pointer bytes could be 64
/Users/vytenis/gocode/m3/src/aggregator/client/payload.go:67:19: struct with 416 pointer bytes could be 408
/Users/vytenis/gocode/m3/src/aggregator/client/ref_count.go:27:15: struct with 16 pointer bytes could be 8
/Users/vytenis/gocode/m3/src/aggregator/client/writer.go:63:13: struct with 168 pointer bytes could be 120
/Users/vytenis/gocode/m3/src/aggregator/client/writer.go:536:20: struct with 24 pointer bytes could be 16
``` …
=> [aggregator] Pack some tcp client structs for lower memory utilization

src/dbnode/persist/fs/persist_manager.go, src/dbnode/persist/fs/persist_manager_test.go, src/dbnode/persist/persist_mock.go, src/dbnode/persist/types.go, src/dbnode/storage/storage_mock.go
Add method to support checkpointing in the cold flush flow. This may trigger a compaction based on index segment size limits. 
Also support preparing an index writer per block. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Support checkpointing in cold flusher and preparing index writer per block

src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/options.go, src/metrics/metadata/metadata.go
Skip rollup rule storage policies when deciding whether to apply default auto mapping rules that write raw metrics to aggregated namespaces. We only want to consider mapping rules here, as we want to apply these rules to metrics that are rolled up to ensure the underlying metric gets written to aggregated namespaces.
NONE
NONE
=> [coordinator] Ignore rollup rule storage policies when deciding to utilize auto-mapping rules

src/cluster/etcd/watchmanager/manager_test.go, src/cmd/services/m3coordinator/ingest/carbon/ingest.go, src/cmd/services/m3coordinator/ingest/carbon/ingest_test.go, src/cmd/services/m3coordinator/ingest/carbon/rewrite.go, src/cmd/services/m3coordinator/ingest/carbon/rewrite_test.go, src/cmd/services/m3query/config/config.go, src/query/server/query.go
Adds ability to cleanse metrics similar to carbon relay for cleaning up metric names.
Performs:
- Trailing/leading dot elimination.
- Double dot elimination.
- Irregular char replacement with underscores (_), currently irregular is defined as not being in [0-9a-zA-Z-_:#].
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Add Graphite rewrite cleanup directive for cleansing incoming metrics

src/dbnode/client/session.go, src/dbnode/client/types.go
Add the ability to skip the origin host when attempting to borrow a connection.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add ExcludeOrigin to skip localhost on BorrowConnections

src/cmd/tools/dtest/docker/harness/query_api_test.go, src/cmd/tools/dtest/docker/harness/resources/coordinator.go
Add a method for Prom remote writes to dtest docker harness 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dtest] Add a method for Prom remote writes

src/query/storage/m3/cluster_resolver.go, src/query/storage/m3/cluster_resolver_test.go
Makes this error a 4xx not 5xx.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix aggregated namespace header to be bad request instead of internal server error

src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/options.go
Confirmed includeRollupsOnDefaultRuleFiltering is working as expected, and it is not useful to configure otherwise.
Technically backwards incompatible by removing config, but this was a temporary feature flag that was not expected to be used elsewhere.
NONE
=> [coordinator] Remove includeRollupsOnDefaultRuleFiltering flag

src/dbnode/network/server/tchannelthrift/node/service.go, src/dbnode/network/server/tchannelthrift/node/service_test.go, src/dbnode/storage/database.go
Removes per-series traces on read queries. That level of trace granularity isn't really needed and the memory allocations end up being expensive.
```release-note
```
```documentation-note
```
=> [dbnode] Remove per-series traces on read queries

src/aggregator/client/tcp_client.go, src/aggregator/client/tcp_client_test.go
It's really expensive to use `ActivePlacement` on large placements if it's only to get currently active version.
```release-note
```
```documentation-note
```
=> [aggregator] Add ActivePlacementVersion to tcp client

site/content/m3query/architecture/_index.md, site/content/m3query/config/annotated_config.yaml, site/content/operator/api.md, src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/metrics_appender_test.go, src/cmd/services/m3coordinator/downsample/options.go
Rollout augmentM3Tags flag to true by default
NONE
NONE
=> [coordinator] Rollout augmentM3Tags flag to true by default

src/metrics/matcher/match.go, src/metrics/matcher/match_test.go
Add latency metrics to rule matching
NONE
NONE
=> [matcher/coordinator] Add latency metrics to rule matching

src/dbnode/storage/shard.go
Adds namespace and shard id fields to the log message of "purgeExpiredSeries encountered invalid series read/write count" error that I need to investigate.
NONE
NONE
=> [dbnode] Log namespace and shard upon invalid series read/write count

src/dbnode/storage/bootstrap.go, src/dbnode/storage/bootstrap_test.go
After a node join, the bootstrapper fails and the bootstrap is retried. The node is improperly marked as bootstrapped and starts serving reads.
```release-note
```
```documentation-note
```
=> [dbnode] Fix node serving reads/marked bootstrapped after bootstrap failure

src/cluster/etcd/watchmanager/manager_test.go, src/cluster/kv/etcd/store_test.go
Fixes flaky tests for WatchManager. I thought it was something with my environment (I got flakes once in a while locally), but since they are flaking in CI, it got me stumped for a while.
Now I consistently have repeatable results locally:
```
╰─$ go test ./src/cluster/etcd/watchmanager/... -run TestWatchNoLeader -count 50                                                                                                                                                                                                                                                                                      1 ↵
ok  	github.com/m3db/m3/src/cluster/etcd/watchmanager	172.472s
go test ./src/cluster/etcd/watchmanager/... -run TestWatchNoLeader -count 50  17.23s user …
```
=> [cluster] Fix flaky watchmanager tests

src/dbnode/network/server/tchannelthrift/node/service.go, src/dbnode/persist/fs/retriever.go
This removes the allocation per series per block done when streaming a request from disk if the ID pool is exhausted.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Remove allocation per series ID when streaming block from disk

src/dbnode/persist/fs/retriever.go, src/dbnode/persist/fs/retriever_test.go
When querying, we check the bloom filter first before grabbing a request from the request pool. This has the additional effect of not incrementing / checking the series read limit until after we know whether we'll be reading from disk.
I added a separate method `seriesPresentInBloomFilter` that needs to be invoked for both the `Stream` and `StreamWideEntry` APIs, rather than trying to push all the request logic into the shared `streamRequest` method. This seemed desirable to avoid making `streamRequest` overly generic.
NONE
NONE
=> [m3db] Check bloom filter before stream request allocation

src/dbnode/storage/index.go, src/query/models/tags.go
Replace `bytes.Compare() == 0` with `bytes.Equal()`. According to benchmark in https://github.com/m3db/m3/pull/3097 , this might improve performance.
```release-note
NONE
```
```documentation-note
NONE
```
=> Replace bytes.Compare() == 0 with bytes.Equal()

src/cluster/etcd/watchmanager/manager_test.go
`TestWatchNoLeader` flaky, started to fail very consistently on CI.
Have to `skip` it temporarily, until a proper resolution.
CC @vdarulis 
```release-note
```
```documentation-note
```
=> [tests] Skip flaky TestWatchNoLeader

src/query/api/v1/handler/prometheus/common.go, src/query/api/v1/handler/prometheus/common_test.go, src/query/api/v1/handler/prometheus/native/list_tags.go, src/query/api/v1/handler/prometheus/native/list_tags_test.go, src/query/api/v1/handler/prometheus/remote/tag_values.go, src/query/api/v1/handler/prometheus/remote/tag_values_test.go, src/query/parser/promql/options.go
Adds bounds parsing to `/api/v1/labels` and `/api/v1/label/<label_name>/values` endpoints
=> [query] Take bounds into account for list endpoints

site/content/cluster/binaries_cluster.md, site/content/cluster/kubernetes_cluster.md, site/content/includes/cluster-architecture.md, site/content/includes/cluster-common-steps.md, site/content/includes/m3query/annotated_config.yaml, site/content/operator/api.md
This PR single-sources a few pieces of content around the cluster quoickstarts, and adds a bit more explanation around things. It also fixes a few small steps for the K8s guide.
The K8s and binaries cluster guides are a little different from each other right now, mostly as I have had a lot of issues getting a local K8s cluster to work properly, and there are so many ways people have this setup anyway… Over time I would like to improve it…
=> [DOCS] Update to cluster docs

src/dbnode/generated/thrift/rpc.thrift, src/dbnode/generated/thrift/rpc/rpc.go, src/dbnode/network/server/tchannelthrift/convert/convert.go, src/dbnode/network/server/tchannelthrift/convert/convert_test.go, src/query/storage/index.go, src/query/storage/index_test.go
[m3db] [m3coordinator] Properly pipe along require-exhaustive param for aggregate queries
NONE 
NONE
=> [m3db] [m3coordinator] Properly pipe along require-exhaustive param for aggregate queries

src/query/api/v1/handler/database/kvstore.go, src/query/api/v1/handler/database/kvstore_test.go
=> [coordinator] Marshal return val of kv handler with jsonpb

src/dbnode/network/server/tchannelthrift/node/service_test.go, src/dbnode/persist/fs/migration/migration_test.go, src/dbnode/persist/fs/migration/task_options_test.go, src/dbnode/storage/bootstrap/bootstrapper/fs/migrator/options_test.go, src/dbnode/storage/bootstrap/bootstrapper/fs/source_data_test.go, src/dbnode/storage/cluster/database_test.go, src/dbnode/storage/options.go
`storage.NewOptions` is expensive because it creates full size object pools.
There is a more lightweight `storage.DefaultTestOptions` for test code, I've switched to this implementation in some unit tests that were using `storage.NewOptions` before.
NONE
NONE
=> [dbnode] Use DefaultTestOptions in unit tests

src/dbnode/storage/index/aggregate_results.go, src/dbnode/storage/index/block.go
Added some clarifying comments / removed unused var as I was reading through agg API code
NONE
NONE
=> [dbnode] Comments / remove unused var

src/dbnode/storage/shard.go, src/dbnode/storage/shard_test.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go
Adds `Shard.OpenStreamingReader` method. I found it to be more convenient to use that callback based `Shard.ScanData` (which I'm planning to remove soon).
NONE
NONE
=> [dbnode] Add Shard.OpenStreamingReader method

src/m3ninx/index/segment/builder/multi_segments_builder.go, src/m3ninx/index/segment/builder/multi_segments_builder_test.go
This fixes the ordering of segments by size to happen before processing (and assigning the `offset` to a segment) since the code that checks whether the postings list can be direct merged during postings list iterating over multi-segments checks the `.offset` of the segment metadata to see if it can directly using the postings.ID values without modifying (since no duplicates can be contained by the first segment with `.offset == 0`):
```go
if termsKeyIter.segment.offset == 0 {
// No offset, which means is first segment we are combining from
// so can just direct union
i.currPostingsList.Union(list)
continue
}
```
```release-note
NONE …
```
=> [dbnode] Alter multi-segments builder to order by size before processing

src/dbnode/client/session_fetch_test.go
This blocks reading the testFetch values until they have been written to
by the go routine.
Previous race
```
go test ./src/dbnode/client -run TestProtoSessionFetchIDs -race -count=100
Read at 0x00c00a14a630 by goroutine 457:
github.com/jhump/protoreflect/codec.(*Buffer).DecodeVarint()
/Users/rhall/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/codec/decode.go:76 +0xa6
github.com/jhump/protoreflect/codec.(*Buffer).DecodeTagAndWireType()
/Users/rhall/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/codec/decode.go:172 +0x3c
github.com/jhump/protoreflect/codec.(*Buffer).DecodeFieldValue()
/Users/rhall/go/pkg/mod/github.com/jhump/protoreflect@v1.6.1/codec/decode_fields.go:62 +0x90
github.com/jhump/protoreflect/dynamic.(*Message).unmarshal() …
```
=> Fix TestSessionFetchIDs flaky test

src/aggregator/client/tcp_client.go, src/aggregator/client/tcp_client_test.go
When TCP Client fails to get placement from KV (f.e. on network partition) on Init() it will return an error, but placementWatcher still does the right thing and tries to reconnect to KV. Before it does so, however, it will return a nil stagedPlacement and any other client methods which read the placement will panic due to NPE.
This PR makes it return an error instead, so client's callers can retry writes on errors and once connection to KV is restored the client will pick up the placement.
```release-note
NONE
```
```documentation-note
NONE
```
=> [aggregator] Prevent tcp client panic on nil placement

src/query/api/v1/handler/graphite/render.go, src/query/graphite/native/aggregation_functions.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go, src/query/graphite/native/summarize.go, src/query/graphite/ts/sortable_series.go, src/query/graphite/ts/sortable_series_test.go
Fixes the Graphite sorting and reduce functions to be deterministic if there is multiple ranked series at the same sort order. This is done by using sort.Stable and if there was no incoming sort order into the function then applying sort by name to have determinism on which sort.Stable will pick as results.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Add determinism to Graphite sorting and reduce functions

src/dbnode/network/server/tchannelthrift/node/service_test.go, src/dbnode/persist/types.go, src/dbnode/storage/bootstrap/bootstrapper/fs/source_index_test.go, src/dbnode/storage/namespace.go, src/dbnode/storage/series/reader_test.go, src/dbnode/storage/series/series.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go, src/query/graphite/native/aggregation_functions_test.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go
Adds abort method to the cold flusher. 
Abort building reverse index if an error is encountered during tile aggregation.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add abort method to cold flusher.

src/aggregator/aggregator/aggregator.go
Placement/shard lookup is pretty expensive for every incoming metric, has loads and loads of locks, yet there's no need to run a hash over metric ID under a read lock.
```release-note
```
```documentation-note
```
=> [aggregator] Move shardID calculation out of lock

src/aggregator/server/rawtcp/server.go
The errors escape to the heap for no good reason, and makes rate-limiting more expensive than it should be:
```
src/aggregator/server/rawtcp/server.go:146:27: addUntimedError literal escapes to heap
src/aggregator/server/rawtcp/server.go:150:27: addUntimedError literal escapes to heap
src/aggregator/server/rawtcp/server.go:154:27: addUntimedError literal escapes to heap
src/aggregator/server/rawtcp/server.go:158:29: addForwardedError literal escapes to heap
src/aggregator/server/rawtcp/server.go:162:25: addTimedError literal escapes to heap
src/aggregator/server/rawtcp/server.go:166:25: addTimedError literal escapes to heap
src/aggregator/server/rawtcp/server.go:170:31: addPassthroughError literal escapes to heap
```
**Special notes for your …
=> [aggregator] Reduce error handling overhead in rawtcp server

src/aggregator/aggregator/aggregator.go, src/aggregator/aggregator/aggregator_test.go
Timers in AddUntimed/etc. methods are usually heavily sampled, however the way it was recorded always recorded current time, which adds up to non-trivial overhead (1% of the profile or so).
This moves the timing logic to the (sampled) stopwatch.
```release-note
```
```documentation-note
```
=> [aggregator] Sample timers completely

src/x/instrument/methods.go, src/x/instrument/methods_benchmark_test.go
```
name                             old time/op  new time/op  delta
SampledTimer                     18.0ns ± 3%  11.0ns ± 5%  -38.92%  (p=0.000 n=9+9)
SampledTimer-6                   33.5ns ± 2%   2.1ns ±11%  -93.59%  (p=0.000 n=9+10)
SampledTimer-12                  30.5ns ± 7%   1.6ns ± 5%  -94.80%  (p=0.000 n=10+10)
SampledTimerLowRate              18.0ns ± 4%  10.6ns ± 1%  -40.76%  (p=0.000 n=10+10)
SampledTimerLowRate-6            33.5ns ± 2%   2.0ns ± 2%  -94.17%  (p=0.000 n=10+8)
SampledTimerLowRate-12           29.5ns ± 5%   1.6ns ± 6%  -94.65%  (p=0.000 n=10+10)
SampledTimerStopwatch             100ns ± 2%    89ns ± 1%  -11.12%  (p=0.000 n=10+10)
SampledTimerStopwatch-6          37.3ns ± 3%  16.1ns ± 4%  -56.89%  (p=0.000 n=10+10) …
```
=> [instrument] Improve sampled timer and stopwatch performance

src/dbnode/storage/index/block.go, src/dbnode/storage/index/filter_fields_iterator.go, src/dbnode/storage/index/filter_fields_iterator_test.go
Do not close reader in filterFieldsIterator.Close()
NONE
NONE
=> [m3db] Do not close reader in filterFieldsIterator.Close()

src/aggregator/aggregator/entry.go, src/aggregator/aggregator/entry_benchmark_test.go, src/aggregator/aggregator/forwarded_writer.go, src/metrics/metadata/metadata_benchmark_test.go, src/metrics/pipeline/applied/type.go, src/metrics/pipeline/applied/type_test.go, src/metrics/pipeline/type.go
Turns out Go was unable to inline most of the comparison logic, adding function call and copy overhead for metadata:
```
name                  old time/op    new time/op    delta
AggregationValues-12     105ns ± 0%      43ns ± 1%  -58.70%  (p=0.000 n=8+8)
```
```release-note
```
```documentation-note
```
=> [aggregator] Avoid large copies in entry rollup comparisons by making them more inline-friendly

src/cluster/placement/staged_placement.go, src/cluster/placement/staged_placement_test.go
Relax closing semantics, as it's causing spurious errors - previously, the locking guaranteed precise ordering, but in either case the placement itself is not invalidated just because it is going to be updated and was closed.
```release-note
```
```documentation-note
```
=> [aggregator] Fix change ActivePlacement semantics on close

src/dbnode/integration/commitlog_bootstrap_helpers.go, src/dbnode/network/server/tchannelthrift/context.go, src/dbnode/network/server/tchannelthrift/node/fetch_result_iter_test.go, src/dbnode/network/server/tchannelthrift/node/service.go, src/dbnode/persist/fs/retriever.go, src/dbnode/storage/bootstrap.go, src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go, src/dbnode/storage/bootstrap/util.go, src/dbnode/storage/index.go, src/dbnode/storage/index/block.go, src/dbnode/storage/index_test.go, src/dbnode/storage/limits/permits/lookback_limit_permit.go, src/dbnode/storage/namespace_test.go, src/x/context/context.go, src/x/context/context_test.go, src/x/context/types.go
The go ctx was always being populated by the thrift server. A few
non-rpc processes, like the bootstrapper, needed to be updated to use
NewBackground instead of NewContext.
Now all m3 code can safely assume a go ctx is always present, instead of
having to check for it.
Fixes #
```release-note
```
```documentation-note
```
=> Remove optional go ctx from m3 ctx

src/cmd/services/m3coordinator/downsample/downsampler_test.go
This adds test coverage for the use case of transforming values without rolling them up with a rollup step.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Add downsampler integration test to add coverage for transforming values without rollup step

src/dbnode/storage/id_list_gen.go, src/x/context/finalizeable_list_gen.go, src/x/generics/list/list.go
The data race is reading the value after the element has been put back
in the pool. Another goroutine can get the element out of pool before
the value is read again.
This was not causing an actual production issue because no caller
actually uses the returned value from Remove. However, it did cause
data race failures in tests when run with -race.
```
WARNING: DATA RACE
Write at 0x00c063a621d8 by goroutine 3582:
github.com/m3db/m3/src/x/context.(*finalizeableList).insertValue()
/Users/rhall/go/src/github.com/m3db/m3/src/x/context/finalizeable_list_gen.go:202 +0xa8
github.com/m3db/m3/src/x/context.(*finalizeableList).PushBack()
/Users/rhall/go/src/github.com/m3db/m3/src/x/context/finalizeable_list_gen.go:239 +0x96
github.com/m3db/m3/src/x/context.(*ctx).registerFinalizeable() …
```
=> Fix data race in genny list Remove

src/dbnode/network/server/tchannelthrift/node/service_test.go, src/dbnode/server/server.go, src/dbnode/storage/limits/permits/lookback_limit_permit.go, src/dbnode/storage/limits/permits/lookback_limit_permit_test.go, src/dbnode/storage/limits/query_limits.go, src/dbnode/storage/limits/query_limits_test.go
Bytes read limit was not being reported correctly because while tally allows metrics with the same `__name__` but different numbers of tags, prometheus does not, erroring silently.
=> [dbnode] Fix jagged metrics issue

src/m3ninx/index/segment/fst/segment.go
Fixes a `uint` underflow in `fst/segment.go`. This was revealed by a panic in one of the BK builds: https://buildkite.com/uberopensource/m3-monorepo-public/builds/7365#e2f76bc7-6a2c-49ba-892a-899f9db9caf7/5333-5542
```release-note
NONE
```
```documentation-note
NONE
```
=> [m3ninx] Fix uint underflow in segment.go

src/dbnode/storage/bootstrap/bootstrapper/fs/options.go
Removes some unused options in fs bootstrapper code to reduce confusion.
NONE
NONE
=> [dbnode] Remove unused fs bootstrapper options

src/cmd/services/m3coordinator/downsample/downsample_mock.go, src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/metrics_appender_test.go, src/cmd/services/m3coordinator/downsample/samples_appender.go, src/cmd/services/m3coordinator/ingest/write.go, src/cmd/services/m3coordinator/ingest/write_test.go, src/metrics/metric/types.go, src/query/generated/mocks/generate.go
This change adds a new m3 special tag `__m3_drop_timestamp` supported by mapping rules that indicate we should drop the timestamp and send metrics to be aggregated untimed..
None
None
=> [coordinator] add mapping rule m3 tag to drop timestamp

src/dbnode/integration/integration.go, src/dbnode/integration/peers_bootstrap_index_aggregate_test.go, src/dbnode/integration/peers_bootstrap_index_test.go
Changes default final bootstrapper in integration tests to `NoOpNoneBootstrapper`, which propagates unfulfilled ranges from the previous steps. This makes it more likely that a regressions in bootstrap process will result in failing tests. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [tests] Change default final bootstrapper to NoOpNoneBootstrapper

src/dbnode/network/server/tchannelthrift/node/service.go, src/dbnode/storage/limits/permits/lookback_limit_permit.go, src/dbnode/storage/limits/permits/lookback_limit_permit_test.go, src/dbnode/storage/limits/permits/noop_permit.go, src/dbnode/storage/limits/permits/types.go
Checks that limit has not been exceeded to short circuit
=> [dbnode] Permit limit exceeded error propagation

src/aggregator/aggregation/quantile/cm/heap.go, src/aggregator/aggregation/quantile/cm/heap_pool.go
Slightly reduce the need for allocations by actually sizing the pool as indented in the comment and other minor tweaks
```
╰─$ benchstat old.txt new.txt
name                                                              old time/op    new time/op    delta
TimerValues-12                                                      32.3ns ± 1%    32.5ns ± 3%     ~     (p=0.770 n=5+5)
TimerValueOf-12                                                     69.6ns ± 1%    66.3ns ± 7%     ~     (p=0.151 n=5+5)
TimerAddBatch/100k_samples_1000_batch_size-12                       1.50ms ± 6%    1.53ms ± 8%     ~     (p=0.548 n=5+5)
TimerAddBatch/100k_samples_1000_batch_size_0..1,000,000_range-12    1.58ms ± 6%    1.56ms ±11%     ~     (p=0.548 n=5+5) …
```
=> [aggregator] Reduce timer stream allocs

src/query/api/v1/handler/namespace/update.go, src/query/api/v1/handler/namespace/update_test.go
Allows updating `namespace.extendedOptions` field via the API.
NONE
NONE
=> [dbnode] Namespace extended options mutable

go.sum, src/cmd/services/m3coordinator/downsample/downsample_mock.go, src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/options.go, src/cmd/services/m3coordinator/downsample/samples_appender.go, src/cmd/services/m3coordinator/ingest/write.go, src/cmd/services/m3coordinator/ingest/write_test.go, src/metrics/metadata/metadata.go
This PR adds support for the drop timestamp tag to universally drop the timestamp while sending the metric to the aggregator.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] make drop timestamp apply to the metric rather than specific rule

src/dbnode/integration/fetch_tagged_quorum_test.go, src/dbnode/integration/index_multiple_node_high_concurrency_test.go, src/dbnode/integration/setup.go, src/dbnode/integration/write_quorum_test.go, src/dbnode/integration/write_read_high_concurrency_test.go, src/dbnode/integration/write_tagged_quorum_test.go
Removes a few more usages of `NoOpAllBootstrapper` from integration tests
```release-note
NONE
```
```documentation-note
NONE
```
=> [tests] Remove a few more usages of NoOpAllBootstrapper from tests

src/aggregator/aggregator/aggregator.go, src/aggregator/aggregator/aggregator_mock.go, src/aggregator/aggregator/aggregator_test.go, src/aggregator/aggregator/placement_mgr.go, src/aggregator/aggregator/placement_mgr_options.go, src/aggregator/aggregator/placement_mgr_test.go, src/aggregator/integration/setup.go, src/cluster/placement/placements_watcher.go, src/cmd/services/m3aggregator/config/aggregator.go, src/cmd/services/m3coordinator/downsample/options.go
This change reduces lock contention by doing less work on the hot path. It also changes the error returned in some cases to shard not owned, not aggregator is not open - the difference is a semantic one, since it's just a guard against initialization bugs.
```release-note
```
```documentation-note
```
=> [aggregator] Move placement checks to a background job

src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/metrics_appender_test.go, src/cmd/services/m3coordinator/ingest/write.go, src/cmd/services/m3coordinator/ingest/write_test.go, src/metrics/metric/types.go
Today we only support filtering on m3 metric type.
Fixes #
```release-note
```
```documentation-note
```
=> [coordinator] Enable rule filtering on prom metric type

src/msg/producer/writer/message_writer.go, src/msg/producer/writer/message_writer_benchmark_test.go, src/msg/producer/writer/message_writer_test.go
Reduce overhead in m3msg queue scans, since we're doing a lot of atomic ops, time calls unnecessarily and it's quite visible in profiles.
Benchmark is not fully representative, as it's quite an effort to write a good one:
```
name              old time/op  new time/op  delta
ScanMessageQueue   351ns ± 3%   286ns ± 2%  -18.36%  (p=0.008 n=5+5)
```
It does however make it more consistent on actual prod workloads:
```release-note
```
```documentation-note
```
=> [m3msg] Improve message scan performance

src/metrics/aggregation/id.go, src/metrics/aggregation/id_test.go, src/metrics/encoding/protobuf/unaggregated_encoder_test.go, src/metrics/generated/proto/metricpb/composite.pb.go, src/metrics/metadata/metadata.go, src/metrics/metadata/metadata_benchmark_test.go, src/metrics/metadata/metadata_test.go, src/metrics/metric/aggregated/types_test.go, src/metrics/pipeline/applied/type.go, src/metrics/pipeline/applied/type_test.go, src/metrics/policy/storage_policy.go, src/metrics/transformation/type.go, src/x/time/unit.go
This is a ton of ugly code to speed up metadata mapping from proto to domain level structs, and is on very hot path.
```
name                                    old time/op    new time/op    delta
Metadata_FromProto/large_metadatas-12      101ns ± 1%      55ns ± 4%  -46.22%  (p=0.000 n=9+10)
Metadata_FromProto/small_metadatas-12     46.9ns ± 1%    28.9ns ± 2%  -38.28%  (p=0.000 n=9+10)
Metadata_FromProto/storage_policies-12    56.8ns ± 2%    26.3ns ± 1%  -53.64%  (p=0.000 n=10+9)
Metadata_FromProto/all-12                  200ns ± 1%     105ns ± 1%  -47.80%  (p=0.000 n=8+10)
```
```release-note
```
**Does this PR require updating code …
=> Optimize StagedMetadatas conversion

src/aggregator/aggregator/flush_mgr_options.go, src/aggregator/aggregator/follower_flush_mgr.go, src/aggregator/aggregator/follower_flush_mgr_test.go, src/aggregator/aggregator/leader_flush_mgr_test.go, src/aggregator/aggregator/options.go, src/aggregator/integration/setup.go, src/cmd/services/m3aggregator/config/aggregator.go
https://github.com/m3db/m3/pull/2818 introduced a special case handling for resolution windows that have not been flushed yet by the leader, but it did not take `BufferPast` into account for timed metrics.
This PR adds the logics to  take `BufferPast` into account for timed metrics.
NONE
NONE
=> [aggregator] CanLead for unflushed window takes BufferPast into account

scripts/docker-integration-tests/m3aggregator.Dockerfile, scripts/docker-integration-tests/m3coordinator.Dockerfile, scripts/docker-integration-tests/m3dbnode.Dockerfile, scripts/dtest/docker-compose.yml, src/dbnode/client/session_aggregate_test.go, src/dbnode/client/session_fetch_tagged_test.go, src/dbnode/persist/fs/files_test.go, src/dbnode/persist/fs/index_claims_manager_test.go, src/dbnode/persist/fs/persist_manager_test.go, src/dbnode/storage/fs_test.go, src/dbnode/storage/index_block_test.go, src/dbnode/storage/namespace_test.go, src/query/storage/m3/storage_test.go, src/x/instrument/invariant.go, src/x/instrument/invariant_test.go
Helpful for catching issues before they are released.
Fixes #
```release-note
```
```documentation-note
```
=> Enable PANIC_ON_INVARIANT_VIOLATED for tests

src/cmd/services/m3dbnode/config/pooling.go, src/dbnode/client/session.go, src/dbnode/encoding/multi_reader_iterator_array_pool.go, src/dbnode/encoding/mutable_series_iterators_pool.go, src/dbnode/server/server.go, src/msg/consumer/config.go, src/msg/protocol/proto/roundtrip_test.go, src/query/ts/m3db/options.go, src/x/pool/bucketized.go, src/x/pool/bytes_test.go, src/x/pool/checked_bytes_test.go, src/x/pool/config.go, src/x/pool/config_test.go, src/x/pool/floats_test.go, src/x/pool/object.go, src/x/pool/object_test.go, src/x/pool/options.go, src/x/pool/types.go
If pool size in config is set to `dynamic`, the backing pool will be simply a wrapped `sync.Pool`.
```
name                                                 time/op
ObjectPoolParallelGetMultiPutContended               1.24µs ± 0%
ObjectPoolParallelGetMultiPutContended-12            2.98µs ± 0%
ObjectPoolParallelGetMultiPutContendedDynamic         818ns ± 0%
ObjectPoolParallelGetMultiPutContendedDynamic-12      203ns ± 5%
ObjectPoolParallelGetMultiPutContendedWithRefill     1.23µs ± 1%
ObjectPoolParallelGetMultiPutContendedWithRefill-12  3.10µs ± 5%
```
```release-note
```
**Does this PR require updating code package or user-facing …
=> [pool] Add support for dynamic, sync.Pool backed, object pools

src/aggregator/aggregation/quantile/cm/heap.go, src/aggregator/aggregation/quantile/cm/heap_test.go, src/aggregator/aggregation/quantile/cm/stream.go
A few more small timer aggregation tweaks.
Total throughput with 12 concurrent streams:
```
name                                                              old speed      new speed      delta
TimerAddBatch/100k_samples_1000_batch_size-12                      604MB/s ± 3%   633MB/s ± 0%   +4.84%  (p=0.008 n=5+5)
TimerAddBatch/100k_samples_1000_batch_size_0..1,000,000_range-12   555MB/s ± 5%   635MB/s ± 0%  +14.50%  (p=0.008 n=5+5)
TimerAddBatch/100k_samples_1000_batch_size_0..100,000_range-12     567MB/s ± 1%   584MB/s ± 5%     ~     (p=0.151 n=5+5)
TimerAddBatch/10k_samples_1000_batch_size-12                       543MB/s ± 2%   590MB/s ± 2%   +8.54%  (p=0.008 n=5+5)
TimerAddBatch/10k_samples_100_batch_size-12                        536MB/s ± 1% …
```
=> [aggregator] Sort heap in one go, instead of iterating one-by-one

src/x/instrument/extended.go
In some environments FD metrics are already provided by cluster manager/other agents on host, so counting them in services with high number of connections is extra overhead and that cannot be disabled.
```release-note
Add `runtime` as an option to extended runtime metrics, that will only emit internal Go runtime metrics.
```
```documentation-note
```
=> [instrument] Config option to emit detailed Go runtime metrics only

src/query/api/v1/handler/ready.go, src/query/api/v1/handler/ready_test.go
`ready` endpoint was panicking when `cluster/namespaces` was not configured (which can be the case for the admin coordinator).
```release-note
```
```documentation-note
```
=> [coordinator] Fix panic in Ready endpoint for admin coordinator

src/aggregator/aggregator/entry.go, src/aggregator/aggregator/entry_test.go
Ensure that there is at least one provided staged metadata,
and that it is not the default staged metadata.
Without such checks, the processing can result in
working off of an empty `metadata.TimedMetadata{}`,
which can `panic()` when processing due to its 0 resolution.
Fixes #
```release-note
```
```documentation-note
```
=> [aggregator] Add validation in AddTimedWithStagedMetadatas

src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/options.go, src/cmd/services/m3coordinator/downsample/samples_appender.go, src/metrics/metadata/metadata.go
This change adds a coordinator config option to force all rollup rules to be considered as untimed.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Add config option to make rollup rules untimed

src/dbnode/persist/fs/msgpack/stream_test.go, src/dbnode/persist/fs/read_test.go, src/query/functions/aggregation/absent_test.go, src/query/functions/aggregation/base_test.go, src/query/functions/aggregation/count_values_test.go, src/query/functions/aggregation/take_test.go, src/query/functions/binary/and_test.go, src/query/functions/binary/binary_test.go, src/query/functions/binary/or_test.go, src/query/functions/binary/unless_test.go, src/query/functions/fetch_test.go, src/query/functions/linear/clamp_test.go, src/query/functions/linear/datetime_test.go, src/query/functions/linear/histogram_quantile_test.go, src/query/functions/linear/math_test.go, src/query/functions/linear/round_test.go, src/query/functions/linear/sort_test.go, src/query/functions/scalar/scalar_test.go, src/query/functions/scalar/time_test.go, src/query/functions/tag/join_test.go, src/query/functions/tag/replace_test.go, src/query/functions/temporal/base_test.go, src/query/functions/unconsolidated/timestamp_test.go, src/query/parser/promql/parse.go
Fixes #
```release-note
```
```documentation-note
```
=> Fix new Go 1.15+ vet check failures

scripts/docker-integration-tests/prometheus/test.sh, src/query/api/v1/handler/graphite/find.go, src/query/api/v1/handler/graphite/render.go, src/query/api/v1/handler/prom/read.go, src/query/api/v1/handler/prom/read_test.go, src/query/api/v1/handler/prometheus/common.go, src/query/api/v1/handler/prometheus/common_test.go, src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go, src/query/api/v1/handler/prometheus/handleroptions/header_test.go, src/query/api/v1/handler/prometheus/handleroptions/headers.go, src/query/api/v1/handler/prometheus/native/common.go, src/query/api/v1/handler/prometheus/native/complete_tags.go, src/query/api/v1/handler/prometheus/native/list_tags.go, src/query/api/v1/handler/prometheus/native/read.go, src/query/api/v1/handler/prometheus/native/read_common.go, src/query/api/v1/handler/prometheus/remote/match.go, src/query/api/v1/handler/prometheus/remote/read.go, src/query/api/v1/handler/prometheus/remote/tag_values.go, src/query/models/query_context.go, src/query/server/query.go, src/query/storage/types.go, src/query/util/json/noop_writer.go, src/query/util/json/writer.go, src/query/util/json/writer_test.go, src/x/headers/headers.go
Adds ability to trim series metadata / label metadata via header.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Add series metadata label limit header for trimming response

src/dbnode/storage/shard_test.go
Noticed some more leftovers, cleaning up.
NONE
NONE
=> [dbnode] Remove unused getMockReader

src/x/clock/offset_clock.go, src/x/clock/offset_clock_test.go
Adds `OffsetClock` constructor that uses given time delta instead of a particular `time.Time` in the past/future.
```release-note
NONE
```
```documentation-note
NONE
```
=> [x] Add OffsetClock constructor that uses given time delta

Makefile, src/cmd/tools/read_commitlog/README.md, src/cmd/tools/read_commitlog/main/main.go, src/cmd/tools/read_data_files/main/main.go, src/dbnode/persist/fs/commitlog/commit_log_test.go, src/dbnode/persist/fs/commitlog/iterator.go, src/dbnode/persist/fs/commitlog/reader.go
Implements a new command line utility for reading M3DB commit log files.
NONE
NONE
=> [tools] read_commitlog util

site/content/operational_guide/etcd.md
Fixes #
```release-note
```
```documentation-note
```
=> [Docs] -- Adding clarification around etcd and M3 to etcd operational guide

src/aggregator/aggregator/list.go, src/aggregator/aggregator/list_test.go, src/aggregator/aggregator/options.go, src/cmd/services/m3aggregator/config/aggregator.go
Adds configuration flag (`timedMetricsFlushOffsetEnabled`) to aggregator config, to control the use of flush offset for timed metrics. The default is `false` to preserve the original behaviour (before https://github.com/m3db/m3/pull/3292).
NONE
NONE
=> [aggregator] A flag to enable FlushOffset for timed metrics

src/query/graphite/graphite/glob.go, src/query/graphite/graphite/glob_test.go
This matches the behavior of graphite-web to allow ** to match empty path segments (i.e. `foo.**.bar` should match both `foo.abc.bar` and `foo.bar`).
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Match graphite-web Graphite ** to allow for empty segment path selector to match elements

src/query/graphite/native/aggregation_functions_test.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go, src/query/graphite/ts/series.go, src/query/graphite/ts/sortable_series_test.go
Adds natural and reverse args to sortByName and implements the generic sortBy function.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Add Graphite sortByName natural and reverse args and generic sortBy

src/query/graphite/native/builtin_functions.go
Uses the standard underlying moving binary transform for `exponentialMovingAverage`.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Cleanup exponentialMovingAverage implementation to use standard moving function semantics

src/aggregator/client/queue.go, src/aggregator/client/queue_test.go
It's not always a good idea to write everything in one go, as calls may time out just because the buffer is in the megabytes+ range - we should write it out in parts instead. It also should make the buffer allocs bounded, as right now we can end up doing a lot of throwaway work if a shard is really hot, etc.:
```release-note
```
```documentation-note
```
=> [aggregator] Limit size of written buffers in rawtcp client

src/aggregator/aggregator/aggregator.go, src/aggregator/aggregator/aggregator_test.go
Right now, errors due to data points arriving too
late from forwarding get grouped into not-categorized.
This change splits it into its own value, arrived-too-late.
Fixes #
```release-note
```
```documentation-note
```
=> [aggregator] Split out errArrivedTooLate out of not-categorized

src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/metrics_appender_test.go, src/cmd/services/m3coordinator/downsample/samples_appender.go
This change adds a processed counter metric in the coordinator that tracks the number of times a metric is processed by the aggregator.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] add a processed counter metric

src/x/pool/config.go, src/x/pool/config_test.go, src/x/pool/options.go
Adds support to various places that don't take object pool options directly, like m3db node client.
```release-note
```
```documentation-note
```
=> [pool] Enable dynamic pool sizing in uses that don't expose pool options

src/dbnode/encoding/m3tsz/roundtrip_test.go, src/dbnode/encoding/m3tsz/timestamp_iterator.go, src/dbnode/ts/types.go
Typical annotation size is only few bytes. This change avoids allocating annotation slices in `TimestampIterator` for anything that fits in 16 bytes, reducing memory pressure during time series decoding.
NONE
NONE
=> [dbnode] Avoid allocating small annotations from TimestampIterator

src/aggregator/aggregator/aggregator_test.go, src/aggregator/aggregator/elem_base_test.go, src/aggregator/aggregator/elem_pool_test.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/entry_pool_test.go, src/aggregator/aggregator/options.go, src/aggregator/aggregator/options_test.go, src/aggregator/aggregator/shard_test.go, src/aggregator/integration/setup.go, src/aggregator/server/server.go, src/cmd/services/m3aggregator/config/aggregator.go, src/cmd/services/m3coordinator/downsample/options.go
Yet another code fix for clock not being propagated where needed.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Fix clock not being propagated where needed

.golangci.yml, src/dbnode/storage/index/fields_terms_iterator_test.go, src/dbnode/storage/namespace_test.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go, src/query/graphite/native/engine_test.go
Fixes case when the original start/end time returns no series but the bootstrapped time range should evaluate the historical data captured by the "moving" time window specified.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite moving fns not evaluating bootstrapped series when current time window has no series

go.mod, go.sum, src/cmd/services/m3dbnode/config/pooling.go, src/cmd/services/m3dbnode/config/pooling_test.go, src/dbnode/server/server.go
A single byte slice pool was used for incoming thrift requests, with default capacity of 2048 bytes. This was wasteful as many of the slices are much shorter than that. This change updates thrift dependency to the version with multiple capacity pooling, and configures it to use capacities of {16, 64, 256, 512, 1024, 2048} bytes.
NONE
NONE
=> [dbnode] Use multiple thrift byte slice pools

src/dbnode/storage/namespace.go, src/dbnode/storage/namespace_test.go
Skip bootstrapping shards from aggregation.
NONE
NONE
=> [dbnode] Skip bootstrapping shards from aggregation

src/query/graphite/common/test_util.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go, src/query/graphite/native/engine_test.go, src/query/graphite/native/expression.go, src/query/graphite/native/functions.go
Fixes calculation of EMA constant value which was using the window points, not the window size in seconds like the original graphite implementation:
https://github.com/graphite-project/graphite-web/blob/f1acda6590627dabccf877ed309f28b7a7263374/webapp/graphite/render/functions.py#L1373
Also fixes the implementation to always return a single timeseries, not two. Before the binary moving transform was evaluating the same timeseries but not lining them up after doing the time shift since sometimes the names of the functions (if using sumSeries over a set of series which changes their name due to ordering) didn't line up between bootstrapped and original series loaded for time window.
Now we just use a unary transformer and just load the whole time range …
=> [query] Fix Graphite exponentialMovingAverage to use correct EMA const and return single series per input series

src/dbnode/encoding/m3tsz/iterator.go, src/dbnode/encoding/m3tsz/iterator_test.go
Depends on #3405
Perf impact is negligible.
```
name            old time/op  new time/op  delta
M3TSZDecode-12  29.6µs ± 0%  29.8µs ± 0%  +0.54%  (p=0.008 n=5+5)
M3TSZEncode-12  69.6µs ± 1%  70.0µs ± 1%    ~     (p=0.151 n=5+5)
```
```release-note
```
```documentation-note
```
=> [dbnode] Decoder: fix handling of values requiring 64bit precision

src/query/graphite/native/builtin_functions.go, src/query/graphite/native/functions.go
Previously this optimization was removed since moving functions which started using the unary context shifter actually needed access to the initial fetch of data, but this does add considerable load when timeShift is used extensively with a lot of alerts.
Restoring this optimization for that use case.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Restore optimization to skip initial fetch for timeShift and unary fns

src/dbnode/storage/series/series_parallel_test.go, src/dbnode/storage/series/series_test.go
This is a timing issue and the buffer past was only set to 1 second in the test options, increasing to 90 seconds is much more lenient for this intensive unit test (marked as "big" since it's more integration like).
Before:
```
go test -v -failfast -run TestSeriesWriteReadParallel -count 100 -tags big -race
=== RUN   TestSeriesWriteReadParallel
panic: datapoint too far in past: id=foo, off_by=134.750835ms, timestamp=13 Apr 21 13:48 -0400, past_limit=13 Apr 21 13:48 -0400, timestamp_unix_nanos=1618336092865249165, past_limit_unix_nanos=1618336093000000000
goroutine 8 [running]:
github.com/m3db/m3/src/dbnode/storage/series.TestSeriesWriteReadParallel.func1(0x2710, 0xc002259a40, 0x20d19a0, 0xc002e41490, 0xc015943733929748, 0x12571266, 0x2821ec0, …
```
=> [dbnode] Fix TestSeriesWriteReadParallel datapoints too far in past with -race flag

src/x/sync/pooled_worker_pool.go
This ensures a new worker is spawned if all workers are currently busy.
With buffered channels, a unit of work might get scheduled on a channel
where the worker is currently processing a long request. That unit of
work will get starved until the long request is complete.
For example in the host_queue worker pool, a long query request might
take 2 mins to complete. An unrelated request might get buffered on that
same chanel and won't get processed for 2 mins.
Also fixed a bug in the host_queue that did not cleanup if the work was
never scheduled due to a context timeout.
Fixes #
```release-note
```
**Does this PR require updating code …
=> Do not use buffer channels if growOnDemand is true

site/content/how_to/m3aggregator.md
Fixes #
```release-note
```
```documentation-note
```
=> [docs] Fix m3aggregagtor typo

src/dbnode/client/client_mock.go, src/dbnode/client/host_queue.go, src/dbnode/client/host_queue_aggregate_test.go, src/dbnode/client/host_queue_fetch_tagged_test.go, src/dbnode/client/options.go, src/dbnode/client/types.go, src/dbnode/integration/query_cancellation_client_test.go
The write code path frequently stack splits but the query path does not and ends up artificially delayed by the host queue flush interval. This removes using the worker pool and also avoids going through the host queue drain/rotate cycle which is delayed by the host queue flush interval.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Avoid use of grow on demand worker pool for fetchTagged and aggregate

src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/metrics_appender_test.go, src/cmd/services/m3coordinator/downsample/samples_appender.go
This PR adds additional information to the processed count metric - indicating if it was processed due to rollup or not.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] add more information to processed count metric

src/dbnode/storage/bootstrap/bootstrapper/peers/source_data_test.go
Fixes data races in source_data_test.go that manifest when changing concurrency options.
NONE
NONE
=> [dbnode] Fix races in source_data_test.go

scripts/dtest/docker-compose.yml
Fixes dtest docker compose config, renaming `env` to [`environment`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment).
```release-note
NONE
```
```documentation-note
NONE
```
=> [dtest] Fix dtest docker compose config: env => environment

src/cmd/services/m3dbnode/config/bootstrap.go, src/dbnode/storage/bootstrap/bootstrapper/peers/options.go
Fixes #3286: when only a subset of `BootstrapPeersConfiguration` parameters were supplied in config, others defaulted to 0 instead of default values mentioned in parameter description. 
https://github.com/m3db/m3/blob/37e8c9b3557a5b3a97513db3bfbcce9dea7d74bc/src/cmd/services/m3dbnode/config/bootstrap.go#L250-L263
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Set default values for BootstrapPeersConfiguration

src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/metrics/aggregation/type.go, src/metrics/metric/types.go
This change adds a new custom tag in the coordinator that will augment the prometheus quantile tag on metrics.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] support for augmenting prom quantiles

src/dbnode/network/server/tchannelthrift/node/service_test.go, src/dbnode/persist/fs/commitlog/commit_log_test.go, src/dbnode/server/server.go, src/dbnode/storage/options.go, src/dbnode/ts/writes/write_batch.go, src/dbnode/ts/writes/write_batch_pool.go, src/dbnode/ts/writes/write_batch_test.go
In some cases we have to handle write batches that are an order of magnitude smaller than the default expected size (128).
Thus, always preallocating the default size (which results in 49152 bytes allocated) is really wasteful.
This PR attempts to avoid preallocating write batches of the given size, and instead defers allocation to a later time, when the actual batch size is known. Then slices of the needed capacity (plus 20% more) are allocated. Allocating 20% more than needed for the current write batch should help avoid subsequent allocations when the same write batch is taken from the pool and is used for another write batch of slightly bigger size.
The original behaviour is preserved in case …
=> [dbnode] Adaptive WriteBatch allocations

src/x/cache/lru_cache.go, src/x/cache/lru_cache_test.go
Under the following (rarely observed in practice) conditions, `LRU.reserveCapacity` would go into an infinite loop under a lock, perpetually blocking any further uses of LRU cache:
- the cache full to `maxEntries` or above
- there are duplicate elements in `byAccessTime`/ `byLoadTime` lists for the same entry (which would happen as a result of double `Put`)
- an attempt to `Get` a non-existing key is made
This PR:
1. Adds a unit test `TestLRU_GetNonExisting_FromFullCache_AfterDoublePut` that reproduces the situation described above.
2. Fixes the issue by preventing duplicate elements in `byAccessTime`/ `byLoadTime` lists (if an element is already in the list, it is now moved to front, instead of repeatingly inserting it to the front).
**Special …
=> Fix LRU cache locking up

src/query/graphite/common/aliasing.go, src/query/graphite/native/alias_functions.go, src/query/graphite/native/alias_functions_test.go, src/query/graphite/native/expression.go, src/query/graphite/native/functions.go
This fixes aliasByNode to match the original Graphite implementation which tokenizes and compiles the series name to detect the first path expression.
This can be seen here with aggKey which is called by aliasByNode:
https://github.com/graphite-project/graphite-web/blob/19f2155a8902f1dc075d4276d384409f1c006764/webapp/graphite/render/functions.py#L111-L115
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite aliasByNode to compile and use the first path expr instead of string check for function

src/x/cache/lru_cache.go, src/x/cache/lru_cache_test.go
A previous commit stopped creating loading channels if the loader is
nil. However, it was not completely correct and would still create a
channel if the entry was expired.
Fixes #
```release-note
```
```documentation-note
```
=> Do not create a loadingCh for expired entries, if loader is nil

src/aggregator/aggregator/aggregator_mock.go, src/aggregator/aggregator/election_mgr.go, src/aggregator/aggregator/election_mgr_test.go, src/aggregator/aggregator/placement_mgr.go, src/aggregator/aggregator/placement_mgr_test.go
Adds a special case to the aggregator election manager - allowing the instance with **no shards** to take the leadership if it is the only instance owning this shard set.
This is needed for limited duration, during cluster expansion, when adding new instances.
NONE
NONE
=> [aggregator] Allow campaigning with no shards

src/dbnode/storage/bootstrap/result/shard_ranges.go, src/dbnode/storage/bootstrap/result/shard_ranges_test.go, src/dbnode/storage/bootstrap/result/types.go, src/dbnode/storage/cleanup.go, src/dbnode/storage/cleanup_test.go, src/dbnode/storage/index.go, src/dbnode/storage/index_test.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go
Updates the logic of index fileset volume cleanup. This change mitigates the cases where recent volumes were not cleaned up after the shards owned by the dbnode changes.
For example, if we have following volumes:
```
volume index | shard list
0            | 0, 1
1            | 0, 1   // shard ownership changes due to modified topology
2            | 0
3            | 0
4            | 0
``` 
Previous cleanup logic would fail to delete some redundant volumes:
```
volume index | shard list
1            | 0, 1
2            | 0
3            | 0
4            | 0
```
After this change, the cleanup would leave following volumes
```
volume index | shard list
1            | 0, 1
4            | 0
```
**Does this PR introduce …
=> [dbnode] Update the logic of index fileset volume cleanup

src/dbnode/integration/setup.go, src/dbnode/persist/fs/migration/migration_test.go, src/dbnode/server/server.go, src/dbnode/storage/bootstrap/bootstrapper/fs/source_data_test.go, src/dbnode/storage/index/block_prop_test.go, src/dbnode/storage/index/postings_list_cache.go, src/dbnode/storage/index/postings_list_cache_test.go, src/dbnode/storage/index/read_through_segment_test.go, src/dbnode/storage/limits/query_limits.go, src/dbnode/storage/options.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go, src/dbnode/storage/util.go
Allowing multiple Transform functions is error prone when sub Options are
dependent on each other and you want to transform both. It's more
straight forward to Transform the top level Option in a single transform
function once.
Additionally, this delays Starting any Option until after the Tranform
is run, in case the originally Option value is transformed.
Fixes #
```release-note
```
```documentation-note
```
=> Replace db server.RunOptions with a single Transform function.

src/query/source/source.go, src/query/source/source_test.go
This middleware func populates the request context with the value of the
M3-Source header. Additionally it allows providing an optional
Deserializer to convert the header value into a more user friendly type
for the application layer. Both the typed and raw values are accessible
from the context. Most likely only other middleware will use the raw
bytes to forward along the source across api boundaries.
Additionally the Middleware uses the new request scoped logger to add
the source logging field.
Fixes #
```release-note
```
```documentation-note
```
=> Add Middleware to populate source in request context

src/cmd/tools/read_data_files/main/main.go
Adds a missing `reader.Close()` to `read_data_files` utility.
NONE
NONE
=> [tools] Close the reader in read_data_files

src/cmd/tools/read_data_files/main/main.go
Modifies `read_data_files` to use `StreamingRead`.
NONE
NONE
=> [tools] Use streaming reads in read_data_files

.buildkite/pipeline.yml
Temporarily disabling while codecov uploading is flaky
Fixes #
```release-note
```
```documentation-note
```
=> [buildkite] Remove codecov uploading from unit tests

src/cmd/services/m3coordinator/downsample/options.go, src/metrics/matcher/config.go, src/metrics/matcher/namespaces.go, src/metrics/matcher/namespaces_test.go, src/metrics/matcher/options.go
This option on the matcher will require that namespace
values and corresponding rulesets are loaded
in the matcher as part of startup.
This is useful in ensuring dynamic rules are loaded
before we start ingesting metrics.
Fixes #
```release-note
```
```documentation-note
```
=> [matcher] [coordinator] Add RequireNamespaceWatchOnInit option

README.md
Until we find another coverage option we should remove the CodeCov badge since it isn't able to process coverage results any longer.
Fixes #
```release-note
```
```documentation-note
```
=> [readme] Remove coverage badge due to CodeCov not able to execute

src/query/graphite/common/context.go, src/query/graphite/common/test_util.go, src/query/graphite/native/builtin_functions_test.go
Expansions of time windows need to be stacked not taken maximum of when creating context shifts so that the first few datapoints have enough of the inner shifted time window than the outer.
This affects calls such as the following missing the first few datapoints (as per test):
```
movingSum(movingSum(foo.bar,"2min"),"5min")
```
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite context time window expansions not being cumulative

src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go, src/query/graphite/native/compiler_test.go, src/query/graphite/native/functions.go
By default Graphite uses `nil` to mean take the sum of the numerator as the denominator. Using an empty list as the default value for the total arg causes it not to be interpreted as explicit `nil` and instead for it to treat it as an empty fetch expression that fetched no series which then causes an error (which is correct if you fetched no series, but in this case the correct behavior is to use the sum of the numerator as the denominator).
This also fixes Graphite function execution to allow passing explicit nil as arguments since before it would cause issues unwrapping the nil without checking during function call execution. …
=> [query] Fix Graphite nil arg not interpreted as explicit nil for asPercent

.golangci.yml, src/aggregator/integration/placement_change_test.go, src/dbnode/integration/bootstrap_retries_test.go, src/dbnode/integration/index_multiple_node_high_concurrency_test.go, src/dbnode/integration/peers_bootstrap_none_available_test.go, src/dbnode/integration/peers_bootstrap_partial_data_test.go, src/dbnode/integration/series_wired_list_panic_test.go, src/dbnode/integration/write_quorum_test.go, src/dbnode/integration/write_read_high_concurrency_test.go, src/dbnode/integration/write_tagged_quorum_test.go, src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_prop_test.go, src/dbnode/storage/index/block_prop_test.go, src/dbnode/storage/series/series_parallel_test.go
Adds missing build tags to linter configuration. Without these, some of the `*.go` files (mostly integration tests) were not linted.
```release-note
NONE
```
```documentation-note
NONE
```
=> [lint] Add missing build tags to linter configuration

src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go
Add movingWindow() functions
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Add Graphite movingWindow() function

src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go, src/query/api/v1/handler/prometheus/handleroptions/fetch_options_test.go
Using the timeout form param name for the header was incorrect. For
backwards compatibility we can still support it, but should encourage
clients to set the M3-Timeout header instead.
Fixes #
```release-note
```
```documentation-note
```
=> Support M3-Timeout header for request timeouts

src/query/api/v1/middleware/metrics.go, src/query/api/v1/middleware/metrics_test.go, src/query/api/v1/middleware/middleware.go, src/query/api/v1/middleware/middleware_test.go, src/query/api/v1/options/handler.go, src/query/util/queryhttp/queryhttp.go
This fixes a bug that was introduced with the middelware refactorings.
The RequestURI cannot be used because it may contain url encoded data.
Instead we want to use the Path registered with the mux.Route. This
required threading the mux.Route to the Middleware funcs.
Fixes #
```release-note
```
```documentation-note
```
=> Use the path template for the http handler metrics

src/aggregator/client/conn.go, src/aggregator/client/conn_test.go
There is a bug in the aggregator client connection retry logic: after the number of failures crosses the maximum configured threshold, the retries are attempted again on every write call without any backoff. That slows down flushing of forwarded metrics from healthy nodes to other healthy nodes and the receiving nodes reject them because they becom past their due time. This condition is triggered when there are dead nodes in the placement due to host(s) going hard-down and becoming unreachable. The healthy nodes still attempt to write forwarded metrics to dead nodes but always fail with tcp timeout errors.
Fix retry logic so that after the maximum threshold is reached, retry again only after the maximum duration time since last attempt.
**Does this …
=> [aggregator] connection retries must be bounded

src/query/api/v1/handler/prometheus/handleroptions/header_test.go, src/query/api/v1/handler/prometheus/handleroptions/headers.go, src/query/block/meta.go, src/query/storage/m3/consolidators/complete_tags_result.go, src/query/storage/m3/consolidators/complete_tags_result_test.go, src/query/storage/m3/consolidators/multi_fetch_result_tag_test.go, src/query/storage/m3/consolidators/multi_fetch_result_test.go, src/query/storage/m3/consolidators/series_fetch_result.go, src/x/headers/headers.go
Adds a returned header tracking the number of unique series included in the query.
=> [query] Return series count header

src/dbnode/encoding/m3tsz/iterator.go
Takes logic from the Current() function used to calculate the values
into the Next() function so that it will only be executed once.
Below benchmarks from running the `./bin/read_data_files` tool:
Before:
```
Running time: 732.597858ms
35238 series read
(48100.06 series/second)
2535668 datapoints decoded
(3461200.40 datapoints/second)
```
After:
```
Running time: 649.265258ms
35238 series read
(54273.66 series/second)
2535668 datapoints decoded
(3905442.30 datapoints/second)
```
=> [query] Improve readerIterator performance

src/cmd/services/m3query/config/config.go, src/dbnode/client/session.go, src/dbnode/storage/index/types.go, src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go, src/query/errors/storage.go, src/query/storage/index.go, src/query/storage/m3/consolidators/id_dedupe_map.go, src/query/storage/m3/consolidators/multi_fetch_result.go, src/query/storage/m3/consolidators/multi_fetch_result_tag_test.go, src/query/storage/m3/consolidators/multi_fetch_result_test.go, src/query/storage/m3/consolidators/tag_dedupe_map.go, src/query/storage/m3/storage.go, src/query/storage/types.go
Previously the per query series limit was passed directly to every
database instance as the series limit.
For large clusters this can result in a lot of wasted series read from the
database. For example a cluster with 30 instances per replica could read 30x
the time series, just to truncate the results in the coordinators.
Theoretically if the data is perfectly sharded, the per instance limit
is equal to the query series limit / # instance per replica. To allow
for unbalanced data, the InstanceMultiple config increases this
theoretical calculation by a factor to add a buffer.
By default, this option is off, but the hope is to add a sane default
for the next major release.
Additionally if this config is set, a bug is fixed that never returned
an error if RequiredExhaustive=true and the …
=> Add InstanceMultiple config to lower per instance series limit

src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go, src/query/api/v1/handler/prometheus/handleroptions/fetch_options_test.go, src/x/headers/headers.go
This allows overriding the query instance_multiple config value per
request. Will be useful for testing the feature on a per request basis.
Fixes #
```release-note
```
```documentation-note
```
=> Add M3-Limit-Instance-Multiple header

src/query/errors/storage.go, src/query/storage/m3/consolidators/multi_fetch_result.go, src/query/storage/m3/consolidators/multi_fetch_result_test.go
This should help in understanding why a query exceeded the series limit.
Options are:
1. exceeded in a single database instance. the error is returned from
the db.
2. exceeded within a single namespace after summing the results from
every database.
3. exceeded when adding the results from a namespace to the existing
results from previous namespaces.
Fixes #
```release-note
```
```documentation-note
```
=> Add the namespace to the series limit error

src/dbnode/client/fetch_state.go, src/dbnode/client/fetch_tagged_op.go, src/dbnode/client/session.go, src/dbnode/client/session_test.go
A previous attempt to lower the req.SeriesLimit to each database
instance, accidentally used that same lower limit when consolidating the
results from all database instances. The consolidation logic should use
the total SeriesLimit for the query.
Fixes #
```release-note
```
```documentation-note
```
=> Do not use the req.SeriesLimit when consolidating fetch results

src/query/api/v1/middleware/metrics.go, src/query/api/v1/middleware/metrics_test.go, src/query/api/v1/middleware/query_inspection.go, src/x/headers/headers.go
This PR allows clients to set a special header, M3-Custom-Response-Metrics-Scope,
so that the response metrics can be created under the specified subscope.
Subscopes will be re-used if the same subscope is specified across multiple
requests.
Fixes #
```release-note
```
```documentation-note
```
=> Add ability to set custom subscopes on response metrics.

src/query/storage/m3/cluster_resolver.go, src/query/storage/m3/cluster_resolver_test.go
This addresses an edge case where a namespace is overloaded for multiple resolutions, some of which store partial sets of the data set, we would fetch multiple times from the same physical namespace. This avoids that edge case.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Deduplicate resolved physical namespaces after logical namespaces resolved

src/aggregator/server/m3msg/server.go, src/msg/consumer/consumer.go, src/msg/consumer/consumer_mock.go, src/msg/consumer/types.go, src/msg/producer/writer/message.go
Logs `shardID` of the message on message processing errors.
Mostly intended to troubleshoot "shard not owned" errors.
NONE
NONE
=> [aggregator] Log shardId on message errors

src/dbnode/client/fetch_state.go, src/dbnode/client/session.go, src/dbnode/client/session_test.go
This has worked well for the FetchTagged endpoint, so rolling out to the
Aggregate and FetchTaggedIDs endpoints as well.
Fixes #
```release-note
```
```documentation-note
```
=> Use lower per db instance limits for aggregate and fetchTaggedIDs

src/query/api/v1/middleware/metrics.go, src/query/api/v1/middleware/metrics_test.go, src/x/headers/headers.go
Previously the middleware would use a subscope when passed an override
header, but this makes inspecting and discovering correct metrics more
difficult. This PR changes this to be a metrics type tag; this in turn
necessitates a default value, since Prometheus does not deal with jagged
metrics well.
=> [coordinator] Middleware metric adds tags vs subscope

src/cluster/shard/shard.go, src/cluster/shard/shard_test.go
`shards.Clone()` was adding the original shards to the cloned `shardMap` without making a copy of them.
NONE
NONE
=> [cluster] Fix a bug in shards.Clone()

src/query/graphite/native/builtin_functions.go, src/query/graphite/native/compiler_test.go, src/query/graphite/native/functions.go
Functions `logarithm` and `removeEmptySeries` need to have defaults be
float values specifically, otherwise they will cause a type conversion
panic when not provided a value.
=> [graphite] Fix graphite panics from wrong defaults

src/cluster/placement/algo/sharded_helper.go, src/cluster/placement/algo/sharded_helper_test.go
Previously, sharded placement optimization (`optimize()`) which is performed during instance removal, replica addition and instance replacement (if `AllowPartialReplace` config is enabled), would cause unnecessary shard movement.
For example, if there were 3 instances A, B, C with 2, 2, 1 shards respectively, then replacement of node A with a new instance D would also trigger a movement of 1 shard from B to C.
To fix this, the way underloaded instance is determined was changed. In addition to checking if any instance has less than its target load of shards, a check for any instance having more than its target load of shards was added. The second check will fail and no optimization will be performed in scenarios like the one described above. …
=> Ignore off-by-one differences when optimizing sharded placement

src/aggregator/aggregation/quantile/cm/list.go
Reduce memory usage of sample lists that were used by very high-volume timers.
Really should just move to an array list or something, but that is more involved and needs perf testing.
```release-note
```
```documentation-note
```
=> [aggregator] Cap length of sample for reusal

src/query/api/v1/handler/graphite/find.go, src/query/api/v1/handler/graphite/render.go, src/query/api/v1/handler/prom/read.go, src/query/api/v1/handler/prometheus/handleroptions/header_test.go, src/query/api/v1/handler/prometheus/handleroptions/headers.go, src/query/api/v1/handler/prometheus/native/complete_tags.go, src/query/api/v1/handler/prometheus/native/list_tags.go, src/query/api/v1/handler/prometheus/native/read.go, src/query/api/v1/handler/prometheus/remote/match.go, src/query/api/v1/handler/prometheus/remote/read.go, src/query/api/v1/handler/prometheus/remote/tag_values.go
This PR adds  `AddDBResultResponseHeaders` and `AddReturnedLimitResponseHeaders` to handle adding response headers to a read response. This refactoring is done so that we can encapsulate all the functionality related to limiting a response in a single place in a future change.
```release-note
```
```documentation-note
```
=> Split handleroptions.AddResponseHeaders into two separate methods

src/dbnode/integration/index_block_rotation_test.go
Sleeping for 10x the tick is flaky. Instead await 5s for the expected
results.
❯ go test -tags integration ./src/dbnode/integration -run TestIndexBlockRotation -count=20
ok  	github.com/m3db/m3/src/dbnode/integration	232.725s
Fixes #
```release-note
```
```documentation-note
```
=> Fix TestBlockRotation flakiness

src/dbnode/integration/index_block_rotation_test.go
It appears like 5s is not long enough to wait. Locally I've seen it
takes 11s.
Fixes #
```release-note
```
```documentation-note
```
=> Wait up to 30s for block rotation test

src/cmd/services/m3dbnode/config/config.go, src/cmd/services/m3dbnode/config/config_test.go, src/dbnode/integration/integration.go, src/dbnode/integration/repair_force_only_compare_test.go, src/dbnode/server/server.go, src/dbnode/storage/namespace.go, src/dbnode/storage/namespace_test.go, src/dbnode/storage/repair.go, src/dbnode/storage/repair/options.go, src/dbnode/storage/repair/types.go, src/dbnode/storage/repair/types_test.go, src/dbnode/storage/repair_test.go, src/dbnode/storage/storage_mock.go, src/dbnode/storage/types.go
Adds ability to force repair regardless of if a namespace has repair option set or not. Also adds the ability to simply run comparison and emit metrics instead of executing the repair of the data, useful for assessing health of the cluster without automatic background repairs running.
Also adds an integration test that verifies the flags are respected between the different components in the storage package.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add ability to force repair regardless namespace has option set and add compare only repair type

src/cmd/services/m3query/config/config.go, src/cmd/services/m3query/config/config_test.go, src/cmd/services/m3query/config/testdata/config.yml, src/query/server/query.go, src/query/server/query_test.go
This PR gives users the ability to configure whether the
coordinator supports requests made via H2C, which are HTTP/2
requests that do not require TLS.
Enabling this flag allows clients to realize the benefits of
HTTP/2 without requiring every request be done via TLS.
```release-note
```
```documentation-note
```
=> [coordinator] Add support for HTTP/2 Cleartext (H2C)

src/query/server/multi_process.go, src/query/server/query.go, src/query/server/query_test.go, src/x/instrument/config.go, src/x/instrument/config_prometheus.go, src/x/instrument/config_test.go
Fixes missing multiprocess label when running coordinator in multiprocess mode.
Initial implementation was using `metrics.RootScope.CommonTags` to add `multiprocess_id` label to all metrics exposed in coordinator when running in multiprocess mode. However this only affected metrics exposed using `tally`. Prometheus client library has a concept of [collectors](https://prometheus.io/docs/instrumenting/writing_clientlibs/#standard-and-runtime-collectors). These collectors were still emitting metrics without added label. 
This PR removes use of `CommonTags` and appends this label at lower level - in `multiGatherer` implementation. This only affects coordinator metrics when multiprocess is enabled.
**Does this PR …
=> [query][coordinator] Fix missing multiprocess label

go.mod, go.sum, src/cluster/placement/compress.go, src/cluster/placement/compress_test.go
zstd compressor is a bit annoying as it spawns goroutines in the background, even if all we use is the bulk, non-streaming methods. however, it means we can avoid pooling.
I think the original issue was just in the non-nil Reader, causing it to attempt reads that never succeed, so this should work just as well and play nicer with tests.
```release-note
```
```documentation-note
```
=> [cluster] Use new zstd encoder/decoder every time

src/collector/reporter/m3aggregator/reporter.go, src/metrics/rules/match_result.go
Additional observability into metrics that are R2 rules vs not.
```release-note
```
```documentation-note
```
=> Add metrics to distinguish between R2 rules and non-R2 rules

src/query/graphite/common/aliasing.go, src/query/graphite/native/alias_functions.go, src/query/graphite/native/alias_functions_test.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go, src/query/graphite/native/compiler.go, src/query/graphite/native/compiler_test.go, src/query/graphite/native/expression.go, src/query/graphite/native/functions.go
Fixes `aliasByNode` and `aliasByMetric` to use robust path expr, there was a case when there was a single non-dot path separated path as a function argument that path extraction wasn't properly working (since patterns that didn't include special chars `{[*-.` were being treated as functions by the parse grammar step).
Also adds missing negative indexing support to `substr` which was missing and is supported by Graphite.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite aliasByNode & aliasByMetric to use robust path expr extraction and add neg indexing to substr

src/aggregator/aggregator/election_mgr.go
Minor refactoring of `electionManager.campaignIsEnabled` logics to make it easier to read (every time I had to look at it, I got annoyed by those double negations etc.).
NONE
NONE
=> [aggregator] Refactor campaignIsEnabled logics to make it easier to read

src/cmd/services/m3query/config/config.go, src/query/api/v1/handler/prom/read.go, src/query/api/v1/handler/prom/read_test.go, src/query/api/v1/handler/prometheus/native/common.go, src/query/api/v1/handler/prometheus/native/common_test.go, src/query/api/v1/handler/prometheus/native/middleware.go, src/query/api/v1/handler/prometheus/native/read.go, src/query/api/v1/handler/prometheus/native/read_common.go, src/query/api/v1/handler/prometheus/native/read_common_test.go, src/query/api/v1/handler/prometheus/native/read_instantaneous_test.go, src/query/api/v1/handler/prometheus/native/read_test.go, src/query/remote/client.go, src/query/storage/fanout/storage.go, src/query/storage/fanout/storage_test.go, src/query/storage/m3/m3_mock.go, src/query/storage/m3/storage.go, src/query/storage/m3/storage_test.go, src/query/storage/mock/storage.go, src/query/storage/noop_storage.go, src/query/storage/remote/storage.go, src/query/storage/storage_mock.go, src/query/storage/types.go, src/query/test/storage.go
This PR gives users the ability to configure whether they'd like to rewrite range durations in queries that would be routed to namespaces that have resolutions greater than the range. When disabled, behavior stays the same as it currently is today. Namely, if the range duration is less than the resolution on the namespace, the query will return no data. When enabled and this condition is detected, the range within the query will automatically be updated to a multiple of the largest namespace resolution for the query. That multiple is configurable. It defaults to 0, which turns the rewriting behavior off.
```release-note
```
**Does …
=> [query] Support rewriting range duration in queries 

src/query/graphite/native/aggregation_functions.go, src/query/graphite/native/aggregation_functions_test.go, src/query/graphite/native/summarize.go, src/query/graphite/native/summarize_test.go
Fixes NPE bug when query groupByNodes using median aggregation function. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite groupByNodes panic on missing agg function when using median

src/query/graphite/common/aggregation.go, src/query/graphite/common/aggregation_test.go, src/query/graphite/native/summarize.go, src/query/graphite/native/summarize_test.go
Fixes graphite summarize/summarize to add missing agg functions, including
1. median
2. diff
3. range
4. stddev
5. Multiply
6. count
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix graphite summarize/summarize to add missing agg functions

src/dbnode/client/session.go, src/dbnode/client/session_fetch_metadata_test.go
This fixes concurrent calls to `addBlockFromPeer` on `streamBlocksResult` resulting in reuse of a tag decoder during active an active repair call which leads to a ref count error. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Fix tag decoder reuse which leads to ref count error for repair code path

site/content/overview/components.md, src/query/README.md, src/query/graphite/common/test_util.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go, src/query/graphite/native/functions.go
Fixes an issue where the windowing size for moving functions is miscalculated if different resolution of data comes back after adjusting the start time to fetch more data to calculate first few datapoints for the moving function being applied.
If new resolution is used for the newly refetched data then the windowing size needs to be recalculated and the data fetched again to make sure it's the exact right length for the moving function being applied.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Update Graphite moving functions to re-fetch if the window size changes based on new query

src/query/api/v1/middleware/rewrite.go, src/query/api/v1/middleware/rewrite_test.go
Setting the body on a GET request can sometimes cause
"http: invalid Read on closed Body" errors within the Golang
HTTP client. As such, ensure that if processing a GET request
the body is not set.
```release-note
```
```documentation-note
```
=> [coordinator] Ensure rewrite middleware doesn't set the body on a GET

src/cmd/tools/read_commitlog/main/main.go, src/cmd/tools/read_data_files/main/main.go, src/cmd/tools/util.go, src/cmd/tools/verify_data_files/main/main.go, src/cmd/tools/verify_index_files/main/main.go
Reduces memory overhead of `read_data_files` command line utility by ~5 GB. The overhead was being caused by allocating byte pool which is no longer needed after the switch to streaming reads in this utility. 
Also did some cleanup in other command line utils.
NONE
NONE
=> [tools] Reduce read_data_files mem overhead

src/dbnode/integration/index_active_block_rotate_test.go, src/dbnode/integration/index_helpers.go, src/dbnode/integration/setup.go, src/dbnode/storage/index.go, src/dbnode/storage/index/mutable_segments.go, src/dbnode/storage/index_block_test.go, src/query/storage/m3/consolidators/convert.go
This changes the logic to detect whether a block is flushed or not (and consequently can GC in-memory series from index). Previously was checking that the block had been sealed (had at least started transition to on disk segment) and that no in-memory series were held by block any longer. This is a poor check since in-memory series are held by the active block not the block for that block start, so would return true even though the block had not been flushed.
Now the check is much more robust since it checks the result of the call to `block.Tick(...)` which explicitly returns whether it has a bootstrapped segment (i.e. a segment which is an on disk segment) held as a reference or not, which is the root for the source of truth on whether the …
=> Fix for index block appearing as a flushed index block, now explicit check has on disk segment

src/x/instrument/option.go, src/x/instrument/option_test.go, src/x/instrument/options.go
When passing iOpts to a new library, I often find my self tagging both the scope and logger with something like "component":"server", this diff makes a utility function for that.
=> Add functions to tag instrument options

src/dbnode/persist/fs/read.go, src/dbnode/persist/fs/types.go
Adds `IndexChecksum` to `StreamedMetadataEntry`.
NONE
NONE
=> [dbnode] Add IndexChecksum to StreamedMetadataEntry

src/dbnode/persist/fs/read.go, src/dbnode/persist/fs/types.go
This reverts commit 743cec50145777fc7d08a10e7c8e6f2a1034ba94.
I've realized that this change would be useless for checking index entries across different filesets because the checksum includes data entry offset which would vary in different filesets.
NONE
NONE
=> Revert "[dbnode] Add IndexChecksum to StreamedMetadataEntry (#3627)"

src/aggregator/client/conn.go, src/aggregator/client/conn_options.go, src/aggregator/client/conn_test.go
Right now placement initialization/update depends on blocking, synchronous connection creation, which can be *very* slow on high-latency links and huge placements, due to this call chain: 
`(placement update hook) -> writerManager.AddInstances -> newRefCountedWriter -> newInstanceWriter -> newInstanceQueue -> newConnection`
Connection state is always checked in Write() method, and writes are called concurrently, so this PR greatly speeds up both placement init and any subsequent changes, as placement updates no longer depend on blocking IO.
Writer instance removal and cleanup has always been async, so everything is flushed in the background and never blocks placement updates themselves:
```
func (rcWriter *refCountedWriter) Close() {
// NB: closing …
```
=> [aggregator] Do not eagerly connect to aggregator instances in TCP client

src/query/storage/m3/consolidators/id_dedupe_map.go, src/query/storage/m3/consolidators/id_dedupe_map_test.go
The change fixes a bug in how we dedupe series on the graphite query path. In particular the `list()` function on `idDedupMap` does not return deterministic ordering of entries. The change sorts the series by id before returning, so multiple calls to the `list()` method always return things in the right order.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Sort by ids in ID dedupe map list method

src/query/graphite/native/aggregation_functions.go, src/query/graphite/native/aggregation_functions_test.go, src/query/graphite/native/builtin_functions.go
Fix groupByNodes to get proper first path, both in normal cases and special cases like `scaleToSeconds(servers.foo-2.pod1.status.500,1)`
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix groupByNodes to get proper first path

src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go
add AverageBelow function
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] add AverageBelow function

src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go
Add invert function
```release-note
DONE
```
```documentation-note
DONE
```
=> [query] Add Graphite invert function

src/query/graphite/native/aggregation_functions.go, src/query/graphite/native/aggregation_functions_test.go
Previously `divideSeriesList` would not return deterministic results (since sometimes input might not be sorted). This changes that behavior to make sure at least a default sort of name occurs if input is not sorted.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite divideSeriesList to return deterministic results

docker/m3coordinator/Dockerfile, docker/m3coordinator/development.Dockerfile, docker/m3dbnode/Dockerfile, docker/m3dbnode/Dockerfile-setcap, docker/m3dbnode/development.Dockerfile, docker/m3query/Dockerfile, docker/m3query/development.Dockerfile, src/query/api/v1/httpd/handler.go, src/query/graphite/graphite/timespec.go, src/query/graphite/graphite/timespec_test.go, src/query/graphite/native/aggregation_functions.go, src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go
The docker images for the query service and services that embedded the query service (such as coordinator and dbnode) were missing timezone info. This meant that the images would not respect the TZ environment variable which would mean that relative times used with graphite (for parameters to functions like `timeSlice`) would use UTC time even if the TZ environment variable was set.
This fixes that issue by adding the timezone info into the docker images.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite relative time parsing not respecting TZ env var

src/dbnode/server/server.go
Adds some minor logs on the effective query index concurrency and index max worker time.
```release-note
NONE
```
```documentation-note
NONE
```
=> [dbnode] Add logs for the effective query index concurrency and max worker time at startup

src/query/graphite/native/builtin_functions.go, src/query/graphite/native/builtin_functions_test.go
fix graphite substr() to handle negative index better. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite substr function to handle negative indexes correctly

src/query/graphite/native/alias_functions_test.go, src/query/graphite/native/compiler.go, src/query/graphite/native/summarize.go
Previously compiler was trying to compile any fetch or pattern that matches name of a function, this caused sub-expressions that matched the name of a function (e.g. identity) to cause aliasByNode to fail since they wouldn't compile as sub-expressions as the pattern would tried to be compiled to a function arg but would fail.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite aliasByNode when sub-expr returns a pattern in an arg of fn that is itself the name of a fn

src/dbnode/persist/fs/read_decode_stream.go
I've noticed that `readerDecoderStream` is using [a very small (8 bytes) buffer](https://github.com/m3db/m3/blob/18430610ed4501dcef1b8da39291dd6cc527681c/src/dbnode/persist/fs/read_decode_stream.go#L44) which does not perform very well with `adler32` hash implementation. Increasing this buffer to 64 bytes gives a very noticeable performance boost for `DataFileSetReader`.
I've chosen 64 bytes as a compromise between buffer size and diminishing performance improvements.
Benchmarking results using `read_data_files` utility in `series` benchmarking mode (no datapoint decoding):
```
read_data_files -b 1596009600000000000 -p ~/testdata/m3db -s 4 -B series
```
| len(buf) | running time |
|----|----|
| 8 | 42 ms |
| 16 | …
=> [dbnode] Increase readerDecoderStream.buf length to 64

src/query/graphite/native/alias_functions_test.go, src/query/graphite/native/compiler.go
Fixes the case where Graphite compiler eagerly parses an identifier that matches a function name (i.e. max) but is actually just an identifier.
Added unit test that covers this case.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite compiler eagerly parsing identifier as function call and not considering pattern

src/dbnode/client/replicated_session.go, src/dbnode/client/replicated_session_test.go
When writing to async sessions, use cloned values of namespace, id and tags because their lifecycle differs from the main write (sync) flow.
This PR replaces the experimental https://github.com/m3db/m3/pull/3637 with the added benefit that it has no effect or resource overhead in cases when async session is not in use.
NONE
NONE
=> [dbnode] Clone namespace, ID, tags in replicatedSession

scripts/docker-integration-tests/aggregator/m3aggregator.yml, src/aggregator/aggregator/entry.go, src/aggregator/aggregator/entry_test.go
This fixes 2 bugs with the function AddTimedWithStagedMetadatas:
1. Use the Resolution from the active StagedMetadata when checking the
buffer past. Previously it would use the Resolution from the
TimedMetadata which is always zero for StagedMetadata. This required
moving the buffer past check, so it runs after the active staged
metadata is computed.
2. Use a timedMetricList instead of a standardMetricList. This is
required so the flusher does not flush aggregated values until after
the buffer past for timed metrics.
Fixes #
```release-note
``` …
=> Fix list type and buffer check for TimedWithStagedMetadatas

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/feature_flags.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/metrics/transformation/binary.go, src/metrics/transformation/func.go
We've found this to be generally desirable, so we're
making it the default behavior.
Fixes #
```release-note
```
```documentation-note
```
=> [aggregator] Rollout IncreaseWithPrevNaNTranslatesToCurrValueIncrease flag

src/cmd/tools/read_data_files/main/main.go, src/cmd/tools/split_shards/main/main.go, src/dbnode/persist/fs/streaming_write.go
Entry counter was not being reset on `streamingWriter` reuse.
NONE
NONE
=> [dbnode] Fix entries count when reusing streamingWriter

src/aggregator/aggregator/elem_base.go, src/aggregator/aggregator/elem_base_test.go, src/aggregator/aggregator/entry.go, src/aggregator/aggregator/entry_test.go, src/metrics/pipeline/applied/type.go, src/metrics/pipeline/applied/type_test.go
This will allow removing the migration in the future. This is a noop
change.
At the moment the aggregationKey still contains Adds instead of Resets,
which makes it impossible to seamlessly transition the rollup rules to
explicitly use Reset instead of Add, since the AggregationKey will change.
If the AggregationKey changes it will result in split aggregations
during the deploy.
Once this has been deployed to the aggregator, the rollup rules in the
coordinator can be changed to use Reset explicilty and the
AggregationKey won't change in the Aggregator. The boolean can then be
dropped once all rules are using Reset instead of Add.
When this change rolls out to the aggregator it will change the
AggregationKey for incoming metrics. However, it will only affect the
follower and once the …
=> Move addToReset migration to the aggregationKey.Pipeline

src/aggregator/server/server.go, src/cmd/services/m3aggregator/main/main.go, src/cmd/services/m3dbnode/main/main.go
Instead of watching for interrupts directly within the
server.Run method. Allow for an interruptCh to be passed
as a RunOption. This will allow the aggregator to be started
and shutdown programatically which will be useful as
we improve upon our integration tests. This pattern is already
used for both the coordinator and db nodes.
```release-note
```
```documentation-note
```
=> [aggregator] Add interrupt channel for Aggregator shutdown

.gitignore, Makefile
I broke lint-$subdir target in #3673 as I didn't clean up the linter targets everywhere.
Also, remove unused retool targets as that was replaced by `go install`
```release-note
```
```documentation-note
```
=> [build] Fix subdir lint and remove unused retool targets

src/aggregator/server/server.go, src/cmd/services/m3aggregator/main/main.go
WaitForInterrupt is the more idiomatic way for us to
handle interrupts and also more gracefully handles
a nil interruptCh.
```release-note
```
```documentation-note
```
=> [aggregator] Use WaitForInterrupt to handle interrupts

src/query/graphite/native/alias_functions.go, src/query/graphite/native/alias_functions_test.go, src/query/graphite/native/compiler.go
This ensures that partial expressions that should not be able to be successfully compiled can still have their path expression extracted for use in functions like groupByNode.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Fix Graphite getFirstPathExpression not able to extract paths from partially complete expressions

src/aggregator/server/server.go, src/dbnode/server/server.go, src/query/server/query.go
This PR lands a couple changes that makes restarting the process in-memory easier by improving resource cleanup. This is primarily for the sake of integration testing. Commits:
```
Ensure shutdown notication sent after resource cleanup
This commit moves the shutdown notification to a deferred
function, and ensures that the function is the last deferred
function called by registering it first. This ensures that
all cleanup behavior happening in deferred functions are
complete before we send a shutdown notification.
```
```
Ensure dbnode debug server shutdown on server shutdown
This commit calls server.Shutdown for the debug server
once the main dbnode server is shutdown. Additionally,
use do not register debug routes on global DefaultServeMux
object. …
```
=> [aggregator][dbnode][query] Improve resource cleanup flow on shutdown

src/dbnode/client/connection_pool.go, src/dbnode/client/connection_pool_test.go, src/dbnode/client/session.go, src/dbnode/client/session_test.go, src/dbnode/client/types.go
Adds an option to consider only the nodes that are fully bootstrapped (via `NodeHealthResult_.Bootstrapped` field) when acquiring a `DedicatedConnection`.
NONE
NONE
=> [dbnode] DedicatedConnection to bootstrapped nodes option

src/query/api/v1/handler/graphite/render.go, src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go, src/query/api/v1/handler/prometheus/handleroptions/fetch_options_test.go, src/query/graphite/common/context.go, src/query/graphite/native/expression.go, src/query/graphite/storage/m3_wrapper.go, src/query/graphite/storage/m3_wrapper_test.go, src/query/graphite/storage/storage.go, src/query/storage/fetch.go, src/query/storage/m3/cluster_resolver.go, src/query/storage/m3/cluster_resolver_test.go, src/query/storage/restrict_query_options.go, src/query/storage/restrict_query_options_test.go, src/query/storage/types.go, src/x/headers/headers.go
This change adds support for querying specific namespaces by
means of headers. It additionally adds support for graphite to use
the full fetch options.
```release-note
NONE
```
```documentation-note
NONE
```
=> Add support for querying specific namespaces

src/dbnode/storage/shard.go, src/dbnode/storage/shard_test.go
During active index block refactoring shard flush state was split into two separate states for data and index. In this specific flow, only the data state was being marked as success, missing the index state.
This PR modifies the flow to also set the index state.
The original implementation was introduced with https://github.com/m3db/m3/pull/2777
The split of `markWarmFlushStateSuccess` into index/data parts happened here: https://github.com/m3db/m3/pull/3464/files#diff-f8370647cf96e48d3ddfbaa013d3139017115829ecabdc59a7adad783c7affefL2499
NONE
NONE
=> [dbnode] Fix markWarmFlushStateSuccess

src/query/api/v1/httpd/graphite_router.go, src/query/api/v1/httpd/graphite_router_test.go, src/query/api/v1/httpd/handler.go, src/query/api/v1/httpd/handler_test.go, src/query/api/v1/httpd/router_test.go, src/query/api/v1/options/handler.go, src/query/server/query.go
This change adds query routers for graphite endpoints, allowing us
to add additional logic to the graphite endpoints.
```release-note
NONE
```
```documentation-note
NONE
```
=> Add graphite query router support

src/dbnode/storage/namespace.go, src/dbnode/storage/types.go
Adds `AggregateTilesOptions.Backfill` field.
Only planning to use it for logging and enriching the metrics.
NONE
NONE
=> [dbnode] Add AggregateTilesOptions.Backfill field

src/dbnode/network/server/tchannelthrift/node/service.go, src/dbnode/storage/database.go, src/dbnode/storage/database_test.go, src/dbnode/storage/namespace.go, src/dbnode/storage/namespace_test.go, src/dbnode/storage/types.go
Add `AggregateTilesOptions.Process` field (enum). This will be more useful than having a boolean.
This overrides https://github.com/m3db/m3/pull/3736.
NONE
NONE
=> [dbnode] Add AggregateTilesOptions.Process field

src/aggregator/server/http/options.go, src/aggregator/server/server.go, src/cmd/services/m3aggregator/main/main.go, src/cmd/services/m3aggregator/serve/serve.go, src/cmd/services/m3coordinator/main/main.go, src/cmd/services/m3query/main/main.go, src/dbnode/server/server.go, src/query/api/v1/httpd/handler.go, src/x/debug/pprof.go, src/x/instrument/config.go, src/x/instrument/config_prometheus.go
Using the global http.DefaultServeMux causes issues with duplicate route registration when an M3 component is restarted within process (e.g. during integration tests). This PR replaces all uses of the global http.DefaultServeMux with a locally scoped default ServeMux that gets destroyed on component shutdown.
```release-note
```
```documentation-note
```
=> [*] Remove uses of http.DefaultServeMux

src/dbnode/storage/database.go
There are also more detailed metrics `aggregate-tiles.sucsess/error` reported from `namespace.AggregateTiles`.
NONE
NONE
=> [dbnode] Remove redundant aggregate tiles metrics

src/dbnode/storage/bootstrap/bootstrapper/peers/source.go, src/dbnode/storage/bootstrap/bootstrapper/peers/source_instrumentation.go
To see the shards of which namespaces take longer to bootstrap.
NONE
NONE
=> [dbnode] Log namespaceID during shard bootstrapping

src/metrics/metadata/metadata.go, src/metrics/metadata/metadata_test.go
hope it's not too late to fix this - the diff just makes the capitalization consistent with the rest of the payload, and omits the field if not set, like for all other optional fields.
=> Fix inconsistent StagedMetadatas.ResendEnabled naming in JSON

src/aggregator/aggregator/flush_mgr_options.go, src/cmd/services/m3aggregator/config/aggregator.go, src/cmd/services/m3coordinator/downsample/options.go, src/cmd/tools/query_index_segments/main/main.go, src/cmd/tools/read_index_segments/main/main.go, src/dbnode/client/host_queue_bench_test.go, src/dbnode/client/options.go, src/dbnode/integration/wide_query_test.go, src/dbnode/persist/fs/commitlog/options.go, src/dbnode/persist/fs/migration/options.go, src/dbnode/persist/fs/retriever_options.go, src/dbnode/server/server.go, src/dbnode/storage/bootstrap/bootstrapper/commitlog/options.go, src/dbnode/storage/bootstrap/bootstrapper/fs/options.go, src/dbnode/storage/bootstrap/bootstrapper/peers/options.go, src/dbnode/storage/index.go, src/dbnode/storage/index/block.go, src/dbnode/storage/index/mutable_segments.go, src/dbnode/storage/namespace.go, src/m3ninx/index/segment/builder/builder.go, src/m3ninx/index/segment/builder/options.go, src/query/functions/temporal/base.go, src/query/graphite/native/aggregation_functions.go, src/query/graphite/native/builtin_functions.go, src/query/remote/server_test.go, src/query/storage/m3/encoded_step_iterator_test.go, src/x/sync/options.go
Containerized Go applications usually also apply cgroup quotas or use cpusets - which are not reflected correctly in runtime at all, so it's common to set expected number of physical threads to use for runtime via GOMAXPROC env var. Using runtime.NumCPU in that context can be counterproductive - eg. a 4-core container on a 64 core machine will be grossly overestimating # of CPUs to use for sharding and worker pools.
There is no change in environments that don't explicitly override GOMAXPROCS, as the default value is equal to # of CPU threads, same as runtime.NumCPU().
This PR replaces all usages of NumCPU with GOMAXPROCS, except for code in `src/query/server/multi_process.go` that is meant to spawn/manage multiprocessing by itself.
**Special notes …
=> [all] Use runtime.GOMAXPROC instead of runtime.NumCPU

src/cmd/services/m3dbnode/server/server.go, src/x/instrument/config.go, src/x/instrument/config_prometheus.go, src/x/instrument/config_test.go
This commit ensures that the metrics http server is closed
if one is created as a part of creating a new prometheus.Reporter.
```release-note
```
```documentation-note
```
=> [query] Ensure metrics server always gets closed

src/dbnode/network/server/tchannelthrift/cluster/service.go
Previously a double call to Close would result in the tag iterator being
added back to the pool twice, which would then result in the same
iterator being given back out to multiple callers later.
Additionally removed the unnecessary call to tagIter.Close() in
Cluster.Query, since closing the results will close the tag iterator.
Fixes #
```release-note
```
```documentation-note
```
=> Make TagIteratorPool.Close idempotent

src/aggregator/aggregation/counter.go, src/aggregator/aggregation/gauge.go, src/aggregator/aggregation/options.go, src/aggregator/aggregation/quantile/cm/options.go, src/aggregator/aggregation/quantile/cm/sample.go, src/aggregator/aggregation/quantile/cm/stream.go, src/aggregator/aggregation/timer.go, src/aggregator/bitset/bitset.go, src/aggregator/client/conn.go, src/aggregator/client/options.go, src/aggregator/client/payload.go, src/aggregator/client/queue.go, src/aggregator/client/writer.go, src/metrics/encoding/protobuf/aggregated_encoder.go, src/metrics/encoding/protobuf/buffer.go, src/metrics/encoding/protobuf/unaggregated_encoder.go, src/metrics/encoding/protobuf/unaggregated_iterator.go, src/metrics/metadata/metadata.go, src/metrics/metadata/metadata_test.go, src/metrics/metric/aggregated/types.go, src/metrics/metric/id/m3/id.go, src/metrics/metric/unaggregated/types.go, src/metrics/pipeline/applied/type.go, src/metrics/pipeline/type.go, src/metrics/transformation/type.go
Went through a couple of packages with `fieldalignment -fix` that are commonly used. Unlike `maligned`, it also moves pointers to the front of the struct to reduce amount of bytes GC has to scan.
Microbenchmarks (that exist) are really boring and don't show anything, except for one that churns through a lot of data and does actually GC:
```
name                                                              old time/op    new time/op    delta
TimerAddBatch/100k_samples_1000_batch_size-12                       1.92ms ± 7%    1.65ms ± 4%  -13.83%  (p=0.008 n=5+5)
TimerAddBatch/100k_samples_1000_batch_size_0..1,000,000_range-12    1.92ms ± 3%    1.67ms ± 7%  -12.88%  (p=0.008 n=5+5)
TimerAddBatch/100k_samples_1000_batch_size_0..100,000_range-12      1.93ms ± 6%    1.83ms ± 1%   -5.10% …
```
=> [aggregator] Move some struct members around using fieldalignment tool

go.mod, src/integration/resources/common/coordinator_client.go, src/integration/resources/docker/common.go, src/integration/resources/docker/coordinator.go, src/integration/resources/docker/dbnode.go, src/integration/resources/docker/docker_resource.go, src/integration/resources/inprocess/coordinator.go, src/integration/resources/inprocess/coordinator_test.go, src/integration/resources/net/net.go
This commit adds an implementation of resources.Coordinator
that is capable of being started in-process as opposed to
being started via a Docker container.
Additionally, adds helper functions for getting an open
port and updating a host:port string where the port is 0
with an actual usuable port.
```release-note
```
```documentation-note
```
=> [tests] Add coordinator capable of being started in-process.

src/integration/resources/inprocess/coordinator.go, src/integration/resources/inprocess/dbnode.go, src/integration/resources/inprocess/dbnode_test.go
This commit adds an implementation of resources.Node that
is capable of being started in-process as opposed to
being started via a Docker container.
```release-note
```
```documentation-note
```
=> [tests] Add dbnode capable of being started in-process.

src/cmd/services/m3query/config/config.go, src/query/server/query.go, src/query/storage/m3/cluster.go, src/query/storage/m3/config.go, src/query/storage/promremote/options.go, src/query/storage/promremote/options_test.go, src/query/storage/promremote/storage.go, src/query/storage/promremote/storage_test.go, src/query/storage/promremote/types.go, src/query/storage/promremote/types_test.go
This is a continuation work for https://github.com/m3db/m3/pull/3742. This PR addresses 2 issues:
- adapts endpoints to M3 Namespaces so that downsampler is a aware of existance of different namespaces to properly downsample data
- returns error when none of the configured endpoints match the incoming write.
This implementation was manually tested. I will continue implementing docker integration tests to cover multiple namespaces.
```release-note
None
```
```documentation-note
Additional downsample config option will be detailed in documentation.
```
=> [coordinator] Support multiple namespaces for prom-remote storage

src/cluster/kv/util/runtime/options.go, src/cluster/kv/util/runtime/value.go, src/cluster/services/options.go, src/cluster/services/services.go, src/cluster/services/services_mock.go, src/cluster/services/services_test.go, src/cluster/services/types.go, src/cmd/services/m3coordinator/downsample/options.go, src/dbnode/environment/config.go, src/dbnode/server/server.go, src/integration/resources/inprocess/coordinator.go, src/integration/resources/inprocess/dbnode.go, src/integration/resources/inprocess/dbnode_test.go, src/metrics/matcher/namespaces.go, src/metrics/matcher/namespaces_test.go, src/metrics/matcher/options.go, src/query/server/query.go, src/x/os/interrupt.go, src/x/watch/options.go, src/x/watch/value.go, src/x/watch/value_test.go
Operations that block the main thread without any way to interrupt them to
shutdown the server can slow down integration tests. This PR fixes two instances:
one in the coordinator and one in the DB node. See the individual commits for
more detail.
```release-note
```
```documentation-note
```
=> [dbnode,query] Allow blocking operations on main thread to be interrupted

src/dbnode/server/server.go
This reverts commit b8d9b0f52cd262e280647024bc6355cc0b98f1ad.
This change was causing division by 0 panics because of 0 value passed for a `thereafter` argument:
```
zap.New(zapcore.NewSamplerWithOptions(logger.Core(), time.Second*30, 1, 0)))
```
NONE
NONE
=> Revert "Sample tracer logs (#3774)"

src/cmd/services/m3coordinator/downsample/async_downsampler.go, src/query/server/query_test.go
Small refactor to query_test.go to use runServer helper to remove some duplicated test code. I have started using MemStore instead of mocked one. It seems it might have revealed race condition in asyncDownsampler constructor that I fixed by moving lock.
```release-note
None
```
```documentation-note
None
```
=> [coordinator] Use runServer in all tests in query_test.go

scripts/docker-integration-tests/carbon/m3coordinator.yml, src/cmd/services/m3query/config/config.go, src/query/api/v1/handler/graphite/find.go, src/query/api/v1/handler/graphite/find_parser.go, src/query/api/v1/handler/graphite/find_test.go, src/query/graphite/storage/m3_wrapper.go, src/query/server/query.go
This more closely matches behavior of other Graphite implementations which only returns the value just once if both an expandable and leaf path value exists for the find endpoint.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Remove Graphite find results that are duplicate if includes both expandable and leaf path values

src/cluster/kv/util/runtime/options.go, src/cluster/kv/util/runtime/value.go, src/cluster/services/options.go, src/cluster/services/services.go, src/cluster/services/services_mock.go, src/cluster/services/services_test.go, src/cluster/services/types.go, src/cmd/services/m3coordinator/downsample/options.go, src/dbnode/environment/config.go, src/dbnode/server/server.go, src/metrics/matcher/namespaces.go, src/metrics/matcher/namespaces_test.go, src/metrics/matcher/options.go, src/query/server/query.go, src/x/os/interrupt.go, src/x/os/interrupt_test.go, src/x/watch/options.go, src/x/watch/value.go, src/x/watch/value_test.go
Passing the interrupt channel to multiple goroutines could
cause a race where the main thread ends up missing the interrupt
that triggers a server shutdown. This commit ensures that only
a single goroutine is listening for the interrupt at a given
time and all other interested parties can check the interrupted
channel. The interrupted channel will be closed as soon as
an interrupt is received. Since closed channels return immediately,
this allows any interested goroutine to know if it should terminate
by simply checking the interrupted channel.
```release-note
```
**Does this PR require updating code package or user-facing …
=> [dbnode,query] Ensure only single listener for interrupt channel

scripts/docker-integration-tests/run.sh
We've been seeing integration test occasionally timeout when trying to install `netcat` because they're importing a new GPG key from Google:
```text
+ yumdownloader --destdir /tmp/tmp.oUFvI69mwM --resolve nc
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                               | 3.7 kB     00:00
google-cloud-sdk/signature                               |  844 B     00:00
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x307EA071:
Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)"
Fingerprint: 7f92 e05b 3109 3bef 5a3c 2d38 feea 9169 307e a071
From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Is this ok [y/N]: # 
```
This commit …
=> [tests] Add -y flag when downloading netcat

src/aggregator/aggregator/aggregator.go, src/aggregator/aggregator/aggregator_test.go, src/aggregator/aggregator/options.go, src/aggregator/integration/setup.go, src/cmd/services/m3aggregator/config/aggregator.go
Replace the `TimedForResendEnabled` feature flag with a set of regexes to allow for incrementally transitioning rollup rules over to using Timed instead of Untimed (as opposed to all or nothing via the original `bool`).
```release-note
```
```documentation-note
```
=> Change TimedForResendEnabled to be a set of regexes against rollup IDs

src/x/serialize/encoder.go
Makes "literal is too long" to result in 400 rather than 500 status code
```release-note
NONE
```
```documentation-note
NONE
```
=> [x/serialize] Change "literal is too long" error to 400 status code

src/dbnode/client/client.go, src/dbnode/client/client_mock.go, src/dbnode/client/fetch_tagged_results_accumulator.go, src/dbnode/client/types.go, src/dbnode/generated/thrift/rpc.thrift, src/dbnode/generated/thrift/rpc/rpc.go, src/dbnode/network/server/httpjson/handlers_test.go, src/dbnode/network/server/tchannelthrift/cluster/service.go, src/dbnode/network/server/tchannelthrift/cluster/service_test.go, src/dbnode/storage/index/types.go
Additionally you can specify the conflict resolution strategy to use
when there are different values for the same timestamp.
This is helpful for inspecting the raw data in the database and to use a
stricter read consistency to verify the data exists on all replicas.
Fixes #
```release-note
```
```documentation-note
```
=> Allow specifying read consistency for Cluster.Query

src/integration/resources/common/coordinator_client.go, src/integration/resources/inprocess/coordinator_test.go, src/integration/resources/types.go
This PR adds Zone and Env to the PlacementOpts for resources.Coordinator. We can now specify the zone and environment of the placement while initializing it.
```release-note
```
```documentation-note
```
=> [tests] Add Env and Zone while handling placements with resources.Coordinator

src/msg/producer/config/writer.go, src/msg/producer/writer/consumer_service_writer.go, src/msg/producer/writer/message_writer.go, src/msg/producer/writer/message_writer_test.go, src/msg/producer/writer/options.go
For large m3msg deployments the number of consumers can add a lot of
cardinality to the metrics. Now users can disable the "consumer" label
via the config option.
Fixes #
```release-note
```
```documentation-note
```
=> Optionally disable m3msg consumer metric scope

src/cmd/services/m3coordinator/downsample/metrics_appender.go
Fixes #
```release-note
```
```documentation-note
```
=> [downsampler] Flesh comments in metrics_appender.go

src/msg/producer/writer/message_writer.go
retry was extremely misleading because these messages weren't being
retried. the counter is incremented if the message is scanned and the
retryAt time is in the future (i.e not ready to be processed)
Fixes #
```release-note
```
```documentation-note
```
=> Relabel not-ready m3msg queue metrics

src/query/server/query_test.go, src/query/storage/promremote/promremotetest/test_server.go, src/query/storage/promremote/storage.go, src/query/storage/promremote/storage_test.go
**What this PR does / why we need it**: 
map <500 response codes to 400.
Makes sure 4xx errors are wrapped in InvalidParamsError that eventually gets mapped to 400 HTTP status code.
This is important because prometheus [scraper retries 5xx errors](https://github.com/prometheus/prometheus/blob/fac1b573349ac4d35c011a891e2bb58f560f9d84/storage/remote/client.go#L241). Before this change any errors returned from endpoint would have been mapped to 500.
Storage layer abstracts away HTTP so it's not possible to just respond with same status codes as in response from the endpoint. However it seems enough to map to 400 or 500 based on Prometheus scraper implementation. …
=> [coordinator] Make <500 endpoint errors as invalid params error

src/m3ninx/index/segment/builder/multi_segments_terms_iter.go
This addresses the recently introduced TODO:
https://github.com/m3db/m3/blob/5d6001047d66693f46f7a141ef81415a49c00b34/src/m3ninx/index/segment/builder/multi_segments_terms_iter.go#L179-L183
by converting `termsIterFromSegments.Next()` to a tail recursive form (in order to prevent stack overflow).
I believe this will fix the following stackoverflow panic:
```
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xcb36d7c3b8 stack=[0xcb36d7c000, 0xcb56d7c000]
fatal error: stack overflow
runtime stack:
runtime.throw(0x21a54d7, 0xe)
/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.newstack()
/usr/local/go/src/runtime/stack.go:1069 +0x7ed
runtime.morestack()
/usr/local/go/src/runtime/asm_amd64.s:458 …
```
=> [dbnode] Make termsIterFromSegments.Next tail recursive

src/integration/resources/inprocess/common.go, src/integration/resources/inprocess/coordinator.go, src/integration/resources/inprocess/dbnode.go, src/integration/resources/inprocess/inprocess.go, src/integration/resources/inprocess/inprocess_test.go
This commit adds an implementation of resources.M3Resources that
is backed by in-process components. Implementation is able
of being configured using resources.SetupCluster which takes
those components and turns them into a cluster ready to
receive reads and writes.
```release-note
```
```documentation-note
```
=> [tests] Adds in-process implementation of resources.M3Resources

src/query/api/v1/handler/influxdb/write.go, src/query/api/v1/handler/influxdb/write_test.go, src/query/api/v1/httpd/handler_test.go
For improved performance InfluxDB protocol suggest using `Content-Encoding: gzip` for the line protocol messages. At the moment, for example Telegraf sends InfluxDB output using gzip by default, [https://github.com/influxdata/telegraf/pull/8269](https://github.com/influxdata/telegraf/pull/8269). The current implementation of the M3 InfluxDB write handler did not support this. This PR adds this capability.
Another fix included is specifying the [timestamp precision](https://docs.influxdata.com/influxdb/cloud/write-data/#timestamp-precision) for the timestamp included in the InfluxDB line protocol. InfluxDB client implementations send the precision along with the write requests and if this is not taken into account, the timestamp value is parsed with …
=> [query] influxdb write improvements

src/x/cache/lru_cache.go, src/x/cache/lru_cache_prop_test.go, src/x/cache/lru_cache_test.go
A regression in LRU cache was introduced here: https://github.com/m3db/m3/blob/e2c6903cc0a027a129674afbf819ef294feceb07/src/x/cache/lru_cache.go#L356-L366
Cache entries were never being evicted when it was being used with no loader. Because of early return under `getWithNoLoader = true` the code that invokes `reserveCapacity` was unreachable, and this was the only place where eviction would happen.
I have added a call to `reserveCapacity` from `Put` (which assumes no loader is in use).
Another possibility would be to fix `tryCache` implementation to reserve the space on cache miss, but then `Put` would happen not under the same lock, creating a race between `Get`s (freeing up space in advance) and `Put`s which …
=> [x/cache] Fix LRU cache mem leak (when used with no loader)

src/integration/resources/docker/common.go, src/integration/resources/docker/config/prometheus.yml, src/integration/resources/docker/coordinator.go, src/integration/resources/docker/docker_resource.go, src/integration/resources/docker/prometheus.go, src/integration/resources/docker/prometheus_test.go, src/integration/resources/types.go
This commit adds an interface for adding external (i.e. not M3)
resources that can be used in integration tests. An
implementation of the interface that allows users to spin up
a docker-backed Prometheus is added as well. This also functions
as a working example for how the interface can be implemented to
support other external resources.
Fixes #
```release-note
```
```documentation-note
```
=> [tests] Add support for resources.ExternalResources

src/query/api/v1/handler/prometheus/remote/write.go, src/query/api/v1/handler/prometheus/remote/write_test.go, src/query/models/options.go, src/query/models/options_test.go, src/query/models/tags.go, src/query/models/tags_test.go, src/query/models/types.go, src/x/serialize/encoder.go, src/x/serialize/limits.go
Add logging for time series labels upon "literal is too long" error. It should help figuring out cases where metrics are being dropped because of unexpected values being placed into labels.
Since the labels can be as long as a few thousands of characters, the label names and values are being truncated and the amount of messages are being limited. This is done to avoid flooding the logs.
The code feels hacky, though let's sort this out during review.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Log summary of time series labels upon "literal too long" error

src/dbnode/storage/database.go, src/dbnode/storage/database_test.go
Fixes #
```release-note
```
```documentation-note
```
=> Simplify some code paths further and use lock/defer unlock in more places

src/cluster/kv/mem/store.go, src/cmd/services/m3coordinator/downsample/downsampler_test.go, src/cmd/services/m3coordinator/downsample/options.go, src/query/server/query.go, src/query/server/query_test.go
This enables running M3 Coordinator with in process M3 Aggregator without external Etcd.
Situation until now:
- When running with M3DB backend embedded Etcd would be provided by DB node.
- Running `noop-etcd` actually makes sense with external Etcd since this is a so called "admin mode"
- Running `gRPC` backend would not setup downsampler and Etcd is not required
- When running `promRemote` Etcd is required since downsampler is initialized. And by default it's an in process one.
With this change it's now possible to run in process aggregator (downsampler) without external Etcd. 
Another fix is to initialize `/namespaces` key if it's not set. Otherwise startup takes 5s more because we are waiting for watcher to …
=> [coordinator] Enable running M3 coordinator without Etcd

src/query/storage/fanout/storage_test.go
It is flaky, because `QueryStorageMetadataAttributes` constructs a map which then iterates.
=> [coordinator] fix flaky test

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_base.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/entry.go, src/aggregator/aggregator/flush.go, src/aggregator/aggregator/flush_mgr.go, src/aggregator/aggregator/flush_mgr_mock.go, src/aggregator/aggregator/follower_flush_mgr.go, src/aggregator/aggregator/follower_flush_mgr_test.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/leader_flush_mgr_test.go, src/aggregator/aggregator/list.go, src/aggregator/aggregator/timer_elem_gen.go
Adds follower flush metrics to mirror existing leader flush metrics.
Fixes #
```release-note
```
```documentation-note
```
=> [aggregator] Add follower flush metrics

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_base.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/flush.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/leader_flush_mgr.go, src/aggregator/aggregator/list.go, src/aggregator/aggregator/list_test.go, src/aggregator/aggregator/timer_elem_gen.go
Adds another histogram tracking forward lag with the jitter removed
This is useful for seeing raw differences in lag without dealing with the
additional variable of jitter that can make it difficult to tell how updates
to the code affect lag
=> [aggregator] Track unjittered forwarding lag

src/aggregator/aggregator/aggregator.go, src/aggregator/aggregator/aggregator_test.go, src/aggregator/aggregator/map.go, src/aggregator/aggregator/map_test.go, src/aggregator/aggregator/shard.go, src/cmd/services/m3aggregator/serve/serve.go
Aggregator's `tickInternal` method can soft-block `aggregator.Close()` for
a long period of time if the doneCh is signalled during a tick; these end up
iterating over internal shard ticks, which can take up to `EntryCheckInterval`,
which defaults to an hour. This is much longer than the graceful close period,
which is 15s by default, so aggregator graceful close almost never completes,
and ends up timing out instead.
=> [aggregator] Propagate cancellation through tick

src/aggregator/aggregation/common.go, src/aggregator/aggregation/counter.go, src/aggregator/aggregation/gauge.go, src/aggregator/aggregation/timer.go, src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_base.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/entry_test.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go
This fixes the following race:
1. Writer creates a new aggregation and adds it to the drity set.
2. Flusher processes dirty set.
3. Writer updates the aggregation value.
This race was introduced with the recent refactor of resending to use to
an explicit dirty set. However, this race existed historically before
resending introduced the notion of a dirty bit.
The fix is to ensure the individual aggregation lock is held when
read/writing the dirty bit.
It was starting to get really confusing what state truly needs to be guarded by the
aggregation lock. This also refactors the code to introduce an
aggFlushState of flusher local state that doesn't need any
synchronization. Now all fields on the lockedAggregation must be
accessed with the lock.
Fixes # …
=> Fix race when checking for dirty aggregations

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/entry_test.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go
This should help when having to iterate through the map to expire. There
are worst case scenarios when the map is sparse that burn a lot of CPU
doing a lot of empty lookups. This worst case happen when metrics become
dormant or infrequent, and you have to scan the entire "range" of the
map for no reason.
Fixes #
```release-note
```
```documentation-note
```
=>  Keep pointers to next/prev aggregations

src/dbnode/persist/fs/files.go
For namespaces with long retentions huge CPU spikes could emerge during node bootstrap. Looking at the CPU profile, we can see that `filesetFiles` function is not very efficient. 
This PR optimizes `filesetFiles` function by reducing the amount of work it needs to do. It now collects `blockStart` and `volumeIndex` fields and later reuse them during sorting and further iterations (without a need to parse them again).
I've written a small benchmark to measure the new implementation (new implementation is ~ 30% faster):
* 230140 ns/op  - new implementation
* 324493 ns/op  - old implementation
```release-note
```
**Does this PR require …
=> [dbnode] Optimize `filesetFiles` function

src/integration/resources/coordinator_client.go, src/integration/resources/inprocess/aggregator_test.go
Fixes #
```release-note
```
```documentation-note
```
=> [tests] Ensure query param is set in InstantQuery and RangeQuery

src/dbnode/integration/index_block_orphaned_entry_test.go, src/dbnode/integration/index_helpers.go, src/dbnode/storage/entry.go, src/dbnode/storage/entry_blackbox_test.go, src/dbnode/storage/index/block.go, src/dbnode/storage/index/block_bench_test.go, src/dbnode/storage/index/block_test.go, src/dbnode/storage/index_query_concurrent_test.go, src/dbnode/storage/index_queue_forward_write_test.go, src/dbnode/storage/index_queue_test.go, src/m3ninx/doc/doc_mock.go, src/m3ninx/doc/types.go
In db nodes, state is kept for cheap lookups to determine if a series is
indexed for a specific block start. This state exists on the document in the
index and in the shard object. On concurrent writes to the same time series,
it's possible for these two sources to get out of sync. Basically, the
state associated with the document on the index is a different instance
than the one that gets placed in the shard's lookup map. This can
result in issues where we don't accurately track that a series in
indexed for a specific block start as only the entry in the lookup
map will get updated in the future.
To resolve this, we introduce reconciliation methods when querying these
objects. If it's noticed on read that we're querying index state that
never got …
=> [dbnode] Gracefully handle reads including documents with stale index state

src/msg/producer/writer/message.go, src/msg/producer/writer/message_writer.go, src/msg/producer/writer/message_writer_test.go
Using Message.InitNanos for lag calculations is misleading for retries,
since retries are intentionally delayed. Now an explicit
ExpectedProcessedAt timestamp is maintained to keep track of when it is
expected for m3msg to process the message in the queue.
Fixes #
```release-note
```
```documentation-note
```
=> [m3msg] Use ExpectedProcessedAt for processing lag calculations

src/cmd/services/m3comparator/main/querier.go, src/cmd/services/m3query/config/config.go, src/query/server/query.go, src/query/storage/options.go, src/query/storage/prom_converter.go, src/query/storage/prom_converter_test.go, src/query/storage/types.go
Allows setting relative decrease tolerance up to which value decreases are eliminated while decoding time series data.
See #3872.
This is intended to replace https://github.com/m3db/m3/pull/3876 which can only operate within a single time series block.
NONE
NONE
=> [query] Prom converter supporting value decrease tolerance

src/aggregator/server/m3msg/server.go, src/cmd/services/m3coordinator/server/m3msg/config.go, src/cmd/services/m3coordinator/server/m3msg/protobuf_handler_test.go, src/msg/consumer/consumer.go, src/msg/consumer/handlers.go, src/msg/consumer/handlers_test.go, src/msg/consumer/types.go
The ConsumerHandler is redundant and unncessary. Use the
MessageProcessor interface for the aggregator so it's consistent with
the coordinator.
This will make it easier to add some base metrics to both consumers in
the future.
Fixes #
```release-note
```
```documentation-note
```
=> [m3msg] Remove unnecessary ConsumeHandler interface

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go
The forward_writer uses a version map indexed by timestamp, which is not
start aligned. When the flusher passes the set of times to expire, it
needs to convert the start aligned time to a timestamp.
This manifests as a significant memory leak for sparse workloads where
the timestamp of N != start aligned time of N+1. In those cases the
versions are never GCd when they expire out of the buffer.
Fixes #
```release-note
```
```documentation-note
```
=> [agg] Use timestamp (not start aligned) for expiring forward versions

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go
When calculating the forwarding lag, we want to add the latenesAllowed
and jitter to the timestamp so it's not counted in the processing lag
number. By subtracting it we were actually adding additional lag that
was incorrect.
forward lag = now - (timestamp + intentional delay)
intentional delay = allowedLateness + jitter
jitter = how long we intentionally delay a flush task so tasks don't run
at the same time.
allowedLateness = how long we intentionally delay a flush task so
allow for late metrics to arrive.
Fixes #
```release-note
```
```documentation-note …
```
=> [agg] Fix forward lag calculation

src/query/functions/temporal/aggregation.go, src/query/functions/temporal/aggregation_test.go, src/query/functions/temporal/base.go, src/query/functions/temporal/base_test.go, src/query/parser/promql/matchers.go, src/query/parser/promql/parse_test.go, src/query/test/compatibility/testdata/functions.test
This `<aggregation>_over_time` function was added in
Prometheus v2.26.0 ([changelog](https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2260--2021-03-31), [docs](https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time)).
Fixes #3883.
```release-note
Add support for `last_over_time`.
```
```documentation-note
NONE
```
=> [query] Add support for `last_over_time`

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_base.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/entry.go, src/aggregator/aggregator/entry_test.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go
This fixes a race when a rollup rule is migrated to resendEnabled, which
triggers using the client timestamp instead of the server timestamp.
However, the client timestamp might be targeting an old aggregation that
is already closed. When this happens, just continue using the
serverTimestamp and target an open aggregation.
This also refactors the existing logic of rolling forward to the next
aggregation when an aggregation is closed. Now that we have multiple
cases, it's easier to handle all of this logic at the higher level.
I kept this as separate commits. The first commit refactors the resendEnabled bit onto the lockedAggregation. This seems safer and easier to reason about, since we have multiple actors reading/writing this bit. Writes update the bit and the flusher reads the bit. …
=> [agg] Fix race when migrating to resendEnabled and the agg is closed 

src/aggregator/server/m3msg/server.go, src/msg/consumer/consumer.go, src/msg/consumer/handlers.go, src/msg/consumer/handlers_test.go, src/msg/consumer/types.go
This fixes a regression that was introduced in https://github.com/m3db/m3/pull/3918
The shared singleton MessageProcessor was being closed when a Connection
was being closed.
Now a Pool interface is introduced. A MessageProcessor is fetched when a
Connection is created and returned when a Connection is closed. It is up
to the pool impl to decide if it should Close the MessageProcessor on
each return or only when the pool is closed.
Fixes #
```release-note
```
```documentation-note
```
=> [msg] Do not Close singleton MessageProcessors when closing connections

src/dbnode/encoding/encoding_mock.go, src/dbnode/encoding/m3tsz/iterator.go, src/dbnode/encoding/m3tsz/iterator_test.go, src/dbnode/encoding/options.go, src/dbnode/encoding/types.go
Reverts #3876.
The functionality was replaced with #3914.
NONE
NONE
=> Revert "[query] Optional value decrease tolerance in M3TSZ decoder (#3876)"

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_base.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go
Previously the timestamp of the aggregation was used to calculate the
forwaridng lag. This could be misleading for late metrics updating
resendEnabled aggregations, since they are in the past.
Now the lastUpdatedAt time is used. The lastUpdatedAt is used to
calculate the expectedProcessingTime as the next resolution window after
the lastUpdatedAt.
Fixes #
```release-note
```
```documentation-note
```
=> [agg] Calculate forwarding lag using expected processing time

src/cmd/services/m3coordinator/ingest/write.go, src/query/storage/converter.go, src/query/storage/converter_test.go, src/query/ts/metadata.go
Open Metrics metric family types are mapped to the same internal enum as Prometheus metric family types, but the logics of what is a cumulative counter depending on a metric name suffix differs.
Was trying to follow https://github.com/OpenObservability/OpenMetrics/blob/2bd6413e040513afa1bfb8f56dd12db8262e18d9/specification/OpenMetrics.md#metric-types.
NONE
NONE
=> [coordinator] Add mapping for Open Metrics types

src/cmd/services/m3coordinator/downsample/id_pool_types.go, src/cmd/services/m3coordinator/downsample/id_pool_types_test.go
Previously the tag merge logic could result in duplicate __rollup__ tags
if the provided tags already had __rollup__.
Additionally refactored to lazily merge the 2 sorted slices when calling
Next(). This made it much easier to add deduping logic and I believe
makes it easier to follow the code.
Fixes #
```release-note
```
```documentation-note
```
=> [coord] Guard against duplicate __rollup__ tags

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_test.go, src/aggregator/aggregator/entry_test.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/timer_elem_gen.go
This fixes a tricky race condition:
1. Flusher copies resendEnabled=false from the agg
2. Writer migrates agg to resendEnabled=true (agg is not closed yet)
3. Flusher closes the agg because it has stale state
(resendEnabled=false)
4. Subsequent writes to the agg will fail with aggregationClosed
The fix is to read the resendEnabled state again in step 3 after
re-acquiring the lock in order to close the agg. If the state changed,
don't close the aggregation.
Fixes #
```release-note
```
```documentation-note
```
=> [agg] Fix race closing an aggregation that migrated to resendEnabled

src/integration/prometheus/prometheus.go, src/integration/resources/coordinator_client.go, src/integration/resources/docker/coordinator.go, src/integration/resources/inprocess/coordinator.go, src/integration/resources/types.go
Allows integration tests to construct `prompb.WriteRequests`. This is useful for sending many timeseries in a single request which previously wasn't possible.
```release-note
NONE
```
```documentation-note
NONE
```
=> [integrations] Add writeRequest API to coordinator client

src/x/instrument/build.go
This commit updates the `instrument` package to be able to log the build info to stdout instead of stderr. GKE logs written to stdout are classified as `INFO` logs in Google Cloud Logging whereas logs written to `stderr` are classified as `ERROR` logs so build info logs are currently classified as `ERROR` logs which doesn't feel appropriate.
=> [instrument] Optionally log build info to stdout

src/cmd/services/m3coordinator/ingest/carbon/ingest.go, src/cmd/services/m3coordinator/ingest/carbon/ingest_test.go, src/cmd/services/m3coordinator/ingest/write.go, src/cmd/services/m3coordinator/ingest/write_mock.go, src/cmd/services/m3coordinator/ingest/write_test.go
Adds reporting of `coordinator_downsampler_metrics_written{source="graphite"}` from carbon ingest endpoint for a complete picture.
NONE
NONE
=> [coordinator] Report written metrics from carbon endpoint

src/aggregator/aggregator/aggregator.go, src/aggregator/aggregator/aggregator_test.go
If a user has enabled resending for an untimed metric, the client
timestamp is checked for lateness just liked timed metrics.
Fixes #
```release-note
```
```documentation-note
```
=> [agg] Handle too far past/future errors for untimed metrics

src/aggregator/aggregator/entry.go, src/aggregator/aggregator/entry_test.go, src/aggregator/aggregator/map.go
This replaces the previous attempt of recording the distributions of
expirations. The previous attempt would update the distribution on
ticks, which would heavily weight untouched metrics.
Instead we just want the distribution between writes to a metric, only
counting metrics that are actually updated.
Fixes #
```release-note
```
```documentation-note
```
=> [agg] Add metric tracking duration between writes

src/aggregator/aggregator/entry.go
This is a minor improvement to combine 2 atomic operations into 1.
Fixes #
```release-note
```
```documentation-note
```
=> [agg] Use an atomic swap for lastAccessNanos

src/cmd/services/m3coordinator/downsample/id_pool_types.go, src/cmd/services/m3coordinator/model/rollup.go
Small refactor to allow us to reuse these values later.
=> [m3coordinator] Add a model for rollup tag name and value

src/msg/producer/config/writer.go, src/msg/producer/config/writer_test.go, src/msg/producer/writer/consumer_writer_test.go, src/msg/producer/writer/message_writer.go, src/msg/producer/writer/message_writer_test.go, src/msg/producer/writer/options.go, src/msg/producer/writer/options_test.go
In a use case I want to make the message writer retry messages like this:
- 1st retry needs to wait 5 minutes to give the consumer some time for processing.
- 2nd retry needs to happen 10s after the 1st retry.
- 3rd and future retries wait approximately 10s after the last retry.
It is impossible to config the retry options to do so.
This pr adds a static retry policy that allows user to declare backoff duration between each retry clearly. 
Fixes #
```release-note
NONE
```
```documentation-note
probably, since we support a new way to config retry policy.
```
=> [M3msg] Add static retry policy for message retry

src/dbnode/storage/series_resolver.go, src/dbnode/storage/series_resolver_test.go, src/dbnode/storage/shard.go, src/dbnode/storage/shard_test.go
`SeriesRefResolver ` might leak entries if they are not already inserted.
This PR decrements reader writer count when resolving new entry from the resolver so the entry could be purged later.
```release-note
```
```documentation-note
```
=> [dbnode] Fixing entry leak in series ref resolver

src/query/api/v1/handler/prom/read.go, src/query/api/v1/handler/prometheus/remote/read_test.go, src/query/storage/prom_converter.go, src/query/storage/prometheus/context.go, src/query/storage/prometheus/prometheus_storage.go, src/query/storage/prometheus/prometheus_storage_test.go, src/query/storage/types.go
- Allows concurrent updates to result metadata. This is necessary when a Prometheus query ends up creating multiple concurrent fetch operations.
- Allows Prometheus result code paths to generate their own metadata without it being immediately overwritten by its caller. This will be useful in the future when those code paths actually do generate their own metadata.
```release-note
```
```documentation-note
```
=> [query] Result metadata fixes

src/query/api/v1/handler/graphite/find_test.go, src/query/api/v1/handler/prometheus/handleroptions/header_test.go, src/query/api/v1/handler/prometheus/handleroptions/headers.go, src/query/api/v1/handler/prometheus/remote/read_test.go, src/query/api/v1/handler/prometheus/remote/tag_values_test.go, src/query/block/meta.go, src/query/graphite/storage/m3_wrapper_test.go, src/query/remote/server_test.go, src/query/storage/m3/storage.go, src/query/storage/prom_converter.go, src/x/headers/headers.go
Breaks down the M3-Series-Count response header into:
* Unaggregated series count (not rolled up series)
* Aggregated series count(rolled up series)
* Series without samples (omitted from the result)
* Series with samples (included in the result)
It also emits the following for diagnostics:
* The set of namespaces accessed when querying m3
* The estimated byte size of the result set (already calculated, now exposed)
* The number of m3 response batches received (already calculated, now exposed)
```release-note
```
```documentation-note
```
=> [storage] Additional metadata on aggregated vs unaggregated series, etc.

src/query/api/v1/handler/prometheus/handleroptions/header_test.go, src/query/api/v1/handler/prometheus/handleroptions/headers.go, src/query/api/v1/handler/prometheus/remote/read_test.go, src/query/block/meta.go, src/query/block/meta_test.go, src/query/storage/fanout/storage_test.go, src/query/storage/m3/storage.go, src/query/storage/m3/storage_test.go, src/query/storage/prom_converter.go, src/query/storage/prom_converter_test.go, src/query/storage/prometheus/prometheus_storage_test.go, src/query/storage/types.go
- Log JSON errors when serializing MetricStats.
- Use metricNameFromLabels in prom_converter.go.
- Reduce string copies by comparing to byte arrays when possible.
- Initialize the MetricStats map with a size.
```release-note
```
```documentation-note
```
=> [query] Some cleanups around generating new stats/metadata fields

src/msg/producer/writer/message.go
There is a race between the writer and the acker when accessing the
expected processed at. The writer updates the value and the acker reads
the value.
Fixes #
```release-note
```
```documentation-note
```
=> [m3msg] Use atomic value for expected processed at

src/cmd/services/m3coordinator/downsample/metrics_appender.go, src/cmd/services/m3coordinator/downsample/metrics_appender_test.go, src/cmd/services/m3coordinator/downsample/options.go, src/x/serialize/unchecked_decoder.go, src/x/serialize/unchecked_decoder_test.go, src/x/serialize/unchecked_metric_tags_iterator.go
This adds an unchecked tag decoder/iterator which removes all safety
checks (i.e ref checking) to improve the performance. It is safe to use
this when the underlying bytes are not shared and are safe to reuse.
A good example of this is the downsampler, that is single threaded and
has to match a metric id against many rules. This significantly
increases the performance of the downsampler.
=> [serialize] Add a fast unchecked tag decoder 

src/cmd/services/m3coordinator/downsample/options.go, src/cmd/services/m3coordinator/downsample/options_test.go, src/query/storage/m3/cluster.go, src/query/storage/m3/config.go, src/query/storage/m3/storage.go, src/query/storage/m3/storage_test.go, src/query/storage/promremote/types_test.go
Add `readOnly` option to namespace config. Such namespace does not accept any writes. 
No auto-mapping rules get created for it, regardless of `downsample.all` setting.
NONE
NONE
=> [coordinator] Add readOnly option to namespace config

src/cmd/tools/m3ctl/README.md, src/cmd/tools/m3ctl/main/main.go, src/cmd/tools/m3ctl/placements/delete.go, src/cmd/tools/m3ctl/placements/get.go, src/cmd/tools/m3ctl/placements/types.go
This is the first commit of adding multiple services support for m3ctl. Current change adds `--service` flag to `m3ctl get placement`, `m3ctl delete placement` commands in order to manage placements for different m3 services, like aggregator, coordinator or m3db (default).
Additional command line flag is added.
NONE
=> [tools] add service type argument to m3ctl placement command

src/cmd/services/m3coordinator/downsample/async_downsampler.go, src/cmd/services/m3coordinator/downsample/downsample_mock.go, src/cmd/services/m3coordinator/downsample/downsampler.go, src/cmd/services/m3coordinator/ingest/write.go, src/cmd/services/m3coordinator/ingest/write_mock.go, src/metrics/matcher/match.go, src/metrics/matcher/matcher_mock.go, src/metrics/matcher/namespaces.go, src/metrics/matcher/ruleset.go, src/metrics/matcher/ruleset_test.go, src/metrics/rules/active_ruleset.go, src/metrics/rules/active_ruleset_test.go
Extend the ActiveRuleset etc interfaces to provide a snapshot of the latest Rollup Rules for a namespace and timeNanos.
This will allow other parts of the code to inspect rollup rules, which can help with query analysis.
```release-note
```
```documentation-note
```
=> [downsampler] Add LatestRollupRules from ActiveRuleset -> Downsampler

go.mod, src/aggregator/aggregator/entry.go, src/aggregator/aggregator/entry_test.go
the various m3 errors don't work well with uber/multierr.
For example if you do m3errors.Is(uberMultierr, target) and uberMultierr
contains a m3.InnerError, it won't find it.
uber/multierr is probably better but we'll need to first retrofit a lot
of the m3.InnerError types to support Is(err).
Fixes #
```release-note
```
```documentation-note
```
=> [agg] Do not use uber/multierr

src/cmd/services/m3query/config/config.go, src/cmd/services/m3query/config/config_test.go, src/query/api/v1/handler/graphite/find_test.go, src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go, src/query/api/v1/handler/prometheus/handleroptions/header_test.go, src/query/api/v1/handler/prometheus/handleroptions/headers.go, src/query/api/v1/handler/prometheus/remote/read_test.go, src/query/api/v1/handler/prometheus/remote/tag_values_test.go, src/query/block/meta.go, src/query/graphite/storage/m3_wrapper_test.go, src/query/remote/client.go, src/query/remote/server_test.go, src/query/storage/fanout/storage.go, src/query/storage/fetch.go, src/query/storage/m3/storage.go, src/query/storage/m3/storage_test.go, src/query/storage/prom_converter.go, src/query/storage/prom_converter_test.go, src/query/storage/types.go, src/x/headers/headers.go
Allows metric metadata stats to be disabled via config or request header.
```release-note
```
```documentation-note
```
=> [query] Configurable metric metadata stats count

src/cluster/placement/algo/sharded_helper.go, src/cluster/placement/algo/sharded_prop_test.go, src/cluster/placement/algo/sharded_test.go
Fixes unbalanced shard assignment to instances when initializing sharded placement. This was caused by nondeterministic comparison function used in a heap. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [cluster] Fix unbalanced initial shard allocation for sharded placement

src/cmd/tools/m3ctl/README.md, src/cmd/tools/m3ctl/main/main.go, src/cmd/tools/m3ctl/topics/delete.go, src/cmd/tools/m3ctl/topics/get.go, src/cmd/tools/m3ctl/topics/types.go, src/x/generated/mock.go
This change adds `get topic`, `delete topic` commands in order to manage m3db topics through m3ctl.
Adds additional command to m3ctl.
Updated README.md
=> [tools] add get/delete topic command to m3ctl

src/cluster/placement/algo/sharded_helper.go
Makes instance selection in `sharded_helper::mostUnderLoadedInstance()` deterministic. Before this, the method would occasionally select a different instance than usual, which would cause flakiness in `TestOptimize()` test, e.g.:
- https://buildkite.com/chronosphereopensource/oss-m3-monorepo-public/builds/364#7bb51f4e-9bd3-446f-8cab-c2a5b383b053/896
- https://buildkite.com/chronosphereopensource/oss-m3-monorepo-public/builds/320#cd3cc8da-c15c-4af3-834f-81e1afad78d2/999 
```release-note
NONE
```
```documentation-note
NONE
```
=> [cluster] Avoid nondeterminism in `mostUnderLoadedInstance()`

src/dbnode/client/connection_pool.go, src/dbnode/client/connection_pool_test.go, src/dbnode/client/session.go, src/dbnode/client/session_test.go
Fixes # Channel leak in DedicatedConnection 
Minimal changes to fix the connection leak. I have another PR to refactor code a bit to extract connection code into func.
```release-note
```
```documentation-note
```
=> [coordinator] Prevent TChannel leaks

src/m3ninx/index/segment/builder/fields_map_new.go, src/m3ninx/index/segment/builder/ids_map_new.go, src/m3ninx/index/segment/builder/postings_map_new.go, src/m3ninx/index/segment/mem/fields_map_new.go, src/query/graphite/storage/series_metadata_map_new.go
Master build got broken after a PR from 2021 (https://github.com/m3db/m3/pull/4015) was merged in 2022 resulting in incorrect copyright year in some of the generated files (genny).
This PR regenerates the files making them contain copyright year 2022.
NONE
NONE
=> [all] make genny-gen to fix master

src/cmd/services/m3query/config/config.go, src/cmd/services/m3query/config/config_test.go, src/cmd/services/m3query/config/testdata/config.yml, src/query/storage/options.go, src/query/test/seriesiter/mock_iter.go
Makes `resolutionThresholdForCounterNormalization` configurable.
NONE
NONE
=> [query] resolutionThresholdForCounterNormalization configurable

src/dbnode/integration/index_block_orphaned_entry_test.go, src/dbnode/storage/entry.go, src/dbnode/storage/entry_blackbox_test.go, src/dbnode/storage/index/block.go, src/m3ninx/index/segment/builder/multi_segments_builder.go
Duplicate reconciliation was added to the background compaction
mechanism in https://github.com/m3db/m3/pull/3999, but this does not
account for cases where reconciliation is needed for series that are
indexed in the foreground segments. This attempts to reconcile duplicate
series if reconciliation is required.
=> [dbnode] Add duplicate reconciliation on query

src/query/storage/prom_converter.go
Before this change, an error returned from `IterTagsAtIndex` would cause early return from `toPromConcurrently`, skipping `wg.Wait()` and possibly leaving other iterators being processed in the background. Then, the caller of `toPromConcurrently` would close those iterators (which are still being processed), causing runtime panics.
Fixed by replacing early `return` with a `break`.
NONE
NONE
=> [query] Fix error handling in toPromConcurrently

src/cmd/tools/m3ctl/README.md, src/cmd/tools/m3ctl/yaml/examples/init.yaml, src/cmd/tools/m3ctl/yaml/examples/new_node.yaml, src/cmd/tools/m3ctl/yaml/examples/replace_node.yaml, src/cmd/tools/m3ctl/yaml/peeker.go
This is required for `apply` command to work after https://github.com/m3db/m3/pull/3979 was integrated.
Updated examples.
NONE
=> [tools] Add service type to m3ctl apply command

src/x/debug/debug.go, src/x/debug/ext/ext.go, src/x/debug/ext/placement.go, src/x/debug/ext/placement_test.go, src/x/debug/test/test.go
Fixes a panic in debug handler caused by `nil` placement. 
```release-note
NONE
```
```documentation-note
NONE
```
=> [x/debug] Fix panic when placement is nil

src/query/storage/m3/consolidators/multi_fetch_result.go
`multiResult.FinalResult` was protected by a lock, but a similar method `multiResult.FinalResultWithAttrs` (that wraps a `FinalResult` call) was not. I am not sure if this was causing any issues, but I will protect the whole `multiResult.FinalResultWithAttrs` with a lock.
Also, took the opportunity to avoid a double call to `dedupeMap.list()` (which is expensive in both CPU and allocations).
NONE
NONE
=> [query] More robust multiResult locking

src/query/storage/m3/consolidators/id_dedupe_map.go, src/query/storage/m3/consolidators/tag_dedupe_map.go
It does not really matter in which order we combine the iterators. But this change both simplifies the implementation, and makes it slightly easier to reason about iterator lifecycles.
NONE
NONE
=> [query] Simplify iterator stitching

src/query/storage/m3/cluster_resolver.go, src/query/storage/m3/cluster_resolver_test.go
Truncate the stitching point to the resolution of aggregated namespace to avoid artefacts with different resolution Prometheus counters.
NONE
NONE
=> [query] Align namespace stitching point with resolution

src/dbnode/encoding/series_iterator_accumulator.go, src/dbnode/encoding/series_iterator_accumulator_test.go, src/query/storage/m3/consolidators/id_dedupe_map_test.go, src/query/storage/m3/consolidators/tag_dedupe_map_test.go
`SeriesIteratorAccumulator.FirstAnnotation` was not always returning the annotation value because it was trying to get it from internal iterators which may have already skipped their first datapoint because of internal start-end range filter.
With this change, the value for `SeriesIteratorAccumulator.FirstAnnotation` will be taken from the underlying `SeriesIterator.FirstAnnotation`.
NONE
NONE
=> [query] Fix SeriesIteratorAccumulator.FirstAnnotation

src/query/api/v1/httpd/handler.go, src/query/api/v1/httpd/handler_test.go, src/query/api/v1/options/handler.go, src/query/server/query.go
Excludes m3db namespace and placement output from the `/debug/dump` of m3query. In coordinator, the ETCD details were not being configured correctly and handler wasn't working as intended, sometimes returning wrong namespaces/placements and sometimes failing.
Namespaces and placements remain being returned in `/debug/dump` of dbnode  under 9004 port.
https://github.com/m3db/m3/blob/6f5a50adcea52f44d3646114f28b29ba9e30fa32/src/dbnode/server/server.go#L861-L874
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Remove the output of m3db placement from /debug/dump

src/dbnode/persist/fs/commitlog/commit_log.go, src/dbnode/persist/fs/commitlog/commit_log_test.go, src/dbnode/persist/fs/commitlog/read_write_prop_test.go, src/dbnode/persist/fs/commitlog/writer.go
This commit adds a `setOnFlush` method to both the `commitLogWriter` and `chunkWriter` intefaces.
This function is necessary to get around a subtle bug in the `WriteWait` commitlog strategy
causing `pendingFlushFns` calls (and therefore `commitLog.Write` returning) to lag.
The issue is that after the first call to `RotateLogs`, when `onFlush` is called, it ends up reading
from the wrong list of `pendingFlushFns`. This is hard to detect as this occurs after the data has
already been flushed to the correct file on disk and only affects reporting completion.
It is not caught by any tests because the next call to `RotateLogs` (or `Close`) will resolve the problem.
Additionally, we mostly test the default `WriteBehind` strategy rather than the …
=> [commitlog] Add setter functions for the onFlush callback

site/content/reference/m3coordinator/api/remote.md
Updates Snappy link that is 404ing
=> [DOCS] Update broken Snappy link

src/x/mmap/mmap_other.go, src/x/mmap/mmap_windows.go
```release-note
```
NONE
```documentation-note
NONE
```
Currently, M3 does not run on Windows. The `src/dbnode/persist/fs/commitlog package` specifically
does not build because of the the internal packages it depends on transitively (`src/x/mmap`)
uses syscalls that are not available on Windows.
This commit creates a dummy implementation of that package only for Windows allows
the commitlog to be used as a package in binaries built for Windows.
=> Allow the commitlog package to build on windows

src/cluster/client/etcd/client.go, src/cluster/client/etcd/client_test.go, src/cluster/client/etcd/config.go, src/cluster/client/etcd/options.go, src/cluster/client/etcd/types.go
GRPC dial options are useful for a variety of use cases--adding default headers (via a stream interceptor), injecting code into the low level connection flow via
a net.Dialer (e.g. to support proxying across network boundaries).
This diff adds an option on clusters to pass through GRPC.DialOptions for these use cases. Defaults of nil should match current behavior.
```release-note
NONE
```
```documentation-note
NONE
```
=> Add GRPC dial options support to etcd cluster options

src/dbnode/persist/fs/commitlog/options.go, src/dbnode/persist/fs/options.go
There are several places where we allocate large pools of memory
in constructors and provide setters to override those pools.
In general, this is fine as it allows us to provide larger or smaller
pools. However, in super memory constrained settings, we prefer to
avoid the initial alloc and GC all together and provide
the properly sized pools to the constructor.
This PR provides the ability to do this for certain properties
of fs.Options and commitlog.Options.
Fixes #
```release-note
```
```documentation-note
```
=> [commitlog] Add the ability to configure pools before allocation

src/x/log/config.go, src/x/log/config_test.go
This PR adds a method that returns a Zap Logger Configuration object while building the logger. This allows other methods to optionally receive the Zap Config object so they can dynamically change the logging level for example. 
Fixes #
**Special notes for your reviewer**: This has been tested in an external library as well as the unit test here.
```release-note
NONE
```
```documentation-note
NONE
```
=> Add method in log/config that returns a Zap Config

src/msg/producer/config/writer.go, src/msg/producer/config/writer_test.go, src/msg/producer/ref_counted.go, src/msg/producer/writer/consumer_service_writer.go, src/msg/producer/writer/consumer_writer_test.go, src/msg/producer/writer/message.go, src/msg/producer/writer/message_pool.go, src/msg/producer/writer/message_pool_test.go, src/msg/producer/writer/message_writer.go, src/msg/producer/writer/message_writer_benchmark_test.go, src/msg/producer/writer/message_writer_test.go, src/msg/producer/writer/options.go, src/msg/producer/writer/options_test.go, src/msg/producer/writer/shard_writer.go, src/msg/producer/writer/shard_writer_test.go
* Fix a potential memory leak as `message` wrapper did not clear `message.RefCountedMessage` pointer - rarely hit in practice due to frequent reuse and limited size of internal `messageWriter` buffer of `scanBatchSize`, but still potentially bloating memory usage.
* Simplify `message` pooling on Producer - best option is to always use the dynamic-sized pool - need to change this in consumer as well. It cleans up the tests as well as they were assuming specific pool implementation behavior.
```release-note
m3msg producer MessagePool configuration is deprecated, pooling is always enabled.
```
**Does this PR require updating code package …
=> [m3msg] Message pooling cleanup

src/aggregator/aggregator/counter_elem_gen.go, src/aggregator/aggregator/elem_base.go, src/aggregator/aggregator/entry_test.go, src/aggregator/aggregator/gauge_elem_gen.go, src/aggregator/aggregator/generic_elem.go, src/aggregator/aggregator/list.go, src/aggregator/aggregator/timer_elem_gen.go
Some of these (dynamic) metrics are on critical path, and storing entire (and pretty large struct) embedded as a lockless cache bloats the element struct size itself, taking overall hundreds of megabytes of memory, when the lock-protected global metric map is ~1mb.
```release-note
```
```documentation-note
```
=> [aggregator] Refactor elem/flush metrics

src/msg/producer/writer/consumer_service_writer_test.go, src/msg/producer/writer/message_writer.go, src/msg/producer/writer/message_writer_benchmark_test.go, src/msg/producer/writer/message_writer_test.go, src/msg/producer/writer/router.go, src/msg/producer/writer/router_mock.go, src/msg/producer/writer/shard_writer.go, src/msg/producer/writer/shard_writer_test.go
... as it only has a single implementation.
Both the interface and implementation are private, so it's safe to remove.
```release-note
```
```documentation-note
```
=> [m3msg] Remove messageWriter interface

.golangci.yml, src/msg/producer/writer/message_writer.go, src/msg/producer/writer/message_writer_benchmark_test.go, src/msg/producer/writer/message_writer_test.go
There's no need for shard in metadataKey for internal messageWriter ack map, as it's always the same shard.
```
name    old time/op  new time/op  delta
Ack-12  56.0ns ± 7%  48.5ns ± 4%  -13.51%  (p=0.000 n=9+9)
```
```release-note
```
```documentation-note
```
=> [m3msg] Specialize messageWriter acker map

src/dbnode/integration/graphite_find_test.go, src/dbnode/integration/setup.go, src/dbnode/storage/coldflush.go, src/m3ninx/index/segment/fst/segment.go, src/query/server/query.go, src/query/stores/m3db/async_session.go, src/x/test/diff.go, src/x/test/util.go
Previously we only had quite basic coverage of simple cases with the `carbon` docker integration tests for the find API (see https://github.com/m3db/m3/tree/v1.1.0/scripts/docker-integration-tests/carbon). 
This adds a much more comprehensive and complex integration test that tests a complex tree and verifies all results in the tree are correctly returned when walking the tree and issuing queries.
```release-note
NONE
```
```documentation-note
NONE
```
=> [query] Add Graphite find integration test that verifies complex trees return valid results

src/integration/aggregator/aggregator.go, src/integration/aggregator/aggregator_test.go, src/integration/repair/repair_and_replication_test.go, src/integration/resources/coordinator_client.go, src/integration/resources/docker/dockerexternal/etcd.go, src/integration/resources/inprocess/aggregator.go, src/integration/resources/inprocess/cluster.go, src/integration/resources/inprocess/coordinator_test.go, src/integration/resources/inprocess/dbnode_test.go, src/integration/resources/inprocess/inprocess.go, src/integration/resources/options.go
PR 4 for https://github.com/m3db/m3/issues/4144
High level approach is as described in https://github.com/m3db/m3/issues/4144 .
This PR integrates docker based etcd into our Go integration tests. It removes the need to have the embed package running
in m3db for them, but doesn't yet touch that functionality.
commit-id:3ae12ffd
---
**Stack**:
- #4150
- #4149
- #4148 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> etcd_docker 4: Incorporate docker based etcd into Go integration tests

src/aggregator/client/config.go, src/aggregator/client/conn.go, src/aggregator/client/options.go, src/aggregator/client/queue.go, src/aggregator/client/queue_mock.go, src/aggregator/client/queue_test.go, src/aggregator/client/writer.go, src/aggregator/client/writer_benchmark_test.go, src/aggregator/client/writer_mgr.go, src/aggregator/client/writer_mgr_test.go, src/aggregator/client/writer_test.go, src/aggregator/integration/client.go, src/x/errors/errors.go, src/x/errors/errors_test.go
The aggregator client performed locking on a per-writer or per-queue basis. This protects against racy access to the underlying conn and queue but does not protect against re-ordering. ie. in case multiple flushes happen at the same time for a writer any one can win. This possibility instructed the users of the client to synchronize the entire flush call at the writer manager level and made it so that all flushes would be blocked until the ongoing flushes for each writer is completed. This means that a slow writer will block the flush of all other writers. 
We therefore want the ability to flush writers at their own speeds effectively only blocking themselves in case they are slow. As such this PR makes sure that a writer will only have one active …
=> Allow non-blocking flushes across writers

site/.htmltest.yml
Got a failure for https://graphite.readthedocs.io/en/latest/functions.html -- the site might just be slow. Spurious failures here seem likely,
so bumping timeout to 30s.
=> Raise ExternalTimeout for htmltest

src/msg/producer/writer/message.go
Fixes #
The race itself is fixed at the root in #4114 - however that PR still isn't ready yet, and this is Good Enough (tm) for now.
It hasn't been a problem in practice, however tests with `-race` complain. Also we should fix the tests to actually run with `-race`.
```documentation-note
```
=> [m3msg] Remove data race

src/query/api/v1/handler/prometheus/handleroptions/options.go, src/query/api/v1/handler/prometheus/remote/test/write.go, src/query/api/v1/handler/prometheus/remote/write.go, src/query/api/v1/handler/prometheus/remote/write_test.go
This helps shadow flow of data to a specific % of unique series which helps control cardinality when shadowing traffic to a smaller cluster than that of the cluster where the data is being forwarded from.
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Add config for forwarding remote write with percent of unique series

src/dbnode/storage/bootstrap/bootstrapper/base.go, src/dbnode/storage/bootstrap/bootstrapper/base_test.go, src/dbnode/storage/bootstrap/util.go
dbnode was not updating in-memory index state to contain the blocks that have been peer bootstrapped. This was the case  because peer bootstrapping is the second bootstrapper run (after filesystem bootstrapper), and there was no code to add the peer-bootstrapped index blocks into final bootstrap result. This PR adds that piece of code to `src/dbnode/storage/bootstrap/bootstrapper/base.go`.
=> [dbnode] Add IndexResults from subsequent bootstrap runs

src/query/api/v1/handler/prometheus/remote/write.go, src/query/api/v1/handler/prometheus/remote/write_test.go
Fixes the inverted interpretation of the Prometheus remote write shadow sampling configuration. The intention was that 10% shadow sampling should mean sending 10% of the traffic passing through the coordinator, not sending a copy of 90% of the traffic passing through and dropping 10% of it.
Also added some tests which would have caught this inverted interpretation (instead of only testing 50% shadow sample rates in the unit tests).
```release-note
NONE
```
```documentation-note
NONE
```
=> [coordinator] Fix inverted interpretation of Prometheus remote write shadow sampling config

docker-compose.yml, src/integration/resources/docker/dockerexternal/etcd.go, src/integration/resources/docker/dockerexternal/etcd_options.go, src/integration/resources/docker/dockerexternal/etcd_test.go, src/integration/resources/docker/dockerexternal/etcdintegration/bridge/README.md, src/integration/resources/docker/dockerexternal/etcdintegration/bridge/bridge.go, src/integration/resources/docker/dockerexternal/etcdintegration/cluster.go, src/integration/resources/docker/dockerexternal/etcdintegration/cluster_test.go, src/integration/resources/docker/dockerexternal/etcdintegration/types.go, src/x/dockertest/common.go, src/x/dockertest/docker_resource.go
PR 2 for https://github.com/m3db/m3/issues/4144
High level approach is as described in https://github.com/m3db/m3/issues/4144 . This PR adds:
- Functions to spin up a 1 node etcd cluster using docker (in `dockerexternal`)
- A drop in replacement for the etcd/integration package using `dockerexternal`
---
**Stack**:
- #4209
- #4208
- #4207
- #4206
- #4205
- #4154 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> etcd_docker 2: Add a docker based etcdintegration package

src/integration/aggregator/aggregator.go, src/integration/aggregator/aggregator_test.go, src/integration/repair/repair_and_replication_test.go, src/integration/resources/coordinator_client.go, src/integration/resources/docker/dockerexternal/etcd.go, src/integration/resources/inprocess/aggregator.go, src/integration/resources/inprocess/cluster.go, src/integration/resources/inprocess/coordinator_test.go, src/integration/resources/inprocess/dbnode_test.go, src/integration/resources/inprocess/inprocess.go, src/integration/resources/options.go
PR 4 for https://github.com/m3db/m3/issues/4144
High level approach is as described in https://github.com/m3db/m3/issues/4144 .
This PR integrates docker based etcd into our Go integration tests. It removes the need to have the embed package running
in m3db for them, but doesn't yet touch that functionality.
---
**Stack**:
- #4209
- #4208
- #4207
- #4206 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> etcd_docker 4: Incorporate docker based etcd into Go integration tests (#4148)

src/msg/producer/producer_mock.go, src/msg/producer/ref_counted.go, src/msg/producer/ref_counted_test.go, src/msg/producer/types.go, src/msg/producer/writer/consumer_service_writer.go, src/msg/producer/writer/consumer_service_writer_mock.go, src/msg/producer/writer/consumer_service_writer_test.go, src/msg/producer/writer/writer.go, src/msg/producer/writer/writer_test.go
**What this PR does / why we need it**: This PR is needed because we currently cannot use both a storage policy filter and consumer service filter inside m3aggregator for a single consumer, we can only use one filter. This limits us from being able to filter on shardSet and storage policy which may be required. [Here](https://github.com/m3db/m3/pull/4223) we currently register filters in a map keyed by serviceID, so if a service has more than one filter it gets overwritten.
**Does this PR introduce a user-facing and/or backwards incompatible change?**: No
**Does this PR require updating code package or user-facing documentation?**: No
=> [m3aggregator] Enable m3agg consumer writers to be able to use multiple filters

src/x/cache/lru_cache.go, src/x/cache/lru_cache_test.go
LRU cache (used for caching compiled query regexps in m3db) was not accepting any additional entries after becoming full. This was happening because `entry.key` was never being set, and then removal did not work.
=> [dbnode] Fix regexp LRU cache bug

src/m3ninx/index/regexp.go, src/m3ninx/index/regexp_prop_test.go, src/m3ninx/index/regexp_test.go, src/query/storage/index.go, src/query/storage/index_test.go, src/x/regexp/empty_matcher.go, src/x/regexp/empty_matcher_test.go
Fixes #4212
```release-note
PromQL queries with regexp OR selectors matching an empty value will now include time series that do not have the given label set (which is the expected behaviour in PromQL).
For example, given time series: foo{bar="a"} and foo{}
and the query: foo{bar=~"|a"} both time series will be now returned by the query.
Prior to this fix, only foo{bar="a"} was being returned.
```
```documentation-note
NONE
```
=> [query] Fix matching of disjunction including empty string

.buildkite/docs-build-pipeline.yml, .buildkite/image-release-pipeline.yml, .buildkite/pipeline.yml
Our buildkite pipeline uses AWS queues and is broken. We are switching over to use GCP queues to fix this. This PR only adds basic unit tests to the pipeline. Further work is needed to fix the remaining steps in our broken pipeline. Having basic unit tests is good enough for now to unblock pending PRs on our repo.
No
No
=> [buildkite] Migrate buildkite pipeline from AWS to GCP

.buildkite/pipeline.yml
Buildkite pipeline is migrated from using AWS queues to GCP queues. It currently only has basic unit tests enabled in the pipeline. This PR enables other passing pipeline steps. Future work needs to be done to fix the remaining broken pipeline steps. 
Fixes #4274 
No
No
=> [buildkite] Enable passing pipeline tests in buildkite pipeline

src/integration/resources/docker/dockerexternal/etcd.go, src/integration/resources/docker/dockerexternal/etcdintegration/cluster.go, src/x/test/log.go
host.docker.internal doesn't work correctly for our etcd integration tests on Mac's, but localhost does. It used to be the case that host.docker.internal didn't resolve at all on Mac's--I encoded this fact into the health check logic for our docker container. Now it does resolve, so I've just switched to an explicit build constraint based version.
=> [integration-tests] Fix etcd use of host.docker.internal on mac

src/x/process/process_linux_test.go, src/x/process/process_notlinux.go
This test was consistently failing for me when run on linux, most likely not due to any issue with the code, but rather to some small change with the number of files opened by the process (kernel update? Who knows). 
Better I think to just use the reference implementation to establish a baseline, and then check that we capture the delta. Perfect? No. Good enough? Probably.
=> [x/process] Fix number of files calculation in test

src/metrics/matcher/config.go, src/metrics/rules/active_ruleset.go, src/metrics/rules/active_ruleset_test.go, src/metrics/rules/options.go, src/metrics/rules/ruleset.go, src/metrics/rules/ruleset_test.go
What this PR does / why we need it:
To add new reserved metric tags, we need to add the reserved tag to the initial metric id, and the rollup id otherwise the reserved tag will be lost during the R2 rollup process. Currently to do this, we would need to manually update the R2 rules to filter for the new reserved tag. However, this is a time consuming process because we need to update all R2 rules in the repo to ensure the reserved tag is added to all rollup ids.
To address this issue, in the matcher config, I added functionality to specify a list of "include tags" which are tags that if seen in the metric id, we should add to the rollup id. So if the metric id contains a reserved tag that needs to be added to the rollup id, the forward matching logic will add the reserved tag to the …
=> Add IncludeTags to R2 Rollup Options

.buildkite/pipeline.yml, src/aggregator/integration/integration_data.go, src/aggregator/integration/one_client_r2_preserve_original_test.go, src/dbnode/x/encoding/shallow_cloner_test.go, src/integration/resources/docker/dockerexternal/etcd.go, src/metrics/rules/active_ruleset_test.go, src/x/process/process_linux_test.go
This PR fixes failing lint test in buildkite pipeline.
Fixes #4274 
No
No
=> [buildkite] Fix lint test in buildkite pipeline

.buildkite/pipeline.yml, src/dbnode/integration/graphite_find_test.go
This PR fixes Integration (dbnode Recently read) %n and Integration (dbnode LRU) %n tests in buildkite pipeline.
TestGraphiteFindSequential is the only test causing these two tests to fail. I am skipping this test because a similar test TestGraphiteFindParallel is also skipped due to known issue running on CI. We need more investigation on these two tests, but am skipping the run of these tests to allow for rest of tests to be run.
Fixes #4274 
No
No
=> [buildkite] Fix integration dbnode lru and dbnode recently read tests in buildkite pipeline

.buildkite/pipeline.yml
FOSSA is EOL as of December 31, 2023. Removing FOSSA license scan from our pipeline.
Fixes #4274 
No
No
=> [buildkite] Remove deprecated fossa pipeline test

.buildkite/pipeline.yml
This test is failing because of issue with access tokens. However, it is a low priority test because it checks for broken links in the M3 documentation. Commenting this test out.
Fixes #4274 
No
No
=> [buildkite] Comment out Documentation Tests

.buildkite/image-release-pipeline.yml
Failing build which is caused by failing quay.io step: https://buildkite.com/uberopensource/m3-monorepo-ci-uber-oss/builds/404#019151d7-5dd3-4ea8-af49-05c3168d004f 
We need to make the build green, so temporarily commenting out the quay.io steps, until a solution is found.
Addresses #4289
=> Temporarily comment out quay.io buildkite steps

src/dbnode/integration/admin_session_fetch_bootstrap_blocks_metadata_test.go, src/dbnode/integration/options.go, src/dbnode/integration/setup.go, src/dbnode/storage/entry.go, src/dbnode/storage/shard.go, src/dbnode/storage/shard_fetch_blocks_metadata_test.go, src/dbnode/storage/shard_test.go
This PR fixes the logic to insert the entries in shard entry list to maintain the strictly increasing order of entry's unique index added to the list. This will fix the issue of skipping few series IDs while fetching the block metadata for peer bootstrapping. 
During peer bootstrapping the dbnode fetches the series metadata from peers via `FetchBlocksMetadataRawV2` call. The  pagination logic for this call is based on the assumption that entries are added in a strictly increasing order of entry's  unique index to the shard  list. While debugging the issue of data loss during peer bootstrapping it was found that some of the entries are not added in this order. This causes some of the series Ids to be skipped during peer bootstrapping which in turn …
=> [dbnode] Add extra entry field to fix the strictly increasing order of shard entry list for FetchBlocksMetadata pagination

src/metrics/rules/active_ruleset.go, src/x/serialize/unchecked_metric_tags_iterator.go
This reverts commit 1a881a097e5b324a1604633d7ccecbe8b653c361.
Fixes #
```release-note
```
```documentation-note
```
=> Revert "Close Iterator in Active Ruleset (#4299)"

src/metrics/matcher/config.go, src/metrics/metric/id/m3/id.go, src/metrics/metric/id/m3/id_bench_test.go, src/metrics/metric/id/m3/id_test.go
Currently, m3.IsRollupID either pulls an id.SortedTagIterator from a pool, or makes one itself. There's no reason to do this; we can just directly create an m3
specific iterator on the stack, which doesn't allocate.
N.B.: if there are any pathological use cases where m3.IsRollupID is used with a pool that returns something *other* than an m3.sortedTagIterator, this would change
behavior. That seems highly unlikely/undesirable though.
commit-id:a2e684ae
---
**Stack**:
- #4305
- #4304 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> Optimize m3.IsRollupID to not allocate

src/aggregator/client/config.go, src/aggregator/client/config_test.go, src/aggregator/client/conn.go, src/aggregator/client/conn_options.go, src/aggregator/client/conn_test.go
After support for TLS was introduced, the aggregator client not only sends data to the aggregator server but also receives data (during the TLS handshake). If, for some reason, the server is unable to respond to the client, the client will be stuck because it doesn't have a timeout for reading data. This PR adds support for read timeout.
=> [aggregator] Add read timeout for aggregator client

src/dbnode/integration/cluster_decommission_one_node_test.go, src/dbnode/storage/namespace.go, src/dbnode/storage/namespace_readers.go, src/dbnode/storage/namespace_readers_test.go
This PR fixes the logic of using shardSet variable in namespace Readers. This variable was created and update during assignShardSet call. We faced issues related to deadlock while decommissioning nodes where AssignShardSet and FetchBlockMetadataV2 interferred with each other. This diff removes deadlock by moving shardSet variable to tick as it used there and only needed in tick.
Fixes #
NONE
```release-note
```
NONE
```documentation-note
```
=> [dbnode] Moving shardSet value out of namespaceReaders and pass it as part of tick

src/aggregator/client/conn.go, src/aggregator/client/conn_test.go
`crypto/tls.Conn.Close()` takes 5 seconds to execute in cases where the connection is half-open, and the send queue (sendq) is full.
To avoid blocking while waiting for this timeout, this PR introduces an asynchronous closure workaround that allows flushing to continue without being delayed.
**References**:
Write deadline in `crypto/tls`: [[link](https://github.com/golang/go/blob/8fd0f83552d3ef9ca38c031bec93a36b189e3e11/src/crypto/tls/conn.go#L1361)]
GitHub issue for this problem: [[link](https://github.com/golang/go/issues/45162)]
Fixes #
```
NONE
```
``` …
```
=> [aggregator] Close Aggregator client connection asynchronously

src/msg/producer/writer/consumer_writer.go
Each MessageWriter within the m3msg Producer has multiple ConsumerWriters depending on the number of replicas configured. The MessageWriter writes a message to its internal queue and a goroutine reads from this queue and writes it serially to the consumerWriters. If any consumerWriter gets stuck then the whole message queue is blocked. This creates a huge backup of messages in the aggregator that instantiates said m3msg producer. 
This PR aims to unblock a stuck Write() within the ConsumerWriter.
Why does the Write() get stuck?
When the consuming service (via m3msg consumer) terminates, it issues a Close() on its listen socket. On seeing this the client as it stands today will first try and re-connect to the same consuming service only to be …
=> Fix m3msg producer Close operation

src/cluster/placement/algo/subclustered.go, src/cluster/placement/algo/subclustered_helper.go, src/cluster/placement/algo/subclustered_test.go, src/cluster/placement/placement_test.go
- The replace instance operation can be performed across multiple subclusters which is why we have added the constraint that the number of adding should be equal to leaving instances  while replacing.
- The adding instance are assigned the subcluster IDs same as the removing instances mapping the indexes one to one, i.e the removing instance at index 0 is mapped to adding instance at index 0.
- Added the code for reclaimLeavingShards which is same as that in sharded algo.
=> Added code to replace instances in subclustered placement

src/cluster/placement/algo/subclustered.go, src/cluster/placement/algo/subclustered_helper.go, src/cluster/placement/algo/subclustered_helper_test.go, src/cluster/placement/algo/subclustered_test.go, src/cluster/placement/placement_test.go
Added code to removeInstances from the subclustered placement.
- The method to removeInstance from the subcluster is same as what is present in sharded algorithm.
- During the removal of instance it is assumed that all the instances of the subclusters will be removed eventually, because the agnostic in the subclustered placement is to remove subcluster or add subcluster. 
- To make sure there is no target load assigned to the instance of the removing subcluster we do not include their weight while scanning current load and we skip these instances while building targetLoad.
- Keeping the assumption in mind while removing an instance the we calculate the shard count on the subclusters by excluding the subcluster of removing instance.
- This also give …
=> Added code to remove instances/subcluster from the placement

src/cluster/placement/algo/sharded_helper.go, src/cluster/placement/algo/subclustered.go, src/cluster/placement/algo/subclustered_helper.go, src/cluster/placement/algo/subclustered_helper_test.go, src/cluster/placement/algo/subclustered_test.go, src/cluster/placement/placement.go, src/cluster/placement/placement_test.go
In this PR we create an initialPlacementHelper method which, 
- first assigns the subcluster ids to the instances
- then create an empty initial placement and passes it to the newSubclusterHelper method where further calculations and validations gets executed.
The method to assign subcluster ids to the instances follows these steps:
- Checks if `instancesPerSubcluster` parameter is set correctly.
- Checks for the current placement and if the placement is not nil and find out all the subcluster that has instances < `instancesPerSUbcluster` and the instance count.
-  Sorts incomplete subcluster by ids in increasing order.
- First we fill all the incomplete subclusters and then we assign the subcluster ID of new subcluster.
- If the current placement …
=> Added code for assigning subcluster Ids and adding validations in initial placement

src/cluster/placement/algo/sharded_helper.go, src/cluster/placement/algo/subclustered.go, src/cluster/placement/algo/subclustered_helper.go, src/cluster/placement/algo/subclustered_helper_test.go, src/cluster/placement/algo/subclustered_test.go, src/cluster/placement/placement.go, src/cluster/placement/placement_test.go
This PR adds the initial validations while creating the subcluster helper and scan the current load on the instances  which means the current number of shards assigned to the instances.
The following validations have been added:
- validateInstanceWeight - validates that each instance in the subcluster has the same weight. This ensures that each instance in the subcluster has same number of shards assigned.
- validateSubclusterDistribution -
- validates if the number of isolation groups are exactly equal to the number of replicas.
- the number of instances in a subclusters should never exceed `instancesPerSubcluster/replicaFactor`. For example: If  `instancesPerSubcluster` value is **6** and `replicaFator` is **3** each isolation group can have at …
=> Added method to validate the weights of instances and scan current load

src/msg/producer/types.go, src/msg/producer/writer/consumer_service_writer.go, src/msg/producer/writer/consumer_service_writer_test.go, src/msg/producer/writer/writer_test.go
**Before:**
- fmt.Sprintf() called on every outgoing metric message (potentially 100K per second)
- Each call created new temporary string allocations
- Massive GC pressure and heap churn
- RLock semantics adding unnecessary CPU overhead.
**After:**
- Key computed once when FilterFuncMetadata is created
- Hot path just returns the cached string (no allocations)
- Dramatically reduced GC pressure (30-50% reduction expected)
- Lower CPU usage and better P99 latency under heavy load
- The fix eliminates the string allocation hot spot while maintaining the same functionality. Since there are only few possible unique key combinations, pre-computing them is trivial but provides massive performance benefits under heavy load.
- Replaced RLock with sync.Map …
=> M3Aggregator fix memory allocation issue in ConsumerServiceWriterMetrics
