- .travis.yml
- Makefile
> Add travis continuous integration

- interfaces/m3db/block.go
- storage/block.go
> Add RemoveBlockAt() to the DatabaseSeriesBlocks interface

- client/session.go
- client/session_test.go
> Open host queue when setting topology map

- client/host_queue.go
> Avoid deadlock scenario from host queue when drain queue checks state

- mocks/buffer.go
- mocks/shard.go
- services/m3dbnode/server/serve.go
- storage/bootstrap.go
- storage/buffer.go
- storage/buffer_test.go
- storage/database.go
- storage/database_test.go
- storage/series.go
- storage/series_test.go
- storage/shard.go
Also refactored bootstrapping logic into a separate `bootstrapManager` interface.
> Force the buffer to be flushed during bootstrapping

- client/errors.go
- client/host_queue.go
- client/host_queue_test.go
- client/session.go
- client/session_fetch_test.go
- network/server/tchannelthrift/cluster/service.go
- network/server/tchannelthrift/node/service.go
- network/server/tchannelthrift/thrift/gen-go/rpc/rpc.go
- network/server/tchannelthrift/thrift/gen-go/rpc/tchan-rpc.go
- network/server/tchannelthrift/thrift/rpc.thrift
- x/errors/errors.go
> Add ability to tell type of errors returned by client

- bootstrap/bootstrapper/noop.go
- client/errors.go
- mocks/shard.go
- storage/bootstrap.go
- storage/shard.go
> Move the creation of the bootstrap process inside the bootstrap manager

- network/server/tchannelthrift/cluster/service.go
- x/logging/config_test.go
- x/logging/logger.go
> Add cluster fetch method

- client/session.go
> Fix series iterator potentially being passed a non-nil m3db.Iterator with a nil data reference

- client/session.go
- encoding/series_iterator.go
> Only pass successful replica iterators to series iterator

- services/m3dbnode/server/serve.go
- storage/bootstrap.go
- storage/bootstrap_test.go
- storage/series.go
- storage/series_test.go
- storage/shard.go
- storage/shard_test.go
- x/errors/errors.go
- x/errors/errors_test.go
> Handle bootstrap errors more gracefully

- storage/database.go
- storage/database_test.go
> Fix recursive read lock

- persist/fs/commitlog/commit_log_test.go
> Fix data race in commit log tests

- client/connection_pool_test.go
> Fix client test data races

- .ci/test-cover.sh
- storage/block_test.go
- storage/database.go
- storage/database_test.go
> Fix data races in storage

- client/session_test.go
- services/m3dbnode/server/serve.go
- sharding/scheme.go
- sharding/scheme_test.go
- sharding/types.go
- storage/database_test.go
take in a set of shards instead of a range
@xichen2020 @robskillington
> Add shard scheme constructor for non-contiguous shards

- network/server/tchannelthrift/node/service.go
> Add error to FetchBlocksMetadata results

- integration/disk_cleanup_test.go
- integration/disk_flush_test.go
- persist/fs/files.go
- persist/fs/files_test.go
- persist/fs/fs.go
- persist/fs/manager.go
- storage/block/block_mock.go
- storage/bootstrap.go
- storage/bootstrap_test.go
- storage/cleanup.go
- storage/cleanup_test.go
- storage/database.go
- storage/database_test.go
- storage/flush.go
- storage/flush_test.go
- storage/fs.go
- storage/fs_test.go
- storage/shard.go
- storage/storage_mock.go
- storage/types.go
> Cleanup logic to clean up expired data files and commit logs

- client/session.go
- client/session_bootstrap_blocks_test.go
> Fix the predictability of TestFetchBootstrapBlocksAllPeersSucceed

- persist/fs/commitlog/commit_log.go
> Emit metric for commit log write queue

- .gitmodules
- instrument/options.go
- instrument/types.go
- persist/fs/commitlog/commit_log.go
- persist/fs/commitlog/commit_log_test.go
- persist/fs/commitlog/iterator.go
Convert m3db over to use tally Scope instead of m3x
> xmetrics -> tally

- glide.lock
- glide.yaml
- network/server/httpjson/cluster/server.go
- network/server/httpjson/context.go
- network/server/httpjson/handlers.go
- network/server/httpjson/node/server.go
- network/server/httpjson/options.go
- network/server/tchannelthrift/cluster/server.go
- network/server/tchannelthrift/context.go
- network/server/tchannelthrift/node/service.go
- services/m3dbnode/server/serve.go
cc @xichen2020 @martin-mao @mmihic
> Move context creation and closing to tchannel server hooks

- glide.lock
- glide.yaml
- instrument/methods.go
- instrument/options.go
- instrument/types.go
- persist/fs/commitlog/commit_log.go
- persist/fs/commitlog/commit_log_test.go
- storage/database.go
- storage/namespace.go
Summary:
Adding some key metrics to the database component of m3db
Test Plan: run on one prod node
CC: @xichen2020 @robskillington
> Metrics for database, commit_log, bootstrapping, persistence

- .ci/test-integration.sh
- .travis.yml
- Makefile
- client/client_mock.go
- client/options.go
- client/session.go
- client/session_test.go
- client/types.go
- encoding/encoding_mock.go
- integration/data.go
- integration/disk_cleanup_test.go
- integration/disk_flush_test.go
- integration/fs_bootstrap_test.go
- integration/integration.go
- integration/options.go
- integration/peers_bootstrap_simple_test.go
- integration/roundtrip_test.go
- integration/setup.go
- integration/truncate_namespace_test.go
- persist/fs/commitlog/commit_log_mock.go
- storage/bootstrap/bootstrapper/base.go
- storage/bootstrap/bootstrapper/peers/source.go
- storage/bootstrap/process.go
- storage/storage_mock.go
cc @xichen2020 @cw9 @martin-mao
> Add peers bootstrapper integration tests

- topology/dynamic_test.go
cc @cw9 @xichen2020 @martin-mao
> Fix test data races in dynamic topology tests

- integration/data.go
- integration/integration.go
- integration/peers_bootstrap_high_concurrency_test.go
> Add peers boostrapper integration test for testing high concurrency

- client/connection_pool_test.go
- generated/thrift/rpc.thrift
- generated/thrift/rpc/rpc.go
- generated/thrift/rpc/rpc_mock.go
- generated/thrift/rpc/tchan-rpc.go
- network/server/tchannelthrift/node/service.go
cc @xichen2020 @martin-mao @cw9
> Respond with boolean bootstrapped field in node health check

- storage/database.go
cc @jra3 @xichen2020 @martin-mao
> Fix stats name for fetchBlocksMetadata

- client/host_queue.go
> Make host queue drain channel buffered to match size of op arrays pool

- storage/database_test.go
- storage/namespace.go
- storage/namespace_test.go
- storage/repair.go
- storage/repair/options.go
- storage/repair/types.go
- storage/repair_test.go
- storage/storage_mock.go
- storage/types.go
cc @robskillington @martin-mao @cw9
> Add jitter and throttle when comparing block metadata in the background

- pool/bytes.go
- storage/block/options.go
- storage/options.go
> Add instrumentation for bytes pool

- storage/bootstrap.go
- storage/bootstrap_test.go
- storage/namespace.go
- storage/namespace_test.go
- storage/series.go
- storage/series_test.go
- storage/shard.go
- storage/shard_test.go
- storage/storage_mock.go
- storage/types.go
> Remove cutover time

- storage/block/block.go
> Lock around context creation

- storage/series.go
- storage/series_test.go
> Optimize block draining when we don't need to merge

- retention/options.go
- storage/database.go
- storage/namespace.go
- storage/namespace_test.go
- storage/shard.go
- storage/shard_test.go
- storage/storage_mock.go
- storage/types.go
> Add inner splay to the tick and make default tick duration 2mins

- context/context.go
> Fix context closers array leak when pooling contexts

- client/session.go
> Return early on client with majority or one consistency on success criteria

- client/session.go
cc @martin-mao @xichen2020 @kobolog
> Return all errors instead of the first error from nodes for client returned errors

- services/m3dbnode/main/main.go
- storage/database.go
- storage/database_test.go
- storage/fs.go
- storage/fs_options.go
- storage/fs_test.go
- storage/options.go
- storage/repair.go
- storage/repair/options.go
- storage/types.go
> Add jitter for database file operations

- client/connection_pool.go
- client/connection_pool_test.go
cc @martin-mao @kobolog @xichen2020
> Add ability to perform a number of attempts on connection before discarding from connection pool

- client/options.go
- client/session.go
- context/context.go
- context/context_test.go
- context/types.go
- storage/block/block.go
- storage/block/block_test.go
- storage/bootstrap/bootstrapper/fs/source_test.go
- storage/bootstrap/bootstrapper/peers/source.go
- storage/namespace.go
- storage/namespace/options.go
- storage/namespace/types.go
- storage/namespace_test.go
- storage/repair/options.go
- storage/repair/types.go
- storage/series/buffer.go
- storage/series/series.go
- storage/series/series_test.go
- storage/shard.go
- storage/shard_test.go
> Add fixes for block metadata and block exchanges

- context/context.go
- context/context_test.go
- context/pool.go
- context/types.go
- storage/block/options.go
- storage/options.go
- storage/series/options.go
> Lazily create contexts and add pooling

- context/context.go
- context/context_test.go
> Allocate closers if needed even if dep is non nil

- client/session.go
> Do not prematurely return results to pool and synchronize incrementing success and setting results

- client/session.go
cc @xichen2020 @martin-mao @kobolog
> Add a more reliable abort mechanism for client session connect

- storage/series/buffer.go
- storage/series/buffer_test.go
cc @robskillington @martin-mao @kobolog
> Discard duplicate datapoints

- client/session.go
- client/session_bootstrap_blocks_test.go
cc @xichen2020 @martin-mao @kobolog
> Add instrumentation for fetch bootstrap blocks procedure

- storage/block/block.go
- storage/block/block_mock.go
- storage/block/block_test.go
- storage/block/types.go
- storage/series/series.go
- storage/series/series_test.go
cc @robskillington @martin-mao @kobolog
> Check if we need to seal blocks more efficiently

- storage/namespace.go
- storage/namespace_test.go
> Fix panic in out of bounds namespace shard lookup

- topology/map.go
- topology/types.go
> Expose HostShardSets from topology map

- storage/namespace.go
- storage/namespace_test.go
> Migrate invalid shard error to make it an invalid params error

- client/client_mock.go
- client/options.go
- client/session.go
- client/session_bootstrap_blocks_test.go
- client/types.go
- integration/peers_bootstrap_merge_peer_blocks_test.go
- storage/block/block.go
- storage/bootstrap/bootstrap_mock.go
- storage/bootstrap/result.go
- storage/bootstrap/types.go
- storage/storage_mock.go
> Merge blocks from peers with different or nil checksums during peer bootstrapping

- .ci/test-integration.sh
- Makefile
> Run integration tests with race detector

- client/options.go
- client/session.go
- client/types.go
- storage/bootstrap.go
cc @xichen2020 @martin-mao @cw9
> Bound the number of processors when adding results from fetching blocks

- client/client_mock.go
- encoding/encoding_mock.go
- persist/fs/commitlog/commit_log_mock.go
- storage/namespace.go
- storage/result.go
- storage/series/series.go
- storage/series/series_mock.go
- storage/series/series_test.go
- storage/series/types.go
- storage/shard.go
- storage/shard_test.go
- storage/storage_mock.go
- storage/types.go
cc @xichen2020 @martin-mao @cw9
> Add tick metrics to measure series and blocks

- client/client_mock.go
- client/connection_pool.go
- client/connection_pool_test.go
- client/options.go
- client/types.go
> Add options for health checking connections to determine if unhealthy before tearing down

- glide.lock
- glide.yaml
> Pull latest m3cluster version

- client/session.go
- encoding/series_iterators.go
> Fix minor memory leak in error edge cases for FetchAll

- client/fetch_batch.go
- client/op_array_pool.go
- client/session.go
- client/write_batch_element_array_pool.go
- encoding/iterator_array_pool.go
- encoding/multi_reader_iterator.go
- encoding/series_iterator.go
- network/server/tchannelthrift/pool.go
- persist/fs/commitlog/commit_log.go
- storage/block/block.go
- storage/block/result.go
- storage/repair.go
- storage/repair/metadata.go
- storage/series/buffer.go
- storage/shard.go
cc @kobolog @xichen2020 @martin-mao
> Fix array pooling leaks where element references are not removed

- pool/object.go
This PR fixes the broken ObjectPool refilling subroutine – previously, the `break` statement would not break out of the loop since it is used inside a `select` block.
> Fix ObjectPool refill termination condition

- client/fetch_batch.go
> Fix a race condition

- glide.lock
- glide.yaml
- topology/dynamic.go
- topology/dynamic_test.go
- topology/host.go
- topology/host_test.go
- topology/options.go
- topology/types.go
> Pick up service discovery interface change

- persist/fs/read.go
This PR fixes an issue where we leak and corrupt the memory obtained from the `NativeHeap` when reading `ts.ID`-s from disk – the `NativeHeap` tracks owned memory chunks using the data pointer and length, while during the read operation we used to shift the start of the slice essentially changing both the pointer and length, leaking the underlying storage and ultimately corrupting the `NativeHeap`.
> Fix slice truncation on ID reads

- client/rc.go
- client/session.go
- client/write.go
> Rename client writeState fields for better readability

- glide.lock
- glide.yaml
- topology/dynamic.go
- topology/host.go
pick up m3cluster interface change introduced in the shard state pr, feel free to close this and do glide update in your own diff @robskillington
> Pull m3cluster with updated service discovery interfaces

- persist/fs/commitlog/commit_log.go
- persist/fs/commitlog/commit_log_test.go
> Fix flapping commit log tests due to race flush detection

- storage/options.go
- storage/series/options.go
- ts/identifier.go
- ts/identifier_pool.go
- ts/identifier_test.go
- ts/types.go
This PR makes non-native pools and heaps the safe default unless configured otherwise.
> Make non-native pools and heaps the default

- integration/truncate_namespace_test.go
- storage/bootstrap.go
- storage/database.go
- storage/database_test.go
- storage/namespace.go
- storage/namespace_test.go
- storage/shard.go
- storage/shard_test.go
> Check IsBootstrapped per shard for data access

- client/session.go
> Fix temp context usage in peer streaming

- client/client_mock.go
- client/host_queue.go
- client/peer.go
- client/session.go
- client/session_bootstrap_blocks_test.go
- client/session_test.go
- client/types.go
- encoding/encoding_mock.go
- persist/fs/commitlog/commit_log_mock.go
- persist/fs/fs_mock.go
- storage/bootstrap/bootstrap_mock.go
- storage/series/series_mock.go
- storage/storage_mock.go
cc @cw9 @xichen2020 @martin-mao
> Use active host queues for peer operations in client sessions

- client/errors.go
- client/session.go
- client/write.go
- encoding/encoding_mock.go
- integration/cluster_add_one_node_test.go
- persist/fs/commitlog/commit_log_mock.go
- persist/fs/fs_mock.go
- retention/times.go
- storage/bootstrap/bootstrap_mock.go
- storage/cleanup.go
- storage/cleanup_test.go
- storage/cluster/database.go
- storage/database.go
- storage/flush.go
- storage/flush_test.go
- storage/fs.go
- storage/fs_test.go
- storage/namespace.go
- storage/namespace_test.go
- storage/series/series_mock.go
- storage/shard.go
- storage/shard_test.go
- storage/storage_mock.go
- storage/types.go
cc @xichen2020 @cw9 @martin-mao @kobolog @ben-lerner @prateek
> Move flush state into shards to allow for flushing shards new & modified

- glide.lock
- glide.yaml
- integration/fake_cluster_services.go
- topology/dynamic.go
- topology/dynamic_test.go
- topology/options.go
Pick up https://github.com/m3db/m3cluster/pull/45
@xichen2020 @robskillington
> Pick up config service client change

- client/client_mock.go
- client/session.go
- encoding/encoding_mock.go
- encoding/multi_reader_iterator.go
- encoding/ostream.go
- encoding/types.go
- integration/cluster_add_one_node_test.go
- integration/fs_bootstrap_test.go
- integration/integration.go
- integration/peers_bootstrap_high_concurrency_test.go
- integration/peers_bootstrap_merge_local_test.go
- integration/peers_bootstrap_merge_peer_blocks_test.go
- integration/peers_bootstrap_node_down_test.go
- integration/peers_bootstrap_select_best_test.go
- integration/peers_bootstrap_simple_test.go
- persist/fs/fs_mock.go
- storage/series/buffer.go
- storage/series/series.go
- storage/series/series_mock.go
- storage/series/series_test.go
cc @xichen2020 @cw9 @kobolog @prateek
> Avoid some races and nil panics for new block/encoder/iterator usage

- encoding/m3tsz/encoder.go
- storage/block/block.go
- ts/segment.go
- x/io/reader.go
> Return copied byte streams for x/io.SegmentReader to pool

- client/session.go
- client/session_bootstrap_blocks_test.go
> Add peer block success/error fetch metrics

- client/session_bootstrap_blocks_test.go
- encoding/encoding_mock.go
- encoding/m3tsz/encoder.go
- encoding/m3tsz/encoder_test.go
- encoding/null.go
- encoding/types.go
- storage/series/buffer.go
- storage/series/series_mock.go
- storage/series/series_test.go
- storage/storage_mock.go
- ts/segment.go
> Avoid discarding byte slices on drain and reset

- storage/series/series.go
> Reduce default series struct size before use

- network/server/tchannelthrift/node/service.go
- persist/fs/commitlog/commit_log.go
- storage/block/result.go
- storage/bootstrap/bootstrapper/commitlog/source.go
- storage/series/buffer.go
- storage/series/series.go
- storage/series/series_pool.go
- storage/shard.go
- ts/segment.go
This PR fixes some leaks around the codebase.
> Fix some leaks here and there

- client/session_bootstrap_blocks_test.go
- encoding/encoding_mock.go
- encoding/m3tsz/encoder.go
- encoding/m3tsz/encoder_test.go
- encoding/null.go
- encoding/types.go
- glide.lock
- glide.yaml
- persist/fs/read_test.go
- persist/fs/seek_test.go
- storage/block/options.go
- storage/series/buffer.go
- storage/series/series_mock.go
- storage/series/series_test.go
- storage/storage_mock.go
- tools/read_index_ids/main/main.go
> Avoid keeping reference to returned byte slice on close

- client/host_queue.go
- client/host_queue_test.go
- client/write.go
Add host IDs to host queue errors.
> Add host description to host queue errors

- storage/series/series.go
This PR intends to fix an issue where we end up having active Series with a nil ID.
> Use a special nilID for non-initialized Series.

- client/session.go
- client/session_bootstrap_blocks_test.go
- glide.lock
- glide.yaml
- tools/read_ids/main/main.go
> Up m3x version to pick up retrier interface change

- Makefile
> Revert "Fix travis builds by pinning glide to v0.12.3"

- Makefile
> Fix travis builds by pinning glide to v0.12.3 

- client/options.go
@robskillington @xichen2020 @prateek
> Change client connection consistency level to ANY

- glide.lock
- glide.yaml
This PR will pull the latest M3X with leak detection support.
> Pull in the latest M3X.

- storage/cluster/database.go
This PR reports shard states for m3db nodes so we have better visibility into shard movements / progress when cluster topology changes
> Report shard states from cluster database

- glide.lock
- glide.yaml
cc @robskillington @cw9 
Update m3x dependency and pin the versions of some packages
> Update m3x dependency

- Makefile
- client/session.go
- client/session_fetch_bulk_blocks_test.go
- glide.lock
- glide.yaml
cc @robskillington @prateek @ben-lerner
> Merge latest peer streaming fixes from dev into master

- Makefile
- tools/clone_fileset/README.md
- tools/clone_fileset/main/main.go
Wired up a tool to clone filesets using `fs.FileSetReader|FileSetWriter`. 
> Add `clone_fileset` tool

- encoding/m3tsz/encoder.go
- encoding/m3tsz/m3tsz.go
- encoding/m3tsz/roundtrip_test.go
Fixing case where m3tsz int optimization overflows with very large ints.
> Fixing m3tsz int overflow edge case

- integration/admin_session_fetch_blocks_test.go
- integration/client.go
- integration/cluster_add_one_node_test.go
- integration/data.go
- integration/disk_flush_test.go
- integration/fs_bootstrap_test.go
- integration/fs_data_expiry_bootstrap_test.go
- integration/generate/generate.go
- integration/generate/options.go
- integration/generate/types.go
- integration/generate/writer.go
- integration/integration.go
- integration/last_read_after_peer_bootstrap_test.go
- integration/peers_bootstrap_high_concurrency_test.go
- integration/peers_bootstrap_merge_local_test.go
- integration/peers_bootstrap_merge_peer_blocks_test.go
- integration/peers_bootstrap_node_down_test.go
- integration/peers_bootstrap_select_best_test.go
- integration/peers_bootstrap_simple_test.go
- integration/roundtrip_test.go
- integration/setup.go
- integration/truncate_namespace_test.go
- New `integration/generate` package to generate faked series data: in-memory and on-disk 
> Extract integration data generation routines into sub-package

- services/m3dbnode/config/bootstrap.go
- storage/bootstrap/config/config.go
Part of work to make `m3dbnode` buildable from GH.
> Add bootstrapper configuration 

- integration/commitlog_bootstrap_helpers.go
- integration/commitlog_bootstrap_test.go
- integration/generate/generate.go
- integration/generate/types.go
Continuation of the work from #317
> Add commit log integration test

- glide.lock
- glide.yaml
- persist/fs/commitlog/read_write_prop_test.go
- e2e prop test for commit log writer/iterator 
> Add prop tests for Commit Log

- .metalinter.json
- digest/reader.go
- encoding/istream_test.go
- encoding/options.go
- persist/encoding/msgpack/schema.go
- persist/fs/commitlog/commit_log.go
- persist/fs/commitlog/read_write_prop_test.go
- persist/fs/commitlog/reader.go
- persist/fs/read_test.go
- storage/database_test.go
- storage/namespace.go
- storage/shard.go
- topology/dynamic_test.go
- topology/types.go
PR before this: https://github.com/m3db/m3db/pull/328
> Add `metalinter: varcheck, structcheck, goconst, ineffassign` (2/n)

- .metalinter.json
- client/session.go
- encoding/m3tsz/iterator.go
- encoding/m3tsz/m3tsz.go
- integration/cluster_add_one_node_test.go
- persist/encoding/msgpack/decoder.go
- persist/fs/commitlog/commit_log.go
- persist/fs/commitlog/reader.go
- persist/fs/persist_manager.go
- runtime/types.go
- storage/block/block.go
- storage/bootstrap.go
- storage/cluster/cluster_test.go
- storage/cluster/database_test.go
- storage/shard.go
- tools/dtest/config/opts.go
- tools/dtest/harness/harness.go
- tools/dtest/util/types.go
- tools/read_index_ids/main/main.go
> Add `metalinter: misspell, unconvert` (3/n)

- client/client_mock.go
- encoding/encoding_mock.go
- glide.lock
- glide.yaml
- integration/fake/cluster_services.go
- persist/fs/commitlog/commit_log_mock.go
- persist/fs/fs_mock.go
- persist/persist_mock.go
- storage/block/block_mock.go
- storage/bootstrap/bootstrap_mock.go
- storage/series/buffer_mock.go
- storage/storage_mock.go
- tools/dtest/config/config.go
- tools/dtest/harness/harness.go
- topology/dynamic.go
- topology/topology_mock.go
- x/io/io_mock.go
@xichen2020 @robskillington @prateek
> Update m3cluster with more refactoring

- storage/series/series.go
- storage/series/series_mock.go
- storage/series/series_test.go
- storage/series/types.go
- storage/shard.go
- storage/shard_test.go
- Fixes race condition in async shard insert during bootstrap
> Fix race condition in Shard insert v bootstrap

- persist/fs/files_test.go
> Fix broken test

- client/config_test.go
- glide.lock
- glide.yaml
- services/m3dbnode/config/config_test.go
- services/m3dbnode/config/pooling.go
- services/m3dbnode/server/server.go
> Add ability to add a low and high watermark for each bytes pool bucket

- storage/bootstrap/bootstrapper/fs/source.go
I ended up not needing to touch this file in a separate P.R, but I already did all the work to extract a few helper methods so we might as well clean it up a little.
> Refactor Filesystem bootstrapper source

- client/config.go
- client/session.go
- storage/bootstrap/bootstrapper/peers/source.go
I'm just including some of the logs that I found most helpful while investigating the peer bootstrapping issues. They vary in severity from Debug to Info to Error
This also fixes the broken peer bootstrapping metrics
> Improve peer bootstrapping instrumentation

- storage/series/buffer.go
Opened an issue to add property tests to catch future bad ownership semantic changes, issue #418.
> Fix buffer ownership semantics freeing buffers twice

- integration/cluster_add_one_node_test.go
- services/m3dbnode/config/config.go
- services/m3dbnode/config/config_test.go
- services/m3dbnode/server/server.go
- topology/types.go
Couple comments/questions: 
1. Where should I put the `StaticConfiguration` struct- it's in the topology package for now?
2. Need to add some tests, but getting this error: `?   	github.com/m3db/m3db/services/m3dbnode/server	[no test files]`  - will look into this
3. I have an example config file for static topology, so wondering if I should put that somewhere specific
> Add support for static topology

- Makefile
- client/client_mock.go
- client/session.go
- client/types.go
- encoding/encoding_mock.go
- encoding/series_iterator.go
- encoding/types.go
- generated/thrift/rpc.thrift
- generated/thrift/rpc/rpc.go
- generated/thrift/rpc/rpc_mock.go
- generated/thrift/rpc/tchan-rpc.go
- glide.lock
- glide.yaml
- network/server/tchannelthrift/cluster/service.go
- network/server/tchannelthrift/node/service.go
- storage/index/types.go
Initial PR for the addition of Tagged methods in the `client` package:
- Describe required changes in the `thrift.rpc` IDL
- Corresponding interface changes for API methods, input/output objects.
> RPC/Interface changes for tagged client APIs

- client/host_queue.go
- client/host_queue_test.go
- client/options.go
- client/session.go
- client/session_write_test.go
- client/types.go
- client/write_op.go
- client/write_state.go
- client/write_test.go
> Refactor writeOp in `client`

- Makefile
- generated/thrift/rpc.thrift
- generated/thrift/rpc/GoUnusedProtection__.go
- generated/thrift/rpc/rpc-consts.go
- generated/thrift/rpc/rpc.go
- generated/thrift/rpc/rpc_mock.go
- generated/thrift/rpc/tchan-rpc.go
- network/server/tchannelthrift/node/service.go
> Add WriteTaggedBatch RPC types

- services/m3dbnode/main/main_test.go
> Migrate `config_test` from integration => services/main

- client/client_mock.go
- client/session.go
- client/types.go
> Include data in FetchTagged return type

- client/options.go
- client/session.go
- glide.lock
- glide.yaml
- services/m3dbnode/server/server.go
- storage/block/options.go
- storage/options.go
- storage/series/options.go
Reworked the context pool to take options so as to allow larger contexts to be pooled. 
> Import latest m3x

- Makefile
- tools/clone_fileset/README.md
- tools/clone_fileset/main/main.go
- tools/read_data_files/README.md
- tools/read_data_files/main/main.go
- tools/read_index_ids/README.md
- tools/read_index_ids/main/main.go
/cc @richardartoul @robskillington
> Add tool to read data files

- storage/bootstrap/bootstrapper/commitlog/source_prop_test.go
> Make commitlog prop test run faster

- services/m3dbnode/config/config_test.go
- services/m3dbnode/config/pooling.go
- services/m3dbnode/config/pooling_test.go
- services/m3dbnode/server/server.go
Task to investigate different values later: https://github.com/m3db/m3db/issues/500
> Set max finalizer pool capacity to 4

- glide.lock
- glide.yaml
- integration/fake/cluster_services.go
- services/m3dbnode/config/config_test.go
- services/m3dbnode/main/main_test.go
- storage/namespace/dynamic.go
- tools/dtest/config/config.go
- tools/dtest/harness/harness.go
- topology/dynamic.go
- topology/dynamic_test.go
- topology/options.go
- topology/topology_mock.go
- topology/types.go
> [WIP] Pull in m3cluster with interface changes

- glide.lock
- glide.yaml
- Pulls upstream fix https://github.com/m3db/m3x/pull/131
> Fix build age reporting

- generated-source-files.mk
- glide.lock
- glide.yaml
> Port to latest m3x genny targets

- glide.lock
- glide.yaml
- integration/index_large_cardinality_high_concurrency_test.go
- integration/options.go
- integration/setup.go
- storage/index.go
- storage/index/iterator.go
- storage/index/iterator_matcher.go
- storage/index/iterator_matcher_test.go
- storage/index/iterator_test.go
- storage/index/options.go
- storage/index_insert_queue.go
- storage/index_test.go
- storage/namespace/dynamic_test.go
- Use `InsertBatch()`
- Enable new async insert/fetch integration test
> Pull latest m3ninx changes

- client/host_queue.go
- client/host_queue_fetch_batch_test.go
- client/host_queue_fetch_tagged_test.go
- client/host_queue_write_batch_test.go
- client/host_queue_write_tagged_test.go
- client/session.go
- client/session_fetch_bulk_blocks_test.go
- client/session_fetch_metadata_test.go
- client/session_fetch_test.go
- client/session_test.go
- client/session_topology_test.go
- There are only cosmetic changes in this PR.
> Client hostQueue ctor refactor

- client/config_test.go
- glide.lock
- glide.yaml
- integration/index_large_cardinality_high_concurrency_test.go
- integration/write_tagged_quorum_test.go
- network/server/tchannelthrift/node/segments_arraypool_gen.go
- services/m3dbnode/config/config_test.go
- services/m3dbnode/main/main_index_test.go
- services/m3dbnode/main/main_test.go
- services/m3dbnode/server/server.go
- storage/index/iterator_matcher.go
- storage/index/iterator_test.go
- storage/index_test.go
- tools/dtest/config/config.go
+1 for the strict marshalling default, already catching shady shit.
> Pull latest m3x changes

- persist/fs/commitlog/read_write_prop_test.go
> Fix test flakiness

- glide.lock
- glide.yaml
- storage/errors/types.go
- storage/index_insert_queue_test.go
- storage/index_test.go
- storage/series/buffer.go
- storage/shard.go
- storage/shard_index_test.go
- storage/shard_ref_count_test.go
- storage/shard_test.go
Trying to simplify https://github.com/m3db/m3db/pull/563.
This only has cosmetic changes.
> Refactorings in storage/index

- storage/index_insert_queue.go
- storage/index_insert_queue_test.go
- storage/shard_insert_queue.go
- storage/shard_insert_queue_test.go
> Fix Shard/Index insert queue termination bug

- client/session.go
- client/session_write_tagged_test.go
> Fix a double free in client.WriteTagged

- glide.lock
- glide.yaml
- integration/index_multiple_node_high_concurrency_test.go
- network/server/tchannelthrift/convert/convert.go
- network/server/tchannelthrift/convert/convert_test.go
Update m3ninx to pull in support for negation queries and update corresponding conversion methods.
> [index] Update m3ninx to pull in support for negation queries

- DEVELOPER.md
- README.md
Wrote down some informal getting started suggestions.
> Getting Started Developer Notes

- generated-source-files.mk
- glide.lock
- glide.yaml
> Adopt new genny knobs

- persist/fs/persist_manager.go
- persist/fs/persist_manager_test.go
- persist/persist_mock.go
- persist/prepare_options_matcher.go
- persist/types.go
- storage/bootstrap/bootstrapper/peers/source.go
- storage/bootstrap/bootstrapper/peers/source_data_test.go
- storage/flush.go
- storage/flush_test.go
- storage/namespace.go
- storage/shard.go
- storage/shard_test.go
- storage/storage_mock.go
- storage/types.go
Only cosmetic changes in this PR
> Rename persist/Manager methods

- .gitignore
- .goreleaser.yml
- Makefile
- glide.lock
- glide.yaml
Add Make targets for releasing a snapshot
> [make] Add Makefile targets for creating a release

- src/dbnode/.metalinter.json
- src/dbnode/integration/index_block_flush_test.go
Cleaning up import order for a file and including @benraskin92's shiny new linter to catch this kinda thing in CI
> PR673 followups

- glide.lock
- glide.yaml
- src/cmd/services/m3dbnode/server/server.go
> Less noisy etcd logging

- src/dbnode/client/connection_pool_test.go
- src/dbnode/client/fetch_tagged_results_accumulator_merge_test.go
- src/dbnode/client/fetch_tagged_results_accumulator_misc_test.go
- src/dbnode/client/host_queue_test.go
- src/dbnode/client/session_fetch_bulk_blocks_test.go
- src/dbnode/client/session_fetch_high_concurrency_test.go
- src/dbnode/client/session_test.go
Addressing recent build flakiness in the package
> [m3db] Speedup src/dbnode/client/ tests

- src/coordinator/test/test_series_iterator.go
- src/coordinator/ts/m3db/generated/test_series_iterator.go
- src/coordinator/tsdb/remote/compressed_codecs_test.go
Move test series iterator generation outside of test
> Move test series iterator generation outside of test

- src/cmd/.excludemetalint
- src/cmd/.metalinter.json
- src/cmd/services/m3dbnode/config/bootstrap_test.go
- src/cmd/services/m3dbnode/config/config.go
- src/cmd/services/m3dbnode/main/main.go
- src/cmd/tools/dtest/harness/harness.go
- src/cmd/tools/read_index_files/main/main.go
* Add metalint configuration files
* Fix lint errors
> Make cmd `metalint-` and `test-ci-integration-`-able

- docs/m3db/architecture/engine.md
- docs/m3db/architecture/index.md
- docs/m3db/architecture/peer_streaming.md
- docs/m3db/architecture/sharding.md
Mostly grammar and formatting fixes.
> Small fixes in docs

- scripts/thriftgen.Dockerfile
- src/dbnode/generated/thrift/generate.sh
> Migrate thrift-gen to quay.io/m3db

- docs/how_to/kubernetes.md
This fixes the k8s storage urls in the docs.
> fix k8s storage urls

- glide.lock
- glide.yaml
> Revert "[m3ninx] Update Vellum"

- docs/introduction/components/components.md
fixed the relative path to the m3db and query engine documentation from the components overview
> documentation uri fix

- src/m3ninx/search/proptest/query_gen.go
> Fix regexp query proptest flake

- src/query/pools/query_pools.go
> Use a better pool size for coordinator writes

- scripts/m3dbnode_bootstrapped.sh
Seeing verbose health output all over the place. Adding more debug
signal in regular output instead.
> [scripts] bootstrapped: no set -x

- src/cmd/services/m3dbnode/config/bootstrap.go
- src/cmd/services/m3dbnode/main/main_index_test.go
- src/dbnode/client/types.go
- src/dbnode/integration/bootstrap_after_buffer_rotation_regression_test.go
- src/dbnode/integration/bootstrap_before_buffer_rotation_no_tick_regression_test.go
- src/dbnode/integration/bootstrap_helpers.go
- src/dbnode/integration/commitlog_bootstrap_merge_test.go
- src/dbnode/integration/fetch_tagged_quorum_test.go
- src/dbnode/integration/fs_bootstrap_index_test.go
- src/dbnode/integration/fs_bootstrap_multi_ns_test.go
- src/dbnode/integration/fs_bootstrap_tags_test.go
- src/dbnode/integration/fs_bootstrap_test.go
- src/dbnode/integration/fs_commitlog_mixed_mode_read_write_test.go
- src/dbnode/integration/fs_data_expiry_bootstrap_test.go
- src/dbnode/integration/integration.go
- src/dbnode/integration/peers_bootstrap_merge_local_test.go
- src/dbnode/integration/setup.go
- src/dbnode/integration/write_quorum_test.go
- src/dbnode/server/server.go
- src/dbnode/storage/bootstrap/bootstrap_mock.go
- src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
- src/dbnode/storage/bootstrap/bootstrapper/uninitialized/source.go
- src/dbnode/storage/bootstrap/process.go
- src/dbnode/storage/bootstrap/provider_options.go
- src/dbnode/storage/bootstrap/types.go
- src/dbnode/storage/cluster/database.go
- src/dbnode/storage/cluster/types.go
- src/dbnode/storage/namespace.go
- src/dbnode/topology/topology_mock.go
- src/dbnode/topology/types.go
> Use cluster topology map in bootstrap process instead of session topology map

- src/query/api/v1/handler/placement/get.go
- src/query/api/v1/handler/placement/get_test.go
This can be useful when debugging and replaying the placement history.
> [coordinator] allow placement GET specific version

- src/query/pools/query_pools.go
- src/query/server/server.go
So I can reuse the instrument options in server.Run()
> Refactor instrument options construction

- src/query/functions/temporal/aggregation.go
- src/query/functions/temporal/aggregation_test.go
- src/query/functions/temporal/base.go
- src/query/functions/temporal/holt_winters.go
- src/query/functions/temporal/holt_winters_test.go
- src/query/parser/promql/parse_test.go
- src/query/parser/promql/types.go
No need to review, still need to clean up and add tests
> Add Holt Winters func

- .excludemetalint
- src/dbnode/storage/shard_race_prop_test.go
Capture more information when we see failures for #1056
> Re-work TestShardTickWriteRace to capture flakes

- src/collector/api/v1/handler/json/report.go
- src/query/api/v1/handler/topic/common.go
Must have forgotten to rebase prior to last push. This should fix the build failures.
> [build] Fix master failures following last push

- glide.lock
- glide.yaml
- src/cmd/services/m3coordinator/downsample/downsampler_test.go
the r2 store in m3ctl is too heavy weighted and meant for UI use mainly
> Refactor downsampler test

- src/query/api/v1/handler/placement/delete.go
- src/query/api/v1/handler/placement/delete_test.go
Provides better feedback to clients making decisions based on delete
responses.
> [query] api/placement: 404 on deleting absent inst

- .buildkite/pipeline.yml
- .codecov.yml
- scripts/process-cover.sh
- src/x/serialize/decoder.go
- src/x/serialize/decoder_lifecycle_prop_test.go
- src/x/serialize/decoder_options.go
- src/x/serialize/decoder_pool_test.go
- src/x/serialize/decoder_test.go
- src/x/serialize/encoder.go
> Optimize serialize.TagDecoder internal pooling usage

- docs/troubleshooting/index.md
a few things I've hit or seen asked and answered
> add some problems to the troubleshooting section

- scripts/m3dbnode_bootstrapped.sh
> [scripts] bootstrapped: healthy if no namespaces

- m3db.io/index.html
Quick fix for https://github.com/m3db/m3/issues/1145
> Fix typo on main page (#1145)

- src/cmd/services/m3coordinator/downsample/downsampler.go
- src/cmd/services/m3coordinator/downsample/downsampler_test.go
- src/cmd/services/m3coordinator/downsample/options.go
- src/cmd/services/m3query/config/config.go
- src/query/server/server.go
This pr adds a configuration struct for downsampler.
> Add configuration for downsampler

- src/cluster/placement/algo/mirrored.go
- src/cluster/placement/algo/sharded_helper.go
- src/cluster/placement/placement.go
- src/cluster/placement/placement_mock.go
- src/cluster/placement/service/service.go
- src/cluster/placement/service/service_test.go
- src/cluster/placement/storage/storage.go
- src/cluster/placement/storage/storage_test.go
- src/cluster/placement/storage/watch_test.go
- src/cluster/placement/types.go
- src/cluster/services/services_test.go
- src/cmd/tools/dtest/harness/harness.go
- src/dbnode/integration/fake/cluster_services.go
- src/m3em/cluster/cluster.go
- src/m3em/cluster/cluster_test.go
- src/msg/integration/setup.go
- src/msg/producer/writer/consumer_service_writer_test.go
- src/msg/producer/writer/writer_test.go
- src/query/api/v1/handler/placement/add.go
- src/query/api/v1/handler/placement/add_test.go
- src/query/api/v1/handler/placement/delete.go
- src/query/api/v1/handler/placement/delete_all_test.go
- src/query/api/v1/handler/placement/delete_test.go
- src/query/api/v1/handler/placement/get.go
- src/query/api/v1/handler/placement/get_test.go
- src/query/api/v1/handler/placement/init_test.go
- src/query/api/v1/handler/placement/replace.go
- src/query/api/v1/handler/placement/replace_test.go
> [cluster] placement: propagate version in storage

- issue_template.md
Ultimately we'd like to automate some of this stuff via an endpoint in the services themselves, but would be good to have a template to start with.
> Create an M3 issue template

- glide.lock
- glide.yaml
- src/cmd/services/m3dbnode/config/config_test.go
Pulls in new file host ID implementation.
> [glide] bump m3x version

- src/query/api/v1/handler/prometheus/common.go
- src/query/api/v1/handler/prometheus/common_test.go
- src/query/api/v1/handler/prometheus/remote/match.go
- src/query/api/v1/httpd/handler.go
- src/query/errors/handler.go
- src/query/parser/promql/types.go
- src/query/storage/types.go
Adds an endpoint for matching results to match prometheus endpoint
> [query] Add endpoint for matching series

- src/query/api/v1/handler/prometheus/native/common.go
- src/query/api/v1/handler/prometheus/native/common_test.go
- src/query/api/v1/handler/prometheus/native/read_common.go
- src/query/api/v1/handler/prometheus/native/read_instantaneous.go
- src/query/api/v1/handler/prometheus/native/read_test.go
- src/query/api/v1/httpd/handler.go
Adds an instantaneous query endpoint to resolve https://github.com/m3db/m3/issues/1226
> [query] Add instantaneous query endpoint

- scripts/lockfile/lockfile.go
- src/x/lockfile/lockfile.go
- src/x/lockfile/lockfile_test.go
This is an initial lockfile implementation, as discussed in #641  
I decided to add a file `scripts/lockfile/lockfile.go` which is used for testing.
> Initial lockfile implementation

- src/query/util/execution/parallel_test.go
The previous version of this test contained a race condition where the select on <-ctx.Done() was hit before context cancellation, causing the request to go through.
```
if f.wait != nil {
<-f.wait
}
select {
case <-ctx.Done():
return ctx.Err()
default:
f.processed = true
return nil
}
```
Sequence of events in the happy path:
```
W = worker, C = coordinator thread
W Receive on f.wait
C ctx.Cancel()
W select ctx.Done(), default
W Receive ctx.Done()
```
Failing path:
```
W Receive on f.wait
W select ctx.Done, default
W Hit default (set processed = true, causing failure)
C ctx.Cancel()
```
Fix is to just unconditionally wait for the context to be cancelled, and assert that it was in fact cancelled (as opposed to some timeout or something).
Running tests with -test.count 1000 repros the race …
> Refix flaky test.

- Makefile
- src/x/panicmon/executor.go
- src/x/panicmon/executor_test.go
> Limit C.I unit test package concurrency and fix flaky test

- src/aggregator/aggregator/handler/config.go
- src/msg/producer/config/writer.go
Metric name change
Disable some retrier metrics for better performance
> [M3agg] metric changes

- src/aggregator/aggregator/handler/config.go
- src/aggregator/aggregator/handler/config_test.go
- src/aggregator/aggregator/handler/writer/protobuf.go
- src/aggregator/aggregator/handler/writer/protobuf_test.go
Allow we filter messages for particular consumer on the producer side to save cost in network roundtrip.
> [M3agg] Add storage policy based filter

- .buildkite/pipeline.yml
There's an issue with the report upload and it's blocking all CI.
> [ci] temp: disable FOSSA scans

- .buildkite/image-release-pipeline.yml
- .buildkite/scripts/check_do_docker.sh
- docker/README.md
- docker/build.sh
- docker/images.json
It turns out you can't log into the same Docker repo with multiple
users. This splits up the builds into 2 steps so that we can have a
separate user per step.
> [buildkite] fix docker build

- kube/sysctl-daemonset.yaml
Include latest changes for `fs.nr_open`.
> [kube] update sysctl daemonset

- src/metrics/matcher/namespaces.go
Start the watches in background goroutines so that if the store is unavailable they timeout (approximately) in unison. This prevents the timeouts from stacking on top of each other when the store is unavailable and causing a delay of timeout_duration * num_rules.
> Start rule watches asynchronously

- .buildkite/docs-docker-compose.yml
Fixes a reference to the docs dockerfile that was recently moved.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [ci] fix docs dockerfile location

- src/dbnode/server/server.go
The MultiReaderIteratorPool doesn't get set in `server.go`, causing references to it use a separate, default pool instead, causing bugs.
```release-note
NONE
```
```documentation-note
NONE
```
> Set MultiReaderIteratorPool in block opts

- docs/operational_guide/replication_and_deployment_in_zones.md
- src/x/docs/docs.go
- src/x/docs/docs_test.go
This PR adds documentation on why running clusters with RF=1 or RF=2 is a bad idea, as this has been a source of confusion. Additionally this explains our reasoning for disallowing such clusters in the future.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [docs] add warnings about RF=1 and RF=2

- .buildkite/docs-build-pipeline.yml
**What this PR does / why we need it**: Updates CI pipeline to not make docs failures block future steps
Fixes #
**Does this PR introduce a user-facing and/or backwards incompatible change?**: No
```release-note
NONE
```
```documentation-note
NONE
```
> [ci] make docs build "soft fail" the build

- .buildkite/pipeline.yml
This reverts commit b3cf54e4656b095f0a05139b85c40c7a521a65cb.
Re-enable FOSSA for CI.
```release-note
NONE
```
```documentation-note
NONE
```
> Re-enable FOSSA

- src/cmd/services/m3aggregator/main/main.go
- src/cmd/services/m3coordinator/main/main.go
- src/cmd/services/m3ctl/main/main.go
- src/cmd/services/m3dbnode/main/main.go
- src/cmd/services/m3query/main/main.go
- src/dbnode/server/server.go
- src/x/etcd/globals.go
This centralizes the global etcd package related configuration we do to `src/x/etcd` and since globals should only ever be set once per process, each service calls into this package at service main initialization.
```release-note
NONE
```
```documentation-note
NONE
```
> Set etcd related globals in each service main initialization

- src/ctl/ui/yarn.lock
**What this PR does / why we need it**: Updates yarn deps to remove versions of packages with vulnerabilities.
Fixes #
**Does this PR introduce a user-facing and/or backwards incompatible change?**: No
```release-note
NONE
```
**Does this PR require updating code package or user-facing documentation?**: No
```documentation-note
NONE
```
> [m3ctl] ui: update yarn deps

- src/dbnode/encoding/proto/parse_schema.go
Improves readability of error message
> Fix error message

- README.md
- docs/how_to/single_node.md
This PR clarifies the need to include `__name__` as a tag if you want to query using PromQL.
Fixes #
```release-note
```
```documentation-note
This is a documentation update. 
```
> [docs] Clarify Prom querying in single_node docs

- src/dbnode/persist/fs/write.go
- src/dbnode/persist/fs/writer_benchmark_test.go
Adds a benchmark for measuring the performance of creating many empty filesets
> Add benchmark for creating empty filesets

- .buildkite/scripts/docs_push.sh
This prevents us from adding new operator docs pages.
**What this PR does / why we need it**: Fixes docs generation for new operator pages
Fixes #
**Does this PR introduce a user-facing and/or backwards incompatible change?**: No
```release-note
NONE
```
**Does this PR require updating code package or user-facing documentation?**: No
```documentation-note
NONE
```
> [docs] don't clean docs output dir

- CHANGELOG.md
Add changelog for 0.9.2
```release-note
NONE
```
```documentation-note
NONE
```
> Add changelog for 0.9.2

- CHANGELOG.md
Add changelog for 0.9.3 release
```release-note
NONE
```
```documentation-note
NONE
```
> Add changelog for 0.9.3

- CHANGELOG.md
Changelog 0.9.4
```release-note
NONE
```
```documentation-note
NONE
```
> Add changelog for 0.9.4

- .github/pull_request_template.md
Update template PR doc to include draft PR link. 
```release-note
NONE
```
```documentation-note
NONE
```
> [docs] Add draft PR instructions to PR template doc

- CHANGELOG.md
Add changelog for 0.9.5 release
```release-note
NONE
```
```documentation-note
NONE
```
> Add 0.9.5 changelog

- .buildkite/pipeline.yml
- Makefile
- docker-compose.yml
- docker/m3aggregator/Dockerfile
- docker/m3collector/Dockerfile
- docker/m3coordinator/Dockerfile
- docker/m3dbnode/Dockerfile
- docker/m3nsch/Dockerfile
- docker/m3query/Dockerfile
- scripts/thriftgen.Dockerfile
- src/query/util/logging/log_test.go
We need to cut a patch release within the 0.9.x series to fix a Docker
issue. I'd rather release a patch release with the fix rather than have
folks have to pull in a new runtime to get the docker fix.
This reverts commit c753f134bac682f5ac1be3e43f762132028ed15f.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> Revert "[ci] build + release m3db with go1.12 (#1505)"

- src/ctl/ui/package.json
- src/ctl/ui/yarn.lock
Mitigating recent vulnerabilities in axios and fstream.
**What this PR does / why we need it**: Updates m3ctl UI deps to mitigate recent vulnerabilities.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [m3ctl] update yarn deps

- src/query/api/v1/handler/prometheus/native/read.go
- src/query/api/v1/handler/prometheus/native/read_common.go
- src/query/api/v1/handler/prometheus/native/read_instantaneous.go
- src/query/api/v1/handler/prometheus/native/read_test.go
- src/query/api/v1/handler/prometheus/remote/read.go
- src/query/api/v1/handler/prometheus/remote/read_test.go
- src/query/api/v1/handler/prometheus/validator/handler.go
- src/query/api/v1/handler/prometheus/validator/handler_test.go
- src/query/api/v1/httpd/handler.go
- src/query/api/v1/httpd/handler_test.go
- src/query/executor/engine.go
- src/query/executor/engine_test.go
- src/query/executor/options.go
- src/query/executor/request.go
- src/query/executor/types.go
- src/query/server/server.go
This PR turns the engine in `query/executor` into an interface. This will allow us to better test queries as we can easily mock out the engine.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Make executor engine an interface

- src/query/api/v1/handler/namespace/schema_test.go
Cleanup lint issue in `schema_test.go`
```release-note
NONE
```
```documentation-note
NONE
```
> Fix lint issue in schema_test.go

- src/dbnode/storage/shard_ref_count_test.go
> Fix test that would fail based on time of day

- .buildkite/pipeline.yml
- src/dbnode/storage/block/lease.go
- src/dbnode/storage/block/types.go
Very basic implementation, probably requires some tests.
```release-note
NONE
```
```documentation-note
NONE
```
> Add block leaser for synchronously notifying seeker manager of block volume updates

- scripts/docker-integration-tests/simple/test.sh
- src/cmd/services/m3dbnode/main/main.go
- src/dbnode/server/server.go
- src/dbnode/storage/series/buffer.go
- src/dbnode/storage/series/buffer_mock.go
- src/dbnode/storage/series/buffer_test.go
- src/dbnode/storage/series/series.go
- src/query/api/v1/handler/prometheus/remote/write.go
- src/query/api/v1/handler/prometheus/remote/write_test.go
- src/query/api/v1/httpd/handler.go
- src/query/benchmark/common/parse_json.go
- src/query/server/server.go
- src/query/storage/converter.go
- src/query/tsdb/remote/codecs.go
- src/x/os/interrupt.go
This gives exact details of how far in the past/future timestamps are as well as a histogram metric to help monitor how old data coming in is.
```release-note
NONE
```
```documentation-note
NONE
```
> [coordinator] Add "ingest_latency" histogram metric and return datapoint too old/new errors with offending timestamps

- CHANGELOG.md
Add changelog
```release-note
NONE
```
```documentation-note
NONE
```
> Add 0.10.1 changelog

- src/dbnode/storage/database.go
- src/dbnode/storage/database_test.go
- src/dbnode/storage/namespace.go
dup of #1703 as the merge is kind of messed up, so start a new branch.
> add test case for not setting schema history to empty

- CHANGELOG.md
Changelog for 0.10.2.
```release-note
NONE
```
```documentation-note
NONE
```
> Add changelog for 0.10.2

- Makefile
- src/ctl/ui/package.json
- src/ctl/ui/yarn.lock
**What this PR does / why we need it**: Fixes some dependency issues for internal builds
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [m3ctl] ui: build with yarn

- DEVELOPER.md
There are no instructions how to setup a local development environment. Those basic steps are somewhat copied in part from [Kubernetes' Github workflow](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md) which should be enough to get people started with hacking on the project.
None.
```release-note
NONE
```
```documentation-note
Updates developer documentation in DEVELOPER.md
```
> [documentation] Include instructions for setting up a local dev environment

- docker/m3aggregator/Dockerfile
- docker/m3collector/Dockerfile
- docker/m3coordinator/Dockerfile
- docker/m3dbnode/Dockerfile
- docker/m3nsch/Dockerfile
- docker/m3query/Dockerfile
- scripts/thriftgen.Dockerfile
We have to use an older version of alpine, as git 2.22 removes the '-x'
flag to a submodule command which in turn breaks glide, the old AF
dependency tool we have. Until we migrate to a new version of glide or
go modules, we need to use this older base image.
Ref https://github.com/m3db/m3/issues/628
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [docker] builder image base alpine 3.9

- Makefile
- scripts/install_nvm.sh
- We can't make assumptions about the version of `node` a user may have
installed. If we don't find `nvm`, install it locally.
- `retool` needs its base dir set if the nearest git dir isn't the
project parent.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [ci] install nvm locally; retool base dir

- mkdocs.yml
This fixes #1773
```release-note
None
```
```documentation-note
None
```
> [docs] Fix broken link to operational guide

- src/dbnode/storage/id_list_gen.go
- src/x/generics/list/list.go
- src/x/generics/list/list_test.go
Fixes the `Reset` function for generic list.
```release-note
NONE
```
```documentation-note
NONE
```
> Fix generic list Reset

- src/query/api/v1/handler/prometheus/remote/read.go
- src/query/executor/engine.go
Allows batched remote-read endpoint
```release-note
none
```
```documentation-note
none
```
> [query] Add multi-query remote read

- src/query/README.md
Fixes m3coordinator docker build command to reflect current file structure.
```release-note
NONE
```
```documentation-note
NONE
```
> Update docker build command for m3c

- scripts/development/m3_stack/start_m3.sh
- src/dbnode/storage/index.go
- src/dbnode/storage/index/block.go
- src/dbnode/storage/index/block_prop_test.go
- src/dbnode/storage/index/block_test.go
- src/dbnode/storage/index/index_mock.go
- src/dbnode/storage/index/types.go
- src/dbnode/storage/index_block_test.go
- src/dbnode/storage/index_query_concurrent_test.go
- src/dbnode/tracepoint/tracepoint.go
This PR introduces tracing through the m3db index. 
```release-note
This PR introduces tracing through the m3db index. 
```
```documentation-note
NONE
```
> [m3db] Add m3db index tracing

- docs/integrations/prometheus.md
tagOptions and idScheme keys are missing from the example configuration based on m3coordinator-cluster-template.yml.
Updating the prometheus.md, adding the missing part of the configuration. 
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Update prometheus.md

- src/dbnode/integration/commitlog_bootstrap_index_test.go
- src/dbnode/integration/fetch_tagged_quorum_test.go
- src/dbnode/integration/fs_bootstrap_index_test.go
- src/dbnode/integration/fs_commitlog_mixed_mode_read_write_test.go
- src/dbnode/integration/index_block_flush_test.go
- src/dbnode/integration/index_block_rotation_test.go
- src/dbnode/integration/index_helpers.go
- src/dbnode/integration/index_multiple_block_query_test.go
- src/dbnode/integration/peers_bootstrap_index_aggregate_test.go
- src/dbnode/integration/peers_bootstrap_index_test.go
- src/dbnode/integration/write_tagged_quorum_test.go
Fixes lint issues in the integration package
```release-note
NONE
```
```documentation-note
NONE
```
> Fix integration lint issues

- docs/overview/media.md
Adding links to recent talks and reordering the media list.
> Add Monitorama and OPS talks and reorder media list

- m3db.io/index.html
Link to `docs.m3db.io` instead of generic GitHub pages on website. Old links are still accessible.
```release-note
NONE
```
```documentation-note
NONE
```
> Use custom domain for docs on website

- src/dbnode/storage/shard.go
- src/dbnode/storage/shard_test.go
This fixes bootstrapping when there are multiple filesets for the same block.
**Special notes for your reviewer**: this is extracting the bug fix from https://github.com/m3db/m3/pull/1790
```release-note
NONE
```
```documentation-note
NONE
```
> Fix bootstrapping with multiple filesets for the same block

- src/dbnode/storage/series/buffer.go
- src/dbnode/storage/series/truncate_type.go
- src/dbnode/storage/series/types.go
This enables visibility on how many cold writes are coming into M3DB.
```release-note
NONE
```
```documentation-note
NONE
```
> Add counter for cold writes

- src/dbnode/storage/shard.go
Check for UpdateOpenLeases error
```release-note
N/A
```
```documentation-note
N/A
```
> Check UpdateOpenLeases error

- scripts/vagrant/Vagrantfile
- scripts/vagrant/provision/manifests/m3db-single.yaml
- scripts/vagrant/provision/manifests/promremotebench-zero.yaml
- scripts/vagrant/provision/run_tunnels.sh
- scripts/vagrant/start_vagrant.sh
- scripts/vagrant/tunnel_vagrant.sh
- src/dbnode/storage/index.go
- src/dbnode/storage/index/results.go
- src/dbnode/storage/index/types.go
- src/dbnode/storage/index_block_test.go
- src/dbnode/storage/index_queue_forward_write_test.go
- src/dbnode/storage/index_queue_test.go
- src/dbnode/storage/index_shard_filter_id_test.go
- src/dbnode/storage/index_test.go
- src/dbnode/storage/namespace.go
- src/dbnode/storage/shard_ref_count_test.go
- src/dbnode/storage/storage_mock.go
- src/dbnode/storage/types.go
This fixes queries to local nodes that returns results from the index that the node owns and then tries to serve the data directly from the node, resulting in "not responsible for shard" errors.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Index queries to local node should return only IDs owned by node

- docs/m3db/architecture/engine.md
Fixes #1799.
```release-note
NONE
```
```documentation-note
NONE
```
> Update storage engine documentation

- docker/m3dbnode/Dockerfile-setcap
There's an incompatibility between our version of git and Glide. It's
easier to downgrade our alpine build image (and thus git version) rather
than upgrade glide, as we have to move off of glide anyway.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [docker] build setcap from alpine 3.9

- examples/dbnode/proto_client/README.md
- m3db.io/_redirects
- m3db.io/index.html
Use Github links while sorting out docs.m3db.io domain
```release-note
NONE
```
```documentation-note
NONE
```
> Use Github links for documentation

- docs/common/headers_optional_read_write.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Update ns specific docs

- src/dbnode/persist/fs/commitlog/commit_log_test.go
Removes a dependency used in a test that is not called out in `glide.yaml` explicitly.
```release-note
NONE
```
```documentation-note
NONE
```
> Remove facebookgo/clock dependency in tests

- docs/overview/media.md
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [talks] add OSCON video + slides

- .buildkite/pipeline.yml
- src/dbnode/storage/index/field_terms_iterator_prop_test.go
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> [ci] skip flaky test + fossa temporarily

- docs/how_to/single_node.md
Fixes single node doc instructions. 
```release-note
```
```documentation-note
```
> [docs] Fix single node docs

- scripts/docker-integration-tests/query_fanout/test.sh
Add determinism to query fanout tests to make sure it doesn't flake.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Fix integration fanout test flake by sorting for determinism

- docs/how_to/cluster_hard_way.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Remove port from endpoint in cluster docs

- docs/troubleshooting/index.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add commands for /debug/dump api

- docs/how_to/cluster_hard_way.md
```
Fixes a typo in the documentation.
```
```release-note
NONE
```
```documentation-note
Updated documentation example of how to create a placement.
```
> [docs] Fixed placement parameter

- docs/how_to/cluster_hard_way.md
- docs/operational_guide/namespace_configuration.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Fix namespace create docs

- scripts/docker-integration-tests/run.sh
add multi_cluster_write test to master integration script run.sh.
> invoke multi_cluster_write integration test

- src/cmd/services/m3dbnode/config/config_test.go
- src/dbnode/client/client_mock.go
- src/dbnode/client/config.go
- src/dbnode/client/config_test.go
- src/dbnode/client/options.go
- src/dbnode/client/replicated_session.go
- src/dbnode/client/replicated_session_test.go
- src/dbnode/client/types.go
* Make worker pool configurable
> [dbnode] make async write worker pool size configurable

- src/dbnode/persist/fs/seek_manager.go
- src/dbnode/persist/fs/types.go
Adds additional information around concepts of the storage engine, particular how seekers
work and what functionality they provide.
```release-note
NONE
```
```documentation-note
NONE
```
@richardartoul
> [dbnode] Add additional comments describing functionality around seekers

- CHANGELOG.md
This PR adds links to pull requests in the CHANGELOG.md file. This helps for faster and easier navigating and exploring the code.
I used regular expression find and replace:
Find: `#(\d+)`
Replace: `[#$1](https://github.com/m3db/m3/pull/$1)`
```release-note
NONE
```
```documentation-note
NONE
```
> Add links to pull requests in CHANGELOG.md

- README.md
This allows us more flexible scheduling for the invite as updates to the shared public google calendar can be reflected in others calendars.
```release-note
NONE
```
```documentation-note
NONE
```
> Update calendar invite on README.md

- src/cluster/client/etcd/config.go
- src/cluster/client/etcd/config_test.go
Make KeepAliveConfig public, so it's possible to build etcd cluster configuration outside of just unmarshalling YAMLs
```release-note
NONE
```
```documentation-note
NONE
```
> [kv] Expose KeepAliveConfig

- docs/operational_guide/availability_consistency_durability.md
- docs/operational_guide/bootstrapping_crash_recovery.md
- docs/operational_guide/namespace_configuration.md
- docs/operational_guide/placement_configuration.md
- docs/troubleshooting/index.md
- mkdocs.yml
Fixes #
```release-note
Added documentation on how to recover from cluster crashes
```
```documentation-note
Added documentation on how to recover from cluster crashes
```
> [docs] add a section on crash recovery

- src/ctl/ui/src/components/HelpTooltip.js
- src/ctl/ui/src/components/MappingRuleEditor.js
- src/ctl/ui/src/components/MappingRulesTable.js
- src/ctl/ui/src/components/RollupRuleEditor.js
- src/ctl/ui/src/components/RollupRulesTable.js
- src/ctl/ui/src/index.js
- src/ctl/ui/src/pages/Namespace.js
- src/ctl/ui/src/pages/Namespaces.js
Explicit import paths for javascript packages local to the repository. YARN can run into issues while building fresh packages due to the ambiguity of the import. 
Fixes #
```release-note
```
```documentation-note
```
> Explicit import paths for local js packages

- src/x/instrument/config.go
This allows callers to get the reporters, alongside the prometheus registry used if constructed.
```release-note
NONE
```
```documentation-note
NONE
```
> [instrument] Return exporters created if desired when creating root metrics scope

- src/dbnode/persist/fs/merger.go
This P.R optimizes the cold flush merging process to avoid calculating the checksum in the special (but common) case where a series data is simply being copied from an old file into a new file and not being merged with any new data from memory.
Fixes #
> [DBNode] - Avoid recalculating checksum during merge if not required.

- docs/common/headers_placement_namespace.md
- docs/operational_guide/namespace_configuration.md
- docs/operational_guide/placement_configuration.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add docs on namespace/placement headers

- glide.lock
Some one force pushed master and removed an old commit from the active repo tree (lovely). This will fix CI and all the other nonsense that's broken thanks to this.
```release-note
NONE
```
```documentation-note
NONE
```
> Fix CI, tests, etc due to go-toml removing a commit from their repo tree

- CHANGELOG.md
Changelog for 0.14.0 release.
```release-note
NONE
```
```documentation-note
NONE
```
> Add changelog for 0.14.0

- CHANGELOG.md
Update changelog for the 0.14.1 release.
```release-note
NONE
```
```documentation-note
NONE
```
> Update changelog 0.14.1

- src/dbnode/encoding/ostream.go
- src/x/checked/bytes.go
- src/x/checked/bytes_test.go
- src/x/checked/debug.go
- src/x/checked/debug_test.go
- src/x/checked/ref.go
- src/x/checked/ref_test.go
- src/x/checked/types.go
Fixes #
```release-note
```
```documentation-note
```
> Make bytesRef finalization called by RefCount Finalize call

- CHANGELOG.md
Fixes #
```release-note
```
```documentation-note
```
> Fix changelog missing item from 0.14.2 release notes

- Makefile
- docker/m3dbnode/development.Dockerfile
- docker/m3dbnode/development.Dockerfille
- scripts/vagrant/provision/manifests/promremotebench-zero.yaml
Adds a development docker file make job so that it's easy to push development docker images for pulling down in development environments.
```release-note
```
```documentation-note
```
> Add development docker build make job

- src/aggregator/aggregator/options.go
- src/cmd/services/m3coordinator/downsample/options.go
Change the default aggregator TTL, as 24h is too high for most users and
causes unnecessary memory usage. Also expose the config setting from the
coordinator downsampler so that users using coordinators for aggregation
may override.
Fixes #
```release-note
Reduce memory usage of default configured aggregators and coordinator downsamplers.
```
```documentation-note
```
> [aggregator] lower default entry TTL; set in coord

- mkdocs.yml
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add monitoring to docs tree

- docs/glossary/index.md
- mkdocs.yml
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add glossary

- README.md
- docs/index.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Replace Gitter links with M3DB Slack

- src/m3ninx/index/segment/builder/fields_map_new.go
- src/m3ninx/index/segment/builder/ids_map_new.go
- src/m3ninx/index/segment/builder/postings_map_new.go
- src/m3ninx/index/segment/mem/fields_map_new.go
Happy new year! This is a build fix for master--it updates the genny generated files to 2020. Ideally we'd have some mechanism to not have to do that, but it's also easy enough to just do, so I did.
> Fix the generated files

- glide.lock
- glide.yaml
Fixes #
```release-note
Update OpenTracing dependency to latest release
```
```documentation-note
```
> [deps] Bump OpenTracing 1.0.2 -> 1.1.0

- src/query/parser/promql/options.go
- src/query/parser/promql/parse.go
- src/query/parser/promql/parse_test.go
Adds custom call parsing functionaltity
> [query] custom call function capability

- docker/m3coordinator/development.Dockerfile
- docs/operational_guide/monitoring.md
- glide.lock
- glide.yaml
- src/cmd/services/m3dbnode/config/config_test.go
- src/query/api/v1/handler/prometheus/remote/write.go
- src/query/server/query.go
- src/x/opentracing/tracing.go
- src/x/opentracing/tracing_test.go
- Add LightStep as a supported OT backend.
- Update docs.
Fixes #
```release-note
Add support for LightStep as a tracing backend.
```
```documentation-note
```
> [tracing] LightStep OpenTracing support

- Makefile
Avoids spamming CI with irrelevant issue.
```release-note
NONE
```
```documentation-note
NONE
```
> Move Makefile comment to avoid printing in CI logs

- src/dbnode/storage/bootstrap/bootstrapper/fs/source.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/source_data_test.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/source_index_bench_test.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/source_index_test.go
- src/dbnode/storage/bootstrap/util.go
- src/x/test/reporter.go
This allows us to measure perf improvements to the index segment building by the FS bootstrapper using the following command:
```
TEST_TSDB_DIR=/tmp/m3db_data PROFILE_CPU=true go test -v -run none -bench Index
```
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Add filesystem index segment bootstrap benchmark test

- src/query/remote/client.go
- src/query/storage/m3/storage.go
- src/query/storage/prom_converter.go
- src/query/storage/prom_converter_test.go
Fixes #
```release-note
```
```documentation-note
```
> [query] Fix a bug that could cause duplicate Prometheus label sets

- kube/sysctl-daemonset.yaml
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Fixes #
```release-note
```
```documentation-note
```
> [kube] Update sysctl daemonset api path

- docs/m3db/index.md
Improves documentation.
```release-note
NONE
```
```documentation-note
NONE
```
> [m3db docs] Improve English

- docs/coordinator/api/remote.md
Fixes #
```release-note
```
```documentation-note
```
> (WIP Docs) Added tuning params to Prometheus remote write section 

- docs/operational_guide/mapping_rollup.md
- mkdocs.yml
Adds docs for mapping rules configuration.
```release-note
```
```documentation-note
```
> [docs] Add mapping rules config docs

- src/dbnode/persist/fs/index_write.go
- src/m3ninx/index/segment/fst/writer.go
- src/m3ninx/postings/roaring/roaring.go
- src/m3ninx/postings/types.go
Speeds up WritePostingsOffsets by at least 60% on test dataset of 600mb.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Improve speed for WritePostingsOffsets to speed up writing FST segments

- CHANGELOG.md
Add changelog for `0.15.0-rc.0` release candidate.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Add changelog for 0.15.0-rc.0 release candidate

- docs/operational_guide/upgrading_m3.md
- mkdocs.yml
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add upgrading m3 docs

- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/network/server/tchannelthrift/node/service_test.go
- src/dbnode/persist/fs/retriever_options.go
- src/dbnode/persist/fs/seek_manager_test.go
- src/dbnode/storage/database.go
- src/dbnode/storage/database_test.go
- src/dbnode/storage/namespace.go
- src/dbnode/tracepoint/tracepoint.go
Adds trace coverage to `m3dbnode` FetchTagged code path.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Add trace coverage to FetchTagged code path

- src/dbnode/server/server.go
The size and capacity were not being logged correctly since the defaults were being used.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Fix bytes pool init logs

- src/dbnode/storage/bootstrap.go
This gives us a metric on how long bootstraps take.
```release-note
N/A
```
```documentation-note
N/A
```
> [dbnode] Emit timer for bootstrap duration

- CHANGELOG.md
Fixes #
```release-note
```
```documentation-note
```
> [changelog] Add changelog for 0.15.0-rc.1

- src/query/server/query.go
- src/query/ts/m3db/encoded_block.go
- src/query/ts/m3db/encoded_block_test.go
- src/query/ts/m3db/encoded_series_iterator.go
- src/query/ts/m3db/encoded_series_iterator_test.go
- src/query/ts/m3db/options.go
- src/query/ts/m3db/types.go
Allows custom series batching functions to help investigate experimental approaches.
> [query] Add ability for custom series batching

- src/dbnode/client/replicated_session.go
Adds metric to measure successful async replication writes.
> Async replication write success metric

- src/m3ninx/index/segment/builder/builder.go
- src/m3ninx/index/segment/builder/builder_test.go
- src/m3ninx/index/segment/builder/bytes_slice_iter.go
- src/m3ninx/index/segment/builder/multi_segments_builder.go
- src/m3ninx/index/segment/builder/multi_segments_field_postings_list_iter.go
- src/m3ninx/index/segment/builder/multi_segments_multi_key_postings_list_iter.go
- src/m3ninx/index/segment/builder/terms.go
- src/m3ninx/index/segment/builder/terms_test.go
- src/m3ninx/index/segment/fst/writer.go
- src/m3ninx/index/segment/mem/segment.go
- src/m3ninx/index/segment/mem/terms_dict.go
- src/m3ninx/index/segment/mem/types.go
- src/m3ninx/index/segment/mem/unique_fields_iterator.go
- src/m3ninx/index/segment/segment_mock.go
- src/m3ninx/index/segment/types.go
Build a per field postings list since per term postings lists are only valid per iteration of `Next()`. 
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Build a per field postings list

- CHANGELOG.md
Update changelog for 0.15.0-rc.2.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update changelog for 0.15.0-rc.2

- CHANGELOG.md
Update changelog for 0.15.0-rc.3.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update changelog for 0.15.0-rc.3

- src/dbnode/storage/bootstrap/bootstrapper/fs/source.go
- src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] bootstrap: Make verbose log debug lvl

- scripts/docker-integration-tests/coordinator_noop/docker-compose.yml
- scripts/docker-integration-tests/coordinator_noop/m3coordinator.yml
- scripts/docker-integration-tests/coordinator_noop/test.sh
- scripts/docker-integration-tests/run.sh
- src/cmd/services/m3query/config/config.go
- src/query/server/query.go
- src/query/storage/noop_storage.go
- Some use cases require the coordinator for serving m3admin APIs but
have no need to communicate with M3DB or serve query data.
- Currently need a live M3DB cluster in order to serve m3admin APIs.
- This PR adds a `noop-etcd` storage backend for serving m3admin APIs.
Example of querying:
```
$ curl -v "localhost:7201/api/v1/query_range?start=$(date '+%s')&end=$(date '+%s')&step=10&query=foo"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 7201 (#0)
> GET /api/v1/query_range?start=1585603982&end=1585603982&step=10&query=foo HTTP/1.1
> Host: localhost:7201
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Access-Control-Allow-Headers: accept, content-type, authorization
< Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
< …
```
> [query] Noop storage backend to serve admin APIs

- src/x/opentracing/tracing.go
Fixes #
```release-note
```
```documentation-note
```
> [opentracing] Fix typo in config error

- src/query/api/v1/handler/prometheus/handleroptions/headers.go
- src/query/api/v1/handler/prometheus/remote/write.go
Fixes #
```release-note
```
```documentation-note
```
> [coordinator] Forward all relevant M3 headers to forwarding targets

- docs/overview/roadmap.md
- mkdocs.yml
Not exhaustive by any means, just something to get started.
```release-note
NONE
```
```documentation-note
NONE
```
> Add first draft of roadmap

- src/cmd/services/m3aggregator/config/aggregator.go
- src/cmd/services/m3aggregator/main/main.go
Fixes #
```release-note
```
```documentation-note
```
> [aggregator] Allow static shutdown wait period

- src/cmd/tools/m3ctl/README.md
Fixes #
```release-note
```
```documentation-note
```
> Fix m3ctl README formatting

- src/aggregator/client/config.go
- src/aggregator/client/config_test.go
Make aggregator client batch write deadline configurable
```release-note
NONE
```
```documentation-note
NONE
```
> Wire up BatchFlushDeadline in aggregator client config

- CHANGELOG.md
Updating changelog.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update changelog for unreleased 0.15 ahead of RC.6

- src/dbnode/client/config.go
Ensure that `WriteTimestampOffset` is always set if configured.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Make sure writeoffset is always set.

- src/query/server/query.go
Propagate instrument options by channel when running query server.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Add instrument options ready channel to receive instrument opts

- src/cmd/services/m3coordinator/downsample/options.go
Allows for specific configuration of matching capacity.
```release-note
NONE
```
```documentation-note
NONE
```
> [coordinator] Allow configuring of matcher configuration

- src/dbnode/storage/bootstrap.go
- src/dbnode/storage/bootstrap/bootstrap_mock.go
- src/dbnode/storage/bootstrap/noop.go
- src/dbnode/storage/bootstrap/types.go
- src/dbnode/storage/bootstrap_hooks.go
- src/dbnode/storage/bootstrap_test.go
Change bootstrap hooks to hook iface to make them safer to use. 
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Change Bootstrap Hooks to Hook Iface

- src/query/api/v1/handler/prometheus/handleroptions/options.go
- src/query/api/v1/handler/prometheus/remote/write.go
Fixes #
```release-note
```
```documentation-note
```
> Add retry to write forwarding

- README.md
We are shutting down the Gitter channel so removed the link from the Read me.
Fixes #
```release-note
```
```documentation-note
```
> Removing link to Gitter

- src/dbnode/storage/cleanup.go
- src/dbnode/storage/cleanup_test.go
See title.
```release-note
NONE
```
```documentation-note
NONE
```
> Don't perform any cleanup while we are still bootstrapping.

- src/cluster/README.md
- src/collector/README.md
- src/m3em/README.md
- src/m3nsch/README.md
- src/metrics/README.md
- src/msg/README.md
- src/query/README.md
Remove references to archived repositories.
```release-note
```
```documentation-note
```
> [docs] Cleanup README files

- src/query/server/query.go
Allows custom storage transforms to be passed into query.
> [query] Allow custom storage transform

- src/query/api/v1/handler/prometheus/remote/write.go
We were not updating this latency previously
> [query] Fix metrics for  forwarding latency

- src/dbnode/storage/index/block.go
- src/dbnode/storage/index/block_bench_test.go
- src/dbnode/storage/index/block_test.go
- src/dbnode/storage/index/mutable_segments.go
Refactors mutable segments out of an index block.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Refactor index block into mutable segments and block

- README.md
Fixes #
```release-note
```
```documentation-note
```
> Add meetup group for community meetings to README.md

- src/dbnode/generated/thrift/rpc.thrift
- src/dbnode/generated/thrift/rpc/rpc.go
- src/dbnode/network/server/tchannelthrift/node/service.go
Adds optional metadata to health check RPCs
> [thrift] Add metadata to node health checks

- src/dbnode/client/config.go
- src/x/retry/retry.go
- src/x/retry/types.go
Prior to this change the coordinator only emitted write/read retry attempt counts and final-error counts if write or fetch retries were explicitly set in config.
This fixes that and turns it on by default, also adds an "calls" counter make it easier to write the metric query to work out final error rate vs calls made.
```release-note
NONE
```
```documentation-note
NONE
```
> [coordinator] Add write/read retry calls vs final-error metrics by default

- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/network/server/tchannelthrift/node/service_test.go
Hotfix for metadata setting, and test to verify.
> [thrift] Hotfix and test for service metadata.

- CHANGELOG.md
Update changelog for 0.15 release
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update changelog for 0.15 release

- CHANGELOG.md
Prepare for 0.15.1.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Prepare changelog for 0.15.1

- src/dbnode/client/fetch_state.go
- src/dbnode/client/fetch_tagged_results_accumulator.go
- src/dbnode/client/session.go
- src/dbnode/client/write_state.go
- src/dbnode/network/server/tchannelthrift/convert/convert.go
- src/dbnode/storage/index.go
- src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go
- src/query/api/v1/handler/prometheus/handleroptions/headers.go
This fixes propagation of require exhaustive option through RPC.
Followup: add integration test.
```release-note
NONE
```
```documentation-note
NONE
```
> [query/dbnode] Fix require exhaustive propagation of require exhaustive option through RPC

- README.md
Fixes #
```release-note
```
```documentation-note
```
> Adding Office Hours info to Readme

- docs/integrations/influxdb.md
- mkdocs.yml
This was missing previously.
```release-note
NONE
```
```documentation-note
NONE
```
> [docs] Add InfluxDB write endpoint to documentation

- .codecov.yml
This makes sure coverage tests do not fail if they reduce coverage by some very small amount.
```release-note
NONE
```
```documentation-note
NONE
```
> [build] Only fail codecov checks if drop in coverage of 5%

- CHANGELOG.md
Adds changelog for 0.15.5.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update for 0.15.5 release

- src/dbnode/storage/index.go
- src/dbnode/storage/index/block.go
- src/dbnode/storage/index/fields_terms_iterator.go
- src/dbnode/storage/index/types.go
- src/dbnode/storage/index_block_test.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Always use block aggregate query for aggregate queries and intersect term results with query postings list

- docs/m3db/architecture/storage.md
- go.mod
- src/dbnode/persist/fs/msgpack/decoder.go
- src/dbnode/persist/fs/msgpack/encoder.go
- src/dbnode/persist/fs/msgpack/encoder_test.go
- src/dbnode/persist/fs/msgpack/roundtrip_test.go
- src/dbnode/persist/fs/msgpack/schema.go
- src/dbnode/persist/fs/write.go
- src/dbnode/persist/schema/types.go
Fixes #2627
In preparation for checksumming index files at the entry level, add the
concept of minor version. Minor version can be used to introduce
non-breaking changes in a controlled fashion.
```release-note
NONE
```
```documentation-note
Yes, updated docs/m3db/architecture/storage.md in PR
```
> [dbnode] Add MinorVersion to Info file

- src/query/api/v1/handler/placement/set.go
All other error code paths have a log message except unmarshal. Adding this in.
```release-note
NONE
```
```documentation-note
NONE
```
> [coordinator] Add missing log message on placement set parse error

- src/dbnode/storage/index_test.go
- src/dbnode/storage/shard_test.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Index flush doc caching via DocRef tests

- src/dbnode/storage/database.go
- src/dbnode/storage/namespace.go
- src/dbnode/storage/shard.go
- src/dbnode/storage/types.go
Adds data writing back to disk for large tiles.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Write for large tiles aggregation

- src/m3ninx/index/segment/builder/builder.go
This protects against concurrent calls to field postings list iter (does not currently exist) as the method sorts and hence mutates state on the builder.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Protect field postings list iter with write vs read lock due to sort mutation

- src/cmd/tools/docs_test/main/main.go
The docs tests have been somewhat flakey due to rate limits, we fixed the GitHub link checking by self-rate limiting but it's clear that for some domains perhaps we'll want to just avoid checking.
In the future if this is still too flakey we can move to a whitelist approach where we just check internal links and GitHub links. Right now this still helps validates things like the M3 Slack URL being valid, etc which is useful.
```release-note
NONE
```
```documentation-note
NONE
```
> [docs_test] Exclude testing certain links for docs_test

- go.mod
- src/query/api/v1/handler/prom/prom_test.go
> [query] Set default Prometheus evaluation interval

- scripts/docker-integration-tests/aggregator/test.sh
- scripts/docker-integration-tests/coordinator_config_rules/test.sh
- scripts/docker-integration-tests/prometheus/test.sh
- scripts/docker-integration-tests/prometheus_replication/test.sh
- scripts/docker-integration-tests/simple_v2_batch_apis/test.sh
- src/dbnode/network/server/httpjson/cluster/server.go
- src/dbnode/network/server/httpjson/handlers.go
- src/dbnode/network/server/httpjson/handlers_test.go
- src/query/api/v1/handler/graphite/find_test.go
- src/query/api/v1/handler/graphite/render.go
- src/query/api/v1/handler/graphite/render_test.go
- src/query/api/v1/handler/placement/common_test.go
- src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go
- src/query/api/v1/handler/prometheus/handleroptions/fetch_options_test.go
- src/query/api/v1/handler/prometheus/handleroptions/header_test.go
- src/query/api/v1/handler/prometheus/handleroptions/headers.go
- src/query/api/v1/handler/prometheus/handleroptions/service_options.go
- src/query/api/v1/handler/prometheus/handleroptions/service_options_test.go
- src/query/api/v1/handler/prometheus/native/common.go
- src/query/api/v1/handler/prometheus/native/complete_tags_test.go
- src/query/api/v1/handler/prometheus/native/list_tags_test.go
- src/query/api/v1/handler/prometheus/native/read_instantaneous_test.go
- src/query/api/v1/handler/prometheus/native/read_test.go
- src/query/api/v1/handler/prometheus/remote/tag_values_test.go
- src/query/api/v1/handler/prometheus/remote/write.go
- src/query/api/v1/handler/prometheus/remote/write_test.go
- src/query/api/v1/handler/search_test.go
- src/query/api/v1/httpd/handler.go
- src/x/headers/headers.go
Fixes https://github.com/m3db/m3/issues/2473 by defaulting to treat unmarshal of unknown fields as bad request.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Strict JSON unmarshal (disallow unknown fields) for raw HTTP/JSON DB node APIs

- src/dbnode/integration/disk_flush_helpers.go
- src/dbnode/integration/disk_snapshot_test.go
- src/dbnode/integration/fs_commitlog_snapshot_mixed_mode_read_write_prop_test.go
- src/dbnode/persist/fs/files.go
- src/dbnode/persist/fs/files_test.go
- src/dbnode/storage/bootstrap.go
- src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
- src/dbnode/storage/bootstrap_test.go
- src/dbnode/storage/cleanup.go
- src/dbnode/storage/cleanup_test.go
- src/dbnode/storage/coldflush.go
- src/dbnode/storage/coldflush_test.go
- src/dbnode/storage/database.go
- src/dbnode/storage/flush.go
- src/dbnode/storage/flush_test.go
- src/dbnode/storage/fs.go
- src/dbnode/storage/fs_test.go
- src/dbnode/storage/mediator.go
- src/dbnode/storage/mediator_test.go
- src/dbnode/storage/series/buffer.go
- src/dbnode/storage/series/buffer_mock.go
- src/dbnode/storage/series/series.go
- src/dbnode/storage/series/series_mock.go
- src/dbnode/storage/series/types.go
- src/dbnode/storage/shard.go
- src/dbnode/storage/shard_test.go
- src/dbnode/storage/storage_mock.go
- src/dbnode/storage/types.go
Background TSDB cold flush process so it doesn't block data snapshotting/commit log rotation.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Background cold flush process

- README.md
Fixes #
```release-note
```
```documentation-note
```
> Adding link to M3 meetup recordings 

- CHANGELOG.md
Update changelog for 0.15.8.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update for 0.15.8

- docs/how_to/aggregator.md
This was a typo.
```release-note
NONE
```
```documentation-note
NONE
```
> [docs] Update aggregator with fix to terminology used when setting m3msg topic up

- README.md
Fixes #
```release-note
```
```documentation-note
```
> Update link to Twitter account

- mkdocs.yml
Update MKDocs extensions to include admonitions and remove critic markup, I intend to use admonitions extensively for "callouts".
> [DOCS] Update MKDocs extensions

- CHANGELOG.md
Update changelog for 0.15.9.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update for 0.15.9

- .buildkite/scripts/docs_push.sh
There seem to be a lot of places where we need to change build scripts for the docs, I think this is actually the final one.
> [DOCS] Fix buildkit doc script

- src/dbnode/storage/bootstrap/bootstrapper/readers.go
Reduces duplicate info file reading work.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Fix enqueue readers info file reading

- CHANGELOG.md
Update for 0.15.0
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update for 0.15.10

- docs/overview/media.md
Adding link to talk
```release-note
```
```documentation-note
```
> [media] - entry to CNCF Webinar 2020 talk

- docs/overview/media.md
Fixes #
```release-note
```
```documentation-note
```
> Nit edit - change July to August for meetup recording 

- docs/overview/media.md
- src/cmd/services/m3dbnode/config/config_test.go
- src/dbnode/client/config.go
Adds peer streaming options to config, this can be used to tweak speed of peer streaming.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Expose stream batch client options to config

- src/x/checked/bytes.go
- src/x/pool/object.go
Fixes #
```release-note
```
```documentation-note
```
> [large-tiles] Try detect double Finalize

- go.mod
- go.sum
Partly addresses #2540:
```
╰─$ go test -race -count 10 ./src/cluster/services/heartbeat/etcd                                                                                                            130 ↵
ok  	github.com/m3db/m3/src/cluster/services/heartbeat/etcd	130.453s
go test -race -count 10 ./src/cluster/services/heartbeat/etcd  57.80s user 9.00s system 50% cpu 2:12.24 total
```
```release-note
```
```documentation-note
```
> Update etcd/boltdb dependency to fix panic in tests on go 1.14

- docs/operational_guide/mapping_rollup.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add `group_by` labels caveat to the docs

- go.mod
- src/cmd/services/m3dbnode/config/bootstrap.go
- src/dbnode/persist/fs/files.go
- src/dbnode/persist/fs/migration/migration.go
- src/dbnode/persist/fs/migration/migration_test.go
- src/dbnode/persist/fs/migration/options.go
- src/dbnode/persist/fs/types.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/migrator/migrator.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/migrator/migrator_test.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/migrator/options.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/migrator/options_test.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/migrator/types.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/options.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/source.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/source_data_test.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/types.go
- src/dbnode/storage/bootstrap/bootstrapper/readers.go
- src/dbnode/tracepoint/tracepoint.go
Fixes #2790
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Add Migrator for performing migrations and wire into fs bootstrapper

- src/cmd/services/m3coordinator/ingest/write.go
- src/cmd/services/m3coordinator/ingest/write_test.go
- src/query/models/tags.go
- src/query/models/tags_test.go
There is no point having them go through the ingestion pipeline if we are going to experience the same errors of writing them to storage where we do validation already for unaggregated metrics.
```release-note
NONE
```
```documentation-note
NONE
```
> [coordinator] Validate and do not send metrics with invalid labels to aggregator

- src/query/graphite/native/builtin_functions.go
- src/query/graphite/native/builtin_functions_test.go
Adds the Graphite `exponentialMovingAverage` function.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Implemented the Graphite `exponentialMovingAverage` function

- src/query/graphite/native/builtin_functions.go
- src/query/graphite/native/builtin_functions_test.go
Added the graphite `aliasByTags` function. It is an exact copy of `aliasByNode`.
Here is the graphite source code if you want proof --> https://github.com/graphite-project/graphite-web/blob/17a34e7966f7a46eded30c2362765c74eea899cb/webapp/graphite/render/functions.py#L5517
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Implemented the Graphite `aliasByTags` function

- CHANGELOG.md
Update changelog.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update changelog for 0.15.14 release

- src/dbnode/server/server.go
- src/dbnode/storage/limits/noop_query_limits.go
- src/dbnode/storage/limits/query_limits.go
- src/dbnode/storage/limits/query_limits_test.go
- src/dbnode/storage/limits/types.go
Forgot to push last minor commit on https://github.com/m3db/m3/pull/2627
```release-note
```
```documentation-note
```
> [dbnode] query limits - missed commit with feedback

- docs/overview/media.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add recent talks

- CHANGELOG.md
Add changelog.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Add changelog for 0.15.15

- src/msg/README.md
- src/msg/producer/writer/README.md
Moves writer README to top level msg README and improve the documentation about multiple consumers.
NONE
NONE
> move writer README to top level msg README 

- src/dbnode/persist/fs/seek_manager_test.go
Fix data race in TestSeekerManagerCacheShardIndices
NONE
NONE
> Fix data race in TestSeekerManagerCacheShardIndices

- src/msg/producer/writer/consumer_writer.go
This is a shared lock across all goroutines, so ideally we limit the
amount of sync points. There is no need to acquire the exclusive lock
when flushing a connection. Instead the shared read lock can be acquired
and individual connection exclusive locks can be acquired to ensure only
a single writer is using the connection at a time.
This is part of a broader fix to prevent deadlocks in the m3msg communication.
Before this change and adding write timeouts, the producer and consumer could deadlock
and stop all messages from flowing. If a producer was sending more messages than
it was acking, it would eventually fill up the TCP buffers and begin to block
writes. If the producer was flushing a connection and holding the exclusive lock,
it would end up …
> [m3msg] Only acquire writeState exclusive lock when resetting connections

- CHANGELOG.md
Changelog update.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Add changelog for v0.15.16

- CHANGELOG.md
> [changelog] Changelog for 0.15.17

- src/aggregator/server/server.go
- src/dbnode/server/server.go
- src/query/server/query.go
- src/x/instrument/build.go
- src/x/instrument/options.go
- src/x/instrument/types.go
The build reporter exposes helpful build metadata in the form of a
constantly updated gauge. However, the set of data it can expose is
fixed. This PR allows adding custom tags.
Fixes #
```release-note
```
```documentation-note
```
> [instrument] Support custom build tags in reporter

- src/dbnode/client/client_mock.go
- src/dbnode/client/config.go
- src/dbnode/client/options.go
- src/dbnode/client/types.go
- src/query/server/query.go
- src/query/storage/m3/cluster_test.go
- src/query/storage/m3/config.go
- src/query/storage/m3/dynamic_cluster.go
- src/query/storage/m3/options.go
- src/query/storage/m3/types.go
This PR adds the plumbing required to pull cluster namespaces
dynamically. Actual code to perform data fetch and updates
will be added in follow on PRs. For the time being, if the
dynamic code path is invoked, an error is returned. Clients
must continue to specify namespace details in the coordinator
configuration.
Will add tests for this once path is actually being used
```release-note
```
```documentation-note
```
> [query] Add plumbing for dynamic Clusters implementation.

- src/dbnode/client/reader_slice_of_slices_iterator.go
- src/dbnode/encoding/iterator_test.go
- src/dbnode/encoding/multi_reader_iterator.go
- src/dbnode/x/xio/reader_slice_of_slices_from_block_readers_iterator.go
- src/dbnode/x/xio/reader_slice_of_slices_from_block_readers_iterator_test.go
- src/dbnode/x/xio/types.go
- src/query/remote/compressed_codecs.go
- src/query/remote/compressed_codecs_test.go
- src/x/sync/pooled_worker_pool_test.go
See https://github.com/m3db/m3/pull/2714 for more details. This is an alternative solution.
```release-note
```
```documentation-note
```
> [dbnode] Allow ReaderSliceOfSlicesIterator to Rewind to index

- src/dbnode/integration/large_tiles_test.go
An attempt to fix flaky integration test by hardening `xclock.WaitUntil` conditions.
```release-note
```
```documentation-note
```
> [dbnode] Try to fix flaky TestReadAggregateWrite

- scripts/comparator/basic_queries/queries.json
These tests weren't correctly fetching data following a comparator refactor a while back.
> [comparator] Fix comparator aggregation function tests

- src/dbnode/storage/index/wide_query_results.go
Fixes #
```release-note
```
```documentation-note
```
> Combine draining into single method for single place to change logic/faster reading of the code

- .buildkite/pipeline.yml
We are upgrading the docs and it needs to be done in a two staged rollout.
While we are in the middle of the rollout, the tests are failing and blocking
master. We can re-enable once https://github.com/m3db/m3/pull/2770 is merged.
NONE
NONE
> Temporarily disable broken docs test

- .buildkite/pipeline.yml
- site/content/docs/faqs/_index.md
- site/content/docs/operational_guide/namespace_configuration.md
- site/content/docs/operational_guide/placement_configuration.md
This reverts commit 8e0f9fcd7fc539e1e0a6d8191878248a6576b9fa.
> [DOCS] Revert "Temporarily disable broken docs test (#2776)"

- scripts/development/m3_stack/m3coordinator-standard.yml
- scripts/development/m3_stack/start_m3.sh
- src/dbnode/client/config.go
- src/dbnode/environment/config.go
- src/dbnode/namespace/dynamic.go
- src/dbnode/namespace/dynamic_options.go
- src/dbnode/namespace/dynamic_test.go
- src/dbnode/namespace/namespace_mock.go
- src/dbnode/namespace/types.go
- src/query/storage/m3/config.go
- src/query/storage/m3/dynamic_cluster.go
- src/query/storage/m3/dynamic_cluster_test.go
Fixes #
Easiest to review by commit as each commit resolves a small issue in wiring up the dynamic Clusters impl for use.
```release-note
```
```documentation-note
```
> [query][dbnode] Wire up etcd-backed Clusters implementation in coordinator

- src/query/server/query.go
Fixes #
```release-note
```
```documentation-note
```
> [query] Support dynamic namespace resolution for embedded coordinators

- src/metrics/rules/active_ruleset_test.go
This adds a simple test to ensure that `keepOriginal` is set to true if _any_ of an ID's matched rollup rules have `keepOriginal: true`.
> [metrics/rules] Add test to assert that mixed-mode keepOriginal uses keepOriginal=true

- src/dbnode/storage/shard.go
Adds a missing check for seriesIter.Err.
NONE
NONE
> [dbnode] Add a check for seriesIter.Err

- Makefile
- src/cmd/tools/query_index_segments/main/main.go
- src/cmd/tools/read_index_segments/main/main.go
- src/cmd/tools/verify_data_files/main/main.go
- src/dbnode/persist/fs/index_read_segments.go
- src/dbnode/persist/fs/persist_manager.go
- src/dbnode/storage/bootstrap/bootstrapper/fs/source.go
Fixes #
```release-note
```
```documentation-note
```
> [read_index_segments] Always validate index segment checksums before reading/validating contents

- .golangci.yml
> [linter] New value for new-from-rev

- src/dbnode/integration/large_tiles_test.go
Skipping the flaky test until we will fix it.
```release-note
NONE
```
```documentation-note
NONE
```
> Skip flaky test

- .golangci.yml
- src/dbnode/storage/dice.go
- src/dbnode/storage/dice_test.go
- src/dbnode/storage/forward_index_dice.go
- src/dbnode/storage/repair.go
As part of the 1.0 release, consolidating common code into areas where it's specifically being used
```release-note
NONE
```
```documentation-note
NONE
```
> Move dice package into dbnode/storage

- .buildkite/hooks/pre-checkout
- .buildkite/hooks/pre-exit
pre-checkout is not a repository hook so this never runs.
pre-exit was adding noise to the build output. just check if the
directory exists first.
"chmod: cannot access ‘./_tools’: No such file or directory"
```release-note
```
```documentation-note
```
> Remove pre-checkout hook and fix pre-exit

- src/aggregator/aggregator/election_mgr.go
I did something stupid in #2855 
```release-note
```
```documentation-note
```
> [aggregator] Fix checkCampaignStateLoop

- .buildkite/pipeline.yml
- Makefile
- docker-compose.yml
- docker/m3aggregator/Dockerfile
- docker/m3collector/Dockerfile
- docker/m3coordinator/Dockerfile
- docker/m3dbnode/Dockerfile
- docker/m3dbnode/Dockerfile-setcap
- docker/m3query/Dockerfile
This reverts commit 55e6e44bd28ee9f80c8f6120147c15daa82193f8.
Go back to 1.13 while regressions are being investigated.
```release-note
```
```documentation-note
```
> Revert "Bump go to 1.14 (#2853)"

- scripts/docker-integration-tests/prometheus/test.sh
- src/x/net/http/errors.go
Return a `504 Gateway Timeout` error code if error is due to actual timeout (deadline exceeded). 
```release-note
NONE
```
```documentation-note
NONE
```
> [all] Return a 504 error if timeout.

- .buildkite/docs-docker-compose.yml
- docker/docs/Dockerfile
- site/content/docs/how_to/kubernetes.md
This dockerfile was lost, and now operator docs was no longer being built.
```release-note
NONE
```
```documentation-note
NONE
```
> [docs] Fix operator docs no longer being built and published

- README.md
Temporarily moved, removing from README for time being.
```release-note
```
```documentation-note
```
> Update README to temporarily remove the logo

- scripts/development/m3_stack/m3dbnode.yml
Fixes #
```release-note
```
```documentation-note
```
> Fix seedNodes config in local stack yaml

- site/content/m3query/_index.md
Corrects old typo in title of m3query page
> [DOCS] Correct old typo

- src/dbnode/client/config.go
Fixes client config not respecting value for connect consistency.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Fix client config respecting value for connect consistency

- kube/storage-fast-aliyun.yaml
[storage] Add aliyun storage class
> [storage] Add aliyun storage class

- site/config.toml
This pull request moves the hard coded menu structure to parameters and changes in the theme (https://github.com/chronosphereio/victor/commit/f5bc1f4ca3c61923e180b4113b4c52f9f8d8fad6)
> [DOCS] Parameterise menus

- src/dbnode/persist/fs/merger.go
- src/dbnode/persist/types.go
Change type names of series metadata types to be more consistent w/ series metadata type names. 
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Update series metadata type name.

- .golangci.yml
Fixes linter not producing any errors. 
For some unknown reason, linting doesn't work when setting `new-from-rev` to https://github.com/m3db/m3/commit/5edd3f1c47a41e1df834f92b0ab062206a9e951a or any revision before it ([see buildkite](https://buildkite.com/uberopensource/m3-monorepo-public/builds/5534#fa3b74c1-6e41-4c95-bcce-047777bdb914)), but it start working when switching to https://github.com/m3db/m3/commit/cc7822453e789be822047de096d30e31780acdc7 ([see buildkite](https://buildkite.com/uberopensource/m3-monorepo-public/builds/5535#9e5b8fa8-f246-42d0-baa7-7c7804b2d722)).
Since quite a few linting errors have creeped in during this time, I'm gonna set `new-from-rev` to most recent commit on `master`. 
**Does …
> [linter] Fix linter not finding any issues

- scripts/docker-integration-tests/prometheus/docker-compose.yml
Temporarily switch to prometheus v2.22 docker image since v2.23 breaks `docker-integration-tests`
```release-note
NONE
```
```documentation-note
NONE
```
> [tests] Switch to prometheus v2.22 docker image in docker-integration-tests

- src/cluster/etcd/watchmanager/manager.go
Just something I noticed while reviewing code.
```release-note
```
```documentation-note
```
> [watchmanager] Do not leak tickers in stopped watches

- src/cluster/etcd/watchmanager/manager.go
Not all errors included the watch key, so make the logger consistent, and include info level messages on watch creation - it's annoying to debug watch timeouts, etc. otherwise.
```release-note
```
```documentation-note
```
> [etcd] Clean up logging in WatchManager

- src/cluster/etcd/watchmanager/manager.go
Forgot to commit this to #2973
```release-note
```
```documentation-note
```
> [etcd] Log watch error source details

- site/content/overview/media.md
Fixes link.
```release-note
NONE
```
```documentation-note
NONE
```
> [docs] Fix link for July 2020 community meeting recording

- site/content/quickstart/docker.md
I believe this line was unintentionally added back to the guide. Adding namespaces to the coordinator config is deprecated in 1.0. The rest of the guide accurately reflects how to create namespaces in such a way that doesn't require changing the coordinator config.
```release-note
```
```documentation-note
```
> [docs] Remove reference to adding namespace to coordinator config

- go.mod
- src/dbnode/namespace/kvadmin/ns_admin.go
- src/m3em/node/node.go
- src/m3ninx/util/uuid.go
Rest of codebase uses `github.com/pborman/uuid`.
The package has serious issues (ex. https://github.com/satori/go.uuid/pull/75 has never been included in a tagged release) and is abandoned.
```release-note
```
```documentation-note
```
> Remove odd uses of satori/go.uuid package

- src/metrics/rules/mapping.go
- src/metrics/rules/mapping_test.go
- src/metrics/rules/ruleset_test.go
Noticed this bug on model conversion.
NONE
NONE
> [rules] Set tags field of mapping rules history conversion

- src/cmd/services/m3coordinator/downsample/options.go
- src/query/server/query.go
> [coordinator] Update ApplyCustomRuleStore interface

- site/static/index.html
Fixes #
```release-note
```
```documentation-note
```
> Adding Hostinger Logo

- src/metrics/rules/view/mapping.go
- src/metrics/rules/view/mapping_test.go
- src/query/models/types.go
Include tags in view.MappingRule Equals()
NONE
NONE
> [coordinator] Include tags in view.MappingRule Equals

- src/dbnode/client/fetch_tagged_results_accumulator.go
Fixes "unable to satisfy consistency requirements" error message, which had underlying error printed twice
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Fix "unable to satisfy consistency requirements" error message

- site/content/includes/quickstart-common-steps.md
- site/go.mod
- site/go.sum
Small PR to fix one incorrect link in quickstart
> [DOCS] Fix services ready path

- src/cmd/services/m3coordinator/downsample/options.go
Remove unused config.
NONE
NONE
> [coordinator] Remove unused DisableAutoMappingRules config

- src/metrics/encoding/protobuf/unaggregated_iterator.go
- src/metrics/encoding/protobuf/unaggregated_iterator_test.go
Fixes #
```release-note
```
```documentation-note
```
> [aggregator] Fix panic on invalid unaggregated payloads

- src/cmd/services/m3coordinator/ingest/carbon/ingest.go
- src/cmd/services/m3coordinator/ingest/carbon/ingest_test.go
- src/cmd/services/m3query/config/config.go
Adds faster than regexp matching string contains check for simpler rule use cases.
```release-note
NONE
```
```documentation-note
NONE
```
> [coordinator] Add Graphite Carbon ingest contains rule matcher for fast match

- scripts/docker-integration-tests/carbon/expected/dbaz.json
- scripts/docker-integration-tests/carbon/expected/ebaz.json
- scripts/docker-integration-tests/carbon/expected/fbaz.json
- scripts/docker-integration-tests/carbon/expected/gbaz.json
- scripts/docker-integration-tests/carbon/expected/hbarbaz.json
- scripts/docker-integration-tests/carbon/expected/ibarbaz.json
- scripts/docker-integration-tests/carbon/m3coordinator.yml
- scripts/docker-integration-tests/carbon/test.sh
Adds integration test for end to end metric cleanup coverage.
```release-note
NONE
```
```documentation-note
NONE
```
> [coordinator] Add Graphite Carbon rewrite cleanup integration test

- src/aggregator/client/tcp_client.go
**Problem**:
When collector fails to write a metric to aggregator, it logs an error but in practice it is almost impossible to tell whether it failed to write to both peers owning a shard or only one of them, i.e. whether data is lost or not.
**Solultion**:
Emit a metric indicating data loss.
NONE
NONE
> [aggregator/client] Metric for dropped metrics

- src/metrics/filters/tags_filter.go
Add TagFilter Matches comments
NONE
NONE
> [coordinator] Add TagFilter Matches comments

- src/dbnode/persist/fs/retriever.go
followup fix for https://github.com/m3db/m3/pull/3103/files#r560565737
> Capture seekerMgr instead Rlock

- scripts/docker-integration-tests/run.sh
Fixes #
```release-note
```
```documentation-note
```
> [tests] Add option to skip setup for docker integration tests

- README.md
A few small bullets issues slipped in with #3077 this PR fixes them
> [DOCS] Fix bullets numbering in readme

- scripts/docker-integration-tests/aggregator/test.sh
- scripts/docker-integration-tests/aggregator_legacy/test.sh
- scripts/docker-integration-tests/carbon/test.sh
- scripts/docker-integration-tests/cold_writes_simple/test.sh
- scripts/docker-integration-tests/coordinator_config_rules/test.sh
- scripts/docker-integration-tests/coordinator_noop/test.sh
- scripts/docker-integration-tests/dedicated_etcd_embedded_coordinator/test.sh
- scripts/docker-integration-tests/multi_cluster_write/test.sh
- scripts/docker-integration-tests/prometheus/test-correctness.sh
- scripts/docker-integration-tests/prometheus/test.sh
- scripts/docker-integration-tests/prometheus_replication/test.sh
- scripts/docker-integration-tests/query_fanout/restrict.sh
- scripts/docker-integration-tests/query_fanout/test.sh
- scripts/docker-integration-tests/query_fanout/warning.sh
- scripts/docker-integration-tests/repair/test.sh
- scripts/docker-integration-tests/repair_and_replication/test.sh
- scripts/docker-integration-tests/replication/test.sh
- scripts/docker-integration-tests/run.sh
- scripts/docker-integration-tests/simple/test.sh
- scripts/docker-integration-tests/simple_v2_batch_apis/test.sh
Fixes #
```release-note
```
```documentation-note
```
> [tests] Support custom M3 path for integration tests

- go.mod
- go.sum
Fixes #
```release-note
```
```documentation-note
```
> Bump uber/tchannel-go dependency

- src/cmd/tools/dtest/docker/harness/resources/harness.go
numShards support in dtests
```release-note
NONE
```
```documentation-note
NONE
```
> [dtest] numShards support

- CHANGELOG.md
Adds changelog for 1.1.0/
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Add changelog for 1.1.0

- site/layouts/404.html
- site/static/404/index.html
- site/static/about/index.html
- site/static/community/index.html
- site/static/index.html
Fixes #
```release-note
```
```documentation-note
```
> [docs] Update footer

- src/dbnode/storage/bootstrap/bootstrapper/base.go
- src/dbnode/storage/bootstrap/process.go
Cleans up the code by removing redundant array definitions.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Remove redundant array definitions in bootstrap logging

- src/dbnode/storage/series/reader.go
Fixes #
```release-note
```
```documentation-note
```
> Add blockReaderIterOpts

- .golangci.yml
Developers might not have a local branch for master and even if they
did, it might not be updated to match the remote master
Fixes #
```release-note
```
```documentation-note
```
> Lint from origin/master

- src/dbnode/network/server/tchannelthrift/node/service.go
Fixes #
```release-note
```
```documentation-note
```
> Expose node.IDResult as an interface

- src/dbnode/integration/options.go
- src/dbnode/integration/serve.go
- src/dbnode/integration/setup.go
Fixes #
```release-note
```
```documentation-note
```
> [tests] Add support for CustomAdminOptions; pass along InstrumentOptions on server create

- site/go.mod
- site/go.sum
This PR fixes white space that broke ascii art images. Closes #3143 
Signed-off-by: ChrisChinchilla <chris@chronosphere.io>
> [DOCS] Update theme to fix white space issues

- src/x/io/write.go
This saves a non-trivial amount of memory and data copies per connection in case buffering is not required, ex. in Aggregator TCP client (4kb per connection), which adds up quick.
```release-note
```
```documentation-note
```
> Use pass-through writer if no buffering is requested

- src/dbnode/storage/index.go
- src/x/sync/types.go
- src/x/sync/worker_pool.go
allows the index query path to compute the total wait time without
locking.
Fixes #
```release-note
```
```documentation-note
```
> Instrument the worker pool with the wait time

- src/metrics/metadata/metadata.go
- src/metrics/metadata/metadata_test.go
Most fields can be unset, yet still serialized as null/default values, which bloats encoded json document size.
```release-note
```
```documentation-note
```
> Add omitempty json tag for all fields in metadatas

- src/aggregator/aggregator/entry.go
Fixes #
```release-note
```
```documentation-note
```
> [aggregator] More range copy cleanups

- src/dbnode/storage/shard.go
Removes some leftover metrics that were not being reported.
NONE
NONE
> [dbnode] Remove unused metrics in shard.go

- src/dbnode/storage/index/block.go
Adds metrics for docs and series matched for both aggregate query endpoints and regular query endpoints.
> [dbnode] Add instrumentation for query docs matched

- src/dbnode/network/server/tchannelthrift/node/service_test.go
- src/dbnode/server/server.go
- src/dbnode/storage/index/block.go
- src/dbnode/storage/index/block_prop_test.go
- src/dbnode/storage/index/block_test.go
- src/dbnode/storage/limits/noop_query_limits.go
- src/dbnode/storage/limits/permits/lookback_limit_permit.go
- src/dbnode/storage/limits/query_limits.go
- src/dbnode/storage/limits/query_limits_test.go
- src/dbnode/storage/limits/types.go
Adds additional metrics for Aggregate queries
> [dbnode] Aggregate query limit metrics

- src/cmd/services/m3query/config/config.go
- src/query/api/v1/handler/prometheus/common.go
- src/query/api/v1/handler/prometheus/common_test.go
- src/query/api/v1/handler/prometheus/native/list_tags.go
- src/query/api/v1/handler/prometheus/remote/match.go
- src/query/api/v1/handler/prometheus/remote/tag_values.go
- src/query/parser/promql/options.go
Fixes #
```release-note
```
```documentation-note
```
> [query] Add ability to require start time set for /label(s) and /series endpoints

- src/dbnode/client/fetch_tagged_results_accumulator_merge_test.go
- src/dbnode/network/server/tchannelthrift/convert/convert.go
- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/network/server/tchannelthrift/node/service_test.go
- src/dbnode/persist/fs/retriever.go
- src/dbnode/persist/fs/retriever_test.go
- src/dbnode/x/xio/types.go
This prevents a rpc routine from waiting around for disk reads to finish
after the caller has canceled the request. Additionally this adds the
caller ctx to the disk read request to skip processing requests that
have already been canceled.
Fixes #
```release-note
```
```documentation-note
```
> Use ctx deadline when reading data series blocks

- src/dbnode/server/server.go
Allow sharing KVStore between M3 components similar to the dbClient.
```release-note
```
```documentation-note
```
> Add KVStoreCh for dbnode

- src/dbnode/storage/index.go
- src/dbnode/storage/index/block.go
- src/dbnode/storage/index/block_test.go
- src/dbnode/storage/index/fields_terms_iterator.go
- src/dbnode/storage/index/index_mock.go
- src/dbnode/storage/index/metrics.go
- src/dbnode/storage/index/types.go
Fixes #
```release-note
```
```documentation-note
```
> Add search and processing timing for aggregate queries

- src/dbnode/storage/index.go
This will help understand how long a query is using one of the workers
for.
Fixes #
```release-note
```
```documentation-note
```
> Instrument the time to process a single index block

- src/query/api/v1/handler/database/kvstore.go
- src/query/api/v1/handler/database/kvstore_test.go
```release-note
```
```documentation-note
```
> Use proto parser only if no error

- src/cmd/services/m3dbnode/config/config.go
- src/cmd/services/m3dbnode/config/config_test.go
- src/cmd/services/m3dbnode/config/fetch_tagged.go
- src/dbnode/network/server/tchannelthrift/node/fetch_result_iter_test.go
- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/network/server/tchannelthrift/options.go
- src/dbnode/network/server/tchannelthrift/types.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Add ability to set blocksPerBatch via config

- src/dbnode/client/aggregate_results_accumulator_merge_test.go
- src/dbnode/client/fetch_tagged_results_accumulator.go
- src/dbnode/client/fetch_tagged_results_accumulator_merge_test.go
The previous impl was not correct and would drop results when merging.
The included unit test exposed the previous bug.
Without the code fix:
```
--- FAIL: TestAggregateResultsAccumulatorIdsMerge (0.00s)
Error Trace:    fetch_tagged_results_accumulator_merge_test.go:397
aggregate_results_accumulator_merge_test.go:86
Error:		Not equal: 6 (expected)
!= 4 (actual)
```
```release-note
```
```documentation-note
```
> Properly merge aggregate results in dbnode client 

- src/dbnode/network/server/tchannelthrift/node/fetch_result_iter_test.go
- src/dbnode/network/server/tchannelthrift/node/service.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Add metric for series blocks read in FetchTagged endpoint

- scripts/docker-integration-tests/prometheus/test.sh
Will add back with deterministic behavior.
```release-note
```
```documentation-note
```
> Remove flaky tests temporarily

- src/cmd/services/m3dbnode/config/fetch_tagged.go
- src/dbnode/network/server/tchannelthrift/node/service_test.go
- src/dbnode/server/server.go
- src/dbnode/storage/limits/permits/lookback_limit_permit.go
- src/dbnode/storage/limits/permits/lookback_limit_permit_test.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Support configurable increments for LookbackLimitPermits

- src/dbnode/server/server.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Set blocksPerBatch on fetchTaggedIter from config

- src/dbnode/storage/index/block.go
Better to use a standard version, than a reimpl
Fixes #
```release-note
```
```documentation-note
```
> Use exposed m3ninx SafeCloser in index/block

- src/dbnode/server/options.go
- src/dbnode/server/server.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Add ability to specify permitOptions in runOptions

- src/dbnode/server/options.go
- src/dbnode/server/server.go
This reverts commit 5d94b4d48dbd8f9f2b0f883af78c36c1619e760d.
Fixes #
```release-note
```
```documentation-note
```
> Revert "[dbnode] Add ability to specify permitOptions in runOptions"

- src/query/api/v1/handler/prometheus/native/common.go
- src/query/api/v1/handler/prometheus/native/common_test.go
- src/query/api/v1/handler/prometheus/native/read.go
- src/query/api/v1/handler/prometheus/native/read_common.go
Before, this was being done in a preceding filtering function which mutated the underlying series array.
```release-note
```
```documentation-note
```
> Apply NaN filtering while rendering series

- src/cmd/services/m3coordinator/downsample/downsampler_test.go
- src/metrics/metadata/metadata.go
- src/metrics/pipeline/applied/type.go
Fixes #
```release-note
```
```documentation-note
```
> [coordinator] Update PipelineMetadata#IsMappingRule to consider rollup rules without rollups 

- src/aggregator/aggregation/quantile/cm/list.go
Fix regression introduced by #3307 
```release-note
```
```documentation-note
```
> [aggregator] Clear pointers on sample list reset

- src/dbnode/network/server/tchannelthrift/node/fetch_result_iter_test.go
- src/dbnode/network/server/tchannelthrift/node/service.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] fetchTaggedResultIter should not release if no acquires done

- src/metrics/rules/active_ruleset.go
Fixes #
```release-note
```
```documentation-note
```
> [coordinator] Simplify iteration logic of matchRollupTarget

- src/metrics/pipeline/type.go
- src/metrics/pipeline/type_test.go
Fixes #
```release-note
```
```documentation-note
```
> [coordinator] Include Type in RollupOp.Equal

- src/aggregator/aggregator/entry.go
- src/aggregator/aggregator/entry_test.go
- src/aggregator/server/m3msg/server.go
- src/metrics/metadata/metadata.go
These messages should be dropped upstream,
however we drop them in the aggregator as a safeguard as well.
We also add logging of the proto messages for
those that we cannot process for debugging purposes.
Fixes #
```release-note
```
```documentation-note
```
> [aggregator] Drop messages that have a drop policy applied

- src/dbnode/storage/shard.go
Noticed and cleaned up some dead code (my own leftovers).
NONE
NONE
> [dbnode] Remove unused shardBlockVolume

- scripts/docker-integration-tests/prometheus/test.sh
Accidentally removed the defer.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Add back teardown of containers at end of Prometheus integration test

- src/dbnode/server/server.go
- src/dbnode/storage/options.go
Fixes `clock.Options` not being propagated to other option stucts that also depend on clock. 
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Fix clock options not propagated where needed

- site/content/overview/media.md
Fixes #
```release-note
```
```documentation-note
```
> Updating media

- src/dbnode/storage/bootstrap/process.go
Updates error text of the obsolete time ranges error to something less alarming. Plus, removing some leftover code.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Update error text of the obsolete time ranges error

- src/dbnode/client/config.go
- src/dbnode/server/server.go
Fixes clock not being propagated where needed
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Fix clock not being propagated where needed

- site/content/faqs/faqs.md
Fixes #
```release-note
```
```documentation-note
```
> Adding some new FAQs

- src/metrics/rules/active_ruleset_test.go
Fixes #
```release-note
```
```documentation-note
```
> [rules] Add unit test for exclude_by in active_ruleset_test

- src/aggregator/aggregator/follower_flush_mgr.go
`followerFlushManager` was incorrectly emitting `windows-never-flushed` metrics for `standard` and `timed` metrics types as `forwarded`.
NONE
NONE
> [aggregator] Fix followerFlushManager metrics

- site/content/operator/api.md
- site/content/operator/configuration/node_affinity.md
Updates the documentation for the m3db-operator to include API params for the latest version (v0.13.0) and includes examples for using the pod anti-affinity settings.  Also fixes a few broken internal links on the page.
NONE
NONE
NONE
> [docs] Update m3db operator docs with v0.13.0 features

- site/config/_default/config.toml
- site/go.mod
- site/go.sum
This PR updates the theme and a config line to fix broken edit links on pages.
Signed-off-by: ChrisChinchilla <chris@chronosphere.io>
> [DOCS] Fix broken links to edit pages

- scripts/docker-integration-tests/aggregator/test.sh
- scripts/docker-integration-tests/coordinator_config_rules/test.sh
- scripts/docker-integration-tests/prometheus/test.sh
- scripts/docker-integration-tests/prometheus_replication/test.sh
- scripts/docker-integration-tests/simple_v2_batch_apis/test.sh
- site/content/reference/m3coordinator/api/remote.md
Fixes #
```release-note
```
```documentation-note
```
> [integration-tests] Use explicit version for quay.io/m3db/prometheus_remote_client_golang

- src/cmd/services/m3query/config/config.go
- src/query/api/v1/handler/database/common.go
- src/query/api/v1/handler/database/create.go
- src/query/api/v1/handler/graphite/find.go
- src/query/api/v1/handler/graphite/find_test.go
- src/query/api/v1/handler/graphite/render.go
- src/query/api/v1/handler/graphite/render_parser.go
- src/query/api/v1/handler/graphite/render_test.go
- src/query/api/v1/httpd/handler.go
- src/query/api/v1/httpd/handler_test.go
- src/query/api/v1/options/handler.go
- src/query/server/query.go
This allows overrides to use different per query limits based on whether it's a Graphite find or render call.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Add Graphite find and render limit option overrides

- site/content/operational_guide/availability_consistency_durability.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Fix typo in consistency level description

- scripts/docker-integration-tests/carbon/m3coordinator.yml
- scripts/docker-integration-tests/carbon/test.sh
Adds integration test for setting find limits by config.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Add Graphite find limit config integration test

- src/query/api/v1/handler/prometheus/native/read.go
Previously it was logging an err value that was nil, since we weren't
setting the err to the Close() err.
Fixes #
```release-note
```
```documentation-note
```
> Log Close err in prom read handler

- Makefile
Fixes #
```release-note
```
```documentation-note
```
> [ci] Enable codecov to be skipped optionally

- Makefile
This reverts commit df4a37129ef4a84713b0fc06cd77da9d4817a2ba.
Fixes #
```release-note
```
```documentation-note
```
> Revert "[ci] Enable codecov to be skipped optionally (#3442)"

- Makefile
This reverts commit c4d6a6bcf8ba6790610e4d8f8cd61f93214d5a9c.
Fixes #
```release-note
```
```documentation-note
```
> [ci] Re-add SKIP_CODECOV option

- src/aggregator/aggregator/aggregator.go
These were missed in https://github.com/m3db/m3/pull/3315/files, and were causing hangs for us in prod.
Suspected sequence leading to hangs:
- RLock()
- Missed unlock on shard not owned `if int(shardID) >= len(agg.shards) return errShardNotOwned`
- Lock() from placement change (will never succeed)
- RLock() -- hangs all subsequent times due to pending Lock()
Once threads start hitting the final RLock, the aggregator locks up and stops processing metrics.
RWMutex behavior is consistent with the docs:
```
// If a goroutine holds a RWMutex for reading and another goroutine might
// call Lock, no goroutine should expect to be able to acquire a read lock
// until the initial read lock is released.
```
https://gist.github.com/andrewmains12/fabc257f4552f8e778828a23346d71c3 has a rough …
> Add missing RUnlock's to m3aggregator locking code

- scripts/docker-integration-tests/prometheus/test.sh
- src/query/api/v1/handler/graphite/render.go
- src/query/api/v1/handler/prom/read.go
- src/query/api/v1/handler/prometheus/native/complete_tags.go
- src/query/api/v1/handler/prometheus/native/list_tags.go
- src/query/api/v1/handler/prometheus/native/read.go
- src/query/api/v1/handler/prometheus/remote/tag_values.go
- src/query/api/v1/handler/search.go
- src/query/errors/handler.go
- src/x/net/http/errors.go
- src/x/net/http/errors_test.go
This makes it easier for users of M3 to rewrite query timeout errors
using the ErrorRewriteFn. Previously a rewrite fn would need to handle
all possible types of timeouts for various engines.
Fixes #
```release-note
```
```documentation-note
```
> Return generic ErrQueryTimeout for query timeouts

- src/query/api/v1/httpd/handler.go
- src/query/api/v1/httpd/handler_test.go
- src/query/api/v1/options/handler.go
- src/query/api/v1/options/middleware.go
- src/query/server/query.go
This allows configuring the Middleware that runs in the query server. By
default if the Middleware is not set, a set of default Middleware
functions are run (i.e the existing middleware)
Fixes #
```release-note
```
```documentation-note
```
> Add configurable Middleware to query server

- src/query/api/v1/httpd/handler_test.go
- src/query/api/v1/options/middleware.go
- src/x/instrument/logging.go
- src/x/instrument/logging_test.go
- src/x/instrument/options.go
- src/x/instrument/types.go
This will allow Middleware to inject common request scoped logging
fields for application code to use.
For example, the TracingMiddleware has been updated to inject trace_id
and span_id fields into the request logger. Now any application code
that gets a logger with LoggerFromContext(ctx) will automatically have
these fields set on log messages.
Fixes #
```release-note
```
```documentation-note
```
> Add a request scoped logger to a context

- src/query/source/source.go
- src/query/source/source_test.go
Also return a BadRequest error if the M3-Source header value is invalid.
Fixes #
```release-note
```
```documentation-note
```
> Skip source Middleware if M3-Source header is missing

- src/aggregator/integration/clock.go
- src/aggregator/integration/custom_aggregations_test.go
- src/aggregator/integration/integration.go
- src/aggregator/integration/metadata_change_test.go
- src/aggregator/integration/multi_client_one_type_test.go
- src/aggregator/integration/multi_server_forwarding_pipeline_test.go
- src/aggregator/integration/one_client_multi_type_forwarded_test.go
- src/aggregator/integration/one_client_multi_type_timed_test.go
- src/aggregator/integration/one_client_multi_type_untimed_test.go
- src/aggregator/integration/one_client_passthru_test.go
- src/aggregator/integration/placement.go
- src/aggregator/integration/placement_change_test.go
- src/aggregator/integration/same_id_multi_type_test.go
Adds integration test for aggregator placement changes
```release-note
NONE
```
```documentation-note
NONE
```
> [aggregator] Add integration test for aggregator placement changes

- src/query/api/v1/handler/prometheus/native/middleware.go
- src/query/api/v1/handler/prometheus/native/middleware_test.go
- src/query/api/v1/middleware/metrics.go
- src/x/http/status.go
These are helpful in debugging query requests.
Fixes #
```release-note
```
```documentation-note
```
> Add M3 headers and status code to QueryResponse logging

- .gitignore
- site/.htmltest.yml
- src/query/api/v1/httpd/handler.go
- src/query/api/v1/httpd/handler_test.go
- src/query/api/v1/middleware/metrics_test.go
- src/query/api/v1/options/handler.go
- src/query/util/queryhttp/queryhttp.go
This ensures all middleware is given the same instrument options, with
the correct metrics scope set.
When the middleware functions were introduced they used different
instrument options, so sometimes would have different metric scopes.
Fixes #
```release-note
```
```documentation-note
```
> Accept instrument opts when buildling middleware

- go.mod
- src/query/api/v1/handler/prometheus/native/middleware.go
- src/query/api/v1/handler/prometheus/native/middleware_test.go
- src/query/api/v1/middleware/middleware.go
The instant query handler uses a special "now" value to indicate using
the current time. Need to handle this value when attempting to parse the
values of the start/end params in the query logger.
Fixes #
```release-note
```
```documentation-note
```
> Handle special now value for start/end params in query logger

- src/query/api/v1/handler/prometheus/native/middleware.go
- src/query/api/v1/handler/prometheus/native/middleware_test.go
Extra information that would be helpful to have in the query logs.
Fixes #
```release-note
```
```documentation-note
```
> Log M3-* Response Headers in query logs

- scripts/docker-integration-tests/prometheus/test.sh
- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/storage/index.go
- src/x/headers/headers.go
Also we now always release permit unless successfully checked out.
```release-note
```
```documentation-note
```
> [coordinator][dbnode] Rename M3-Limit-Require-NoWait to Limit-Require-No-Wait to match canonical header value

- scripts/docker-integration-tests/prometheus/test.sh
Fixes #
```release-note
```
```documentation-note
```
> [integration-test] Optionally run global limits integration test

- DOCUMENTATION.md
- site/content/quickstart/docker.md
Fixes typos in documents
```release-note
NONE
```
```documentation-note
NONE
```
> [docs] Fix typos in Documents

- src/query/api/v1/handler/prometheus/native/middleware.go
- src/query/api/v1/handler/prometheus/native/middleware_test.go
- src/x/http/status.go
This will help for debugging failed status codes by including the error
message as well.
Fixes #
```release-note
```
```documentation-note
```
> Track the error message for logging query responses

- src/query/graphite/common/basic_functions.go
- src/query/graphite/native/builtin_functions.go
- src/query/graphite/native/builtin_functions_test.go
Update removeEmptySeries to support xFilesFactor
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Update removeEmptySeries to support xFilesFactor

- site/config/_default/config.toml
While looking at #3437 I realised that the Docker version was behind, so this PR updates it
> [DOCS] Update Docker version

- src/query/graphite/common/aggregation.go
- src/query/graphite/common/aggregation_test.go
- src/query/graphite/common/percentiles.go
- src/query/graphite/native/builtin_functions.go
- src/query/graphite/native/builtin_functions_test.go
Implement filterSeries: https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.filterSeries
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Implement Graphite filterSeries function

- src/query/graphite/native/builtin_functions.go
- src/query/graphite/native/compiler_test.go
`filterSeries` was implemented without being registered, this registers the function and adds a compiler test.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Register Graphite filterSeries function

- go.mod
- go.sum
- src/cluster/placement/compress.go
- src/cluster/placement/compress_test.go
Trying to track down the cause of occasional hangs in placement decoding.
A bit of cleanup - reuse decoder/encoder; do NOT pass a byte reader to decoder and use DecodeAll - it could possibly result in buggy behavior. 
```release-note
```
```documentation-note
```
> [cluster] Placement compression fixes

- src/query/api/v1/httpd/handler.go
- src/query/api/v1/httpd/router.go
- src/query/api/v1/httpd/router_test.go
- src/x/headers/headers.go
Fixes #
```release-note
```
```documentation-note
```
> Move M3-Engine header to headers file

- src/dbnode/storage/namespace.go
Just noticed that `errNamespaceReadOnly` was not reporting the error to the `MethodMetrics` properly.
NONE
NONE
> [dbnode] Properly report metrics on errNamespaceReadOnly

- src/dbnode/storage/namespace.go
Adds a metric for writes without annotations.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Count writes without annotations

- src/dbnode/integration/bootstrap_retries_test.go
- src/dbnode/integration/integration.go
- src/dbnode/integration/options.go
- src/dbnode/integration/serve.go
- src/dbnode/integration/setup.go
- src/dbnode/storage/bootstrap/process.go
- src/dbnode/storage/bootstrap/process_test.go
Only retry bootstrapping when the time window shifts if peer bootstrapping will run due to bootstrapping initializing shards. If there is no initializing shards and bootstrap will only bootstrap from disk, commit logs and snapshots then there's no reason to retry a bootstrap since all data from disk is as up to date as it ever will be.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Only retry bootstrap on time window shift if peer bootstrapping

- src/x/time/unix_nano.go
- src/x/time/unix_nano_test.go
Mimic stdlib API here like other methods do:
https://golang.org/pkg/time/#Duration.Truncate
```release-note
```
```documentation-note
```
> [time] UnixNano.Truncate should not panic on zero duration

- src/query/api/v1/handler/graphite/render.go
Since Graphite evaluation happens in an asynchronous goroutine (one per query target) the default middleware does not catch panics nor log them. Therefore this adds the panic capture and logging for that code path.
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Add Graphite render panic logging

- .buildkite/pipeline.yml
- Makefile
- docker-compose.yml
- docker/m3aggregator/Dockerfile
- docker/m3collector/Dockerfile
- docker/m3coordinator/Dockerfile
- docker/m3dbnode/Dockerfile
- docker/m3dbnode/Dockerfile-setcap
- docker/m3query/Dockerfile
- go.mod
- go.sum
- src/dbnode/client/client_mock.go
- src/query/remote/compressed_codecs_test.go
- src/query/server/query.go
- src/query/server/query_test.go
Upgrades M3 to use Go 1.16.
This will require production testing which is ongoing.
```release-note
NONE
```
```documentation-note
NONE
```
> Upgrade Go runtime to Go 1.16

- src/query/api/v1/middleware/rewrite.go
- src/query/api/v1/middleware/rewrite_test.go
Fixes #
```release-note
```
```documentation-note
```
> [coordinator] Ensure request body is reset for non-rewritten requests

- docker/m3aggregator/Dockerfile
- docker/m3collector/Dockerfile
- docker/m3coordinator/Dockerfile
- docker/m3dbnode/Dockerfile
- docker/m3dbnode/Dockerfile-setcap
- docker/m3query/Dockerfile
Fixes #
```release-note
```
```documentation-note
```
> [buildkite] Setup actual go 1.16 docker image

- docker/m3aggregator/Dockerfile
- docker/m3collector/Dockerfile
- docker/m3coordinator/Dockerfile
- docker/m3dbnode/Dockerfile
- docker/m3dbnode/Dockerfile-setcap
- docker/m3query/Dockerfile
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
Fixes #
```release-note
```
```documentation-note
```
> [buildkite] Use alpine 3.13 to avoid issues with faccessat2

- src/cluster/client/etcd/client.go
Fixes #
```release-note
```
```documentation-note
```
> [etcd] Bump grpc request limits

- src/aggregator/integration/integration_data.go
- src/aggregator/integration/multi_server_forwarding_pipeline_test.go
- src/aggregator/integration/setup.go
Generates more varying annotations in aggregator integration tests. 
We recently had some issues where byte slices where shared across requests (https://github.com/m3db/m3/pull/3605), leading to written metrics having incorrect annotations. Having a more varying set of annotations should increase the likelihood of uncovering such cases. 
```release-note
NONE
```
```documentation-note
NONE
```
> [aggregator] Generate more varying annotations in integration tests

- src/query/models/types.go
- src/query/storage/m3/options.go
- src/query/storage/m3/storage.go
- src/query/storage/m3/types.go
Useful to know what namespace the tags are being written to
Fixes #
```release-note
```
```documentation-note
```
> Add namespace to TagTransform

- src/cmd/services/m3query/config/config.go
Validation incorrectly didn't allow
configuration of >0.
https://github.com/m3db/m3/issues/3574
Fixes #
```release-note
```
```documentation-note
```
> [m3query] Allow for perCPU max of 1.0

- site/content/operator/getting_started/create_cluster.md
Fixes https://github.com/m3db/m3db-operator/issues/295
```release-note
```
```documentation-note
```
> [docs] Point to latest m3db operator

- src/dbnode/integration/index_active_block_rotate_test.go
- src/dbnode/integration/setup.go
- src/dbnode/storage/index.go
Fixes #
```release-note
```
```documentation-note
```
> Fix considering block as flushed based on result from tick (check block result not aggregated results)

- src/query/api/v1/handler/prom/read.go
`res.Err` was being logged as error but `err` was the error being checked in the if statement on whether to write the log or not (and thus should be the thing we are logging).
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Fix log statement that obscures error returned when failed to write response to client

- src/query/graphite/native/alias_functions_test.go
- src/query/graphite/native/builtin_functions.go
- src/query/graphite/native/builtin_functions_test.go
- src/query/graphite/native/compiler.go
- src/query/graphite/native/compiler_test.go
- src/query/graphite/native/engine_test.go
- src/query/graphite/native/expression.go
- src/query/graphite/native/functions.go
Fixes #
```release-note
```
```documentation-note
```
> [query] Fix Graphite timeShift series renaming

- src/query/graphite/native/builtin_functions.go
- src/query/graphite/native/builtin_functions_test.go
add graphite roundFunction
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Add Graphite round function

- src/aggregator/aggregator/entry.go
The previous format did not include seconds, which is pretty important
for lateness checks since the entire buffer might only be a minute.
The format changes from 02 Jan 06 15:04 -0700 -> 2006-01-02T15:04:05Z07:00
Fixes #
```release-note
```
```documentation-note
```
> Include seconds in timestamp for late errors

- src/query/graphite/native/builtin_functions.go
…terval argument
Add graphite hitcount function default handling for alignToInterval
```release-note
NONE
```
```documentation-note
NONE
```
> [query] Add Graphite hitcount function default value for alignToInterval argument

- src/dbnode/client/session.go
Just a minor logging change for better visibility.
NONE
NONE
> [dbnode] Log numShards on topology update

- src/dbnode/persist/fs/streaming_write_test.go
Test case for https://github.com/m3db/m3/pull/3664 fix.
NONE
NONE
> [dbnode] TestReuseStreamingWriter

- src/cmd/tools/split_shards/main/main.go
Reduce the likelihood of collisions when splitting directly into a running cluster.
NONE
NONE
> [tools] Increment fileset volume in shard splitter

- src/cmd/services/m3dbnode/config/config.go
- src/cmd/services/m3dbnode/config/config_test.go
- src/cmd/services/m3dbnode/main/main.go
- src/cmd/services/m3dbnode/server/server.go
Before this change, the main() method housed logic that determined if
a coordinator needed to be started alongside the dbnode. To ensure
integration tests don't duplicate this logic, we add a wrapper method,
server.RunComponents, that both main() and integration tests can call.
Additionally, allow clients to provide an interrupt channel so that
components can be stopped programmatically within a test.
```release-note
```
```documentation-note
```
> [dbnode] Expose single method for starting dbnode and optional coordinator

- src/aggregator/server/server.go
- src/dbnode/server/server.go
- src/query/server/query.go
This commit allows clients to provide a channel to receive
a notification that a component server has shutdown. The
primary use case for this will be for integration tests
that start components in-process. This will allow tests
to know precisely when a server has stopped instead of
relying on polling API endpoints or waiting for a
timeout.
```release-note
```
```documentation-note
```
> [dbnode][aggregator][coordinator] Add shutdownCh for server shutdown notification

- src/integration/harness_test.go
- src/integration/resources/docker/common.go
- src/integration/resources/docker/coordinator.go
- src/integration/resources/docker/dbnode.go
- src/integration/resources/docker/docker_resource.go
- src/integration/resources/docker/harness.go
- src/integration/resources/docker/options.go
- src/integration/resources/resources.go
- src/integration/resources/types.go
This commit takes the existing implementation of Node
and Coordinator and moves it to a docker package where it will
exist as a Docker-backed implementation of those interfaces.
Additionally, rename DockerResources to M3Resources. These changes
give us a vehicle for providing an in-process backed implementation
of M3Resources, Node, and Coordinator.
```release-note
```
```documentation-note
```
> [integration] Create M3Resources interface with current code as Docker-backed impl

- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/network/server/tchannelthrift/node/service_test.go
- src/dbnode/network/server/tchannelthrift/types.go
This commit stores the originating endpoint in the
context.Context. This can be useful for some internal M3 metrics
where a breakdown by endpoint is of interest, but no request
data is available where the metric is being emitted.
```release-note
```
```documentation-note
```
> [dbnode] Store request endpoint in context

- src/dbnode/network/server/tchannelthrift/endpoint.go
- src/dbnode/network/server/tchannelthrift/endpoint_test.go
- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/network/server/tchannelthrift/types.go
Useful if there's no value in the context where we expect
one to exist.
```release-note
```
```documentation-note
```
> [dbnode] Add enum value for Unknown RPC endpoint

- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/network/server/tchannelthrift/node/service_test.go
Fixes #
```release-note
```
```documentation-note
```
> [dbnode] Don't clobber endpoint in ctx when setting source

- src/query/api/v1/handler/prometheus/handleroptions/header_test.go
- src/query/api/v1/handler/prometheus/handleroptions/headers.go
- src/query/block/meta.go
- src/query/storage/m3/consolidators/completed_tags.go
- src/query/storage/m3/consolidators/completed_tags_test.go
- src/x/headers/headers.go
This commit adds an M3-Metadata-Count header that tracks the
amount of metadata (e.g. label names, label values) fetched
from the database before results are potentially truncated
and sent to the browser. This header is analogous to M3-Series-Count
which tracks the same thing but for timeseries instead of metadata.
```release-note
```
```documentation-note
```
> [query] Add M3-Metadata-Count header for tracking fetched metadata

- src/query/api/v1/handler/prometheus/handleroptions/fetch_options.go
- src/query/api/v1/handler/prometheus/handleroptions/fetch_options_test.go
- src/x/headers/headers.go
Addressing feedback to make this header clearer.
```release-note
NONE
```
```documentation-note
NONE
```
> Rename header to M3-Restrict-By-Storage-Policies

- src/query/server/query.go
Passing instrument.Opts is useful when things like handlers need access
to tracing or metrics scopes.
> [query] Make RunOptions more functional.

- src/aggregator/aggregator/aggregator.go
- src/aggregator/aggregator/aggregator_test.go
The previous attempt at migrating Untimed -> Timed would migrate all
Pipelines for a metric, even if only some of the Pipelines supported
resending aggregate values. This fix splits the Pipelines appropriately
and makes 2 calls if necessary.
Fixes #
```release-note
```
```documentation-note
```
> Only migrate Untimed to Timed for enabled pipelines

- src/dbnode/storage/namespace.go
This way it will get a more precise scope created in `NewAggregateTilesOptions`:
```
scope := insOpts.MetricsScope().SubScope("computed-namespace")
insOpts = insOpts.SetMetricsScope(scope.Tagged(map[string]string{
"target-namespace": targetNsID.String(),
"process":          process.String(),
}))
```
Also no more noop metrics will be created for default/aggregated namespaces.
NONE
NONE
> [dbnode] Better metrics scope for namespace.AggregateTiles

- src/query/api/v1/middleware/metrics.go
- src/query/api/v1/middleware/metrics_test.go
Requests that fail do not provide enough information to properly
classify them (i.e. they do not return the number of results
fetched). As a result, ensure they are marked unclassified.
Previously, they were placed into the smallest result bucket,
skewing the results of said bucket.
```release-note
```
```documentation-note
```
> [query] Do not attempt to classify size of requests that fail

- src/dbnode/network/server/tchannelthrift/node/service.go
- src/dbnode/storage/database.go
- src/dbnode/storage/database_test.go
- src/dbnode/storage/namespace.go
- src/dbnode/storage/namespace_test.go
- src/dbnode/storage/types.go
- src/x/serialize/fake_encoder.go
Add some new settings to `AggregateTilesOptions`.
NONE
NONE
> [dbnode] Metric type controls in AggregateTilesOptions

- src/aggregator/integration/multi_server_forwarding_pipeline_test.go
- src/aggregator/integration/multi_server_resend_test.go
- src/aggregator/integration/options.go
- src/aggregator/integration/placement.go
- src/aggregator/integration/placement_change_test.go
- src/aggregator/integration/setup.go
- src/aggregator/integration/topic.go
Unskips aggregator's placement change integration test when running with m3msg client. 
Only updating this one test for now. Will update and clean-up other tests in a follow-up PR. 
```release-note
NONE
```
```documentation-note
NONE
```
> [aggregator] Unskip placement change integration test with m3msg client

- src/aggregator/integration/custom_aggregations_test.go
- src/aggregator/integration/metadata_change_test.go
- src/aggregator/integration/multi_client_one_type_test.go
- src/aggregator/integration/multi_server_forwarding_pipeline_test.go
- src/aggregator/integration/multi_server_resend_test.go
- src/aggregator/integration/one_client_multi_type_forwarded_test.go
- src/aggregator/integration/one_client_multi_type_timed_test.go
- src/aggregator/integration/one_client_multi_type_untimed_test.go
- src/aggregator/integration/one_client_passthru_test.go
- src/aggregator/integration/options.go
- src/aggregator/integration/placement.go
- src/aggregator/integration/placement_change_test.go
- src/aggregator/integration/resend_stress_test.go
- src/aggregator/integration/same_id_multi_type_test.go
- src/aggregator/integration/setup.go
- src/aggregator/integration/topic.go
- src/dbnode/integration/fake/cluster_services.go
Updates and cleans-up aggregator integration tests after recently introduced support for m3msg client.
Depends on https://github.com/m3db/m3/pull/3744
```release-note
NONE
```
```documentation-note
NONE
```
> [aggregator] Update and cleanup aggregator integration tests

- src/metrics/pipeline/type.go
- src/metrics/pipeline/type_test.go
Our custom marshaler was missing the type field.
Fixes #
```release-note
```
```documentation-note
```
> Marshall RollupOp.Type in JSON

- src/cmd/services/m3dbnode/server/server.go
This commit ensures that if a shutdown notification channel
is provided to server.RunComponents, then that channel is
appropriately passed along to each component that is
started.
```release-note
```
```documentation-note
```
> [dbnode] Thread shutdown channel to individual M3 components.

- go.mod
- src/aggregator/aggregator/entry.go
- src/aggregator/aggregator/entry_test.go
- src/aggregator/aggregator/map.go
- src/aggregator/aggregator/map_test.go
- src/aggregator/hash/hash.go
Clean up aggregator.Entry a bit:
* shrink some data structures, map keys
* make rwlock private
* avoid option interface indirection for time lock
* use go.uber.org/{atomic,multierr} for simpler error/atomic handling
```release-note
```
```documentation-note
```
> [aggregator] Entry cleanups

- scripts/comparator/regression_data/rate_tag_mismatch.json
- scripts/comparator/utils/compare_utilities_regression.go
> [tools] Fix time units in comparator

- src/dbnode/client/client_mock.go
- src/dbnode/client/host_queue.go
- src/dbnode/client/options.go
- src/dbnode/client/session.go
- src/dbnode/client/types.go
- src/dbnode/encoding/multi_reader_iterator_array_pool.go
For highly-concurrent workloads preallocated channel-based pools are the bottleneck in both read and write path.
```release-note
```
```documentation-note
```
> [dbnode] Add support for dynamic (stdlib) pools in m3db client

- src/aggregator/aggregator/capture/aggregator.go
Fixes #
```release-note
```
```documentation-note
```
> [aggregator] Include resendEnabled in clone()

- site/config/production/config.toml
> [DOCS] Add version 1.2

- src/dbnode/server/server.go
```release-note
```
```documentation-note
```
Sample tracer logs to reduce noise.
> Sample tracer logs

- src/aggregator/client/queue.go
Previous limit can be too low for some workloads, and cause allocs for no good reason. 512kb should be sufficient and not cause use to hold on to too much memory:
```release-note
```
```documentation-note
```
> [aggclient] Bump max queue buffer size

- src/cmd/services/m3coordinator/downsample/metrics_appender.go
- src/metrics/metadata/metadata.go
- src/metrics/metadata/metadata_test.go
Fixes #
```release-note
```
```documentation-note
```
> [downsampler] Avoid mutating global DropPipelineMetadatas

- src/cmd/tools/read_index_files/main/main.go
Outputs some useful additional info about index fileset.
NONE
NONE
> [tools] Output shards and volumeType in read_index_files

- go.mod
- src/cmd/services/m3dbnode/config/config.go
- src/dbnode/persist/fs/index_claims_manager.go
- src/integration/resources/inprocess/cluster.go
- src/integration/resources/inprocess/cluster_test.go
- src/integration/resources/inprocess/coordinator.go
- src/integration/resources/inprocess/coordinator_test.go
- src/integration/resources/inprocess/dbnode.go
- src/integration/resources/inprocess/dbnode_test.go
- src/integration/resources/net/net.go
- src/integration/resources/resources.go
- src/integration/resources/types.go
inprocess.NewCluster allows clients to quickly spin up
a new cluster based on the desired config. Additionally,
can tweak the cluster topology from a set of ClusterOptions.
As a part of this refactor how we update configuration for
in-process components.
```release-note
```
```documentation-note
```
> [tests] Add support for inprocess.NewCluster

- src/dbnode/storage/bootstrap.go
- src/dbnode/storage/bootstrap_test.go
- src/dbnode/storage/database.go
- src/dbnode/storage/database_test.go
- src/dbnode/storage/storage_mock.go
- src/dbnode/storage/types.go
Fixes #
```release-note
```
```documentation-note
```
> Simplify callback logic by having the mediator own the lifecycle of the callback functions

- src/integration/resources/resources.go
Fixes #
```release-note
```
```documentation-note
```
> [tests] Check for nil options before using isolation groups

- src/integration/resources/docker/common.go
- src/integration/resources/docker/coordinator.go
- src/integration/resources/docker/dbnode.go
- src/integration/resources/docker/docker_resource.go
- src/integration/resources/docker/harness.go
- src/integration/resources/docker/options.go
- src/integration/resources/docker/prometheus.go
Fixes #
```release-note
```
```documentation-note
```
> [tests] Export useful docker functionality

- src/aggregator/aggregator/entry.go
- src/aggregator/aggregator/entry_test.go
This fixes a corner case when an aggregation has a mix of resendEnabled
pipelines. The previous code was incorrectly mutating the timestamp
parameter in the for loop and might result in using the client timestamp
for resendEnable=false pipelines.
Fixes #
```release-note
```
```documentation-note
```
> Correctly handle aggregations with mix of resendEnabled pipelines

- src/integration/resources/inprocess/aggregator_test.go
This PR fix the tests for in-process aggregators based on the new changes to its port generation logic.
```release-note
```
```documentation-note
```
> [tests] Fix in-process Aggregator tests

- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/elem_base.go
- src/aggregator/aggregator/elem_test.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/timer_elem_gen.go
A previous refactor added unncessary info to the flush state that is
retained for the life of the aggregation. This commit removes everything
from the flush state that does not need to be retained.
Fixes #
```release-note
```
```documentation-note
```
> Reduce the flush state retained by the aggregator

- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/elem_test.go
- src/aggregator/aggregator/flush.go
- src/aggregator/aggregator/forwarded_writer.go
- src/aggregator/aggregator/forwarded_writer_test.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/list.go
- src/aggregator/aggregator/timer_elem_gen.go
This minimizes how much data the forward writer needs to keep around
after a flush. Only the version needs to be kept around for the life
time of the the timed aggregation to support resending data.
Additionally, simplified the memory reuse to get rid of the
cachedValues. This is unnecessary and we can just reuse the slices
correctly when adding new aggregations/values.
Fixes #
```release-note
```
```documentation-note
```
> Only keep the bucket version in the forward writer

- src/dbnode/storage/index.go
- src/dbnode/storage/index_insert_queue.go
- src/dbnode/storage/index_insert_queue_test.go
- src/dbnode/storage/index_queue_forward_write_test.go
- src/dbnode/storage/index_queue_test.go
- src/dbnode/storage/options.go
- src/dbnode/storage/shard.go
- src/dbnode/storage/shard_insert_queue.go
- src/dbnode/storage/shard_insert_queue_test.go
- src/dbnode/storage/shard_ref_count_test.go
- src/dbnode/storage/storage_mock.go
- src/dbnode/storage/types.go
- src/x/sync/num_cores_darwin.go
- src/x/sync/num_cores_linux.go
- src/x/sync/num_cores_unsupported_os.go
Additionally allows us to provide a CoreFn to get the current CPU core which is useful for tests that shard work by the current core.
```release-note
```
```documentation-note
```
> [x/sync][dbnode] Detect number of cores based on OS

- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/elem_test.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/timer_elem_gen.go
```release-note
```
```documentation-note
```
> [aggregator] add test coverage for async dirty and consumed agg time processing

- src/cmd/services/m3query/config/config.go
- src/query/server/query.go
Fixes #
```release-note
```
```documentation-note
```
> [query] Move prometheus convert options to query prometheus config

- src/integration/resources/coordinator_client.go
- src/integration/resources/docker/coordinator.go
- src/integration/resources/inprocess/aggregator_test.go
- src/integration/resources/inprocess/coordinator.go
- src/integration/resources/inprocess/coordinator_test.go
- src/integration/resources/inprocess/dbnode_test.go
- src/integration/resources/types.go
- src/query/api/v1/handler/prometheus/remote/match.go
- src/query/api/v1/httpd/handler.go
- src/query/api/v1/route/prom.go
Fixes #
```release-note
```
```documentation-note
```
> [tests] Add support for calls to label APIs in resources.Coordinator

- src/aggregator/aggregator/aggregator.go
- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/elem_base.go
- src/aggregator/aggregator/elem_test.go
- src/aggregator/aggregator/entry.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/timer_elem_gen.go
These extra counters will help understand the amount of work a given
flush task is doing.
1. elements scanned - the number of metric elements scanned by the flush
task.
2. values processed - the number of values (i.e aggregated timestamps)
that are dirty and need to be flushed.
3. values expired - the number of values expired and no longer needed.
Additionally noticed we were missing active/inactive elements for timed
metrics, so added those too.
Fixes #
```release-note
```
```documentation-note
```
> [agg] Add more flushing counts

- src/integration/resources/coordinator_client.go
- src/integration/resources/docker/coordinator.go
- src/integration/resources/inprocess/coordinator.go
- src/integration/resources/types.go
This PR adds the graphite render query api to resources.coordinator.
```release-note
```
```documentation-note
```
> [tests] Add graphite render query to resources.coordinator

- CHANGELOG.md
Fixes #
```release-note
```
```documentation-note
```
> [changelog] v1.4.0 updates

- CHANGELOG.md
Fixes #
```release-note
```
```documentation-note
```
> [changelog] v1.4.1 updates

- src/integration/prometheus/prometheus.go
- src/integration/resources/coordinator_client.go
- src/integration/resources/docker/coordinator.go
- src/integration/resources/inprocess/coordinator.go
- src/integration/resources/types.go
Fixes #
```release-note
```
```documentation-note
```
> [tests] Add conversion of prometheus docker integration test - part 2

- src/integration/cluster_integration_tests.md
Fixes #
```release-note
```
```documentation-note
```
> [docs] Add documentation for writing cluster integration tests

- src/integration/aggregator/aggregator.go
- src/integration/aggregator/aggregator_test.go
This PR converts the docker integration test docker-integration-tests/aggregator/test.sh into an in-process implementation.
```release-note
```
```documentation-note
```
> [tests] Convert aggregator docker integration test to in-process

- src/aggregator/aggregator/aggregator.go
- src/aggregator/aggregator/aggregator_test.go
Also log a message for non-categorized errors so they are easier to
track down in the future.
Fixes #
```release-note
```
```documentation-note
```
> Classify aggregation closed errors

- src/integration/resources/inprocess/aggregator.go
- src/integration/resources/inprocess/common.go
- src/integration/resources/inprocess/coordinator.go
- src/integration/resources/inprocess/dbnode.go
Fixes #
```release-note
```
```documentation-note
```
> [tests] Support passing config to component StartFn

- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/elem_base.go
- src/aggregator/aggregator/elem_base_test.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/timer_elem_gen.go
This is a better indicator for the actual aggregator workload. The
current counts for incoming requests are not equal, since one request
can have many Pipelines can each Pipeline updates an Element.
Fixes #
```release-note
```
```documentation-note
```
> [agg] Add a count for element writes

- .buildkite/pipeline.yml
- Makefile
- src/integration/resources/inprocess/aggregator_test.go
- src/integration/resources/inprocess/cluster_test.go
- src/integration/resources/inprocess/coordinator_test.go
- src/integration/resources/inprocess/dbnode_test.go
- src/integration/resources/inprocess/inprocess.go
- src/integration/resources/inprocess/inprocess_test.go
Fixes #
```release-note
```
```documentation-note
```
> [tests] Enable cluster integration test harness tests

- src/cmd/services/m3coordinator/ingest/write.go
Add `source` label to `dropped` metrics counter (same as for `written`).
NONE
NONE
> [coordinator] Add source label to dropped metrics counter

- src/dbnode/storage/shard.go
Log the actual error causing invariant violation.
NONE
NONE
> [dbnode] Log error on invariant violation in dbShard.finishWriting

- .buildkite/pipeline.yml
- Makefile
- scripts/docker-integration-tests/prometheus/docker-compose.yml
- scripts/docker-integration-tests/prometheus/m3coordinator.yml
- scripts/docker-integration-tests/prometheus/m3dbnode.yml
- scripts/docker-integration-tests/prometheus/metadata-limits.sh
- scripts/docker-integration-tests/prometheus/prometheus.yml
- scripts/docker-integration-tests/prometheus/test-correctness.sh
- scripts/docker-integration-tests/prometheus/test.sh
- scripts/docker-integration-tests/repair_and_replication/docker-compose.yml
- scripts/docker-integration-tests/repair_and_replication/m3coordinator-cluster-a.yml
- scripts/docker-integration-tests/repair_and_replication/m3coordinator-cluster-b.yml
- scripts/docker-integration-tests/repair_and_replication/m3dbnode-cluster-a.yml
- scripts/docker-integration-tests/repair_and_replication/m3dbnode-cluster-b.yml
- scripts/docker-integration-tests/repair_and_replication/test.sh
- scripts/docker-integration-tests/run.sh
- scripts/docker-integration-tests/simple/test.sh
This reverts commit e413adaad542d785fbc23695fe235882c7931a85.
Fixes #
```release-note
```
```documentation-note
```
> Revert "[tests] Enable cluster integration tests (#3961)"

- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/timer_elem_gen.go
This commit tweaks the flush metrics since they weren't quite correct.
A metric for Elements Scanned was previously added, but never used.
Additionally Values Processed should actually be inside the for loop, to
track the total number of values processed (potentially many per
element).
Previously values processed was actually elements scanned, which was
misleading.
Fixes #
```release-note
```
```documentation-note
```
> [agg] Add Elements Scanned metric

- src/metrics/policy/storage_policy.go
The # of StoragePolicies is typically very small, so the overhead of a
clone and then sort is more expensive than just doing an n^2 traversal
looking for all matches.
Fixes #
```release-note
```
```documentation-note
```
> [metrics] Do not sort StoragePolicies for equality

- src/cmd/services/m3coordinator/downsample/downsampler.go
- src/cmd/services/m3coordinator/downsample/downsampler_test.go
- src/cmd/services/m3coordinator/downsample/id_pool_types.go
- src/cmd/services/m3coordinator/downsample/metrics_appender.go
- src/cmd/services/m3coordinator/downsample/metrics_appender_test.go
- src/cmd/services/m3coordinator/downsample/options.go
- src/metrics/filters/filter.go
- src/metrics/filters/filter_benchmark_test.go
- src/metrics/filters/tags_filter.go
- src/metrics/filters/tags_filter_test.go
- src/metrics/integration/match_rule_update_stress_test.go
- src/metrics/matcher/cache/cache.go
- src/metrics/matcher/cache/cache_test.go
- src/metrics/matcher/config.go
- src/metrics/matcher/match.go
- src/metrics/matcher/match_test.go
- src/metrics/matcher/matcher_mock.go
- src/metrics/matcher/namespaces.go
- src/metrics/matcher/namespaces_test.go
- src/metrics/matcher/ruleset.go
- src/metrics/matcher/ruleset_test.go
- src/metrics/metric/id/tag.go
- src/metrics/rules/active_ruleset.go
- src/metrics/rules/active_ruleset_test.go
- src/metrics/rules/mapping.go
- src/metrics/rules/mapping_test.go
- src/metrics/rules/match_result.go
- src/metrics/rules/rollup.go
- src/metrics/rules/rollup_test.go
- src/metrics/rules/ruleset_test.go
This allows reusing the same tag iterator for every computation in
a Match request. Fetching a new tag iterator from the pool for every
computation is unecessary and causes a lot of contention.
Fixes #
```release-note
```
```documentation-note
```
> [matcher] Specify opts per Match Request

- src/cmd/services/m3coordinator/downsample/downsampler_test.go
- src/cmd/services/m3coordinator/downsample/metrics_appender.go
- src/cmd/services/m3coordinator/downsample/metrics_appender_test.go
- src/metrics/filters/filter.go
- src/metrics/filters/filter_benchmark_test.go
- src/metrics/filters/filter_test.go
- src/metrics/filters/tags_filter.go
- src/metrics/filters/tags_filter_test.go
- src/metrics/integration/match_rule_update_stress_test.go
- src/metrics/matcher/cache/cache.go
- src/metrics/matcher/cache/cache_test.go
- src/metrics/matcher/match.go
- src/metrics/matcher/match_test.go
- src/metrics/matcher/matcher_mock.go
- src/metrics/matcher/namespaces.go
- src/metrics/matcher/namespaces_test.go
- src/metrics/matcher/ruleset.go
- src/metrics/matcher/ruleset_test.go
- src/metrics/rules/active_ruleset.go
- src/metrics/rules/active_ruleset_test.go
If there is a problem decoding the tags from the id, we should bubble up
that error instead of returning "no match".
Fixes #
```release-note
```
```documentation-note
```
> [matcher] Return errors from Tag Matchers

- src/dbnode/storage/series_resolver.go
Fixes #
```release-note
```
```documentation-note
```
> Cleanup use of increment/decrement

- scripts/comparator/docker-compose.yml
This works around an apparent regression in latest (v2.32.0+) when
running 'make docker-compatibility-test'.
Upstream issue: https://github.com/prometheus/prometheus/issues/10027
Fixes #
```release-note
```
```documentation-note
```
> [integration] Temporarily pin Prometheus to prom/prometheus:v2.31.2

- src/dbnode/storage/index/mutable_segments.go
Flamegraphs reveal slow linear memory growth over time from the foreground compactor's use of FST builder structs.
These constructs intentionally pool for re-using structs/arrays. However, this pooling can lead to long tail accumulation of sizes of these arrays. Prior to the index active block change, this was a non-issue since on a block rotation compactors for the rotated block were closed. With the long-lived active block, we now periodically GC the old and create a new foreground compactor.
```release-note
```
```documentation-note
```
> [dbnode] Periodically replace foreground compactor

- src/dbnode/storage/bootstrap/bootstrap_mock.go
- src/dbnode/storage/bootstrap/types.go
- src/dbnode/storage/bootstrap/util.go
- src/dbnode/storage/entry.go
- src/dbnode/storage/namespace_bootstrap_data_accumulator.go
- src/dbnode/storage/namespace_bootstrap_data_accumulator_test.go
- src/dbnode/storage/series_resolver.go
- src/dbnode/storage/series_resolver_test.go
- src/dbnode/storage/shard.go
- src/dbnode/storage/shard_test.go
In the bootstrap path, the series resolver can encounter a case where we decrement the same entry more than once, which leads to the invariant error of an entry having < zero read/write ref count.
```release-note
```
```documentation-note
```
> [dbnode] Fix index entry ref over-decrementing when resolved through shard

- src/cmd/services/m3coordinator/downsample/downsampler.go
- src/cmd/services/m3coordinator/downsample/options.go
- src/metrics/integration/match_rule_update_stress_test.go
- src/metrics/matcher/cache/cache.go
- src/metrics/matcher/cache/cache_test.go
- src/metrics/matcher/cache/list_test.go
- src/metrics/matcher/cache/options.go
- src/metrics/matcher/config.go
- src/metrics/matcher/config_test.go
- src/metrics/matcher/match.go
- src/metrics/matcher/match_test.go
- src/metrics/matcher/namespace/resolver.go
- src/metrics/matcher/namespace/test_id.go
- src/metrics/matcher/namespaces.go
- src/metrics/matcher/namespaces_test.go
- src/metrics/matcher/options.go
- src/metrics/matcher/ruleset.go
- src/metrics/matcher/ruleset_test.go
- src/metrics/rules/active_ruleset.go
- src/metrics/rules/active_ruleset_test.go
- src/metrics/rules/ruleset.go
- src/metrics/rules/ruleset_test.go
This consolidates the various Matcher interfaces into a single
interface. The biggest difference was some included a namespace and some
did not. Just change the interface to take a id.ID instead of a []byte
so the namespace can be resolved from the metric ID.
Fixes #
```release-note
```
```documentation-note
```
> [matcher] Consolidate various Matcher interfaces

- src/dbnode/persist/fs/commitlog/commit_log.go
- src/dbnode/persist/fs/commitlog/commit_log_test.go
A couple of tests relied on asserting the size of the commit log queue,
which can be flaky with a background task pulling things off the queue.
This commit adds a test only hook that allows blocking the async task
from running (until ready).
Before:
```
❯ go test ./src/dbnode/persist/fs/commitlog --run=TestCommitLogQueueLength --count=1000
--- FAIL: TestCommitLogQueueLength (0.06s)
Error Trace:    commit_log_test.go:876
Error:		Not equal: 2 (expected)
!= 1 (actual)
--- FAIL: TestCommitLogQueueLength (0.08s)
Error Trace:    commit_log_test.go:876
Error:		Not equal: 5 (expected)
!= 1 (actual)
--- FAIL: TestCommitLogQueueLength (0.09s)
Error Trace:    commit_log_test.go:876
Error:		Not equal: 2 (expected)
!= 1 (actual)
```
After:
```
❯ go test ./src/dbnode/persist/fs/commitlog …
```
> [db] Fix flaky commit log tests

- src/m3ninx/index/segment/mem/concurrent_postings_map.go
- src/m3ninx/postings/roaring/roaring.go
- src/m3ninx/search/searcher/conjunction.go
- src/m3ninx/search/searcher/disjunction.go
Sorting posting lists before doing set operations on them, as described in `TODO` comments.
```release-note
NONE
```
```documentation-note
NONE
```
> [m3ninx] Sort posting lists before making set operations on them

- src/query/storage/m3/storage.go
- src/query/storage/m3/storage_test.go
```release-note
```
```documentation-note
```
> [storage] Add the ability to lookup reserved labels more efficiently.

- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/timer_elem_gen.go
Satisfies my OCD
```release-note
```
```documentation-note
```
> [aggregator] Move metric out of loop

- src/dbnode/client/errors.go
- src/query/api/v1/handler/prometheus/remote/write.go
- src/query/storage/m3/options.go
- src/query/storage/m3/storage.go
- src/query/storage/m3/types.go
- src/x/errors/errors.go
- src/x/errors/errors_test.go
This PR adds an interface for implementing rate limiting between the m3coordinator and the db nodes.
Fixes #
```release-note
no
```
```documentation-note
NONE
```
> [m3coordinator] Add rate limiting interface

- src/query/graphite/graphite/glob.go
- src/query/graphite/graphite/glob_test.go
- src/query/graphite/lexer/lexer.go
- src/query/graphite/lexer/lexer_test.go
Fixes #
```release-note
```
```documentation-note
```
> [graphite] Add ~ as a valid symbol in the lexer

- src/dbnode/client/session.go
- src/dbnode/client/session_aggregate_test.go
- src/dbnode/client/session_fetch_tagged_test.go
- src/dbnode/client/session_fetch_test.go
- src/dbnode/client/session_test.go
- src/dbnode/client/session_write_tagged_test.go
- src/dbnode/client/session_write_test.go
- src/dbnode/storage/database.go
- src/dbnode/storage/types.go
Adds additional metric for `AggregateTiles()` errors.
```release-note
NONE
```
```documentation-note
NONE
```
> [dbnode] Additional metrics for AggregateTiles errors

- CHANGELOG.md
Update changelog before v1.5.
```release-note
NONE
```
```documentation-note
NONE
```
> [changelog] Update changelog for v1.5 release

- src/x/instrument/build.go
- src/x/instrument/build_test.go
**What this PR does / why we need it**: This PR adds a function that logs build information in JSON format instead of plaintext. This is useful if all logs in an application using this library need to be in JSON (for instance if a script is parsing all the logs of that application and converting it to a language specific object like a Python dictionary).
Tested in application 
Fixes #
**Does this PR introduce a user-facing and/or backwards incompatible change?**: 
```release-note
NONE
```
**Does this PR require updating code package or user-facing documentation?**: 
```documentation-note
NONE
```
> [instrument] Add function to log Build Info in JSON

- src/msg/producer/ref_counted.go
Reduces GC overhead for m3msg payloads:
```
/Users/vytenis/go-code/gocode/m3/src/msg/producer/ref_counted.go:33:24: struct with 56 pointer bytes could be 24
```
```release-note
```
```documentation-note
```
> [m3msg] Field alignment fix for RefCountedMessage

- go.mod
- go.sum
Pick up an optimization from https://github.com/uber-go/tally/pull/172
```release-note
```
```documentation-note
```
> [deps] Bump Tally version

- src/aggregator/aggregator/counter_elem_gen.go
- src/aggregator/aggregator/elem_base.go
- src/aggregator/aggregator/elem_base_test.go
- src/aggregator/aggregator/gauge_elem_gen.go
- src/aggregator/aggregator/generic_elem.go
- src/aggregator/aggregator/timer_elem_gen.go
Looks like it was introduced in a refactor #3901 
```release-note
```
```documentation-note
```
> [aggregator] Fix an unintended allocation during element flushing

- site/content/operator/operator.md
Doc tests are failing on master branch because of outdated link:
```
Get "https://coreos.com/operators/": dial tcp: lookup coreos.com on 10.0.0.2:53: no such host --- docs/operator/operator/index.html --> https://coreos.com/operators/
--
  | ========================================================================
  | ✘✘✘ failed in 49.605326045s
  | 1 errors in 96 documents
```
```release-note
```
```documentation-note
```
> [docs] Fix outdated link

- site/.htmltest.yml
- site/content/overview/media.md
- site/static/community/index.html
... and disable www.uber.com validation - URLs are firewall-blocked for bot agents.
Fixes #
```release-note
```
```documentation-note
```
> Fix links in docs

- .buildkite/pipeline.yml
This PR fixes failing "Check for docker and docs builds" test in buildkite pipeline.
Fixes #4274 
No
No
> [buildkite] Fix Docker and Doc build test in buildkite pipeline

- src/aggregator/client/config.go
Add ContextDialer to Aggregator Client Connection Configuration so that it can be passed in via options enabling proxying/tunneling capabilities in the client.
**Does this PR introduce a user-facing and/or backwards incompatible change?**: 
```release-note
NONE
```
```documentation-note
NONE
```
> [m3aggregator-client] Add ContextDialer to Aggregator Client Connection Configuration

- src/metrics/rules/active_ruleset_bench_test.go
This PR adds a relatively basic benchmark for ReverseMatch.
> Add benchmark for ReverseMatch

- src/msg/producer/writer/message_writer.go
This metric will help us track how much time we spend on writes over failed connections. The idea is to be able to debug any issues with utilizing the available connections to the replicas of the consumer services effectively.
Fixes #
**Does this PR introduce a user-facing and/or backwards incompatible change?**: 
```release-note
NONE
```
```documentation-note
NONE
```
> Emit write error latency metric

- src/msg/producer/writer/message_writer.go
Emit write latency metrics to better understand how effectively we load balance across the connections to the consumer services.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```
> Emit write success and write error latency Histograms

- src/dbnode/storage/result_test.go
- src/dbnode/storage/series/series_pool_test.go
- src/dbnode/storage/util_test.go
Fixes #
```release-note
```
```documentation-note
```
> Added unit tests for dbnode/storage package

- src/dbnode/storage/block/block_pool_test.go
- src/dbnode/storage/block/lease_noop_test.go
- src/dbnode/storage/block/metadata_test.go
- src/dbnode/storage/block/options_test.go
- src/dbnode/storage/block/retriever_manager_test.go
- src/dbnode/storage/result_test.go
- src/dbnode/storage/series/series_pool_test.go
- src/dbnode/storage/util_test.go
Fixes #
```release-note
```
```documentation-note
```
> Added unit tests for dbnode/storage/block package

- src/dbnode/storage/block/block_pool_test.go
- src/dbnode/storage/block/lease_noop_test.go
- src/dbnode/storage/block/metadata_test.go
- src/dbnode/storage/block/options_test.go
- src/dbnode/storage/block/retriever_manager_test.go
- src/dbnode/storage/result_test.go
- src/dbnode/storage/series/series_pool_test.go
- src/dbnode/storage/util_test.go
- src/dbnode/x/m3em/convert/conver_test.go
- src/dbnode/x/m3em/node/node_test.go
- src/dbnode/x/tchannel/logger_test.go
- src/dbnode/x/tchannel/options_test.go
Fixes #
```release-note
```
```documentation-note
```
> Added unit tests for dbnode/x package

- src/dbnode/storage/block/block_pool_test.go
- src/dbnode/storage/block/lease_noop_test.go
- src/dbnode/storage/block/metadata_test.go
- src/dbnode/storage/block/options_test.go
- src/dbnode/storage/block/retriever_manager_test.go
- src/dbnode/storage/result_test.go
- src/dbnode/storage/series/series_pool_test.go
- src/dbnode/storage/util_test.go
- src/dbnode/ts/segment_test.go
- src/dbnode/ts/writes/write_batch_pool_test.go
- src/dbnode/x/m3em/convert/conver_test.go
- src/dbnode/x/m3em/node/node_test.go
- src/dbnode/x/tchannel/logger_test.go
- src/dbnode/x/tchannel/options_test.go
Fixes #
```release-note
```
```documentation-note
```
> Added unit tests for dbnode/ts package

- src/dbnode/storage/block/block_pool_test.go
- src/dbnode/storage/block/lease_noop_test.go
- src/dbnode/storage/block/metadata_test.go
- src/dbnode/storage/block/options_test.go
- src/dbnode/storage/block/retriever_manager_test.go
- src/dbnode/storage/result_test.go
- src/dbnode/storage/series/series_pool_test.go
- src/dbnode/storage/util_test.go
- src/dbnode/topology/consistency_level.go
- src/dbnode/topology/consistency_level_test.go
- src/dbnode/topology/dynamic_test.go
- src/dbnode/topology/static_test.go
- src/dbnode/ts/segment_test.go
- src/dbnode/ts/writes/write_batch_pool_test.go
- src/dbnode/x/m3em/convert/conver_test.go
- src/dbnode/x/m3em/node/node_test.go
- src/dbnode/x/tchannel/logger_test.go
- src/dbnode/x/tchannel/options_test.go
Fixes #
```release-note
```
```documentation-note
```
> Added unit tests for dbnode/topology package

- docker/m3aggregator/debug.Dockerfile
- scripts/development/m3_aggregator_local/README.md
- scripts/development/m3_aggregator_local/debug_example.sh
- scripts/development/m3_aggregator_local/start_m3.sh
With this change, we can start up the existing dockerized aggregator cluster in debug mode which will allow you attach the DLV debugger to any running aggregator node by specifying the node's debug port.
For usage details refer to the README.
Fixes #
```release-note
```
```documentation-note
```
> [m3aggregator] Support m3aggregator local debug mode

- src/x/tls/config_manager.go
This PR fixes a data race reliability issues within the m3aggregator client on the TLS connection code path where the tlsConfig is read without taking a read-lock.
Fixes #
```release-note
```
```documentation-note
```
> [m3aggregator-client][TLS conn] Fix data race in TLS config manager
