bootstrap/process.go
x/time/ranges.go
x/time/ranges_test.go

We should use one time range with two subranges instead of two time ranges for bootstrapping. Also removed the logic in the `Ranges` implementation that automatically merges adjacent ranges touching on an endpoint.

Use one time range with two subranges instead of two time ranges for bootstrapping

---

storage/series.go
storage/shard.go
storage/shard_test.go

Currently there is a race condition in the `shard.Tick()` method. Basically it first iterates over all the series, finds out all the ones that are empty, acquires the shard lock, and removes them from the shard. AFAICT there are two issues that could cause a series with recent data to be removed from the shard:
- If a series is written to after it's determined to be empty when we iterate over all series in `Tick`
- Consider the following sequence of actions:
- all datapoints for series "foo" have expired 
- a new datapoint for "foo" comes in, we find the corresponding series by calling `series := shard.series(id)`, but haven't called `series.Write(...)` yet.
- In the meantime, `shard.Tick()` starts, finds "foo" to be an empty series, and removes it from the shard.
- …

Fix race condition when removing series from a shard

---

bootstrap/result.go
bootstrap/result_test.go
integration/disk_flush_test.go
interfaces/m3db/bootstrap.go
mocks/bootstrap.go
storage/database.go

Add `RemoveSeries` to the `ShardResult` interface.
Also add throttling to `Tick()` to reduce locking overhead observed during bootstrapping.

Add RemoveSeries to the ShardResult interface

---

client/session.go
encoding/series_iterator_test.go

Currently there is a race condition in session.go, which I believe was the culprit of the nil pointer issue we were seeing.
Specifically in session.go, let's say `pending` is 2, and two go routines get to line 418 at the same time. Both of them increment `success`, after which one of them proceeds and the other waits (due to context switch etc). If the proceeding goroutine happens to be the one in which `pending` is 0, it'll reach line 435, sees that `success` is 2, and passes `results[:2]` to `iter.Reset`, even though the other goroutine hasn't set `results[1]` to the corresponding iterator yet, which means `results[1]` is still `nil` at this point, which causes a nil pointer exception when we try to dereference `results[1]` in series_iterator.go. 
By moving the logic …

Fix a race condition when fetching data

---

client/options.go
client/session.go
client/session_fetch_test.go
client/session_test.go
client/session_write_test.go
interfaces/m3db/consistency.go
interfaces/m3db/options.go
interfaces/m3db/topology.go
mocks/options.go
topology/host.go
topology/static.go

Add session connect consistency level

---

persist/fs/commitlog/reader.go
persist/fs/commitlog/writer.go

Use digest buffer for read and writing digests in commit log writer/reader

---

client/session.go
client/session_bootstrap_blocks_test.go
client/session_fetch_test.go

Unseal blocks streamed from peers and track processed channel items without spawning a goroutine

---

persist/fs/commitlog/commit_log.go

cc @xichen2020 @cw9 @martin-mao

Use a gauge for the commit log writes queued metric

---

topology/dynamic.go
topology/dynamic_test.go
topology/options.go
topology/types.go

Originally DynamicTopology was waiting on Source.WaitOnInit() channel, changed to simply wait on watch.C()

Refactor dynamic topology

---

storage/block/block.go
storage/block/block_test.go

cc @robskillington @martin-mao 
Creating context objects and returning contexts to pool shows up in cpu profile during fs bootstrapping and takes roughly 20% of the bootstrap CPU.

Lazily get context from pool for database blocks

---

storage/bootstrap.go
storage/bootstrap/bootstrap_mock.go
storage/bootstrap/bootstrapper/fs/options.go
storage/bootstrap/bootstrapper/fs/source.go
storage/bootstrap/bootstrapper/fs/source_test.go
storage/bootstrap/bootstrapper/fs/types.go
storage/bootstrap/options.go
storage/bootstrap/process.go
storage/bootstrap/result.go
storage/bootstrap/types.go
storage/bootstrap_test.go
storage/namespace.go

cc @robskillington @martin-mao 
This reduces the time to bootstrap 48 hours of data from disk on a single node from 30 mins to 3-4 mins.

Optimize filesystem bootstrapper performance

---

persist/fs/commitlog/commit_log.go
persist/fs/commitlog/commit_log_test.go
storage/shard.go
ts/identifier_pool.go
ts/identifier_test.go
ts/types.go

This PR introduces pooling to the ID cloning code that happens when we enqueue writes to the CommitLog. Due to the asynchronous nature of the CommitLog, we cannot reuse the IDs passed from the RPC code and using nested contexts and `DependsOn() ` machinery proved to be prohibitively expensive.

Allocate IDs for CommitLog writes from a pool.

---

persist/fs/commitlog/commit_log.go

cc @kobolog @xichen2020 @martin-mao

Halt on commit log failure instead of using sliding window of 3 failures

---

storage/series/buffer.go
storage/series/buffer_test.go

Exclude nil encoder streams when merging bucket encoders

---

client/client_mock.go
client/errors.go
client/errors_test.go
client/options.go
client/session.go
client/session_fetch_test.go
client/session_write_test.go
client/types.go
glide.lock
glide.yaml

cc @xichen2020 @martin-mao @cw9 @kobolog 
This introduces the concept of "unstrict majority" for reads such that applications can use to always attempt to achieve majority but in the case when all nodes have answered and less than the majority of nodes have responded successfully to go ahead nonetheless and return with a successful result.  
This means that if two nodes are healthy the application will always read from the majority of nodes to ensure data is merged from both healthy nodes to read what you put in at consistency level majority.  It does mean in an extreme failure case of two nodes being unhealthy that the application can continue to serve reads knowingly with no guarentees of serving partial reads.

Add read level consistency of unstrict majority and error metadata

---

client/client_mock.go
client/session.go
client/session_fetch_test.go
client/session_test.go
client/session_write_test.go
client/types.go
x/metrics/test_reporter.go

cc @xichen2020 @martin-mao @cw9 @kobolog 
This change adds metrics for how many nodes are responding with errors.  It also allows for callers of client methods to determine which shard an ID belongs to so they can drill down into which shards are likely affected during times when write/read operations begin failing frequently (likely due to nodes responding with success not meeting consistency requirements).

Add metrics for how many nodes are failing for write/fetch requests

---

storage/series/buffer.go
storage/series/series_test.go

cc @robskillington @martin-mao @kobolog @cw9 
Currently we use timestamps to determine which bucket among all the buffer buckets a read or write belongs to, which in turn determines the order data in different buckets get read. However if we just crossed the block boundary and attempt to read data, the center bucket would have been shifted even though the old buckets have not been reset or drained, leading to out-of-order reads. This is what's causing sudden shadow query match rate drops at the beginning of a new block.
This PR uses `pastMostBucketIdx` to keep track of the oldest bucket so we always read data in the correct order. `pastMostBucketIdx` is updated when a drain or reset happens.

Do not prematurely move center bucket until a drain and reset happens

---

client/client_mock.go
client/rc.go
client/session.go
client/write.go
persist/fs/commitlog/commit_log_mock.go

Client-side runtime and heap profiles demonstrated that almost 50% of all allocations in m3dbingester happen in `session.Write()` due to inferior quality of Go's escape analysis algorithms. Essentially, the algorithm marks any variable that is captured in a lambda as heap-allocated (even if the lambda does not outlive the function scope). In our case, some lambdas in `session.Write()` might outlive the function scope, so almost all local variables are marked as escaping.
This PR explicitly recaptures all escaping variables in a pooled heap-allocated object, effectively reducing the number of heap allocations, live objects and the amount of time required to do a GC scan pass.
Here's a list of TODOs:

Reduce heap escapes in session.Write().

---

client/host_queue.go
client/session.go
encoding/m3tsz/encoder.go
pool/bytes.go
pool/heap.go
pool/heap_test.go
pool/mmap.go
pool/mmap_darwin.go
pool/mmap_linux.go
pool/native.go
pool/native_test.go
pool/object.go
pool/options.go
pool/types.go
storage/options.go
ts/identifier_pool.go
ts/identifier_test.go

This PR introduces a new object pool type which is opaque to the GC. The rationale behind it is that we accumulate an enourmous number of active objects on the GC heap and eventually GC starts to struggle when scanning all of them to determine if any of these objects should be deallocated. In reality, none of these objects would ever be deallocated since they are all pooled, so GC is essentially wasting CPU. The general observation is that background GC pause time is linear with the size of the heap, so reducing its size also reduces the width of CPU consumption peaks when background GC kicks in.
The `NativePool` works around this issue by hiding pooled objects from the GC – from GC's PoV there's only one giant slice of `uint8`s. Each time a new object is requested, a new `interface{}` is …

GC-opaque heap & object pool.

---

ts/identifier.go

This PR fixes `ID` data slice being a reference instead of a copy of the argument in non-pooled `ID` constructor. The result of this is that `Series` constructor would end up having a reference to an incoming `ID` from the client, which in turn comes from a pool, so that when it is returned when request is completed, `Series` would have a dangling reference to a memory that might (and in fact ends up) being reused for other data, e.g. the actual `Block` contents.

Fix ID data not being properly copied on creation

---

ts/identifier.go
ts/identifier_test.go

cc @robskillington @kobolog @martin-mao @cw9 @prateek @ben-lerner 
This PR adds logic to protect ID hashes from data races.
Previously there is a race condition where two goroutines have reference to the same ID object, now if the first goroutine calls `id.Hash()`, it'll realize that the hash hasn't been initialized and starts computing. It'll then proceed to set the hash. However if halfway through setting the hash, the second goroutine also calls `id.Hash()`, it'll see a half-filled hash array and think the hash has been initialized, and return that hash even though it's incomplete. This in turn will trigger a crash in the client code.
The reason why we don't use a RWLock is to save space (4 bytes compared to 24 bytes needed for a RWLock object). This overhead adds up given we have a …

Protect ID hash from data races

---

persist/fs/commitlog/commit_log.go
storage/namespace/metadata.go
storage/options.go
storage/series/options.go
storage/series/series.go
storage/series/types.go
storage/shard.go
storage/types.go
ts/identifier.go
ts/identifier_pool.go
ts/identifier_test.go
ts/segment.go
ts/types.go

This PR changes the `DatabaseSeries` construction to use the ID pool instead of allocating IDs in place out of the GC heap.

Pool DatabaseSeries IDs

---

context/context.go
context/context_test.go
context/pool.go
context/types.go
network/server/tchannelthrift/node/service.go
persist/fs/commitlog/commit_log.go
storage/block/block.go
storage/block/block_test.go
storage/repair.go
storage/repair/metadata.go
storage/repair/types.go
storage/series/buffer.go
storage/series/series.go
ts/identifier.go
ts/identifier_pool.go
ts/identifier_test.go
ts/types.go

This PR refactors `context.Context` to avoid having a pointer to the `dependecies` object. In practice, all Contexts always have it initialized eventually – after a few minutes of runtime – and we have tens of millions of Contexts active. This effectively **reduces the number of active pointers in the GC heap by almost 20%**.
This PR also refactors Closers concept and renames it to Finalizers to avoid a naming ambiguity with regards to `Close()`/`OnClose()` calls. The proposed naming is still not perfect but in my head is less confusing. Up for a discussion. An outstanding issue with this mechanics is the `context.CloserFn` conversion that takes up a considerable portion of total allocations but in essence is a no-op, i.e. an object with `Close()` is effectively is a Closer already, but a …

Refactor context.Context

---

encoding/m3tsz/encoder.go

cc @kobolog @xichen2020
This is to avoid the known case of `Stream()` taking a reference to a bytes slice that is returned to the pool from `ostream.go` when appending bytes with `pool.AppendByte(..., bytesPool)`.
In the future we can build a dependency graph here using contexts to avoid copying, for now this will workaround the current free after use issues.

Avoid references to released bytes when taking a snapshot of an encoder

---

storage/block/block.go

Avoid returning block byte slices to pool from SegmentReader

---

persist/fs/seek.go
ts/identifier.go
ts/identifier_pool.go
ts/types.go

This PR fixes a bug where ID hashes are never cached. It also reverts IDs to be immutable again.

Fixes for IDs

---

storage/series/series.go
storage/series/series_pool.go
storage/shard.go

Avoid passing references to objects across function boundaries which are not meant to be shared.

Avoid false reference sharing

---

client/connection_pool_test.go
client/host_queue.go
client/host_queue_test.go
client/session.go
client/session_test.go
client/session_write_test.go
client/write.go
client/write_test.go
sharding/shardset.go
sharding/shardset_test.go
sharding/types.go

Add support for bootstrapping to the write client. While bootstrapping the initializing and leaving shards count as a single shard towards a quorum, and only if the client successfully writes to both of them.

Write quorum logic during bootstrapping

---

persist/fs/seek.go
ts/identifier.go

This PR introduces a mechanic where ID creation can be avoided in case only an ID hash is required and hash caching would not bring any benefit.

Avoid ID creation where only hash is needed.

---

storage/repair.go

This PR fixes an issue where pooled resources in metadata results are being used after the enclosing object was destroyed.

Fix use-after-free in repair logic.

---

storage/block/result.go
storage/shard.go

This PR fixes a small resource leak in `FetchBlocksMetadata()`: if one of the resulting series metadata objects has no blocks, it is ignored, but its ID is not being returned back to the pool.

Fix a resource leak in FetchBlocksMetadata().

---

client/options.go
client/session.go
client/session_bootstrap_blocks_test.go
client/session_truncate_test.go
client/types.go

This change adds checking and verification to the checksums and sizes when peer bootstrapping.  This means if there is any interference either inside the process itself or during network transfer for the block itself the error is identified and also retried on top of to ensure it does not corrupt nor fatally stall the bootstrapping.
cc @kobolog @xichen2020 @martin-mao @prateek

Add retries and checksum & size verification for peer block streaming

---

client/session.go

The latest block changes its size constantly as it's being written so this doesn't always match the size sent when streaming metadata.
The checksum verification will catch any size mismatch anyhow, so this check is superfluous.  The latest block always has a nil checksum so this issue doesn't affect it.
cc @xichen2020 @kobolog

Remove block size verification for streamed blocks, latest block size changes

---

storage/series/series.go

The ctx registers the reader, so it's Close() call also closes the reader. This makes the explicit deferred Close() calls double frees.
/cc @robskillington @xichen2020 @cw9

Remove double frees in series.mergeBlock()

---

persist/fs/read_write_test.go
persist/fs/write.go

This fixes an issue when head and tail of a `ts.Segment` is passed directly into the second argument of the fs Writer `WriteAll(id ts.ID, data []checked.Bytes)` call.
cc @prateek @xichen2020 @kobolog @ben-lerner

Fix fs writer not being nil aware of the checked bytes array

---

Makefile

- Travis builds have been broken since `glide 0.13.0`, best guess is the issue has to do with: https://github.com/Masterminds/glide/issues/745
- Eg broken builds:  
- https://travis-ci.org/m3db/m3db/builds/194081709
- https://travis-ci.org/m3db/m3cluster/jobs/194083048
- This patch pins the glide install to `0.12.3` which works around the issue for now.
/cc @xichen2020 @robskillington @kobolog @cw9

Fix travis builds by pinning glide to v0.12.3

---

persist/fs/files.go
persist/fs/files_test.go
persist/fs/read_write_test.go
storage/bootstrap/bootstrapper/fs/source.go

tiny changes: 
- Make fs bootstrapper read start from protobuf records within Info file rather than the filename. 
- Add a unit test for Info file read/write coverage
/cc @robskillington @xichen2020

Cleanup persist/fs.ReadInfoFile usage

---

client/session.go
client/session_fetch_bulk_blocks_test.go
generated/thrift/rpc.thrift
generated/thrift/rpc/rpc.go
generated/thrift/rpc/tchan-rpc.go
network/server/tchannelthrift/node/service.go
network/server/tchannelthrift/node/service_test.go
storage/block/result.go
storage/block/result_test.go
storage/block/types.go
storage/database_test.go
storage/series/buffer.go
storage/series/series.go
storage/series/series_test.go
storage/shard_test.go

Right now we verify the checksum of the streamed block from the checksum we retrieve when fetching metadata for all the blocks.  This could change, say perhaps due to a repair in progress that's happening.
Instead we should send the checksum of the block when returning it during the FetchBlocks calls.  Then the client can check that checksum value and compare against the received bytes.

Send the checksum of the block when returning it for streaming

---

client/session.go
client/session_fetch_bulk_blocks_test.go

Observed that some m3db nodes get stuck in "repairing" state, only recovering after a restart. 
Stack trace shows the repairer is stuck waiting on data to come through. 
```
chan receive [1171 minutes] [Created by sync.(*workerPool).Go @ .:0]
client  session.go:2219     (*peerBlocksIter).Next(0xcd0df2a6c0, 0xcace5e1450)
storage repair.go:333       shardRepairer.repairDifferences(0xf8f6e0, #3, 0xf8c800, #6, 0xf8c680, #4, #11, #5, #8, 0, ...)
storage repair.go:91        repairDifferences)-fm(0xf88c80, #7, 0xf8c740, #9, 0x26f85, 0x26f85, 0xf882c0, 0xc8ddb58480, 0xf882c0, 0xc8ddb584e0, ...)
storage repair.go:140       shardRepairer.Repair(0xf8f6e0, #3, 0xf8c800, #6, 0xf8c680, #4, #11, #5, #8, 0xc8675d8b40, ...)
storage <autogenerated>:194 (*shardRepairer).Repair(0xc86733ec00, 0xf888c0, #10, …
```

Investigate deadlock in session.go FetchBlocksFromPeers 

---

Makefile

- Fix an issue @cw9 saw with the all-gen target
- Reuse common.mk glide install target
/cc @cw9 @xichen2020 @robskillington

Fix makefile codegen, reuse .ci/common.mk

---

glide.lock
glide.yaml
persist/fs/commitlog/bitset.go
persist/fs/commitlog/bitset_test.go

cc @robskillington @kobolog @martin-mao @cw9
This PR addresses an inefficiency in how we use bitset in commit logs. The current bitset implementation keeps track of the maximum value it has seen so far and triggers a reallocation if it needs to set a value larger the current max. However it only reallocates space enough to represent the new value, which means in case each reallocation only grows the internal slice the bitset implementation by 1 slot and copies the existing over, causing significant CPU overhead and GC time. As a result, we explicitly control when the reallocation happens and grow the slice explicitly to amortize the allocation cost.

Explicitly control bitset reallocation in commit logs

---

integration/options.go
integration/repair_high_concurrency_test.go
integration/repair_merge_test.go
integration/repair_simple_test.go
integration/setup.go
storage/database.go
storage/options.go
storage/repair.go
storage/types.go

For the m3db in collector, there will be no peers to repair from,
should have an option to just turn repair off and save some resource

Add option to disable repair in database

---

client/session.go
client/session_fetch_test.go

cc @robskillington @cw9 
We use the length of the `errors` slice as the number of errors so we need to append all errors. Besides it provides full context about the errors, which helps debuggability

Append all client-side errors

---

client/write.go
client/write_test.go

Correctly propagate error types in write.go

Ensure client write errors propagate retryable, non-retryable, and bad request errors

---

storage/bootstrap/bootstrapper/fs/source.go
storage/options.go

- Fix a race in fs-bootstrapper
- Fix db block pool initialization in `storage.Options`
/cc @r @xichen2020

Minor fixes in Expire-Blocks-Data-And-Fetch-On-Read

---

client/client_mock.go
client/host_queue.go
client/options.go
client/session.go
client/types.go
client/write.go
client/write_test.go
encoding/encoding_mock.go
integration/fake_cluster_services.go
persist/fs/commitlog/commit_log_mock.go
storage/block/block_mock.go
storage/series/series_mock.go
storage/storage_mock.go
ts/identifier.go

Using `ts.ID` with `checked.Bytes` the allocations become quite heavy at large write volumes.  This change adds an identifier pool to the client session to avoid these ongoing heavy allocations.

Add identifier pool to client session to avoid allocations and potential stack splits

---

digest/fd_digest.go
persist/fs/read.go
persist/fs/seek.go

Using a high shard count with a lot of open seekers the process can use a ton of FDs:
```
250 shards * 24 filesets * (info fd + index fd + digest fd + data fd) = 24,000
```
We can cut down the amount of idle open FDs by 75% by closing them after the initial open.

Keep less open file descriptors for fs Seeker and Reader

---

client/session.go
client/session_fetch_bulk_blocks_test.go

This PR fixes an issue where we incorrectly account for the number of items enqueued when performing delayed enqueuing, causing the queue channel to never be closed and therefore the process to hang indefinitely during peer streaming.

Properly increment number of items when performing delayed enqueuing

---

client/session.go
client/session_fetch_bulk_blocks_test.go

This PR records the errors that happened when fetching blocks from peers so we can better understand why streaming sometimes fails during peer bootstrapping

Add more detailed error messages for peer streaming

---

storage/database.go
storage/options.go
storage/repair.go
storage/types.go

Use a noop repairer if no repair is needed, this is in order to avoid having to pass in a repair option with a valid admin client when the user don't need to repair at all.
A similar commit has been made on dev branch (#239), but cherry-picking that is too hard because that commit also touches several repair integration tests that are not in the master branch
@xichen2020 @robskillington

Add an option to disable repair on database level

---

persist/fs/seek.go
persist/fs/seek_test.go

We were setting decoder to nil after calling seeker.readIndex, which causes future read calls to panic on nil decoder, I don't think it's necessary to set the decoder to nil, let me know your thoughts, will add unit test if this approach looks good.
@xichen2020 @robskillington @martin-mao

Make seeker reusable

---

client/session.go

This PR explicitly formats the errors because the logger doesn't format them properly

Explicitly format the errors

---

client/errors.go
client/session.go
glide.lock
glide.yaml

This PR uses the inbuilt `fmt.Sprintf(...)` to format errors in the session select blocks from peers method.

Format session errors with fmt.Sprintf(..) vs custom fmt

---

client/session.go
client/session_fetch_bulk_blocks_test.go

This PR fixes an issue when removing blocks from peers after we select a block from multiple peer candidate or the peer list has been exhausted. In particular when a block is removed, we used to swap it with the last block and shrink the block list, thereby destroying invariant that the blocks are sorted by their start times. This in turn causes issues because we use the block start times to determine which peers can provide the block and relies on the block order to align the peers. When the block ordering is disrupted, it leads to the error case where a block is only selected from one peer, even though multiple peers are eligible to provide this block.
Also added two test cases to catch the error cases. Both cases are failing against HEAD and …

Maintain block order after peer selection or exhaustion during peer streaming

---

Makefile
client/session.go
client/session_fetch_bulk_blocks_test.go

cc @robskillington @ben-lerner @prateek 
This PR fixes an issue during merging reads where if we failed to read from even one peer, the block will be retried across all peers, tripling the load on the cluster. Additionally, it is considered as a failure if we couldn't  read from any of the peers. This is not what we want, in particular if one peer is malfunctioning, we should still consider it a success if we could read from the other peers.
This PR changes it so that if we manage to read data from at least one of the peers, we consider it a success. In addition, if we fail to read data from a peer during a merging read, the attempt will only be retried on that peer and therefore significantly reducing the number of attempts.

Peer streaming only fails when unable to read data from any peer during merging reads

---

Makefile
client/session.go
client/session_fetch_bulk_blocks_test.go

This PR adds a metric to report final errors (as opposed to intermediate errors we are reporting now) during peer streaming, which is likely to be the high-level metric we care about.
Also converted some logging messages to be debugging messages since they pollute logs with intermediate block fetch errors and we already capture them in reattempt data structures.

Add metrics to report final errors during peer streaming

---

persist/fs/retriever.go

This change avoids checking the namespace path exists when a new retriever is opened.  There is the possibility no flushes have ever occurred and since the seeker already validates before opening the fileset exists at the namespace there is no need to check this before use.
On seek to a block it will validate the namespace, shard and block fileset all exists before trying to open it.

Avoid checking namespace path exists when creating a retriever

---

storage/bootstrap.go
storage/bootstrap_test.go
storage/database.go
storage/database_test.go

This PR addresses an issue where we used to flush data at the end of bootstrapping but not drain the buffer for the most recent 2-hour block, causing them not to be flushed to filesystem and permanent lost due to interaction with block retrieval manager.
This PR temporarily disables data flushing during bootstrapping, a longer-term fix will be in an upcoming PR shortly.

Don't flush data during bootstrapping

---

persist/fs/seek_manager.go
persist/fs/seek_manager_test.go

This PR fixes a bug in `CacheShardIndices` function which incorrectly used the slice indices instead of the slice values as shards, which means only a subset of the bootstrapped shards will be cached during bootstrapping, causing large latency spikes right after bootstrapping as a result of opening seekers that should have been opened. This bug however doesn't affect the functionality of the nodes, only performance.
Also added regression tests that are failing against HEAD but passing with the changes.

Properly cache shard indices during filesystem bootstrapping

---

client/client_mock.go
persist/fs/fs_mock.go
persist/fs/manager.go
persist/types.go
storage/bootstrap.go
storage/bootstrap/bootstrap_mock.go
storage/bootstrap/bootstrapper/base.go
storage/bootstrap/bootstrapper/base_test.go
storage/bootstrap/bootstrapper/commitlog/source.go
storage/bootstrap/bootstrapper/commitlog/source_test.go
storage/bootstrap/bootstrapper/fs/source.go
storage/bootstrap/bootstrapper/fs/source_test.go
storage/bootstrap/bootstrapper/noop.go
storage/bootstrap/bootstrapper/noop_test.go
storage/bootstrap/bootstrapper/peers/options.go
storage/bootstrap/bootstrapper/peers/peers_test.go
storage/bootstrap/bootstrapper/peers/source.go
storage/bootstrap/bootstrapper/peers/source_test.go
storage/bootstrap/bootstrapper/peers/types.go
storage/bootstrap/process.go
storage/bootstrap/run_options.go
storage/bootstrap/types.go
storage/bootstrap_test.go
storage/namespace.go
storage/namespace_test.go
storage/series/series_mock.go
storage/shard.go
storage/shard_test.go
storage/storage_mock.go
storage/types.go

This change makes the first time range that's bootstrapped an incremental bootstrap which means if raw data is being read for blocks it is incrementally flushed and replaced with retrievable blocks in place of the full raw block.
The peers bootstrapper uses these semantics to flush raw block data as it finishes each shard.  This avoids having to hold the entire set of data in memory when doing a full peer stream.

Add incremental bootstrapping for the peers bootstrapper

---

client/client_mock.go
client/fetch_attempt.go
client/fetch_batch.go
client/op_array_pool.go
client/options.go
client/reader_slice_of_slices_iterator.go
client/reader_slice_of_slices_iterator_pool.go
client/session.go
client/types.go
client/write.go
client/write_attempt.go
client/write_test.go
encoding/encoding_mock.go
persist/fs/commitlog/commit_log_mock.go
storage/namespace.go
storage/namespace_test.go
storage/storage_mock.go

This change adds the ability to set a retrier for writes and fetches.  It allows for anyone to use an out of the box retrier from the `github.com/m3db/m3x/retry` package.  It also let's them create their own custom retrier that fits the `Retrier` interface and specify that instead.

Add an inbuilt facility to perform write and fetch retries

---

storage/bootstrap.go
storage/bootstrap_test.go

This PR disables ticking and flushing after bootstrapping because we observed that it added large load on the cluster, causing commit log queues to back up. Instead we'll let the buffer draining and data flushing happen naturally to spread out the load across the cluster. This has shown to reduce the commit log queue spikes significantly.

Disable ticking and flushing after bootstrapping

---

client/session.go
client/session_topology_test.go
integration/cluster_add_one_node_test.go
integration/fake/cluster_services.go
integration/setup.go

This change only connects to new sets of hosts on a topology change and only closes the host queues belonging to hosts no longer in the topology.
This will reduce the large double connection count required for a topology change.  Since the topology can change a lot during shards becoming available one by one this should reduce a lot of overhead.

Open only the delta set of connections on topology change

---

encoding/encoding_mock.go
glide.lock
glide.yaml
persist/fs/persist_manager.go
persist/fs/persist_manager_test.go
persist/persist_mock.go
persist/types.go
storage/bootstrap.go
storage/bootstrap_test.go
storage/cleanup.go
storage/database_test.go
storage/flush.go
storage/fs.go
storage/mediator.go
storage/namespace_test.go
storage/repair.go
storage/repair_test.go
storage/storage_mock.go
storage/types.go

This PR adds logic to report how much time is spent on doing actual work vs. sleeping during flushing so we have better visibility into what's happening during filesystem persistence.

Report timing breakdowns during persistence

---

client/connection_pool.go
client/fetch_batch.go
client/host_queue.go
client/host_queue_test.go
client/op_array_pool.go
client/session.go
client/session_fetch_high_concurrency_test.go
client/session_fetch_test.go

This change fixes the use of the op length when calling the call backs for the operation.  This lead to newly enqueued callbacks in the double used operation to be called, causing more than once callback semantics for a given callback, leading to unexpected results.
It also introduces ownership semantics and checking for fetch batch operations for further safety going forward.
cc @xichen2020 @cw9 @prateek @ben-lerner @kobolog

Fix fetch batch op pooling misuse

---

client/client_mock.go
network/server/tchannelthrift/node/service.go
network/server/tchannelthrift/node/service_test.go
persist/fs/commitlog/commit_log.go
persist/fs/commitlog/commit_log_mock.go
persist/fs/commitlog/commit_log_test.go
persist/fs/fs_mock.go
storage/database.go
storage/database_test.go
storage/options.go
storage/storage_mock.go
storage/types.go
x/counter/frequency_counter.go
x/counter/frequency_counter_test.go
x/counter/options.go

This PR adds load shedding when the server is overloaded. We use the number of "commit log queue full" errors as a proxy to measure whether the server is overwhelmed. In particular, if the number of such errors exceeds a given threshold, the server will return "database is overloaded" back to the client.
Load shedding is currently only applicable to `FetchBlocksMetadata` and `FetchBlocks` calls because they are less performance critical, but may be applied to other methods in the future.

Add load shedding when server is overloaded

---

client/client_mock.go
encoding/encoding_mock.go
integration/fs_bootstrap_test.go
integration/fs_data_expiry_bootstrap_test.go
integration/integration.go
persist/fs/fs_mock.go
storage/bootstrap.go
storage/bootstrap/bootstrap_mock.go
storage/bootstrap/noop.go
storage/bootstrap/process.go
storage/bootstrap/types.go
storage/bootstrap_test.go
storage/mediator_test.go
storage/namespace.go
storage/namespace_test.go
storage/options.go
storage/series/buffer_mock.go
storage/series/series_mock.go
storage/storage_mock.go
storage/types.go

This change reuses the bootstrap process to avoid creating a new process every bootstrap.  During a topology change each shard that changes states causes a bootstrap, this creates churn creating the bootstrap process over and over again for small and sometimes no-op bootstraps (depending if the node is affected by the topology change or not).  This avoids that overhead.
cc @xichen2020 @kobolog @prateek @ben-lerner

Reuse the bootstrap process

---

persist/fs/retriever_test.go
persist/fs/seek_manager.go

This change fixes a minor race to read the 'accessed' field of a seeker by the seeker open/close loop that garbage collects open seekers and opens seekers ahead of time to newly flushed blocks.

Fix minor disk block retrieve seeker 'accessed' race

---

storage/block/block.go
storage/block/options.go
storage/block/types.go

This PR uses a worker pool to limit the concurrency when closing contexts to avoid the goroutine explosion problem during topology changes.

Limit context closing concurrency to avoid goroutine explosion during topology changes

---

retention/options.go
retention/types.go
storage/block/block_mock.go
storage/block/types.go
storage/namespace.go
storage/result.go
storage/series/buffer.go
storage/series/buffer_mock.go
storage/series/buffer_test.go
storage/series/series.go
storage/series/series_test.go
storage/series/types.go
storage/shard.go
storage/shard_test.go

This change adds metrics for wired, unwired, open and made unwired blocks.  This will help us choose correct sizes for our wired blocks LRU list.
There is also a small amount of refactoring to reduce the number of loops when looping series blocks during a tick, and also some further allocation avoidance in the inner loops inside the buffer.
Short expiry is also being removed as it's not used in preference for block data expiry.
cc @xichen2020 @cw9 @kobolog @prateek

Add wired, unwired, open, made unwired block stats

---

.travis.yml
Makefile
client/session_fetch_test.go
client/session_topology_test.go
client/session_write_test.go
glide.lock
glide.yaml
integration/fake/cluster_services.go
integration/integration.go
persist/fs/commitlog/commit_log_test.go
storage/namespace_test.go
x/metrics/test_reporter.go

Upgrading vendored packages to latest versions. 
- Update Makefile to `m3db/ci-scripts` convention 
- Pull latest m3cluster version, corresponding changes
- Pull latest Tally version, corresponding changes

Upgrade m3db vendored packages

---

glide.lock
glide.yaml

Got a bunch of build issues with Travis today. e.g. [failed build](https://travis-ci.org/m3db/m3db/builds/244590286?utm_source=github_status&utm_medium=notification). 
```
[ERROR]	Failed to set version on github.com/m3db/m3em to b2df2120f842f90e734eb8048bcc5b02cd8e199b: Unable to update checked out version
[DEBUG]	Output was: fatal: reference is not a tree: b2df2120f842f90e734eb8048bcc5b02cd8e199b
```
It's complaining about a reference it can't find, but it exists afaict [b2df2120f842f90e734eb8048bcc5b02cd8e199b](https://github.com/m3db/m3em/commit/b2df2120f842f90e734eb8048bcc5b02cd8e199b)
Not sure what's going on. Updating to the latest m3em head seems to resolve this.

Update to latest m3em

---

integration/fake/cluster_services.go
integration/setup.go
storage/cluster/database.go

race condition when shutting down the integration `testSetup` constructs: the testSetups receive lot of redundant kv updates

Address bug in integration tests: testSetup.Close()

---

glide.lock
glide.yaml
integration/commitlog_bootstrap_merge_test.go
integration/commitlog_bootstrap_multi_ns_test.go
integration/commitlog_bootstrap_test.go
integration/disk_cleanup_multi_ns_test.go
integration/disk_flush_multi_ns_test.go
integration/fs_bootstrap_multi_ns_test.go
integration/fs_bootstrap_test.go
integration/options.go
persist/fs/commitlog/commit_log_test.go
persist/fs/commitlog/options.go
storage/cleanup.go
storage/cleanup_prop_test.go
storage/cleanup_test.go
storage/database_test.go
storage/flush.go
storage/flush_test.go
storage/fs.go
storage/namespace.go
storage/namespace_test.go
storage/types.go
storage/util_test.go

Changes:
- Rework commit log cleanup times calculation
- Add property test to ensure we don't cleanup commit logs for un-flushed data
/cc @xichen2020 @robskillington

Rework CommitLog cleanup times

---

integration/commitlog_bootstrap_helpers.go
persist/fs/commitlog/commit_log_test.go
persist/fs/commitlog/types.go
persist/fs/commitlog/writer.go
storage/shard.go

This change passes the current commit log start for a series all the way to the commit log writer using the stack rather than accessing the heap which can be from all different parts of memory (bad CPU cache locality) because the current commit log start entry for a series piece is placed all over the process' heap.
cc @prateek @xichen2020 @martin-mao

Improve the memory locality for the commit log writer

---

integration/commitlog_bootstrap_helpers.go
persist/fs/commitlog/bitset.go
persist/fs/commitlog/bitset_bench_test.go
persist/fs/commitlog/bitset_prop_test.go
persist/fs/commitlog/bitset_test.go
persist/fs/commitlog/commit_log.go
persist/fs/commitlog/commit_log_mock.go
persist/fs/commitlog/commit_log_test.go
persist/fs/commitlog/read_write_prop_test.go
persist/fs/commitlog/types.go
persist/fs/commitlog/writer.go
storage/database.go
storage/namespace.go
storage/shard.go

Reverting the seen series storage for a given commit log to be a bitset.  This bitset implementation is a derivation of the previously used bitset library.  It makes it both a little simpler and also enforces that the growth of the bitset is 2x required length, instead of dependent on the library version.
Even with the changes to fix the memory locality when testing whether a series has already been written to the current commit log, the updating of that data still has very poor memory locality as the source of truth still sits on the heap across a large part of the memory of the process.  The bitset implementation originally set in place allows for much better locality with the caches close to the CPU, even if it is not as clean as keeping the relevant data next to the series themselves. …

Revert the seen series store to a bitset for the commit log

---

storage/block/block.go
storage/block/block_test.go
storage/block/types.go
storage/bootstrap/bootstrapper/commitlog/source.go
storage/bootstrap/bootstrapper/commitlog/source_test.go
storage/bootstrap/result/result.go
storage/bootstrap/result/result_test.go
storage/namespace.go
storage/options.go
storage/series/buffer.go
storage/series/buffer_test.go
storage/series/series.go
storage/series/series_pool.go
storage/series/series_test.go

Observed latest builds deployed to prod were using more memory than previous builds. 
<details>
<summary>(1) master build - total size 118GB</summary>
```
❯ echo top | go tool pprof -inuse_space old-m3dbnode-build old-heap-dump
Entering interactive mode (type "help" for commands)
(pprof) 103.58GB of 117.49GB total (88.15%)
Dropped 1126 nodes (cum <= 0.59GB)
Showing top 10 nodes out of 92 (cum >= 8.75GB)
flat  flat%   sum%        cum   cum%
25.16GB 21.41% 21.41%    25.60GB 21.79%  code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/storage/block.NewDatabaseBlock
19.17GB 16.31% 37.73%    19.17GB 16.31%  code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/storage/block.(*databaseSeriesBlocks).AddBlock
16.31GB 13.88% 51.61%    16.31GB 13.88% …
```

Avoid redundant series pool creation

---

persist/fs/commitlog/options.go
persist/fs/write.go

- Catches an error we were dropping in the `persist/fs.Writer.Close()`
Making a test for this is more involved, opened #348 as a follow up. 

Check checkpoint file writer error

---

tools/dtest/config/config.go
tools/dtest/config/opts.go
tools/dtest/harness/harness.go
tools/dtest/tests/add_down_node_bring_up.go
tools/dtest/tests/add_up_node_remove.go
tools/dtest/tests/dtest.go
tools/dtest/tests/remove_down_node.go
tools/dtest/tests/remove_up_node.go
tools/dtest/tests/replace_down_node.go
tools/dtest/tests/replace_up_node.go
tools/dtest/tests/replace_up_node_remove.go
tools/dtest/tests/replace_up_node_remove_unseeded.go
tools/dtest/tests/seeded_bootstrap.go
tools/dtest/tests/simple_bootstrap.go

This PR fixes existing dtests for namespace isolation changes. Opened #355 to add dtests for new code-paths. 

DTest updates for kv backed namespaces 

---

glide.lock
glide.yaml
persist/fs/write.go

I looked through the commits on the dev branch since the last hash we pinned. A lot of stuff looked like tweaks / bug fixes, but a few things stood out:
1. "Don't close connections on errors": https://github.com/uber/tchannel-go/commit/b9dc4c162aad44e2f01508cf0c6e81032675b4cf
2. "Close connections if the RelayHost returns a ProtocolError": https://github.com/uber/tchannel-go/commit/fef3a3f5eb009e12c7d4446979a425aa2435a760
3. "Set DiffServ (QoS) bit on Outbound connections": https://github.com/uber/tchannel-go/commit/6b8d075c6f47e574ee33513fe1375648fd9a0651

Update to dev branch of tchannel-go

---

storage/bootstrap.go
storage/bootstrap_test.go
storage/cleanup.go
storage/cleanup_prop_test.go
storage/cleanup_test.go
storage/database.go
storage/database_test.go
storage/flush.go
storage/flush_test.go
storage/mediator.go
storage/mediator_test.go
storage/repair.go
storage/storage_mock.go
storage/tick.go
storage/types.go

The test was flaky because after the Database had shutdown, background goroutines would continue running (sometime between the call to Terminate() completing and the actual process exiting) and when they called GetOwnedNamespaces() they would receive an empty list.
The empty list is bad, because when the list of namespaces is empty, the logic in [this function](https://github.com/m3db/m3db/blob/master/storage/cleanup.go#L143) allows M3DB to delete all commitlog files which triggers data loss / test failure.

Fix race condition in Terminate which fixes flaky integration test MixedModeReadWrite

---

integration/disk_flush_helpers.go
persist/fs/clone/cloner.go
persist/fs/clone/cloner_test.go
persist/fs/options.go
persist/fs/read.go
persist/fs/read_test.go
persist/fs/seek.go
persist/fs/seek_manager.go
persist/fs/seek_test.go
persist/fs/types.go
storage/bootstrap/bootstrapper/fs/source.go
storage/bootstrap/bootstrapper/fs/source_test.go
tools/read_index_ids/main/main.go

We were using a single buffer size for readers of all the different file types, despite 3/5 files being significantly smaller than the other two. This PR addresses that.
/cc @robskillington @richardartoul

Rewire fs options to use different sizes for different file types

---

.travis.yml

Changing parallelisation of targets to give unit tests more individual time. E.g. run that drove this – 
/cc @robskillington @richardartoul @jskelcy

Reorder travis targets to better parallelise 

---

Makefile
services/m3dbnode/server/server.go

Removes the typo on the log announcing the listen address.  We also no longer support Go 1.5 builds so dropping VENDOR_ENV flags we set during build for GO15VENDOREXPERIMENT=1.

Fix typo for announcing listen address and remove VENDOR_ENV

---

.metalinter.json
.travis.yml
Makefile
client/session_fetch_bulk_blocks_test.go
glide.lock
glide.yaml
storage/block/block_test.go
storage/bootstrap/bootstrapper/commitlog/source_test.go
storage/bootstrap/bootstrapper/fs/source.go
storage/bootstrap/bootstrapper/fs/source_test.go
storage/series/series_test.go

1) Add a linter to automatically detect usage of map[time.Time]
2) Fix remaining instances of map[time.Time]
3) Fix tests that do the equivalent of time.Time == time.Time
4) Add Go 1.9.2 to travis.yml

Support Go 1.9.X

---

persist/fs/mmap.go
persist/fs/mmap_test.go

Should not break in warning case, otherwise file descriptor pointer doesn't get updated

Make Mmap files handle mmap warning appropriately

---

persist/fs/fs.go
persist/fs/options.go
persist/fs/read.go
persist/fs/seek.go
persist/fs/seek_test.go
persist/fs/types.go

Instead of scanning through data files in the seeker using a file descriptor and the Seek() syscall, we can use mmap instead.

Replace scanning through dataFD (using seek) with an mmap

---

persist/fs/bloom_filter.go
persist/fs/index_lookup.go
persist/fs/read.go
persist/fs/read_test.go
persist/fs/seek.go
services/m3dbnode/server/server.go
topology/dynamic_test.go
x/mmap/mmap.go
x/mmap/mmap_linux.go
x/mmap/mmap_other.go
x/mmap/mmap_test.go

Currently if the host doesn't support HugeTLB then there is a huge amount of log spam warning that HugeTLB is not supported and that we're falling back to not using it. This P.R changes it so that will only happen once at startup.

Refactor mmap into separate xpackage, and check if host supports HugeTLB on startup

---

storage/series/buffer.go
storage/series/series_test.go

time.Truncate does not equal to a simple math division.
For example:
```
now := time.Now()
blockSize := 5 * 24 * time.Hour
fmt.Println(now)
fmt.Println(now.Truncate(blockSize))
fmt.Println(time.Unix(0, now.UnixNano()/int64(blockSize)*int64(blockSize)))
```
returns:
```
2018-01-24 14:29:31.624265 -0500 EST m=+0.003810489
2018-01-21 19:00:00 -0500 EST
2018-01-23 19:00:00 -0500 EST
```
That is because `Truncate returns the result of rounding t down to a multiple of d (since the zero time).`, where as `UnixNano returns t as a Unix time, the number of nanoseconds elapsed since January 1, 1970 UTC.`.
Since the start of each bucket are aligned using Truncate, we need to use Truncate when looking up which bucket to write to.
@xichen2020 @robskillington

Use truncate instead of divide to decide bucket index

---

integration/peers_bootstrap_high_concurrency_test.go
integration/peers_bootstrap_v2_high_concurrency_test.go

re-enabling expensive integration tests in the CI. This does make builds run about 2-3 minutes longer, and flakier.

Enable expensive integration tests in CI

---

client/client.go
client/client_mock.go
client/fetch_attempt.go
client/session.go
client/session_fetch_high_concurrency_test.go
client/session_fetch_test.go
client/session_test.go
client/session_write_test.go
client/types.go
client/write.go
client/write_attempt.go
client/write_test.go
encoding/encoding_mock.go
encoding/series_iterator.go
encoding/series_iterator_pool.go
encoding/series_iterator_test.go
encoding/types.go
generated/thrift/rpc/GoUnusedProtection__.go
generated/thrift/rpc/rpc-consts.go
generated/thrift/rpc/rpc.go
generated/thrift/rpc/tchan-rpc.go
glide.lock
glide.yaml
integration/client.go
integration/config_test.go
integration/write_quorum_test.go
integration/write_read_timezone_test.go
network/server/tchannelthrift/cluster/service.go
network/server/tchannelthrift/node/service.go
storage/series/series_test.go

Changes:
- Changes all API methods in `client/Session` to use `ts.ID` (instead of string) for both namespace and metric ID
- Adds a ts.ID iterator type
/cc @robskillington @richardartoul @jeromefroe

client.Session methods use `ts.ID`

---

network/server/tchannelthrift/node/service.go
x/xpool/pool.go
x/xpool/pool_test.go
x/xpool/types.go

This pool is currently only used by `network/server/tchannelthrift/node/service`, a subsequent PR requires it in a new package (`serialize` which does tag encoding/decoding) too. Doing the extraction in this PR to keep the review small.

Extract checked bytes wrapper pool into `x/xpool`

---

persist/fs/seek_manager_test.go

I think this test fails in C.I sometimes due to high concurrency causing the background loop combined with the 1-second sleep in-between loops to not execute frequently enough.
Cannot reproduce the flaky test locally.

Shorten sleep to make test less flaky

---

storage/shard.go
storage/shard_foreachentry_prop_test.go
storage/shard_race_prop_test.go
storage/shard_test.go

- `tickAndExpire`s usual path of calling `purgeExpired` within the `forEachShardEntry` always skipped cleanup for entries present in the underlying batch; it cleaned up stuff in the lagging if check at the end. 
- A race in `forEachShardEntry`: took a reference to the front of the list but didn't increment the entry's reference count immediately, and released a lock. This was the bug allowing ticks to cleanup data while something else held a reference to it.
- Another race in `forEachShardEntry`: similar to the point above, we held onto an entry pointer with zero reference counts while transitioning from one batch to another, this pointer could get invalidated during a tick and cause panics. 
- Tests to ensure we are guarding against these issues
/cc @robskillington @richardartoul

Fix Race Conditions in Shard

---

.codecov.yml
.excludecoverage
Makefile
README.md
integration/commitlog_bootstrap_merge_test.go
tools/read_ids/main/main.go

- Use `codecov.io` for coverage reports
- Separate big unit tests into their own make target 
- Add coverage reporting for integration tests under separate codecov flags
- Exclude `integration/`, `generated/`, `tools` and a couple of other files from coverage reports
/cc @richardartoul @robskillington

Codecov enhancements

---

client/config.go
environment/config.go
services/m3dbnode/config/config.go
services/m3dbnode/config/config_test.go
services/m3dbnode/main/main_test.go
services/m3dbnode/server/server.go

Enable an embedded etcd cluster to be run in M3DB via configuration.
The KV config can be minimally specified with the service defaulting required arguments, e.g.:
```
config:
service:
env: production
zone: embedded
service: m3db
cacheDir: /var/lib/m3kv
embeddedServer:
initialCluster: host1=http://1.1.1.1:2380,host2=http://1.1.1.2:2380,host3=http://1.1.1.3:2380
```
Or more fully as something like:
```
config:
service:
env: production
zone: embedded
service: m3db
cacheDir: /var/lib/m3kv
etcdClusters: # defaults to endpoints parsed from initialCluster
- zone: embedded
endpoints:
- 1.1.1.1:2379
- 1.1.1.2:2379
- 1.1.1.3:2379
embeddedServer:
listenPeerUrls: # defaults to below
- http://0.0.0.0:2380
listenClientUrls: # defaults to below
- http://0.0.0.0:2379
dir: '/var/lib/etcd' # defaults to …
```

Embedded KV cluster

---

.excludecoverage
TESTING.md
persist/fs/retriever_concurrent_test.go
storage/shard_foreachentry_prop_test.go
storage/shard_race_prop_test.go

Includes following changes:
- Run `+build big` tests without the race detector (https://github.com/m3db/ci-scripts/pull/46)
- Move any `+build big` tests which need race detection to be non-big unit tests
Results:
- Big unit tests finish in 3m instead of 7m+ 
Pending:

Speeding up CI

---

environment/config.go
services/m3dbnode/config/config_test.go
services/m3dbnode/server/server.go

This, along with `namespaceResolutionTimeout`, will enable users to specify a long enough duration for them to set up an M3DB cluster properties so they don't feel rushed to complete the process before the timeout is reached.

Add topologyResolutionTimeout to config

---

client/client_mock.go
client/host_queue_fetch_batch_test.go
client/host_queue_write_batch_test.go
client/host_queue_write_tagged_test.go
client/session.go
client/session_pools.go
client/session_util.go
client/session_write_tagged_test.go
client/types.go
client/write_tagged_test.go
client/write_test.go

Only cosmetic changes included, no functionality has changed in this PR. It's broken off the fetch tagged one to keep it shorter, changes:
- Refactor `session.pools` into it's own struct 
- Break up host queue tests into files per RPC endpoint
- Extract `writeConsistencyAchieved` and `readConsistencyAchieved` methods from `session`

Refactoring client/

---

integration/cluster_add_one_node_test.go
integration/integration.go
storage/cluster/cluster_test.go
storage/cluster/database_test.go
topology/testutil/shard.go
topology/testutil/topology.go

No functionality changes in this PR. It's a refactor to extract some common testing utilities out of a package. 
NB: the coverage drops because this PR is taking code out of a `_test.go` file into a non-test file. in a sub-package Go doesn't calculate coverage for test files so the original code wasn't covered, it's being covered now, and we only do package level coverage checks in the files that use this code, so we loose coverage :(

Extract topology construction utilities

---

client/fetch_state.go
client/fetch_tagged_results_accumulator.go
client/fetch_tagged_results_accumulator_consistency_prop_test.go
client/fetch_tagged_results_accumulator_consistency_test.go
client/fetch_tagged_results_accumulator_merge_test.go
client/fetch_tagged_results_accumulator_misc_test.go
client/fetch_tagged_results_index_iterator.go
client/fetch_tagged_results_index_iterator_test.go

Originally I'd wanted to do all the follow-ups to #530 in this PR, but it's already pretty long, going to start chaining again. 
Changes:
- Re-work consistency calculation. Earlier version treated `LeveUnstrictMajority` the same as `LevelOne`. This PR addresses that.
- Fix an issue in the `Exhaustive` calculation: We needed to know if there was data pending being read if we terminated iteration early. Exposed a new parameter in the `forEachID` type to satisfy this.
- Loads of unit test
NB:
- Subsequent PR for next round of changes: #549

FetchTagged followups [1/n]

---

.metalinter.json
client/consistency_level.go
digest/test_util.go
integration/bootstrap_helpers.go
integration/client.go
integration/commitlog_bootstrap_helpers.go
integration/data.go
integration/disk_cleanup_helpers.go
integration/disk_flush_helpers.go
integration/integration.go
integration/setup.go
persist/fs/commitlog/commit_log.go
persist/fs/msgpack/schema.go
storage/cluster/database.go
storage/repair.go
storage/repair/metadata.go
storage/shard.go
storage/types.go
topology/consistency_level.go
x/xio/null.go

It's only generating noise at this point. `unused` catches all legitimate cases, and handles build tags so has much fewer false positives.

Remove `deadcode` from static-analysis

---

integration/bootstrap_after_buffer_rotation_regression_test.go
integration/bootstrap_before_buffer_rotation_no_tick_regression_test.go
integration/commitlog_bootstrap_helpers.go
integration/commitlog_bootstrap_merge_test.go
integration/commitlog_bootstrap_multi_ns_test.go
integration/commitlog_bootstrap_only_reads_required_files_test.go
integration/commitlog_bootstrap_test.go
integration/mixed_mode_read_write_test.go
persist/fs/commitlog/commit_log_test.go
persist/fs/commitlog/iterator.go
persist/fs/commitlog/reader.go
persist/fs/commitlog/types.go
persist/fs/files.go
persist/fs/files_test.go
persist/fs/inspection.go
persist/fs/inspection_test.go
services/m3dbnode/config/bootstrap.go
storage/block/block_test.go
storage/bootstrap/bootstrapper/commitlog/commit_log.go
storage/bootstrap/bootstrapper/commitlog/source.go
storage/bootstrap/bootstrapper/commitlog/source_prop_test.go
storage/bootstrap/bootstrapper/commitlog/source_test.go
storage/cleanup.go
tools/verify_commitlogs/main/main.go

Adds the concept of a FilesystemInspection which can be used by the commitlog reader to avoid reading commitlog files that were generated since the process started.
Also fixes case where the commitlog bootstrapper could deadlock because it was not returning a resource to a cyclical pool (if a datapoint didn't pass the readSeries predicate we would not return the byte slice to the buffer channel).

Add filesystem inspection and use it in commitlog bootstrapper

---

generated/thrift/rpc.thrift
generated/thrift/rpc/rpc.go
generated/thrift/rpc/tchan-rpc.go
glide.lock
glide.yaml
network/server/tchannelthrift/convert/convert.go
network/server/tchannelthrift/convert/convert_test.go
network/server/tchannelthrift/node/service_test.go
storage/index/block.go

This PR updates the RPC layer to use m3ninx's methods to Marshal and Unmarshal queries instead of representing the queries in m3db itself. It resolves #558.

[index] Use m3ninx methods to serialize and deserialize queries directly

---

src/coordinator/Makefile

This will allow `make m3coordinator` and `make test-internal` to work after cd-ing into `src/coordinator` so that local dev work is easier.

Make coordinator make-able again

---

Makefile
src/cmd/services/m3coordinator/handler/namespace/add_test.go
src/cmd/services/m3coordinator/handler/namespace/delete_test.go
src/cmd/services/m3coordinator/handler/namespace/get_test.go
src/cmd/services/m3coordinator/handler/placement/add_test.go
src/cmd/services/m3coordinator/handler/placement/delete_all_test.go
src/cmd/services/m3coordinator/handler/placement/delete_test.go
src/cmd/services/m3coordinator/handler/placement/get_test.go
src/cmd/services/m3coordinator/handler/placement/init_test.go
src/cmd/services/m3coordinator/handler/prometheus/native/read_test.go

* Have unit tests in `src/cmd/` run again - add two more jobs to CI after landing this PR
1. `NPROC=4 TEST_TIMEOUT_SCALE=20 PACKAGE=github.com/m3db/m3db make test-ci-unit-cmd`
1. `TEST_TIMEOUT_SCALE=20 PACKAGE=github.com/m3db/m3db make test-ci-big-unit-cmd`
* Fix unit tests

Make cmd unit tests run again

---

src/cmd/services/m3dbnode/main/common_test.go
src/cmd/services/m3dbnode/main/main_index_test.go
src/cmd/services/m3dbnode/main/main_test.go
src/dbnode/client/client_mock.go
src/dbnode/client/session.go
src/dbnode/client/types.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source_data_test.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source_index_test.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source_test.go

Fix flaky tests: TestConfig and TestEmbeddedConfig

---

src/dbnode/network/server/tchannelthrift/node/service.go
src/dbnode/network/server/tchannelthrift/node/service_test.go

Reject all read requests when the database is overloaded to protect the node from losing writes due to being overwhelmed by expensive queries.

Implement check for database.IsOverlaoded in all read endpoints

---

README.md

We may arguably be reaching badge overload on the landing README, but we
should link our Gitter room.

[readme] Add Gitter badge

---

glide.lock
glide.yaml
src/dbnode/integration/fake/cluster_services.go
src/dbnode/storage/cluster/database.go
src/dbnode/storage/cluster/database_test.go
src/dbnode/topology/dynamic.go
src/dbnode/topology/topology_mock.go
src/dbnode/topology/types.go

When a cluster comes online it needs to mark a lot of shards as available, this change marks multiple shards as available in one go to help reduce the RPCs required when a new node with a lot of shards comes online.
~Note: still need to update m3cluster to a ref from master once https://github.com/m3db/m3cluster/pull/226 is merged.~

Mark shards available in batch

---

src/dbnode/storage/database_test.go
src/dbnode/storage/index.go
src/dbnode/storage/index/block.go
src/dbnode/storage/index/block_test.go
src/dbnode/storage/index/index_mock.go
src/dbnode/storage/index/types.go
src/dbnode/storage/index_block_test.go
src/dbnode/storage/mediator.go
src/dbnode/storage/namespace.go
src/dbnode/storage/namespace_test.go
src/dbnode/storage/shard.go
src/dbnode/storage/shard_foreachentry_prop_test.go
src/dbnode/storage/shard_race_prop_test.go
src/dbnode/storage/shard_test.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/tick.go
src/dbnode/storage/tick_test.go
src/dbnode/storage/types.go

There is currently a bug in the interaction between the Tick logic and Flush logic. Sequence of events:
1.  Tick() runs, and sometime during the tick the current time reaches the threshold such that calls to shard.removeAnyFlushStatesTooEarly() can remove the flush state for the oldest block.
2. After tick completes, Flush() runs, but its using the pre-stick timestamp in which the oldest block is still valid. It will detect that their is no flush state for the oldest block for some of the shards and attempt to flush it.
3. Shard tries to flush oldest block (which it doesn't have any data for anyways) and fails because the file still exists on disk, but hasn't been cleaned up yet.
To address the issue, I've flowed the tickStart timestamp through the tick logic as well. I additionally …

Use the same timestamp for all Tick() logic as we do for Flush() logic

---

src/dbnode/storage/block/block.go
src/dbnode/storage/block/block_mock.go
src/dbnode/storage/block/types.go
src/dbnode/storage/namespace.go
src/dbnode/storage/result.go
src/dbnode/storage/series/series.go
src/dbnode/storage/series/series_test.go
src/dbnode/storage/series/types.go
src/dbnode/storage/shard.go

This would have been useful to diagnose an issue with a double free in blocks pending merge.

Add metric for blocks pending merge

---

src/dbnode/persist/fs/seek.go

Fix seekers using excess memories by holding onto digest readers after call to Open()

---

src/dbnode/integration/commitlog_bootstrap_helpers.go
src/dbnode/integration/disk_cleanup_helpers.go
src/dbnode/integration/disk_cleanup_multi_ns_test.go
src/dbnode/integration/disk_cleanup_test.go
src/dbnode/integration/fs_commitlog_mixed_mode_read_write_test.go
src/dbnode/integration/fs_commitlog_snapshot_mixed_mode_read_write_prop_test.go
src/dbnode/integration/integration.go
src/dbnode/integration/integration_data_verify.go
src/dbnode/integration/options.go
src/dbnode/integration/setup.go
src/dbnode/persist/fs/commitlog/commit_log_test.go
src/dbnode/persist/fs/commitlog/files.go
src/dbnode/persist/fs/commitlog/files_test.go
src/dbnode/persist/fs/commitlog/iterator.go
src/dbnode/persist/fs/commitlog/reader.go
src/dbnode/persist/fs/commitlog/types.go
src/dbnode/persist/fs/files.go
src/dbnode/persist/fs/files_test.go
src/dbnode/persist/fs/fs.go
src/dbnode/persist/fs/read_write_test.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
src/dbnode/storage/cleanup.go
src/dbnode/storage/cleanup_prop_test.go
src/dbnode/storage/cleanup_test.go
src/dbnode/storage/namespace.go
src/dbnode/storage/namespace_test.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go
src/dbnode/storage/util.go

Delete commit log files that are covered by snapshot files

---

src/dbnode/storage/shard.go
src/dbnode/storage/shard_test.go

Callers already finalize the ID and Tags passed into `newShardEntry(...)` with 1) the block retriever after calling `OnRetrieveBlock(...)` on the `dbShard` callback and 2) the RPC calls `WriteBatchRaw(...)` and `WriteTaggedBatchRaw(...)` at the end of the response by the context registering the finalizer of `*writeBatchPooledReq`.
As such we need to avoid closing/finalizing tags after reading them in `newShardEntry(...)`. 
This change also tests the correct behavior of when and when not to take a ref to the ID passed to `newShardEntry(...)` based on whether it has been marked as not be finalized by checking result of `IsNoFinalize()`.

Ensure tags iter not closed during new shard entry and IDs are copied/ref'd appropriately

---

src/dbnode/storage/database_test.go
src/dbnode/storage/namespace.go
src/dbnode/storage/namespace_test.go
src/dbnode/storage/options.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go

This change avoids potentially returning `false` from `NeedsFlush(...)` for a namespace when max retries have been exceeded for flushing.
There are two faults with this behavior:
1. If `false` returns from `NeedsFlush(...)` due to retries being exceeded for a given block time start, the cleanup code may believe that it was successful and can cleanup commit logs and snapshots - hence losing data on the local node.
1. Naturally if disk was not writeable for some time, we'd ideally like it to just natively recover and flush out blocks that haven't been flushed yet, rather than max retries being hit and then having to restart nodes to have them flush out their data.

Do not cap attempts to flush with retries, should always attempt to write out

---

src/dbnode/client/options.go
src/dbnode/persist/fs/retriever.go

Running `make` fails due to metalinter warnings 
```
src/dbnode/client/options.go:339:2:warning: redundant if ...; err != nil check, just return error instead. (golint)
src/dbnode/persist/fs/retriever.go:161:2:warning: redundant if ...; err != nil check, just return error instead. (golint)
```

Fix meta linter warnings

---

Makefile

This is a small convenience Makefile change which adds a target to grabs all needed git submodules if they haven't already been downloaded (h/t to an approach I've seen elsewhere at Uber). Since we have an include on `$(SELF_DIR)/.ci/common.mk` , it should end up running the first time `make` does, and not after. 
I've tested this out against a fresh clone--`make m3dbnode` works with it, and `make ci-test-unit` mostly works with it (looks like there may be unrelated failures).

Add a target which grabs the .ci submodule in case it wasn't retrieved with git clone --recursive

---

scripts/integration-tests/prometheus/prometheus-integration-test.sh
scripts/integration-tests/prometheus/prometheus.yml
src/query/api/v1/handler/prometheus/remote/test/remote/write.go
src/query/api/v1/handler/prometheus/remote/write_test.go
src/query/api/v1/httpd/handler.go
src/query/api/v1/httpd/handler_test.go
src/query/server/server.go
src/query/server/server_test.go
src/query/storage/local/cluster_test.go
src/query/storage/local/config.go

Since we started spinning up the coordinator role as a dedicated role for the Prometheus integration test we need to change the remote read/write endpoint to the coordinator hostname in the Prometheus configuration file.

Fix docker Prometheus integration tests

---

Makefile
scripts/docs.Dockerfile

The `docs-deploy` target was broken because 1) the version of default
version of git in alpine linux is lightweight and doesn't include
`fast-import`, which `mkdocs` relies on and 2) even if that was the case
the git process in the container couldn't push to github due to lack of
ssh key access. This fixes those issues.

[docs] Fix docs deploy target

---

src/dbnode/integration/commitlog_bootstrap_index_test.go
src/dbnode/integration/fs_bootstrap_index_test.go
src/dbnode/storage/shard_ref_count_test.go
src/m3ninx/index/index_mock.go
src/m3ninx/index/segment/fst/fst_mock.go
src/m3ninx/index/segment/fst/segment.go
src/m3ninx/index/segment/fst/writer_reader_test.go
src/m3ninx/index/segment/mem/reader.go
src/m3ninx/index/segment/mem/reader_test.go
src/m3ninx/index/segment/mem/segment_test.go
src/m3ninx/index/types.go
src/m3ninx/search/query/regexp.go
src/m3ninx/search/searcher/regexp.go
src/m3ninx/search/searcher/regexp_test.go

- Only construct a regexp dfa once per regexp query.

[2/n] Cache regexp fst automata construction

---

src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go

This is causing log spew for newly provisioned clusters.  We don't need this unless we're using debug logs.

Change log level from Info to Debug for no snapshot for shard on bootstrap

---

src/dbnode/integration/disk_cleanup_helpers.go
src/dbnode/persist/fs/commitlog/writer.go
src/dbnode/persist/fs/files.go
src/dbnode/persist/fs/files_test.go
src/dbnode/persist/fs/index_read.go
src/dbnode/persist/fs/index_write.go
src/dbnode/persist/fs/read.go
src/dbnode/persist/fs/read_test.go

Improve speed of DataFileSetExistsAt

---

glide.lock
glide.yaml
src/dbnode/persist/fs/commitlog/commit_log_test.go

- This time ensuring the old sha1 sticks around to avoid old builds having issues

Pull latest upstream vellum

---

src/cmd/services/m3dbnode/config/cache.go
src/dbnode/integration/setup.go
src/dbnode/server/server.go
src/dbnode/storage/block/block.go
src/dbnode/storage/block/block_mock.go
src/dbnode/storage/block/block_test.go
src/dbnode/storage/block/types.go
src/dbnode/storage/block/wired_list.go
src/dbnode/storage/block/wired_list_test.go
src/dbnode/storage/series/series.go
src/dbnode/storage/series_wired_list_interaction_test.go

Fix LRU deadlock + regression test and improve comments / logging

---

src/m3ninx/postings/roaring/roaring.go

All the segments/readers do the necessary locking external to the postings list, so we don't need the locking inside the postings lists on top of that.

Eliminate locking from postings lists

---

src/query/functions/temporal/functions_test.go
src/query/server/server.go

Fixes an issue where m3 can hang if stopped during initialization

Only use signal channel if running embedded

---

src/m3ninx/index/segment/fst/encoding/docs/data.go
src/m3ninx/index/segment/fst/encoding/docs/index.go
src/m3ninx/search/proptest/common_test.go
src/m3ninx/search/proptest/concurrent_test.go

H/T @sboschman for debugging and suggesting the issue. 
Example failure of added test without fix - https://pastebin.com/mtBbNUr6

Fix data race in FST Segment Reads

---

src/dbnode/storage/bootstrap/bootstrapper/peers/source.go

A recent change to the peers bootstrapper source caused it to begin emitting error logs when it should not. The reason it was emitting errors was because normally when we perform an incremental flush, we then remove all the series and blocks from the bootstrap result so that they don't get loaded into memory for no reason (increasing memory pressure).
Now that we've added the concept of a "snapshot" flush, the peers bootstrapper source needs to be aware that it should not remove series/data from memory when its doing an incremental flush that is of type snapshot, because the node is still expecting all that data to be returned for the active block. The existing code detected that the series that it was trying to remove still had data blocks in them, so it emitted an error log instead of …

Refactor peers source to not emit error logs when it should not

---

src/cmd/services/m3dbnode/config/config_test.go
src/dbnode/environment/config.go
src/dbnode/server/server.go
src/dbnode/storage/database.go
src/dbnode/storage/namespace/dynamic.go
src/dbnode/storage/namespace/dynamic_options.go
src/dbnode/storage/namespace/dynamic_test.go
src/dbnode/storage/namespace/namespace_mock.go
src/dbnode/storage/namespace/types.go
src/dbnode/topology/dynamic.go
src/dbnode/topology/dynamic_test.go
src/dbnode/topology/options.go
src/dbnode/topology/topology_mock.go
src/dbnode/topology/types.go

We weren't passing a timeout properly to the ServiceClient so:
```golang
watch, err := services.Watch(opts.ServiceID(), opts.QueryOptions())
```
would hang forever if there was no topology.
In addition, in the case where there is no topology or namespace the error message is cryptic (timeout) when it could be slightly more helpful

Timeout topology watch and return better error messages for missing topology / namespaces

---

integrations/grafana/m3db_dashboard.json

This replaces `.*` regex glob for `$instance` variable with `label_values` query which returns all m3db instances.

Populate instances variable with actual m3db nodes

---

m3db.io/_redirects

Have redirects from our other domains to `m3db.io`. Docs will have to be served via Netlify [branch subdomains](https://www.netlify.com/docs/custom-domains/#branch-subdomains) in a different PR.

Fix _redirects file

---

docker/m3nsch/Dockerfile
src/cmd/services/m3nsch_server/config/config.go
src/cmd/services/m3nsch_server/main/main.go

This updates the config for `m3nsch_server` to allow configuring the db
client. Additionally a `Dockerfile` for m3nsch is included that will by
default start the server but also include the client binary.

[m3nsch] agent: add dbclient to config; dockerize

---

src/query/storage/converter.go
src/query/storage/converter_test.go
src/query/ts/values.go

Before
```
BenchmarkFetchResultToPromResult-8   	      30	  34556216 ns/op	25773633 B/op	 1014479 allocs/op
```
After
```
BenchmarkFetchResultToPromResult-8   	     100	  10563444 ns/op	25368543 B/op	    4443 allocs/op
```

Significantly improve performance of FetchResultToPromResult and helper functions

---

CHANGELOG.md
DEVELOPER.md

With a backfill on the changelog, we should aim to add notes for unreleased versions as they are added to the stack of pending release changes.

Backfill changelog and add developers guide for updating CHANGELOG.md

---

src/query/api/v1/handler/placement/add.go
src/query/api/v1/handler/placement/add_test.go
src/query/api/v1/handler/placement/common.go
src/query/api/v1/handler/placement/common_test.go
src/query/api/v1/handler/placement/delete.go
src/query/api/v1/handler/placement/delete_test.go

I realized that even with the change to make adds "safe" by default,
there could still be a race. That is, the placement that all shards were
validated as AVAILABLE for could not be the present placement by the
time `AddInstances` was called.
This changes placement adds/removes to use the placement algorithm to
construct the new placement, and perform a `CheckAndSet` with the old
placement.
Additionally, this implements "safe" adds in the delete handler as well.

[coordinator] placement: add+remove fully atomic

---

src/m3em/agent/agent_test.go

`m3em` isn't actively used so I don't feel bad about skipping a test in it for CI stability.

Skip flaky test: TestClientReconnect

---

src/cmd/services/m3coordinator/server/m3msg/config.go
src/cmd/services/m3coordinator/server/m3msg/handler.go
src/cmd/services/m3coordinator/server/m3msg/handler_test.go
src/cmd/services/m3coordinator/server/m3msg/types.go

Part 1 for the ingestion change in M3coordinator. 
This diff adds a m3msg server which decodes traffic from m3msg consumer into metrics and takes in a WriteFn to write those metrics.
Part 2 will be implementing a storage based ingester to fulfill the WriteFn.

Add a m3msg server for ingestion

---

.excludemetalint

Skipping file causing CI flakiness. Can revert once https://github.com/m3db/build-tools/issues/27 is addressed

Skip flaky importorder bug

---

.buildkite/hooks/pre-command

This is the nit of all nits, but the BK separator is `---` not `----`,
and using `----` causes sections to not be pretty-separated.

[ci] fix buildkite output separator

---

scripts/development/m3_stack/docker-compose.yml

We were previously calling the grafana image in the docker-compose file the same as the canonical image which meant that docker-compose would not build it and default graphs / sources would not be copied into the image. Renaming it forces the image to be built at least once so users of the command always get default dashboards / sources.

Rename grafana image in docker-compose to force build at least once

---

src/cmd/services/m3dbnode/config/bootstrap.go
src/cmd/services/m3dbnode/config/config_test.go
src/dbnode/integration/bootstrap_after_buffer_rotation_regression_test.go
src/dbnode/integration/bootstrap_before_buffer_rotation_no_tick_regression_test.go
src/dbnode/integration/bootstrap_helpers.go
src/dbnode/integration/commitlog_bootstrap_merge_test.go
src/dbnode/integration/fs_commitlog_mixed_mode_read_write_test.go
src/dbnode/persist/fs/commitlog/commit_log_test.go
src/dbnode/persist/fs/commitlog/files.go
src/dbnode/persist/fs/commitlog/files_test.go
src/dbnode/persist/fs/commitlog/iterator.go
src/dbnode/persist/fs/commitlog/read_write_prop_test.go
src/dbnode/persist/fs/commitlog/types.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/options.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_data_test.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_index_test.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_prop_test.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/types.go
src/dbnode/storage/bootstrap/bootstrapper/peers/options.go
src/dbnode/storage/bootstrap/bootstrapper/peers/peers_test.go
src/dbnode/storage/cleanup.go
src/dbnode/storage/cleanup_prop_test.go
src/dbnode/storage/cleanup_test.go
src/dbnode/storage/util.go

Handle commit log files with corrupt info headers during cleanup and bootstrap

---

src/query/api/v1/handler/prometheus/native/read_test.go
src/query/api/v1/handler/prometheus/remote/read_test.go
src/query/api/v1/httpd/handler_test.go
src/query/executor/engine.go
src/query/executor/engine_test.go
src/query/executor/request.go
src/query/server/server.go

Tested with following targets:
- targets: ['localhost:9090','docker.for.mac.localhost:7203']

Add metrics for engine to track all processing.

---

docs/m3db/architecture/engine.md
src/dbnode/integration/disk_cleanup_multi_ns_test.go
src/dbnode/integration/disk_cleanup_test.go
src/dbnode/persist/fs/commitlog/commit_log.go
src/dbnode/persist/fs/commitlog/commit_log_conc_test.go
src/dbnode/persist/fs/commitlog/commit_log_mock.go
src/dbnode/persist/fs/commitlog/commit_log_test.go
src/dbnode/persist/fs/commitlog/read_write_prop_test.go
src/dbnode/persist/fs/commitlog/types.go
src/dbnode/persist/fs/commitlog/writer.go
src/dbnode/storage/cleanup.go
src/dbnode/storage/cleanup_prop_test.go
src/dbnode/storage/cleanup_test.go
src/dbnode/storage/database.go
src/dbnode/storage/fs.go
src/dbnode/storage/fs_test.go
src/dbnode/storage/mediator.go
src/dbnode/storage/mediator_test.go

This P.R allows us to distinguish between corrupt commitlogs and active commitlogs (which sometimes look corrupt because the header info hasn't been flushed yet), allowing us to delete corrupt commitlog files safely.

Add ActiveLogs() API to commitlog and use it in the CleanupManager

---

src/query/README.md
src/query/config/m3query-dev-etcd.yml

Another small tweak--I found that when I got panics running locally, the stack trace was huge due to the large number of goroutines we had spawned. Most of them were from the `readWorkerPool` and `writeWorkerPool` in query, since default config gives you 4096 threads. I added config to the local query config to shrink this down to a starting size of 10, which is much more manageable.
Let me know if I should propagate that through some of the other config files as well.

Use a default pool size of 10 in development for query

---

src/cmd/services/m3query/config/config.go
src/cmd/services/m3query/config/config_test.go
src/cmd/services/m3query/config/testdata/sample_config.yml
src/query/api/v1/handler/prometheus/native/read.go
src/query/api/v1/handler/prometheus/native/read_test.go
src/query/api/v1/httpd/handler.go
src/query/config/config_test.go

The approach here is taken directly from prom code; we basically want to prevent queries which go from the beginning of time at a nanosecond step size.
The limit is configured by `limits` in query config:
```
limits:
maxComputedDatapoints: 20000
```
[edit] It defaults to being disabled, so as to not disrupt existing queries. 
I've also added some basic tests for config, just to make sure my validation was working.
Let me know if you want any code anywhere different than where I have it; I did what seemed convenient and in the existing style, but I'm totally open to moving things.

Add a very basic limit on number of resolved datapoints

---

src/query/models/matcher.go
src/query/models/matcher_test.go

The teeniest of fixes here. I noticed that the plan printed by debug=true included some not very useful byte arrays. Turns out that's because `Matcher.String()` was defined on `*Matcher`, and we always use `Matcher`.
Before:
```
2018-10-18T15:03:54.267-0400	INFO	logical plan	{"rqID": "67a88734-6c10-4f09-991a-6f94306c7fb4", "plan": "Plan steps: map[0:Parents: [], Children: [], Transform: ID: 0, Op: type: fetch. name: prometheus_tsdb_wal_corruptions_total, range: 0s, offset: 0s, matchers: [{= [106 111 98] [112 114 111 109 101 116 104 101 117 115] <nil>} {= [95 95 110 97 109 101 95 95] [112 114 111 109 101 116 104 101 117 115 95 116 115 100 98 95 119 97 108 95 99 111 114 114 117 112 116 105 111 110 115 95 116 111 116 97 108] <nil>}]], Pipeline: [0]"}
```
After:
``` …
```

Fix Matcher string method to use non-pointer receiver

---

src/aggregator/client/queue.go
src/aggregator/client/writer.go
src/aggregator/client/writer_mgr_test.go
src/aggregator/client/writer_test.go

Currently closing a writer is blocked on draining the queue within it. When the size of the queue is large, it could take a long time for it to drain. Which would cause the writer close to take a long time.
On the other hand the writer manager needs to close the writer with a lock when an instance is removed from the placement. A delayed writer close could block writes from acquiring the lock.
This changes changes the `RemoveInstance` behavior to synchronously remove the writer from its map and calls `writer.Close()` asynchronously.

[Aggregator Client] Drain queue asynchronously when closing writer

---

src/dbnode/client/fetch_state_leakcheckpool_gen_test.go
src/dbnode/client/fetch_tagged_attempt_leakcheckpool_gen_test.go
src/dbnode/client/fetch_tagged_op_leakcheckpool_gen_test.go
src/dbnode/storage/block/block.go
src/dbnode/storage/block/block_test.go

Prior to being [removing the CacheAllMetadata policy](https://github.com/m3db/m3/pull/1110/files#diff-8605e9ad35bdfdb5c194ed171978939dL206), this used to be set in the `OnRetrieveBlock` function. Properly set it here.

Set wasRetrievedFromDisk properly

---

glide.lock
glide.yaml
src/query/api/v1/handler/prometheus/remote/write.go
src/query/models/matcher_test.go
src/query/storage/m3/cluster.go
src/query/storage/m3/multi_fetch_result.go
src/query/storage/m3/storage.go

Previously, was returning the concatenated error messages for all
errors seen, which got very noisy if a single failure was causing each
request to error. Now returns only last error if any seen.

Reduce noise from multi errors by returning last

---

Makefile

If for some reason `install-vendor` step fails, vendor dir will remain and builds will fail unless one manually removes it. Running `make clean` should remove all artifacts created for the build.

make clean should remove vendor dir, too

---

src/query/api/v1/httpd/handler.go

The logging currently kicks in with force if there's any issues with m3, but we can get all the information from `prometheus_remote_storage_sent_batch_duration_seconds_bucket` in prometheus, so removing the loggging cuts down on noise and potential side effects in case of issues.

remove time logging on the prom/remote/write endpoint

---

.buildkite/pipeline.yml
.buildkite/scripts/Dockerfile
.buildkite/scripts/adhoc_build.sh
docker-compose.yml

Our dockerized CI tests currently run based off the `ci-base` image,
which is just a golang image with our directory in it. This is somewhat
inefficient as we have to bump another docker image if we want to change
the test harness.
This modifies the buildkite builds to use a similar pattern we've used
in other repos, which is to base directly off the golang image and add
the workdir via docker-compose configs.
Additionally, a script is included for creating buildkite builds in an
adhoc manner. The URL referenced in the script is publicly
reconstructable just by looking at any PR on the monorepo, so we're not
exposing any info.

[ci] remove dependency on docker CI base image

---

src/query/server/server.go

We were previously not setting the cluster client for the coordinator
when collocated with the dbnode.

[coordinator] set cluster client w/ dbnode colo

---

src/query/server/server_test.go

I noticed that my tests were failing locally while I had a query instance running, and tracked it down to this. Pretty small; just switches the port to a different fixed port. Random ephemeral would be ideal, but that would require passing a `net.Listener` through to `Run` as described [here](https://stackoverflow.com/questions/43424787/how-to-use-next-available-port-in-http-listenandserve), and it didn't seem worth it.

Use a random test port in server_test.go

---

src/msg/producer/producer_mock.go
src/msg/producer/types.go
src/msg/producer/writer/writer.go
src/msg/producer/writer/writer_test.go

Expose the total number of shards of the topic the producer is producing to. So users of the producer interface could shard traffic accordingly.

Expose number of shards in producer

---

src/query/api/v1/handler/prometheus/native/complete_tags.go
src/query/api/v1/handler/prometheus/native/read.go
src/query/api/v1/handler/prometheus/remote/tag_values.go
src/query/api/v1/httpd/handler.go
src/query/api/v1/httpd/handler_test.go
src/query/server/server.go

Fixes #1135 . Currently, we set CORS headers manually in each request. This has middleware do that for us instead. I used etcd's implementation of this (github.com/coreos/etcd/pkg/cors), since it's good enough, simple, and already a dependency, but I could also switch to a dedicated package (e.g. [github.com/rs/cors](https://github.com/rs/cors) which would support a bit more config). 
No config right now; let me know if you want it. This middleware sets:
```
Access-Control-Allow-Headers: accept, content-type, authorization
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: *
```

Use CORS middleware (etcd's implementation) instead of setting CORS headers on all requests

---

specs/README.md
specs/dbnode/snapshots/SnapshotsSpec.tla

This is the first TLA+ specification for M3DB and is meant to be a relatively simple piece that we can use as a basis for introducing additional specifications. This spec models how M3DB acks writes by storing them in the commitlog, as well as the background commit log rotation / snapshotting (including snapshot failures) / cleanup process at a very high level. 
Running TLC with the following parameters:
```
numWrites <- 40
minNumWritesForPersistence <- 20
numClients <- 3
minNumWritesForCleanup <- 20
```
and requiring the following invariants be checked at each step:
```
AllAckedWritesAreBootstrappable
```
results in TLC finding no invariant violations along with the following model checking results

Add TLA+ specification for commitlog / snapshotting / rotation / cleanup logic.

---

src/cluster/services/services.go

Debugging what keys are missing when watches time out is difficult.

[cluster] placement: better error message

---

src/dbnode/storage/database.go
src/dbnode/storage/database_test.go

Fixes a bug introduced in #1157 where we ignore the WritesToCommitlog flag on the namespace configuration

Honor namespace-level "WritesToCommitlog" configuration

---

src/dbnode/persist/fs/commitlog/commit_log.go
src/dbnode/server/server.go
src/dbnode/storage/database.go

Auto-calculate reasonable values for WriteBatchPoolSize and return batches to the pool even if commitlog queue is full

---

scripts/development/m3_stack/start_m3.sh
scripts/docker-integration-tests/prometheus/test.sh
scripts/docker-integration-tests/simple/test.sh
src/dbnode/client/errors.go
src/dbnode/integration/cluster_add_one_node_test.go
src/dbnode/integration/options.go
src/dbnode/integration/setup.go
src/dbnode/runtime/runtime_options.go
src/dbnode/storage/bootstrap.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source_data_test.go
src/dbnode/storage/cluster/database.go
src/dbnode/storage/cluster/database_test.go
src/dbnode/storage/database.go
src/dbnode/storage/database_test.go
src/dbnode/storage/flush.go
src/dbnode/storage/flush_test.go
src/dbnode/storage/namespace.go
src/dbnode/storage/namespace/options.go
src/dbnode/storage/namespace_test.go
src/dbnode/storage/options.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go
src/query/api/v1/handler/database/create_test.go
src/query/api/v1/handler/namespace/add_test.go
src/query/api/v1/handler/namespace/get_test.go

Previously, M3DB implemented durability during topology changes by forcing the peers bootstrapper to write out a snapshot file for any *mutable* data that was streamed in from a peer. This ensured that if the node crashed after the topology change, the commitlog bootstrapper could restore all the data the node was expected to have.
We're currently trying to move M3DB to a model where every set of snapshot files indicates that all the data that had been received by the node up until the beginning of the snapshot could be recovered from a combination of the data files, snapshot files, and commitlog files. The existing implementation clashes with that idea because it was writing out individual snapshot files that were not tied to any large snapshot process.
As a result, this P.R modifies …

Improve how M3DB handles data durability during topology changes

---

src/query/api/v1/handler/prometheus/validator/handler.go

I noticed this after I rebased; seems like we're using an instance field when we don't necessarily need to, exposing us to an (admittedly unlikely) race condition. I just went ahead and fixed it since the change was so small.

Fix small race condition in debug handler

---

src/m3ninx/index/segment/mem/options.go

Change pooling options for index array pool to prevent (almost) unbounded growth over time

---

src/query/api/v1/handler/prometheus/native/common.go
src/query/executor/state.go
src/query/executor/transform/types.go
src/query/functions/fetch.go
src/query/models/params.go
src/query/plan/physical.go
src/query/storage/m3/storage.go
src/query/storage/types.go

There seem to be issues with the new iterator expansion logic for very small datasets. This hides that logic behind a `iters=true` flag on the query until that issue is resolved

[query] Hide m3 iterator expansion behind a query flag 

---

.dockerignore
Makefile
docker/grafana/Dockerfile
docker/grafana/dashboards.yaml
docker/grafana/datasource.yaml
tools.json

This pins mockgen that's used for generating mocks to a specific version installed by retool.  This will ensure mock generation does not break due to updates of mockgen without an explicit update.

Enforce mockgen is installed at retool installed version

---

src/dbnode/server/limits.go
src/dbnode/server/server.go
src/x/os/limits_linux.go
src/x/os/limits_other.go

When developing/running locally, validate process limits check would spin constantly and spit out `invalid configuration found [unable to determine process limits: unable to determine process limits on non-linux os], refer to linked documentation for more information [{url https://m3db.github.io/m3/operational_guide/kernel_configuration}]` without ever resolving, since that path will always fail on other systems.
This adds a check to see if the limit check is possible on the current OS, and if it's not will warn once and stop checking.

Reduce process limit validator spam when running on non-Linux OS

---

src/m3ninx/search/query/conjunction.go
src/m3ninx/search/query/util.go
src/m3ninx/search/query/util_test.go

Previously, ConjunctionQuery.String() would only print out actual queries, but not show any negated.

[m3x] Change conjunction query String() method to add any negated queries

---

src/query/storage/m3/storage.go
src/query/ts/m3db/convert.go
src/query/ts/m3db/convert_test.go
src/query/ts/m3db/encoded_block_iterator.go
src/query/ts/m3db/encoded_block_iterator_builder.go
src/query/ts/m3db/encoded_series_iterator.go
src/query/ts/m3db/encoded_step_iterator.go
src/query/ts/m3db/options.go
src/query/ts/m3db/types.go

Refactors the list of args taken in by encoded block conversion to avoid long argument lists and consolidate all option permutations into one object.

[query] Refactor encoded block conversion to use options

---

src/cmd/services/m3query/config/config.go
src/query/api/v1/handler/prometheus/common.go
src/query/api/v1/handler/prometheus/remote/tag_values.go
src/query/api/v1/handler/search_test.go
src/query/errors/handler.go
src/query/policy/filter/storage.go
src/query/server/server.go
src/query/storage/fanout/storage_test.go
src/query/storage/index.go
src/query/storage/index_test.go
src/query/storage/m3/multi_fetch_tags_result.go
src/query/storage/m3/storage.go
src/query/storage/m3/storage_test.go
src/query/test/seriesiter/mock_iter.go

Remote storage was hard coded to be the only storage allowed to return complete tags results, this sets it to local only by default and allows overriding any of the read/write/complete tags filter in config.
It also adds CompleteTags for M3 storage so it can be used for local storage CompleteTags queries.  This is for now just aggregating results of a search query, but in the future the DB could natively aggregate and return specifically just the unique tag values over the wire to the query server.

Add CompleteTags method for M3 storage and by default enable it

---

integrations/systemd/m3dbnode.service

The correct option name is RestartSec and not RestartSecs.

Fix Typo in m3dbnode.service.

---

scripts/development/m3_stack/start_m3.sh
scripts/docker-integration-tests/prometheus/test.sh
scripts/docker-integration-tests/simple/test.sh
src/dbnode/integration/fetch_tagged_quorum_test.go
src/dbnode/integration/setup.go
src/dbnode/integration/write_quorum_test.go
src/dbnode/integration/write_tagged_quorum_test.go
src/dbnode/network/server/tchannelthrift/node/service.go
src/dbnode/network/server/tchannelthrift/node/service_test.go
src/dbnode/storage/cluster/database.go
src/dbnode/storage/cluster/database_test.go
src/dbnode/storage/database.go
src/dbnode/storage/flush.go

The existing health checks use IsBootstrapped() to determine if a node is healthy and bootstrapped which is fine in the normal case, but in the situation where a topology change has occurred this is problematic.
The reason its problematic in that scenario is that after a topology change, as a result of #1183 the node will not mark its shards as available until a snapshot has occurred. This is an issue for our automated tooling which will assume that once a node is "healthy" it can proceed with adding more nodes because we don't want the tooling to proceed until the previous node has marked all its shards as available otherwise we can end up in weird shards state (I.E R.F = 3 but we have 2 shard states AVAILABLE, 1 LEAVING, and 2 Initializing and 2/5 will not achieve quorum so writes / …

Use IsBootstrappedAndDurable instead of IsBootstrapped in health checks

---

src/query/api/v1/handler/namespace/add.go
src/query/api/v1/handler/namespace/common.go
src/query/api/v1/handler/namespace/delete.go
src/query/api/v1/handler/namespace/get.go

Our documentation (and all of our other APIs) are scoped by service, but namespace APIs weren't scoped by service properly. This P.R scopes them by service, but continues to register the old APIs for backwards compatibility. 
Addresses #1274

Change namespace URLs to be scoped by service

---

src/query/api/v1/handler/prometheus/native/common.go
src/query/api/v1/handler/prometheus/native/common_test.go
src/query/executor/state.go
src/query/executor/transform/types.go
src/query/functions/fetch.go
src/query/models/block_type.go
src/query/models/block_type_test.go
src/query/models/params.go
src/query/plan/physical.go
src/query/storage/m3/storage.go
src/query/storage/types.go
src/query/ts/m3db/convert.go
src/query/ts/m3db/convert_test.go
src/query/ts/m3db/encoded_block_iterator_builder.go
src/query/ts/m3db/encoded_series_iterator_test.go
src/query/ts/m3db/encoded_step_iterator_test.go
src/query/ts/m3db/encoded_unconsolidated_iterator_test.go

Adds tests and fills in blocks in sparse series with empty iterators, allowing downstream functions to work correctly.

[query] splits series into blocks, filling in missing blocks

---

scripts/development/m3_stack/m3aggregator.yml
scripts/development/m3_stack/m3coordinator.yml
src/aggregator/aggregator/handler/config.go
src/aggregator/aggregator/handler/protobuf.go
src/aggregator/aggregator/handler/protobuf_test.go
src/aggregator/aggregator/handler/writer/options.go
src/aggregator/aggregator/handler/writer/protobuf.go
src/aggregator/aggregator/handler/writer/protobuf_test.go
src/aggregator/aggregator/handler/writer/sharded.go
src/aggregator/aggregator/handler/writer/sharded_test.go
src/cmd/services/m3coordinator/server/m3msg/protobuf_handler.go
src/metrics/encoding/protobuf/aggregated_encoder.go
src/metrics/encoding/protobuf/aggregated_roundtrip_test.go

New flush handler to flush aggregated metrics in protobuf
Placeholder for config changes, could turn on sending/receiving metrics in protobuf by toggling the config in the future, need to coordinate external users.

[M3agg] Add flush handler to flush aggregated metrics in protobuf

---

docs/operational_guide/kernel_configuration.md
src/dbnode/server/limits.go

A lot of users run into this issue, there is no cost to using a higher value, and 3 million is what we run in production.

Increase recommended max_map_count to 3 million

---

specs/dbnode/flush/FlushVersion.tla

Add TLA+ specification for future M3DB version-based flushing

---

src/query/functions/temporal/base.go
src/query/functions/temporal/base_test.go

I ran into this bug locally today--temporal functions don't properly propagate series tags (thanks to @arnikola for suggesting this as the bug!).
For instance, given series:
```
coordinator_engine_datapoints{type="fetched"} 1386
coordinator_engine_datapoints{type="generated"} 104
```
a query like `increase(coordinator_engine_datapoints[5s])` will return
```
{
"__name__": "coordinator_engine_datapoints",
"instance": "host.docker.internal:7203",
"job": "coordinator",
"role": "remote"
}
{
"__name__": "coordinator_engine_datapoints",
"instance": "host.docker.internal:7203",
"job": "coordinator",
"role": "remote"
}
```
dropping tags. Query the same range without `increase` gives all tags, as expected.
Fix is simple; we weren't copying tags into the new block's `SeriesMetas`; now we do.

Fix tag propagation for temporal functions

---

src/query/api/v1/handler/json/write.go
src/query/api/v1/handler/json/write_test.go

Unmarshaling error was not being returned correctly, which could cause null pointer references later on.

Correctly return error for failed json unmarshal

---

Makefile
scripts/development/m3_stack/m3coordinator.yml
scripts/docker-integration-tests/carbon/m3coordinator.yml
scripts/docker-integration-tests/carbon/test.sh
scripts/docker-integration-tests/common.sh
src/cmd/services/m3query/config/config.go
src/query/server/server.go
src/query/server/server_test.go

This also updates the carbon ingester configuration to match the default M3 ingester config where if the config is not nil, then it is used, otherwise it's not. This removes the enabled field which was rather different to how the M3 ingester config's presence or absence defines whether to use it or not.

Enable and fix carbon and graphite docker integration test

---

NOTICES.txt
src/query/api/v1/httpd/handler.go
src/x/net/http/cors/cors.go
src/x/net/http/cors/cors_test.go

A small hack I did caught up to me--etcd had a reasonable cors middleware implementation, which I added to m3query. They later removed the package (not surprisingly--it was a random thing to expose). This causes `glide up` to fail. To fix this, I copied in the package to `x/net/http`. We could instead add a different dependency (e.g. https://github.com/rs/cors); let me know your preference on that. I mostly went with the copy route because the package is quite small and it didn't seem worth the added dep.

Copy cors from etcd, since they eliminated the package

---

docs/operational_guide/placement_configuration.md
src/cmd/services/m3dbnode/config/config.go
src/cmd/services/m3dbnode/config/config_test.go
src/dbnode/environment/config.go

Replacing a seed node requires some extra steps and was previously not
feasible using config alone. This adds a config flag to the seed node
list to allow a new seed node to join the etcd cluster, and adds docs
for replacing a seed node.

[dbnode] allow replacing of seed node + docs

---

docker/grafana/Dockerfile
integrations/grafana/m3db_overlaid_dashboard.json
scripts/development/m3_stack/m3dbnode.yml

This allows users to flip between Prometheus query processing and
M3Query processing. Also adds a new dashboard that overlays M3Query on
the same graph as Prometheus Query, allowing for easy comparisons.

[query] M3DB dashboard now uses templated data source

---

src/query/api/v1/handler/placement/get.go

If we don't exit early then we'll panic when trying to `.Proto()` the
nil placement.

[api] placement: return early on placement err

---

src/dbnode/server/server.go

As discussed in #641, with this PR a lock on `filePathPrefix` will be acquired when starting a db node. Two dbnode processes will not be able to run with the same `filePathPrefix`.
In case another process already has a lock, this error message would be printed:
```
16:07:39.082121[F] could not acquire lock on /tmp/m3db/.lock: failed obtaining lock: resource temporarily unavailable
```
When the dbnode exits gracefully, the lock file will be removed (using a `defer`).
When the dbnode doesn't exit gracefully, another dbnode process will be able to obtain the lock. A bit more details: there's a distinction b/w the *lock file* which resides on the FS, and the *lock* which resides in memory; when the dbnode is killed ungracefully the *lock file* will remain on the FS, but the *lock* will be …

Obtain a lock on `filePathPrefix` on dbnode startup. Close #641

---

integrations/grafana/m3nsch_dashboard.json

Super basic dashboard showing m3nsch write success/errors and p99
latencies:

[integrations] grafana: add m3snch dashboard

---

src/query/graphite/common/transform.go
src/query/graphite/native/builtin_functions.go

isNonNull doesn't count up values itself, but replaces datapoints
with 1 or 0 depending on whether the datapoint is null.

Update documentation for isNonNull

---

docs/how_to/cluster_hard_way.md
docs/how_to/single_node.md

We should keep `-sS` but remove `-f`
```
-s/--silent
Silent or quiet mode. Do not show progress meter or error messages.  
Makes Curl mute.
-S/--show-error
When used with -s it makes curl show an error message if it fails.
-f/--fail
(HTTP)  Fail silently (no output at all) on server errors. This is mostly
done to better enable scripts etc to better deal with failed attempts. In
normal  cases  when a HTTP server fails to deliver a document, it returns
an HTML document stating so (which often also describes  why  and  more).
This flag will prevent curl from outputting that and return error 22.
This method is not fail-safe and there are occasions where non-successful
response codes will  slip  through,  especially  when  authentication  is
involved (response codes 401 and 407).
```
This …

Remove fail silent from curl

---

src/cmd/services/m3dbnode/main/main_index_test.go
src/dbnode/network/server/tchannelthrift/node/service.go
src/dbnode/network/server/tchannelthrift/node/service_test.go
src/dbnode/storage/database.go
src/dbnode/storage/database_test.go
src/dbnode/storage/errors/types.go
src/dbnode/storage/errors/types_test.go

Return clearer RPC errors when requests use unknown namespaces

Better error responses for unknown namespaces

---

src/query/api/v1/handler/namespace/add.go
src/query/api/v1/handler/namespace/add_test.go
src/query/api/v1/handler/placement/init.go
src/query/api/v1/handler/placement/init_test.go

Currently when a placement exists and we try to initialize one we send
a 500 error, and when we try to add an existing placement we get a
generic 400 error. This PR adds 409 conflict statuses in both of those
cases.

[api] more granular status codes in ns-add/pl-init

---

docker/sysctl-setter/Dockerfile
docs/how_to/kubernetes.md
docs/operational_guide/kernel_configuration.md
kube/sysctl-daemonset.yaml
src/dbnode/server/limits.go

This PR provides users with a docker image and Kubernetes DaemonSet that
will set the host's sysctls to our recommended settings. We try to be
careful about this and recommend pinning to a docker image SHA so that
the content is immutable (i.e. someone who controlled our Quay repo
couldn't run arbitrary root containers on hosts that have the image).

[docker] add image for setting recommended sysctls

---

src/query/api/v1/handler/graphite/render.go
src/query/functions/aggregation/base.go
src/query/functions/aggregation/count_values.go
src/query/functions/aggregation/take.go
src/query/functions/binary/and.go
src/query/functions/binary/binary.go
src/query/functions/binary/or.go
src/query/functions/linear/base.go
src/query/functions/linear/histogram_quantile.go
src/query/functions/temporal/base.go
src/query/functions/unconsolidated/timestamp.go
src/query/test/block.go

I don't think this is causing a bug right now, but I think it might be in my PR. I figured it was worth just adding err checks for all these calls; there's no reason (that I'm aware of) to ignore them.
Depending on how awful it is to do, I may try to get `errcheck` passing on this repo, so we can catch these kinds of things.

Add error checks to all block.Builder calls

---

Makefile
docs/how_to/single_node.md
docs/integrations/prometheus.md
kube/README.md
kube/bundle.yaml
kube/etcd.yaml
kube/m3dbnode-statefulset.yaml
kube/m3nsch.yaml
kube/scripts/build_bundle.sh
kube/scripts/m3nsch_client.sh
src/cmd/services/m3nsch_server/main/main.go

Previously users had to `exec` into a pod and manually provide m3nsch
endpoints. This is unnecessary as we can gather the IPs of the agent
pods and pass that via the command line.
Also included a make target to generate the simple manifest bundle in CI
to avoid it becoming stale.

[m3nsch] script to more easily run on k8s

---

src/dbnode/storage/index/block_prop_test.go
src/dbnode/storage/index/postings_list_cache.go
src/dbnode/storage/index/postings_list_cache_lru.go
src/dbnode/storage/index/postings_list_cache_lru_test.go
src/dbnode/storage/index/postings_list_cache_test.go
src/dbnode/storage/index/read_through_segment.go
src/dbnode/storage/index/read_through_segment_test.go
src/m3ninx/idx/query.go
src/m3ninx/search/proptest/concurrent_test.go
src/m3ninx/search/proptest/prop_test.go
src/m3ninx/search/proptest/query_gen.go

The postings list cache was broken in that the key did not include the field that the query was executed against. This meant that for a given segment UUID the results of a query for one term could be mixed up with the results of the same query but for a different term. This would lead to incorrect results being returned when the index block was queried.
This P.R introduces the field as part of the key in the postings list cache to resolve the issue. In addition, it introduces a property test that generates two index blocks, one with the postings list cache enabled and one without, and then executes hundreds of different queries against both blocks and makes sure that they return the exact same result in all cases.

Fix postings list cache causing incorrect results

---

scripts/m3dbnode_bootstrapped.sh

Ensure that no health check processes hang if the dbnode is hanging.

[scripts] health: set curl timeouts

---

src/query/util/logging/log.go

It's often clear where errors are coming from. When stack traces are
enabled, if a coordinator is being used as a prom backend and there's an
error with the M3DB cluster then every single prom write causes a stack
trace and the logs quickly fill up, making debugging difficult.

[coordinator] only log stack traces on panic

---

docs/operational_guide/placement.md
docs/operational_guide/placement_configuration.md

This PR tweaks the operational guide for placement.
In placement.md a few cosmetics in the ascii diagrams addressed.
Regarding placement_configuration.md, now, when m3db.io is rendered,  this text
```
This value should be in the form of <M3DB_HOST_NAME>:<M3DB_NODE_LISTEN_PORT> and identifies how network requests should be routed to this particular node in the placement.
```
is rendered incorrectly:

Tweak operational guide - cosmetics

---

docs/m3db/architecture/peer_streaming.md
mkdocs.yml

Sorry about bunch of changes showing up for the peer_streaming doc, the
only real change there is fixing `helfpul` -> `helpful`, the rest is
autoformatted

[docs] Update docs, fix typo and add a link to fanout docs

---

.buildkite/docs-build-pipeline.yml
.buildkite/docs-docker-compose.yml
.buildkite/pipeline.yml
.buildkite/scripts/check_do_docs.sh
.buildkite/scripts/docs_push.sh
Makefile

We currently have auto builds set up for our GH pages site, but not
https://docs.m3db.io which we also link to frequently.
This PR adds a Buildkite step that allows us to build and push docs from
builds on `master`.
Example of this working: https://github.com/m3db/m3/commit/a7f558c82c066d392be635192fd51899cd3fab16
Fixes #1406

[ci] push / build docs from BK

---

scripts/m3dbnode_bootstrapped.sh

Sometimes 5s isn't enough if the dbnode is under heavy pressure.

[scripts] bootstrapped: bump curl timeout to 60s

---

glide.lock
glide.yaml

The semver range in `glide.yaml` needs to be more specific as `jaeger-client-go@2.16.0` is incompatible with `jaeger-client-go@2.15.0`.

Pin jaeger-client-go to ~2.15

---

Makefile
scripts/docker-integration-tests/aggregator/docker-compose.yml
scripts/docker-integration-tests/aggregator/m3aggregator.yml
scripts/docker-integration-tests/aggregator/m3coordinator.yml
scripts/docker-integration-tests/aggregator/test.sh
scripts/docker-integration-tests/common.sh
scripts/docker-integration-tests/m3aggregator.Dockerfile
scripts/docker-integration-tests/setup.sh
src/cmd/services/m3coordinator/downsample/downsampler.go
src/cmd/services/m3coordinator/downsample/downsampler_test.go
src/cmd/services/m3coordinator/downsample/metrics_appender.go
src/cmd/services/m3coordinator/downsample/options.go
src/cmd/services/m3coordinator/downsample/samples_appender.go
src/query/config/m3coordinator-local-etcd.yml
src/query/config/m3query-dev-etcd.yml
src/query/config/m3query-local-etcd.yml
src/query/server/server.go

To do:
Followups tracked in "Remote metrics aggregation integration followups" issue https://github.com/m3db/m3/issues/1507.

Add m3coordinator capability to downsample using remote m3aggregator

---

src/dbnode/storage/index/read_through_segment.go

This forces new methods added to index.Reader to be explicit about implementing caching in the read through segment.

[m3ninx] Explicitly implement index.Reader on read through segment reader

---

src/dbnode/persist/fs/retriever.go
src/dbnode/persist/fs/retriever_test.go
src/dbnode/persist/fs/seek.go

This bug had no impact on correctness, but could impact performance by preventing blocks for series that weren't already in memory from being added to the cache after being read from disk.
Bug was introduced by #1421
Basically even when there are no encoded tags, we wrapped the bytes into a checked.Bytes. The retriever would see that the encoded tags weren't nil and try to put them into a tag decoder. The tag decoder would attempt to read nil bytes and return an error which would prevent a new shard entry from being created for items that were recently read and needed to be put in the cache.
This P.R fixes the issue by performing a length test in the retriever so even if it receives checked.Bytes with zero length it will ignore it AND it changes the seek logic to only pass along a non-nil …

Fix bug where data would sometimes not get loaded into cache after successful read

---

kube/scripts/m3nsch_client.sh

We see some weird behavior when all of the clients try to start at once,
let's add a warmup.

[m3snch] kube script: add warmup between starts

---

.buildkite/scripts/docs_push.sh

We serve the operator's docs from a branch subdomain of the monorepo.
Let's incorporate it into the build process.
This means that once we update docs in the operator repo (which will
eventually be merged w/ the monorepo anyway) we'll have to wait until
the next master build, but that slight drift is fine.

[ci] docs: also build operator docs

---

src/dbnode/server/server.go

Seeing this in the logs has been driving me crazy:
```
bytes pool registering bucket capacity=842356189232, size=842356189240,
refillLowWatermark=%!f(*float64=0x26044d8),
refillHighWatermark=%!f(*float64=0x26044d0)
```

[dbnode] fix byte pool watermark log message

---

CHANGELOG.md
src/dbnode/persist/fs/commitlog/commit_log_test.go
src/dbnode/persist/fs/commitlog/iterator.go
src/dbnode/persist/fs/commitlog/types.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go

Currently the commit log bootstrapper will only attempt to read commit log files that were present on disk before the node started to prevent it from trying to read the files that are currently being written to.
In addition to this check, we also need to add a guard against identifying the active file as corrupt. If the active file appears corrupt it will trigger logic in the commit log bootstrapper that makes configurable decisions about whether the commit log bootstrap should fail or whether the corrupt file should be ignored.
The existing code allowed callers to pass a predicate to the commit log iterator which could be used to filter out files that were not present before the node started, however, this filter was not being applied to files that …

[dbnode] Filter out corrupt commit log files that were not present before the node started in the commit log bootstrapper

---

src/dbnode/encoding/proto/common.go
src/dbnode/encoding/proto/encoder.go
src/dbnode/encoding/proto/iterator.go
src/dbnode/encoding/proto/round_trip_test.go

This P.R adds support for boolean fields in the proto encoder / decoder so that the complex types feature can support efficiently compressing messages with boolean fields.
There are no added test cases because the existing property test already had logic for generating messages with boolean fields but the list of types of fields it would generate came from the map of support custom-encoded fields which was missing booleans. Now that booleans have been added to that map, the property test will now test against it as well (verified this behavior by adding the booleans to the map but not implementing the encoding/decoding and the property test started failing).
**Does this PR introduce a user-facing and/or backwards …

[dbnode] Add support for bools in proto encoder/decoder

---

src/cmd/services/m3dbnode/config/config.go
src/dbnode/client/config.go
src/dbnode/encoding/proto/iterator.go
src/dbnode/encoding/proto/parse_schema.go
src/dbnode/server/server.go

Makes the message name configurable when parsing a proto schema + allow the proto iterator to operate even if the bytes pool is not configured.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Make message name configurable when parsing proto schema + allocate if no byte pool

---

src/query/api/v1/handler/graphite/find.go
src/query/api/v1/handler/prometheus/common.go
src/query/api/v1/handler/prometheus/native/list_tags.go
src/query/api/v1/handler/prometheus/remote/tag_values.go
src/query/api/v1/handler/prometheus/remote/tag_values_test.go
src/query/api/v1/httpd/handler.go
src/query/block/offset_test.go
src/query/functions/fetch_test.go
src/query/pools/query_pools.go
src/query/test/mock_pools.go
src/query/tsdb/remote/compressed_codecs.go

Fixes an issue where the values endpoint, `/label/{name}/values` was not returning correct results. Issue was caused since the new optimized tag completion endpoint now considers query range params, and they were not being set correctly.
```release-note
Fixes a user-facing bug
```
```documentation-note
NONE
```

[query] Add start and end time to tag values endpoint

---

src/query/api/v1/handler/graphite/find_test.go
src/query/functions/binary/binary.go
src/query/functions/binary/binary_test.go
src/query/functions/binary/common.go
src/query/functions/binary/common_test.go
src/query/models/tags_test.go
src/query/test/block.go

Fixes #1520
Fixes an issue in binary functions; previously there was a requirement that series name tags matched to match series from left and right; this drops name tags from binary functions.
NB: this also drops the name tag from appearing in the output series for binary operations with a scalar argument; this is intentional to mirror the same behaviour as Prometheus 
```release-note
Fixes an issue where binary functions would not match series correctly.
```
**Does this PR require updating code package or user-facing documentation?**: 
```documentation-note
NONE
```

[query] Ignore name tags for matching binary functions

---

CHANGELOG.md

Commit the changelog for 0.9.0 so we can cut a new release.

0.9.0 Changelog

---

src/query/api/v1/handler/prometheus/native/common.go
src/query/api/v1/handler/prometheus/native/common_test.go

Fixes #1610 
Previously, if you included a float step size with no units (e.g. 15.00), the query would fail with 
```
"error":"error parsing param: step, error: time: missing unit in duration 15.00"
```
This PR allows you to add a float step size without units (and assumes it is in seconds -- equivalent to what Prometheus does) 
```release-note
```
```documentation-note
Maybe we can add something in the docs, but I don't think it's necessary. 
```

[query] Fix step parsing

---

Makefile
src/dbnode/persist/fs/seek.go

This re-enables using `PANIC_ON_INVARIANT_VIOLATED=true` for integration tests, since the root of the issue that led us to disabling it is fixed with PR https://github.com/m3db/m3/pull/1531.
```release-note
NONE
```
```documentation-note
NONE
```

Use PANIC_ON_INVARIANT_VIOLATED=true for integration tests

---

CHANGELOG.md

Updates change log for 0.9.1 release.
```release-note
NONE
```
```documentation-note
NONE
```

Update change log for 0.9.1

---

src/dbnode/client/fetch_tagged_results_accumulator_merge_test.go
src/dbnode/client/session_fetch_bulk_blocks_test.go
src/dbnode/encoding/encoding_mock.go
src/dbnode/encoding/m3tsz/encoder.go
src/dbnode/encoding/m3tsz/encoder_test.go
src/dbnode/encoding/m3tsz/roundtrip_test.go
src/dbnode/encoding/null.go
src/dbnode/encoding/proto/encoder.go
src/dbnode/encoding/proto/round_trip_prop_test.go
src/dbnode/encoding/types.go
src/dbnode/integration/generate/writer.go
src/dbnode/network/server/tchannelthrift/node/service_test.go
src/dbnode/storage/block/merged_block_reader.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_data_test.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_prop_test.go
src/dbnode/storage/series/buffer.go
src/dbnode/storage/series/buffer_mock.go
src/dbnode/storage/series/buffer_test.go
src/dbnode/storage/series/series.go

This P.R updates the Stream() API to be more difficult to misuse (returning a bool indicating if any data is present) as well as accept an options struct which will be used in a subsequent P.R.
In addition to the updated API, this P.R fixes two bugs in `buffer.go` and adds regression tests for them as well.
If there is an error during encoding its possible to end up with an encoder in the buffer that has no writes (an empty stream) which will cause the `Flush()` method to panic because it doesn't account for this possibility.
Additional changes included in this P.R:
Fixes #805

Update Stream() API and refactor/fix bugs in buffer.go

---

src/dbnode/encoding/proto/round_trip_prop_test.go

Right now if the iterator returns zero messages (even though it should have returned more than zero) the test will pass. This fixes it so the property test will catch issues that cause the iterator to return zero messages.

Make proto encoder prop test verify number of iterated messages

---

src/x/instrument/config.go
src/x/instrument/prom_process_collector.go
src/x/instrument/prom_process_collector_test.go

Recently we introduced a more optimized open FD reporter to replace the Prometheus collector which exhibited significant load querying open FDs by the process.  This however removed some stats that some existing dashboards currently rely on.  This adds those back with a modified version of the collector that turns off open FD reporting.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Add Prometheus process collector with open FD reporting disabled

---

src/dbnode/storage/errors/types.go
src/dbnode/storage/series/buffer.go

When any datapoint outside of the buffer is currently written, the user gets back a msg saying that the coldWrites feature (which is not ready) is not enabled. This causes a lot of confusion.

[dbnode] Remove coldwrites error message until feature is ready

---

src/dbnode/client/config.go
src/dbnode/client/config_test.go

Allow client configuration to load schema from file.
The code is the same as in cmd/services/m3dbnode/config

[dbnode] add schema registry to client configuration

---

glide.lock
glide.yaml

Upgrade Tally to 3.3.10 to fix Tally Prometheus reporter listen port conflict not panic'ing correctly with the correct error message
```release-note
NONE
```
```documentation-note
NONE
```

Upgrade Tally to 3.3.10

---

src/dbnode/encoding/istream.go
src/dbnode/encoding/m3tsz/float_encoder_iterator.go
src/dbnode/encoding/ostream.go
src/dbnode/encoding/ostream_test.go
src/dbnode/encoding/proto/benchmarks_test.go
src/dbnode/encoding/proto/buffer_encode.go
src/dbnode/encoding/proto/common.go
src/dbnode/encoding/proto/custom_marshal.go
src/dbnode/encoding/proto/custom_marshal_test.go
src/dbnode/encoding/proto/custom_unmarshal.go
src/dbnode/encoding/proto/custom_unmarshal_test.go
src/dbnode/encoding/proto/docs/README.md
src/dbnode/encoding/proto/docs/encoding.md
src/dbnode/encoding/proto/docs/marshal.md
src/dbnode/encoding/proto/docs/unmarshal.md
src/dbnode/encoding/proto/encoder.go
src/dbnode/encoding/proto/encoder_test.go
src/dbnode/encoding/proto/iterator.go
src/dbnode/encoding/proto/round_trip_prop_test.go
src/dbnode/encoding/proto/round_trip_test.go
src/dbnode/namespace/schema.go
src/m3ninx/postings/pilosa/codec_test.go
src/msg/protocol/proto/types.go

Remove `jhump/protoreflect` from the hot path as much as possible, plus some other optimizations and cleanup.
Results:
1. 10x improvement in encoding and decoding for non-custom fields.
2. 2x improvement in encoding for custom fields.
3. 4x improvement in decoding for custom fields (original goal).
before
```
goos: darwin
goarch: amd64
pkg: github.com/m3db/m3/src/dbnode/encoding/proto
BenchmarkEncoder/with_non_custom_encoded_fields_enabled-8         	    1000	   1432754 ns/op	  374435 B/op	    8177 allocs/op
BenchmarkEncoder/with_non_custom_encoded_fields_disabled-8        	   10000	    111547 ns/op	   13430 B/op	       0 allocs/op
BenchmarkIterator/with_non_custom_encoded_fields_enabled-8        	    1000	   1274402 ns/op	  323059 B/op	    8196 …
```

Optimize protobuf encoder and iterator for various workloads

---

src/dbnode/server/server.go

Reading the repair config from YAML was disabled because we weren't using this feature at all. As we begin to invest into M3DB's repair functionality we want to be able to test the existing code.

Support repair config in server.go

---

src/dbnode/storage/namespace.go
src/dbnode/storage/namespace_test.go
src/dbnode/storage/repair.go
src/dbnode/storage/repair_test.go
src/dbnode/storage/shard.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go

Repair logic needs access to the nsctx long term so that it can perform remote reads / merges.

Flow NS Context into shard repairer

---

src/query/block/lazy.go
src/query/block/lazy_test.go
src/query/functions/fetch.go
src/query/functions/lazy/base.go
src/query/functions/lazy/base_test.go
src/query/parser/promql/parse.go
src/query/parser/promql/parse_test.go
src/query/parser/promql/types.go

This PR fixes #1619. It introduces support for unary expressions -- specifically `+` and `-`. For example, this query is now supported: 
```
-sum(up)
```
```release-note
Yes, this PR adds support for Prometheus unary expressions (`+` and `-`).
```
```documentation-note
NONE
```

[query] Add support for unary expressions

---

CHANGELOG.md
docker/m3dbnode/Dockerfile

Fixes #1671
```release-note
NONE
```
```documentation-note
NONE
```

[docker] don't set m3dbnode binary caps in build

---

src/query/api/v1/handler/prometheus/native/common.go
src/query/api/v1/handler/prometheus/native/common_test.go

Follows on from #1682 to also remove series with no NaN-values in the given range, as they were still appearing as empty series.
```release-note
Will no longer add series with no non-NaN points in the given range
```
```documentation-note
NONE
```

[query] Drop series with no values in the given range

---

src/query/api/v1/handler/prometheus/remote/read.go
src/query/api/v1/handler/prometheus/remote/read_test.go
src/query/api/v1/httpd/handler.go

Limit was not correctly propagated for remote reads, which could OOM clusters when using the Prometheus remote read endpoints.
```release-note
Users who set a low limit but relied on the prom read endpoints may see less data returned, but this is unlikely, and is easily fixed by updating the limit in coordinator settings.
```
```documentation-note
NONE
```

[query] Propagate Limit settings for remote reads

---

scripts/docker-integration-tests/query_fanout/docker-compose.yml
scripts/docker-integration-tests/query_fanout/m3coordinator-cluster-a.yml
scripts/docker-integration-tests/query_fanout/m3coordinator-cluster-b.yml
scripts/docker-integration-tests/query_fanout/m3coordinator-cluster-c.yml
scripts/docker-integration-tests/query_fanout/test.sh
src/cmd/services/m3query/config/config.go
src/query/server/server.go

Adds multi-zone capability to remote reads for Query
```release-note
NONE
```
```documentation-note
NONE
```

[Query] Add multi-zonal capability to remote reads

---

src/dbnode/namespace/namespace_mock.go
src/dbnode/namespace/schema_registry.go
src/dbnode/namespace/schema_registry_test.go
src/dbnode/namespace/types.go
src/dbnode/storage/namespace.go

namespace bootstrap depends on namespace.metadata for schema.
We need to deliver dynamic schema to namespace metadata as well, since bootstrap can be invoked when new shards are assigned to a node.

update namespace metadata dynamically

---

docs/operational_guide/namespace_configuration.md
src/query/api/v1/handler/namespace/get.go
src/query/api/v1/handler/namespace/get_test.go
src/x/net/http/convert.go
src/x/net/http/convert_test.go

This PR allows you to pass in an optional `debug` parameter to the `/api1/v1/namespace` endpoint in the coordinator, which returns durations instead of nanoseconds for the duration fields. This should help with readability and debugging. Below is a sample output using start_m3. 
```
{
"registry": {
"namespaces": {
"metrics_0_30m": {
"bootstrapEnabled": true,
"cleanupEnabled": true,
"flushEnabled": true,
"indexOptions": {
"blockSizeDuration": "10m0s",
"enabled": true
},
"retentionOptions": {
"blockDataExpiry": true,
"blockDataExpiryAfterNotAccessPeriodDuration": "5m0s",
"blockSizeDuration": "10m0s",
"bufferFutureDuration": "5m0s",
"bufferPastDuration": "5m0s",
"retentionPeriodDuration": "30m0s"
},
"snapshotEnabled": true,
"writesToCommitLog": true
}, …
```

[query]Add debug param to namespace get API

---

src/dbnode/client/connection_pool.go
src/dbnode/client/errors.go
src/dbnode/client/session.go
src/dbnode/client/session_fetch_bulk_blocks_test.go

Handle host not available scenario during peer bootstrap more gracefully

---

src/query/api/v1/handler/placement/delete_all.go
src/query/api/v1/handler/placement/delete_all_test.go

**What this PR does / why we need it**: Returns a 404 rather than 500 from the coordinator if we attempt to delete a nonexistent placement.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```

[api] placement delete: return 404 if not found

---

.buildkite/pipeline.yml
Makefile
docker-compose.yml
docker/m3aggregator/Dockerfile
docker/m3collector/Dockerfile
docker/m3coordinator/Dockerfile
docker/m3dbnode/Dockerfile
docker/m3nsch/Dockerfile
docker/m3query/Dockerfile
scripts/thriftgen.Dockerfile
src/query/util/logging/log_test.go

To be merged after ongoing docker fixes.
Fixes #
```release-note
Build and release M3DB with Go 1.12
```
```documentation-note
NONE
```

[ci] build + release with go1.12 (again)

---

src/dbnode/persist/fs/read_test.go
src/dbnode/storage/series/reader.go
src/dbnode/storage/series/reader_test.go

Fixes #1640 
@martin-mao This is the bug we were talking about last time I saw you.

Fix multiple blocks with the same block start returned from fetchblocks pathway

---

CHANGELOG.md
integrations/grafana/m3coordinator_dashboard.json
src/cmd/services/m3coordinator/downsample/options.go
src/cmd/services/m3coordinator/downsample/options_test.go

This fixes a relatively unreasonable default of only 10% of tile size for the aggregation buffer past value.  Table based approach allows for some reasonable defaults, the observed delay from Prometheus remote write seems to be under 15seconds when it's healthy (not 5s like the current clamp minimum).
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Use table based approach for aggregation tile buffer past calculation

---

src/dbnode/storage/block/lease.go
src/dbnode/storage/block/lease_test.go

This P.R adds test for the block.LeaseManager interface.

Add tests for block leaser

---

src/dbnode/storage/database.go
src/dbnode/storage/database_test.go
src/dbnode/storage/lease_verifier.go
src/dbnode/storage/lease_verifier_test.go
src/dbnode/storage/namespace.go
src/dbnode/storage/namespace_test.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go

This P.R adds a `block.LeaseVerifier` implementation that wraps `storage.Database`. This will be used by the `block.Leaser` to verify requests from the `SeekManager` to lease blocks are valid and for the latest volume.

[DBNode] - Add Block Lease Verifier Implementation

---

src/aggregator/aggregator/aggregator.go
src/aggregator/aggregator/entry.go
src/aggregator/aggregator/entry_test.go
src/aggregator/aggregator/options.go
src/cmd/services/m3coordinator/downsample/options.go
src/cmd/services/m3coordinator/downsample/options_test.go

Returns specific errors for metrics that are being aggregated that arrive too late or too early.
```release-note
NONE
```
```documentation-note
NONE
```

Add aggregation specific errors

---

src/dbnode/storage/block/block_mock.go
src/dbnode/storage/block/lease.go
src/dbnode/storage/block/lease_noop.go
src/dbnode/storage/block/lease_test.go
src/dbnode/storage/block/types.go
src/dbnode/storage/lease_verifier.go
src/dbnode/storage/lease_verifier_test.go

This P.R adds a `OpenLeaseForLatest()` API to the block.LeaseManager so that when the SeekManager is opening seekers of its own accord (as opposed to as the result of receiving an `UpdateOpenLeases()` notification, it can determine which volume to open for a given block.

[DBNode] Add LeaseLatest() API to block.LeaseManager

---

src/dbnode/persist/fs/seek_manager.go
src/dbnode/storage/block/lease.go
src/dbnode/storage/block/lease_test.go

The existing implementation has a potential to deadlock(although not an actual bug in master since this is "dead" / feature-flagged code) when the SeekManager is being closed as described in the comments in the P.R.

[DBNode] Register/unregister leaser outside of locks in SeekManager and make UpdateOpenLeases() concurrency safe

---

scripts/docker-integration-tests/common.sh
scripts/docker-integration-tests/simple/test.sh
src/cmd/services/m3dbnode/main/main_index_test.go
src/cmd/services/m3dbnode/main/main_test.go
src/dbnode/integration/setup.go
src/dbnode/persist/fs/seek_manager.go
src/dbnode/storage/block/lease.go
src/dbnode/storage/bootstrap/bootstrapper/fs/source.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source_data_test.go
src/dbnode/storage/namespace.go
src/dbnode/storage/namespace_test.go

This P.R calls `OpenLatestLease()` before opening a new seeker in the seek manager to ensure that the seek manager is always opening the latest volume for a given file. This is required for correct behavior of the cold write feature.
In addition, this change means that `CacheShardIndices` cannot be called before shards complete bootstrapping (since they cannot perform lease verification until they are bootstrapped). As a result, `CacheShardIndices` cannot be called in the F.S and peers bootstrapper as it is currently. Instead, this P.R moves the call to `CacheShardIndices` into the namespace `Bootstrap()` method immediately after all the shards are marked as bootstrapped (and as a result can perform lease verification).

[DBNode] Use OpenLatestLease() in SeekManager and move CacheShardIndices() to namespace bootstrap

---

src/metrics/rules/validator/config.go
src/metrics/rules/validator/config_test.go
src/metrics/rules/validator/options.go
src/metrics/rules/validator/options_test.go
src/metrics/rules/validator/validator.go
src/metrics/rules/validator/validator_test.go

**What this PR does / why we need it**: Make rule validator more robust for a common gotcha.
Fixes #
**Special notes for your reviewer**: `timertype` is added at the aggregation tier, not at the client layer.
```release-note
NONE
```
```documentation-note
NONE
```

[metrics] rules: reject timertype tag in filters

---

.buildkite/scripts/pr_build.sh

Until we have a more complex label system for running PRs from external
contributors, this can hold us over.
Fixes #
```release-note
NONE
```
```documentation-note
NONE
```

[ci] add script for running builds on external PRs

---

src/dbnode/persist/fs/msgpack/decoder.go
src/dbnode/persist/fs/msgpack/encoder.go
src/dbnode/persist/fs/msgpack/encoder_test.go
src/dbnode/persist/fs/msgpack/roundtrip_test.go
src/dbnode/persist/fs/msgpack/schema.go
src/dbnode/persist/fs/read.go
src/dbnode/persist/fs/read_write_test.go
src/dbnode/persist/fs/write.go
src/dbnode/persist/schema/types.go
src/dbnode/storage/shard.go
src/dbnode/storage/shard_test.go

This P.R add the `VolumeIndex` into the Info file of all the fileset files in a backwards and forwards compatible way. It also ensures that the volume index is written out by the writers and return by calls to `ReadInfoFile`.
Finally, it updates the shard bootstrap logic to restore the Cold flush version on bootstrap as well as the flush state.

Add VolumeIndex back/forwards compatible to info files + restore flush version on shard bootstrap

---

src/query/api/v1/handler/prometheus/remote/read.go
src/query/api/v1/httpd/handler.go
src/query/storage/converter.go
src/query/storage/converter_test.go

Drops empty series appearing in remote read endpoint unless specified otherwise by config
```release-note
No longer returns empty series to remote read
```
```documentation-note
No
```

[query] remove empty series from remote read endpoint

---

src/dbnode/persist/fs/files.go
src/dbnode/persist/fs/files_test.go
src/dbnode/persist/fs/write.go
src/dbnode/storage/series/buffer.go
src/dbnode/storage/series/buffer_test.go
src/dbnode/storage/shard.go

* Fixes `DataFileSetExists` incorrectly checking the legacy fileset when the volume isn't `0`
* Fixes the `ForEach` func for `OptimizedTimes` to not loop through zero values that weren't explicitly added
```release-note
NONE
```
```documentation-note
NONE
```

DataFileSetExists and OptimizedTimes ForEach bug fixes

---

src/dbnode/storage/shard.go
src/dbnode/storage/shard_test.go

Currently, cold flushes happen unnecessarily because `dirtySeriesToWrite` contains empty `seriesList`s (since it is a shared resource between shards). Checking for data in `dirtySeries` is a sufficient condition in figuring out whether a merge should actually happen or not.
```release-note
NONE
```
```documentation-note
NONE
```

Exit cold flush early when there is nothing to merge

---

src/dbnode/persist/fs/retriever_test.go
src/dbnode/persist/fs/seek_manager.go
src/dbnode/persist/fs/seek_manager_test.go
src/dbnode/storage/block/types.go

This P.R is required for the out of order writes feature. After a new volume for a given namespace/shard/blockstart is written out, the SeekerManager will be notified via a call to UpdateOpenLease(). This function imlpements UpdateOpenLease such that the SeekerManager "hot swaps" its old seekers for the old volume with new seekers for the new volume.
In terms of testing, this P.R adds some basic unit testing but the meat of the assurance that it works comes from extending the existing concurrency tests to use the new code paths AND simulate error cases so that those paths get tested as well (which they previously were not).

Implement UpdateOpenLease in `SeekManager`

---

src/dbnode/server/server.go

Some users are setting all the kernel settings right, but they don't know to set the environment variable. It is not harmful to just attempt raising the limit, so that's what this change does (avoids requiring the environment variable to be set).
See for reference:
```
> Oh, looking from the pod, I do see the sysctl settings took, but it seems I'll need to find a way to get this to actually play nice:
/ # cat /proc/sys/fs/nr_open
3000000
/ # sysctl -n fs.nr_open
3000000
/ # sysctl -n fs.file-max
3000000
/ # cat /proc/self/limits | grep files
Max open files 65536 65536 files
```
```release-note
NONE
```
**Does this PR require updating …

[dbnode] Raise rlimit to number of file limit by default

---

src/cmd/services/m3aggregator/main/main.go
src/cmd/services/m3ctl/main/main.go
src/cmd/services/m3em_agent/agentmain/agent.go
src/cmd/services/m3nsch_server/main/main.go
src/collector/server/server.go
src/dbnode/server/server.go
src/query/server/server.go
src/x/config/config.go
src/x/config/config_test.go

Fixes #1549
I tried to cover all services that require a config, let me know if I forgot any.
```release-note
NONE
```
```documentation-note
NONE
```

Check config for deprecated fields

---

src/query/server/server.go

Fixes #1801
```release-note
NONE
```
```documentation-note
NONE
```

[query] Log config file in query/coordinator

---

scripts/docker-integration-tests/carbon/expected/cbar.json
scripts/docker-integration-tests/carbon/expected/cbaz.json
scripts/docker-integration-tests/carbon/test.sh
src/query/graphite/graphite/glob.go
src/query/graphite/graphite/glob_test.go
src/query/graphite/lexer/lexer.go
src/query/graphite/lexer/lexer_test.go

This allows Graphite query expressions to contain colons as part of the identifier since we allow this as part of the metric name when ingesting Carbon (which is valid).
```release-note
- Add support for Graphite query expressions to use colon as part of identifier or pattern
```
```documentation-note
NONE
```

[query] Allow Graphite query expressions to use colon as part of identifier

---

src/cluster/client/etcd/client.go
src/cluster/client/etcd/client_test.go
src/cluster/client/etcd/config.go
src/cluster/client/etcd/config_test.go
src/cluster/client/etcd/options.go
src/cluster/client/etcd/types.go
src/cluster/kv/etcd/options.go
src/cluster/kv/etcd/store.go
src/cluster/kv/etcd/store_test.go
src/cmd/services/m3dbnode/config/config_test.go
src/dbnode/environment/config.go
src/dbnode/environment/config_test.go
src/dbnode/server/server.go

Fixes #1751 
```
NONE
```
```release-note
NONE
```
```documentation-note
NONE
```

Automatically create folder for KV cache

---

src/cmd/services/m3dbnode/main/main_index_test.go
src/cmd/services/m3dbnode/main/main_test.go
src/dbnode/server/server.go
src/x/debug/debug_test.go

Exposes debug dump (https://github.com/m3db/m3/pull/1767) to HTTP endpoint `/debug/dump`
Just wondering if we should make `cpuProfileDuration` (currently set to 1s) and the path (currently set to `/debug/dump`) configurable?
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Expose debug dump on /debug/dump

---

src/dbnode/storage/series/buffer.go
src/dbnode/storage/series/buffer_mock.go
src/dbnode/storage/series/buffer_test.go
src/dbnode/storage/series/series.go
src/dbnode/storage/series/series_all_test.go
src/dbnode/storage/series/series_mock.go
src/dbnode/storage/series/series_parallel_test.go
src/dbnode/storage/series/series_test.go
src/dbnode/storage/series/types.go
src/dbnode/storage/series_wired_list_interaction_test.go
src/dbnode/storage/shard.go
src/dbnode/storage/shard_test.go

This is the first P.R to begin the process of making it possible load data dynamically into a shard/series/buffer such that the data will be merged with any data in memory or on disk and successfully persisted. The ability to do so is a key requirements of the background repairs feature which is being actively developed.

[dbnode] Add Load() API and refactor buffer.Bootstrap() logic to take warm vs. cold writes into account

---

src/dbnode/persist/fs/merger.go
src/dbnode/persist/fs/merger_test.go

[DBNode] - Optimize Cold Flush Merge Logic

---

src/cmd/services/m3dbnode/config/config.go
src/cmd/services/m3dbnode/config/config_test.go
src/cmd/services/m3dbnode/config/limits.go
src/dbnode/network/server/tchannelthrift/node/service.go
src/dbnode/network/server/tchannelthrift/node/service_test.go
src/dbnode/network/server/tchannelthrift/options.go
src/dbnode/network/server/tchannelthrift/types.go
src/dbnode/server/server.go

While we still need to address [this proposal](https://github.com/m3db/proposal/issues/13) to solve the backpressure problem in depth, this P.R improves M3DB's ability to apply backpressure by supporting the ability to (optionally) limit the maximum number of outstanding write and read requests. This allows us to apply back pressure even earlier because in situations where the nodes are really overwhelmed many goroutines will get stuck allocating way before the commit log backpressure ever kicks in.
This P.R also allows us to size the writeBatchReq pool exactly to fit our requirements in the case that a maximum number of outstanding write requests has been configured.

[DBNode] - Add support for limiting the maximum number of outstanding write/read requests at the RPC level

---

scripts/docker-integration-tests/aggregator/docker-compose.yml

The host id should not be the same on both containers. Having it the
same causes problems with aggregator leader election.
Without the fix:
m3aggregator02_1   | {"level":"warn","ts":1564148579.7962255,"msg":"campaign is not enabled, no cutover shards"}
m3aggregator01_1   | {"level":"warn","ts":1564148579.49419,"msg":"campaign is not enabled, no cutover shards"}
m3aggregator02_1   | {"level":"error","ts":1564148581.3063626,"msg":"leader has not changed","electionKey":"shardset/1/lock","electionTTL":10,"leaderValue":"m3aggregator01:6000","error":"leader has not changed"}
m3aggregator01_1   | {"level":"error","ts":1564148581.2203503,"msg":"leader has not changed","electionKey":"shardset/1/lock","electionTTL":10,"leaderValue":"m3aggregator01:6000","error":"leader has not changed"} …

Fix M3AGGREGATOR_HOST_ID in integration test

---

kube/sysctl-daemonset.yaml

```release-note
NONE
```
```documentation-note
NONE
```

[kube] fix minor typo in sysctl-setter daemonset

---

DEVELOPER.md
src/dbnode/persist/fs/fs_mock.go
src/dbnode/persist/fs/retriever.go
src/dbnode/persist/fs/retriever_test.go
src/dbnode/persist/fs/seek_manager.go
src/dbnode/persist/fs/types.go

Fixes #1760 
Right now bloom filters that are returned via `seekerManager.ConcurrentIDBloomFilter` https://github.com/m3db/m3/blob/04d9c0654c80688e79ac7ffb2f15dd7ab3b4e8f8/src/dbnode/persist/fs/seek_manager.go#L212 are not tracked, which can lead to errors if one goroutine tries to access it (e.g. search for an ID) while another has closed the filter in the meantime. 
This PR introduces the `Test` method on `DataFileSetSeekerManager` https://github.com/m3db/m3/blob/04d9c0654c80688e79ac7ffb2f15dd7ab3b4e8f8/src/dbnode/persist/fs/types.go#L168 which tests for an ID while the lock on a bloom filter is still being held, to avoid the above described scenario. `seekerManager.Test` is now being used in …

[dbnode] Safe handling of concurrent bloom filters

---

src/dbnode/server/server.go
src/x/instrument/string_list_emitter.go
src/x/instrument/string_list_emitter_test.go

The bootstrap gauge introduced with #1756 can lead to a panic, when the amount of label keys changes in regards to what it had been initialised with. For example, if `dbnode` has been started with four bootstrappers configured but this amount is changed to three during runtime, the Prometheus Reporter for tally will panic.
In this PR the exposition of the bootstrap order has been changed from a single to multiple gauges in `StringListEmitter`, where each gauge has different value for the label key `type`:
```
bootstrappers0{type="filesystem"} 1
bootstrappers1{type="peers"} 1
bootstrappers2{type="commitlog"} 1
bootstrappers3{type="uninitialized_topology"} 1
```
Changing the order will set the old metric/value …

[dbnode] Fix panic when updating bootstrappers gauge on Promreporter with different label keys

---

docker/images.json
docker/m3dbnode/Dockerfile
docker/m3dbnode/Dockerfile-setcap
docs/operational_guide/kernel_configuration.md
glide.lock
mkdocs.yml
src/dbnode/server/server.go

TODO:
Fixes #1671
- Default to attempting to raise FD limits rather than opt in: raising
the limits is benign if it fails.
- Dual-publish Docker images with a setcap'd binary for users running as
non-root that want to raise limits.
```release-note
- Dual-publish Docker images with SYS_RESOURCE capabilities on the m3dbnode binary for users running as non-root with added capabilities that wish to raise process limits.
- Default to attempting to raise FD limits to max possible, with an environment variable to skip doing so.
```
```documentation-note
YES: …
```

[docker] dual-publish setcap; default raise limits

---

src/dbnode/encoding/proto/round_trip_prop_test.go

This P.R adds a property test to ensure that the protobuf encoding format remains bijective.

Add property test for protobuf encoding bijectivity

---

src/dbnode/encoding/m3tsz/timestamp_encoder.go
src/dbnode/encoding/proto/iterator.go
src/dbnode/encoding/proto/round_trip_test.go

Current the Protobuf encoder/iterator misbehaves when time units are changed mid-stream and generates invalid data. This P.R fixes the issue and adds a unit test.

[DBNode] - Fix bug in Protobuf encoding when time units are changed

---

docs/how_to/cluster_hard_way.md
docs/operational_guide/namespace_configuration.md
docs/operational_guide/placement_configuration.md
docs/troubleshooting/index.md

Adds documentation regarding recommended config settings for namespace and placement. 
```release-note
```
```documentation-note
```

[docs] Add shard/block size recs

---

scripts/vagrant/Vagrantfile
src/cmd/services/m3dbnode/config/pooling.go
src/dbnode/server/server.go
src/dbnode/ts/types.go
src/dbnode/ts/write_batch.go

The PR for improving tag encoding in the commit log failed to return encoded tags to the pool due to `SetOutcome` in the `WriteBatch` clobbering the `Write.Series.EncodedTags` field when result from the namespace/shard is returned.
This makes sure it is not clobbered, I've verified the fix restores and also improves the overall write performance of the DB nodes.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix perf regression not returning pooled encoded tags

---

CHANGELOG.md
src/metrics/aggregation/id.go
src/metrics/aggregation/id_test.go
src/metrics/aggregation/type.go
src/metrics/aggregation/type_test.go
src/metrics/pipeline/type.go
src/metrics/pipeline/type_test.go
src/metrics/policy/drop_policy_test.go
src/metrics/policy/policy.go
src/metrics/policy/policy_test.go
src/metrics/policy/storage_policy.go
src/metrics/policy/storage_policy_test.go
src/metrics/transformation/type.go
src/metrics/transformation/type_test.go
src/x/test/testmarshal/marshal.go
src/x/test/testmarshal/marshal_test.go

**What this PR does / why we need it**: Many of our types (24 in my last count) implement `UnmarshalYAML` but not `MarshalYAML`. This means (in most cases) that the types don't "roundtrip" in YAML--you can't serialize to YAML and get the same object back. 
This PR fixes that issue, adding MarshalYAML methods where needed, and switching to the use of (Un)MarshalText where possible. Both YAML and JSON respect the [TextMarshaler](https://golang.org/pkg/encoding/#TextMarshaler) interfaces; for types which we marshal as their string representation, e.g. `StoragePolicy`, this saves a bit of boilerplate. 
N.B.: I haven't fixed this issue for *every* type it affects; unfortunately, the fix + testing is pretty manual, despite the helpers. I can file a separate issue for that if desired.
**Special …

[aggregator] Make YAML serialization roundtrip for config types

---

docker/grafana/Dockerfile
integrations/grafana/m3db_overlaid_dashboard.json
integrations/grafana/temporal_function_comparison.json
src/query/api/v1/handler/prometheus/native/common.go
src/query/block/column.go
src/query/functions/aggregation/absent.go
src/query/functions/temporal/aggregation.go
src/query/functions/temporal/aggregation_test.go
src/query/functions/temporal/base.go
src/query/functions/temporal/base_test.go
src/query/functions/temporal/functions.go
src/query/functions/temporal/functions_test.go
src/query/functions/temporal/holt_winters_test.go
src/query/functions/temporal/linear_regression.go
src/query/functions/temporal/linear_regression_test.go
src/query/functions/temporal/rate.go
src/query/functions/temporal/rate_test.go

FIxes very slow temporal function application when working with larger ranges
This is a quick and easy solution for the time being, just removing the allocations made in a tight loop.
```release-note
None
```
```documentation-note
None
```

[Query] Increase performance of temporal functions

---

src/dbnode/storage/database.go
src/dbnode/storage/database_test.go

Currently a bootstrap will be triggered for each topology change, even if the node doesn't receive any new shards. These bootstraps are generally short-lived (since their is nothing to bootstrap) but they make the nodes flicker in and out of the "bootstrapped" state during topology changes which is confusing.
In addition, the fact that the nodes are flickering in and out of the "bootstrapped" state significantly delays the amount of time until a node appears "BootstrappedAndDurable". This is most pronounced during node removes where basically every node in the cluster is accepting a few new shards. Imagine a 4 node cluster where one node is removed and as a result nodes A,B, and C all receive some of node D's shards.
Node A completes bootstrapping …

Only trigger bootstrap on topology change if node receives new shards

---

src/query/api/v1/handler/topic/common.go
src/query/api/v1/handler/topic/common_test.go
src/query/api/v1/handler/topic/delete.go
src/query/api/v1/handler/topic/delete_test.go
src/query/api/v1/handler/topic/get_test.go

Users may need to delete m3msg topics.
Fixes #
```release-note
Added support for deleting m3msg topics in coordinator API
```
```documentation-note
None
```

[query] topic api: support DELETE on /topic

---

src/dbnode/client/client_mock.go
src/dbnode/client/options.go
src/dbnode/client/session.go
src/dbnode/client/session_fetch_test.go
src/dbnode/client/session_proto_test.go
src/dbnode/client/session_test.go
src/dbnode/client/types.go

Existing implementation would silently return zero results instead of an error if proto mode was enabled but the provided namespace did not have a known schema.

[DBnode] Return error in M3DB client if proto mode is enabled and trying to read from namespace with no known schema

---

scripts/docker-integration-tests/common.sh
scripts/docker-integration-tests/prometheus_replication/docker-compose.yml
scripts/docker-integration-tests/prometheus_replication/m3coordinator01.yml
scripts/docker-integration-tests/prometheus_replication/m3coordinator02.yml
scripts/docker-integration-tests/prometheus_replication/test.sh
scripts/docker-integration-tests/run.sh
src/query/api/v1/handler/prometheus/remote/write.go

This adds an integration test for Prometheus remote write replication to other downstreams for best effort replication purposes.
```release-note
NONE
```
```documentation-note
NONE
```

Add Prometheus remote write forwarding integration test

---

.goreleaser.yml

This adds the m3aggregator to the release binaries.
```release-note
NONE
```
```documentation-note
NONE
```

[aggregator] Add aggregator to release binaries

---

src/dbnode/client/replicated_session.go

Remove redundant error format string from replicate error (zap doesn't need format string)

Fixed error format

---

src/dbnode/client/replicated_session.go
src/dbnode/client/replicated_session_test.go

Sync and async sessions in replicated sessions all use the same scope for reporting metrics. This PR adds a subscope for each async session such that their metrics may be separated from one another.

Create subscope for async sessions

---

docs/operational_guide/namespace_configuration.md

Change to recommend that:
- index blockSize match DB blockSize
- blockSize be based on resolution instead of retention
Updates the docs with newer blocksize recommendations
**Special notes for your reviewer**: based on converstations with @robskillington 
Also, I'm not sure if the index options could be changed without creating a new namespace, but it seemed that logically the answer should be `no` and that seemed like the better default.
```release-note
NONE
```
```documentation-note
updated namespace configuration doc
```

[docs] update blocksize recommendations

---

scripts/docker-integration-tests/carbon/test.sh
src/query/api/v1/handler/graphite/render_test.go
src/query/graphite/storage/m3_wrapper.go
src/query/graphite/storage/m3_wrapper_test.go

Graphite fetches would always be truncated to start point, which can cause flapping when refreshing a series.
-
```release-note
None
```
```documentation-note
None
```

[query] Graphite fetches truncated to resolution

---

scripts/development/m3_stack/m3coordinator.yml
scripts/docker-integration-tests/aggregator/m3coordinator.yml
scripts/vagrant/provision/manifests/m3coordinator-two.yaml

Previously all config references to the worker pool size for the coordinator was 100 which is far too small for concurrent writes to M3DB for production workloads when aggregator sends metrics to the coordinators over m3msg.
This raises the default to a sane 10000.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Fix default worker pool size for m3msg ingester

---

.goreleaser.yml
CHANGELOG.md

We set `CGO_ENABLED=0` in our make targets, but hadn't been doing so in
our `goreleaser` config. Disabling cgo ensures our builds will work
across OS's that may use different libc implementations.
Fixes #2003
```release-note
Ensure cgo is disabled in release binaries
```
```documentation-note
```

[build] goreleaser: ensure cgo disabled in build

---

CHANGELOG.md
config/README.md
glide.lock
glide.yaml
src/x/config/config.go
src/x/config/config_test.go

This PR switches the x/config package to use the `go.uber.org/config` under the hood. This has the following advantages:
1. Supports deep config merging out of the box.
2. Supports env var interpolation (this will let us deprecate the code in `config/listenaddress` in a separate PR).
3. Equally lightweight (just a dep on `yaml`: https://github.com/uber-go/config/blob/master/glide.yaml  )
Fixes #
```release-note
Switch to go.uber.org/config: this adds env var interpolation for strings in the format: ${ENV_VAR}. Users should be unaffected except in the rare case that they have strings of this form in their config.
``` …

[x/config] Switch to using go.uber.org/config library in x/config

---

Makefile

Running `make services` will eventually execute the `build-ui-ctl-statik` target. This target unconditionally runs `statik` to generate the file `src/ctl/generated/ui/statik/statik.go`. By default, `statik` will include the time at which it is run in the file that it generates. This has the unfortunate consequence that running `make services` modifies the code base though. Since we unconditionally run `statik` we can set the `-m` flag to ensure that `statik` includes a constant modification time in the output that it generates, thereby ensuring that the file it generates is deterministic.

[build] Use constant modification time when generating statik files

---

glide.lock
glide.yaml

In my previous [diff](https://github.com/m3db/m3/pull/2016) I added go.uber.org/config as a dependency using `glide get`. For my attempt to do things the right way, glide helpfully reverted many of our dependencies to a later version: https://pastebin.com/87uuRpfH
Look at the individual commits for a better view of the diff (this should be landed atomically, which is why I didn't stack).
```release-note
NONE
```
```documentation-note
NONE
```

[build] Fix glide 

---

src/dbnode/namespace/schema_registry.go
src/dbnode/namespace/schema_registry_updater.go

This was confusing as an operator since this is not an error state, it is the regular expected case when operating a DB node with namespaces that are not configured with protobuf schemas.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix overzealous log message for missing schema with non-protobuf namespace

---

src/query/api/v1/handler/prometheus/native/read.go
src/query/api/v1/handler/prometheus/remote/read.go

Adds metrics for latency on the remote read path

[query] Add latency metrics to remote reads

---

src/x/config/config.go
src/x/config/config_test.go

My previous config PR didn't have the default behavior I expected it to--go.uber.org/config only expands env vars if you pass it the option. 
I made x/config pass os.LookupEnv as an option to the config library by default.
```release-note
${VAR_NAME} strings will now actually be expanded.
```
```documentation-note
NONE
```

Make expand work by default

---

src/cmd/services/m3query/config/config.go
src/query/api/experimental/annotated/handler.go
src/query/api/experimental/annotated/handler_test.go
src/query/api/experimental/annotated/iter.go
src/query/api/experimental/annotated/iter_test.go
src/query/api/v1/handler/types.go
src/query/api/v1/httpd/handler.go

Adds an experimental API group to the coordinator for handling annotated metric write requests.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Add experimental API support for writing annotated samples

---

src/query/api/experimental/annotated/handler.go
src/query/api/v1/handler/prometheus/remote/write.go
src/query/api/v1/handler/prometheus/remote/write_test.go
src/query/api/v1/httpd/handler.go

Ensure the Prometheus remote write handlers use a consistent set of labels.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Ensure Prometheus handlers use consistent set of labels

---

src/dbnode/persist/fs/index_read.go
src/dbnode/storage/index/block.go
src/dbnode/storage/index/compaction/compactor.go
src/dbnode/storage/index/read_through_segment.go
src/m3ninx/index/segment/fst/segment.go
src/m3ninx/index/segment/segment_mock.go
src/m3ninx/index/segment/types.go
src/x/instrument/invariant.go
src/x/mmap/mmap_linux.go
src/x/mmap/mmap_other.go

Currently, memory usage scales w/ the size of the index up until retention. This is due to flushed index segment files being mmap'ed into memory and remaining in memory after we take a checksum. This PR naively frees file backed mmap'ed memory pages every Tick.
Left a `TODO` for implementing a more sophisticated free strategy in the future.
```release-note
- Reduce index memory usage.
```
No.

[dbnode] Make index memory RSS usage flat block over block

---

src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
src/dbnode/storage/bootstrap/process.go

Fixes issue #2051 on master with the latest bootstrapping changes, the commit log bootstrapper was attempting to bootstrap data from shards it no longer owned.
Followup change with an integration test to catch this case will follow.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix bootstrapping data for an unowned shard with commit log

---

src/query/api/v1/handler/prometheus/native/common.go
src/query/api/v1/handler/prometheus/native/common_test.go
src/query/api/v1/handler/prometheus/native/read.go
src/query/api/v1/handler/prometheus/native/read_instantaneous.go
src/query/api/v1/handler/prometheus/native/read_instantaneous_test.go
src/query/api/v1/httpd/handler.go
src/query/api/v1/httpd/handler_test.go

**What this PR does / why we need it**: Allow POST requests in coordinator read APIs. Supports common use cases such as Grafana datasources that use POST.
Fixes #
```release-note
Allow query requests to be GET or POST
```
```documentation-note
```

[query] Allow GET + POST for read APIs

---

src/dbnode/persist/fs/read_write_test.go
src/dbnode/persist/fs/write.go
src/dbnode/persist/fs/write_test.go

This P.R fixes a bug in the fileset writer that would trigger a (near) infinite loop when the writer was reused after the previous set of files encountered an error trying to write out their index files. The P.R includes a regression test to ensure the issue doesn't crop up again and verify the included fix.
The bug was caused by the following sequence of events:
1. For some reason (root cause still pending on that) writing out a set of fileset files encountered an error during the call to `Close()`, likely that duplicate series IDs had been written into the fileset file which will cause the writer to error out when it tries to write its index-related files.
2. The writer is reused for writing out an entirely different set of fileset files. Normally this is fine since the call to `Open()` …

Fix (almost) infinite loop in Fileset writer when previous fileset encountered an error writing out index files

---

src/dbnode/client/config.go

`PooledWorkerPool` is already instrumented so this PR just passes in instrument options during instantiation.

Instrument async replication worker pool utilization

---

docs/faqs/index.md

Fixes #
```release-note
```
```documentation-note
```

[docs] Add docs for num unique time series

---

src/x/sync/pooled_worker_pool.go

The existing instrumentation in `PooledWorkerPool` emits the number of workers currently in the pool. This PR instruments the number of workers currently engaged in work, so that a utilization percentage may be calculated.

Added gauge for the number of active routines

---

src/cmd/services/m3aggregator/main/main.go
src/cmd/services/m3collector/main/main.go
src/cmd/services/m3coordinator/main/main.go
src/cmd/services/m3ctl/main/main.go
src/cmd/services/m3dbnode/main/main.go
src/cmd/services/m3query/main/main.go
src/collector/server/server.go
src/dbnode/server/server.go
src/query/server/server.go

`etcd.SetGlobals(...)` was mutating stdlib `log.Fatal(..)` from emitting config error loads being printed to stdout/stderr. 
Until a logger is built, always use `fmt.Fprintf(os.Stderr, ...)` so that no other packages can redirect output intended to be printed by the process for fatal errors.
```release-note
NONE
```
```documentation-note
NONE
```

Use fmt.Fprintf(os.Stderr, ..) instead of stdlib log.Fatal(..) to ensure config errors always print

---

src/cmd/services/m3coordinator/ingest/carbon/ingest.go
src/cmd/services/m3query/config/config.go

Allows multiple graphite rules to be matched.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Add continue to rule when matching Graphite rules

---

src/query/block/info.go
src/query/block/info_test.go

Fixes a bug in block info wrapping, adds tests

[query] Fix block info wrapping

---

src/dbnode/integration/index_block_flush_test.go

Fixes CI flakiness with the previous aggressive timeouts.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix TestIndexBlockFlush CI flakiness by allowing for longer stalls

---

scripts/vagrant/docker/daemon_nvme.json
scripts/vagrant/multi/Vagrantfile
scripts/vagrant/provision/setup_privileged.sh
scripts/vagrant/shared/ssh.sh
scripts/vagrant/shared/tunnel.sh

Adds shareable scripts for ssh/tunneling to vagrant boxes. Supports azure nvme disks.
```release-note
NONE
```
```documentation-note
NONE
```

Shareable Vagrant Scripts && Azure NVMe Disk Support

---

scripts/docker-integration-tests/carbon/expected/a.b.json
scripts/docker-integration-tests/carbon/expected/a.ba.json
scripts/docker-integration-tests/carbon/expected/a.json
src/query/api/v1/handler/graphite/find.go
src/query/api/v1/handler/graphite/find_parser.go
src/query/api/v1/handler/graphite/find_test.go

Fixes issue where graphite find result for a node that is both a leaf and has children would not display the leaf case.

[query] Fix bug in graphite find result

---

src/dbnode/storage/index/aggregate_results.go
src/dbnode/storage/index/aggregate_results_test.go
src/dbnode/storage/index/aggregate_values.go

This allows empty term values to be returned for aggregate index values requests. This helps when using M3DB as a generic metric store and generic TSDB since differentiating a field that exists with empty string and a field that doesn't exist at all can be helpful for some use cases. 
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Allow returning empty term values from aggregate index values RPC

---

src/dbnode/storage/shard.go
src/dbnode/storage/shard_race_prop_test.go
src/dbnode/storage/shard_test.go

Fixes #2127
```release-note
NONE
```
```documentation-note
NONE
```

Remove nested read lock to prevent deadlock

---

src/dbnode/storage/shard_race_prop_test.go

Follow up from PR https://github.com/m3db/m3/pull/2128#discussion_r373260862

Make number of series a property of prop test

---

src/cluster/kv/util/runtime/value.go
src/x/watch/options.go
src/x/watch/value.go
src/x/watch/value_test.go

**What this PR does / why we need it**: Ensures that all watch errors will include the key they're watching. Sometimes loggers have enough context to include this error, but not always. Should make watch errors less ambiguous.
This doesn't fully fix the problem as we don't have access to the raw etcd key, but should make some cases less difficult to debug.
Before:
```json
{"level":"fatal","ts":1581361983.0189734,"msg":"error creating aggregator options","error":"initializing value error:init watch timeout"}
```
After:
```json
{"level":"fatal","ts":1581362476.4911253,"msg":"error creating aggregator options","error":"initializing value error (key='m3aggregator'): init watch timeout"}
```
Fixes #
**Does this PR introduce a user-facing and/or backwards …

[kv] Include key name in watch errors

---

src/aggregator/aggregator/handler/trafficcontrol/controller.go
src/msg/producer/writer/consumer_service_writer.go
src/msg/producer/writer/writer.go

**What this PR does / why we need it**: Allows for more verbose errors. Similar to #2138.
Fixes #
```release-note
```
```documentation-note
```

[m3msg] Set key on value watches

---

src/query/api/v1/handler/placement/common.go
src/query/api/v1/handler/placement/delete.go
src/query/api/v1/handler/placement/delete_all.go
src/query/api/v1/handler/placement/delete_all_test.go
src/query/api/v1/handler/placement/delete_test.go

Keys related to the aggregator were not being cleaned up after placement deletion and as such there's no way to really cleanly reset an environment after aggregator has been setup (i.e. coordinator placement deleted, aggregator placement deleted and aggregator topic deleted).
Here were the remaining keys that should be removed if they still exist after placement deletion:
```
$ ETCDCTL_API=3 etcdctl get --prefix '' --keys-only| grep shard
_kv/default_env/shardset/1/flush
_kv/default_env/shardset/2/flush
_kv/default_env/shardset/3/flush
_kv/default_env/shardset/4/flush
_kv/default_env/shardset/5/flush
_kv/default_env/shardset/6/flush
_kv/default_env/shardset/7/flush
_kv/default_env/shardset/8/flush
_kv/default_env/shardset/9/flush
```
**Special notes …

[coordinator] Delete related etcd keys when aggregator placement deleted

---

scripts/docker-integration-tests/prometheus/test.sh
scripts/docker-integration-tests/simple_v2_batch_apis/test.sh
scripts/vagrant/provision/manifests/kube-prometheus/0prometheus-operator-clusterRole.yaml
scripts/vagrant/provision/manifests/kube-prometheus/0prometheus-operator-deployment.yaml
scripts/vagrant/provision/manifests/kube-prometheus/grafana-deployment.yaml
scripts/vagrant/provision/manifests/kube-prometheus/kube-state-metrics-deployment.yaml
scripts/vagrant/provision/manifests/kube-prometheus/node-exporter-daemonset.yaml
scripts/vagrant/provision/manifests/kube-prometheus/prometheus-adapter-deployment.yaml
scripts/vagrant/provision/manifests/kube-prometheus/prometheus-roleSpecificNamespaces.yaml
scripts/vagrant/provision/manifests/m3db-primary.yaml
scripts/vagrant/provision/manifests/m3db-secondary.yaml
scripts/vagrant/provision/manifests/operator.yaml
scripts/vagrant/provision/setup_kube.sh
scripts/vagrant/provision/setup_unprivileged.sh

Updates `kind` version so it creates a `default` `StorageClass` that uses `local-path-provisioner` to create persistent volumes.
Also upgrades prom/kube operators since kind/kube APIs changed as well.
```release-note
None
```
```documentation-note
None
```

Update kind & kube/prom operators

---

scripts/docker-integration-tests/aggregator/m3aggregator.yml
scripts/docker-integration-tests/aggregator/m3coordinator.yml
scripts/docker-integration-tests/aggregator/test.sh
scripts/docker-integration-tests/run.sh
src/query/api/v1/handler/topic/add.go
src/query/api/v1/handler/topic/common.go
src/query/api/v1/handler/topic/common_test.go
src/query/api/v1/handler/topic/delete.go
src/query/api/v1/handler/topic/get.go
src/query/api/v1/handler/topic/init.go

**What this PR does / why we need it**: We previously had not been taking the `Cluster-Environment-Name` and `Cluster-Zone-Name` headers into account in the topic handler. Users rely on these for namespace and placement handlers. This updates the topic handlers to respect them as well.
Fixes #
```release-note
```
```documentation-note
```

[query] api: Respect env+zone headers in topic

---

src/aggregator/client/config.go
src/aggregator/client/options.go

The default was also vastly too small for workloads with a lot of metrics being sent to a single aggregator instance. 
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Add aggregator client maxBatchSize config for bigger buffer for data sent to aggregator

---

src/dbnode/storage/index/block.go

Prom client doesn't allow registering of keys w/ differing label names. See error:
```
a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"index_block_segment_free_mmap\", help: \"index_block_segment_free_mmap counter\", constLabels: {}, variableLabels: [result skip_type]} has different label names or a different help string
```
```release-note
NONE
```
```documentation-note
NONE
```

Align index block metric labels.

---

src/cmd/services/m3dbnode/config/config.go
src/cmd/services/m3dbnode/config/config_test.go
src/dbnode/client/config.go
src/dbnode/client/options.go
src/dbnode/server/server.go
src/dbnode/x/tchannel/options.go
src/query/storage/m3/config.go

Set defaults and allow configuration of tchannel options `MaxIdleTimeout` and `IdleCheckInterval` to allow cleaning up of idle tchannel connections.
```release-note
NONE
```
```documentation-note
NONE
```

Set defaults and expose configuration of tchannel timeouts.

---

src/dbnode/integration/dynamic_namespace_add_test.go
src/dbnode/storage/block/lease.go

Fixes #2155 .
```release-note
NONE
```
```documentation-note
NONE
```

Add regression test for and fix deadlock.

---

docs/how_to/kubernetes.md
kube/bundle.yaml
kube/m3dbnode-statefulset.yaml

**What this PR does / why we need it**: Updates Kubernetes manifests to ensure M3DB containers can raise their permissions.
Fixes #
```release-note
```
```documentation-note
```

[kube] Add CAP_SYS_RESOURCE to m3db container

---

src/query/api/v1/handler/placement/replace.go
src/query/api/v1/handler/placement/set.go

We had been serving on `/api/v1/${SVC}/set` rather than
`/api/v1/services/${SVC}/set`.
Fixes #
**Does this PR introduce a user-facing and/or backwards incompatible change?**: **YES**
```release-note
Fix routes that m3coordinator + m3aggregator `/replace` and `/set` routes are served on. WARNING: this is a breaking change to fix a bug in route naming. We are not aware of any users leveraging these APIs, but if you are you will have to update `/api/v1/${SVC}/set` to `/api/v1/services/${SVC}/set`.
```
```documentation-note
NONE
```

[query] api: Fix agg+coord set+replace routes

---

src/dbnode/storage/series/buffer.go
src/dbnode/storage/series/buffer_test.go

During a cold flush, we first collect all the block starts that require cold flushing. This includes two cases:
1. Any block that has a cold bucket with new un-flushed writes (a "writable bucket")
2. Any block that has a cold bucket with writes that have failed to flush completely
After getting all these blocks, we go through each one to fetch data and compact.
Therefore when fetching data for a ColdFlush, encountering a block that has no writable bucket is not an error, since that means we're hitting case (2).
Please see the section explaining bucket versions [here](https://m3db.github.io/m3/m3db/architecture/engine/#buffer) for more context if needed.
**Does this PR introduce a user-facing and/or backwards …

Don't return error on missing writable bucket during cold flush

---

src/dbnode/encoding/encoding_mock.go
src/dbnode/encoding/iterator_test.go
src/dbnode/encoding/multi_reader_iterator.go
src/dbnode/encoding/series_iterator.go
src/dbnode/encoding/series_iterator_test.go
src/dbnode/encoding/types.go

Exposes SchemaDescr on the MultiReaderIterator interface

[dbnode] Expose SchemaDescr on MultiReaderIterator

---

scripts/docker-integration-tests/prometheus/test.sh
src/aggregator/aggregation/counter.go
src/aggregator/aggregation/counter_test.go
src/aggregator/aggregation/gauge.go
src/aggregator/aggregation/gauge_test.go
src/aggregator/aggregation/options.go
src/aggregator/aggregation/options_test.go
src/aggregator/aggregation/timer_benchmark_test.go
src/aggregator/aggregation/timer_test.go
src/aggregator/aggregator/aggregation.go
src/aggregator/aggregator/aggregation_test.go
src/aggregator/aggregator/counter_elem_gen.go
src/aggregator/aggregator/elem_base.go
src/aggregator/aggregator/elem_base_test.go
src/aggregator/aggregator/elem_test.go
src/aggregator/aggregator/gauge_elem_gen.go
src/aggregator/aggregator/generic_elem.go
src/aggregator/aggregator/timer_elem_gen.go
src/aggregator/integration/integration_data.go
src/aggregator/integration/multi_server_forwarding_pipeline_test.go

We've noticed that at times a bunch of values for the same gauge can arrive at the same time to the aggregator with a varying set of timestamps, gauge last value aggregation should take the last value by timestamp not by arrival time to account for this. 
```release-note
NONE
```
```documentation-note
NONE
```

[aggregator] Take last value by value timestamp not arrival time

---

.goreleaser.yml

Without specifying architecture goreleaser by default builds both amd64 and i386. To speed up releases this makes m3query only build amd64 like all our other binaries.
```release-note
NONE
```
```documentation-note
NONE
```

[goreleaser] Only build amd64 architecture for m3query releases

---

src/msg/protocol/proto/decoder.go
src/msg/protocol/proto/roundtrip_test.go

On the occasion that a message is sent over max size, it can cause large allocations. This avoids increasing the buffer before checking if over max size to avoid these large allocations when this occurs.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Ensure does not grow M3Msg buffer if message over max size

---

src/query/storage/m3/storage.go
src/query/storage/m3/storage_test.go

Fixes checked debug log being reused, which is unsafe.
```release-note
NONE
```
```documentation-note
NONE
```

[query] Fix namespace resolve debug log not being written with multiple namespaces

---

src/dbnode/storage/bootstrap.go

BootstrappedAndDurable is what is reported as "bootstrapped" by `/health` endpoint. Adding this metric gives us visibility in this database status without hitting the endpoint for that information.
```release-note
NONE
```
```documentation-note
NONE
```

Add metric for BootstrappedAndDurable

---

src/cmd/services/m3coordinator/ingest/m3msg/config.go
src/cmd/services/m3coordinator/ingest/m3msg/ingest_test.go
src/query/server/query.go
src/query/server/query_test.go

Previously the default tag options were being used for the M3Msg ingester with the coordinator, this uses the configured tag options for the coordinator with the M3Msg ingester.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Use tag options specified in config with M3Msg ingester

---

src/m3ninx/index/segment/builder/multi_segments_field_postings_list_iter.go
src/m3ninx/index/segment/builder/multi_segments_field_postings_list_iter_test.go
src/m3ninx/index/segment/builder/multi_segments_multi_key_postings_list_iter.go
src/m3ninx/index/segment/builder/multi_segments_terms_iter.go

Need to account for negative/positive offsets when building per field postings lists from multiple segments.
Also adds a test to verify that per field postings lists built from multiple segments is correct.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Account for Neg/Pos Offsets when building per field roaring bitmap posting lists

---

src/cmd/services/m3coordinator/downsample/downsampler_test.go
src/cmd/services/m3coordinator/downsample/metrics_appender.go
src/metrics/policy/storage_policy.go

After seeing mapping rules in use, it's become obvious that default aggregations should not honored if a matching mapping rule already specifies an aggregation for the same storage policy (retention + resolution). Letting both apply will cause race conditions on which aggregated value makes it to storage with the same metric name and tags.
This keeps the current behavior as is however will remove any applicable default aggregations for aggregated namespaces defined if a mapping rule has already been applied for the given storage policy (retention + resolution).
```release-note
NONE
```
**Does this PR require updating code package or …

[coordinator] Only honor default aggregation policies if not matched by mapping rule

---

src/cluster/mem/mem.go
src/cluster/mem/mem_test.go

This adds a small testing utility to back a `cluster/client.Client` with an in-memory kv.Store. We have the `cluster/kv/mem` implementation of kv.Store, but there's currently no way to back a `cluster/client.Client` with it. Construction of the kv.Store is tightly coupled with etcd in the current class; having a separate class seemed like a reasonable way to do this given the current code, but we could consider a more dependency injection style for that--let me know if you want to hash that out.
```release-note
NONE
```
```documentation-note
NONE
```

Add an in memory implementation of cluster/client.Client

---

src/query/api/v1/handler/prometheus/native/read.go
src/query/api/v1/handler/prometheus/native/read_instantaneous.go
src/query/api/v1/handler/prometheus/remote/read.go
src/query/api/v1/handler/search.go

This helps debug whether timeout's are being applied as expected, and also which errors are causing which logged errors operators encounter.
```release-note
NONE
```
```documentation-note
NONE
```

[query] Log query errors with query params

---

scripts/development/m3_stack/docker-compose.yml
scripts/development/m3_stack/start_m3.sh
src/query/server/cost_reporters.go
src/query/server/cost_reporters_test.go
src/query/server/query.go
src/query/server/query_test.go
src/x/close/close.go

We had correctly registered the limit metrics (the global limit metrics at least, not per query limit metrics) but had not kicked off reporting after creating the limiters. This adds the kick off required to report metrics.
```release-note
NONE
```
```documentation-note
NONE
```

[query] Fix query limit metrics reporting not starting at startup

---

src/msg/producer/buffer/buffer.go

This PR makes the errBufferFull in m3msg producer public, so the caller can handle this err appropriately.
No
No

[msg] Make errBufferFull public

---

Makefile
tools.json

Kubeval depends on `hashicorp/go-multierror`, which now depends on
go1.13 error methods.
Fixes #
```release-note
```
```documentation-note
```

[ci] Temporarily disable kubeval validation

---

docker/m3dbnode/Dockerfile
docker/m3dbnode/Dockerfile-setcap
docker/m3dbnode/development.Dockerfile

This keeps memory profile lower at the expense slightly slower allocation speed. Since we memory pool a lot of our data structures we don't usually face the allocation slow down, we'd prefer lower memory profiles with larger heap sizes.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Use madvdontneed=1 for GODEBUG flags

---

src/dbnode/storage/bootstrap/result/shard_ranges.go
src/dbnode/storage/bootstrap/result/shard_ranges_test.go

ShardTimeRanges `AddRanges` must clone the shard ranges if it does not exist before setting the ranges for the shard.
```release-note
NONE
```
```documentation-note
NONE
```

ShardTimeRanges AddRanges Clone if Not Exists

---

src/query/functions/linear/histogram_quantile.go
src/query/functions/linear/histogram_quantile_test.go

Fixes the histogram part of #2214

[query] fix a bug when building histograms

---

src/query/api/v1/handler/prometheus/handleroptions/options.go
src/query/api/v1/handler/prometheus/remote/write.go

Adds the ability to add headers to outgoing forwarded remote write requests.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Add headers to along with request to remote write forward target

---

src/query/plan/physical.go
src/query/plan/physical_test.go

The offset was applied to series start twice; once in physical plan (removed here), then again on query execution. What this did was fetch the range [ `start-offset*2`-`end-offset` ] rather than [ `start-offset`-`end-offset` ]
The data would then be removed before values are returned, but this may cause a lot of additional data with large offsets

[query] Fix offset fetching too much data

---

src/dbnode/persist/fs/files.go
src/dbnode/persist/fs/files_test.go
src/dbnode/persist/fs/on_disk_segments.go
src/dbnode/persist/fs/segments.go
src/dbnode/persist/fs/types.go
src/dbnode/persist/schema/types.go
src/dbnode/storage/bootstrap/result/shard_ranges.go
src/dbnode/storage/bootstrap/result/shard_ranges_test.go
src/dbnode/storage/bootstrap/result/types.go
src/dbnode/storage/cleanup.go
src/dbnode/storage/cleanup_test.go
src/dbnode/storage/fs.go
src/dbnode/storage/fs_test.go
src/dbnode/storage/index.go
src/dbnode/storage/index_test.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go

Clean up dupe index segments from disk.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Cleanup duplicate index segments from disk

---

integrations/grafana/m3db_dashboard.json

Having 2 refIds that are identical in the same panel causes grafana to be unable to load the panel. This sets the 2nd query to be a different refId
n/a
```release-note
NONE
```
```documentation-note
NONE
```

[docs] fix refId for Persitence graph

---

src/dbnode/persist/fs/files.go
src/dbnode/persist/fs/files_test.go
src/dbnode/persist/fs/segments.go
src/dbnode/persist/fs/types.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
src/dbnode/storage/bootstrap/bootstrapper/commitlog/source_data_test.go
src/dbnode/storage/bootstrap/result/shard_ranges.go
src/dbnode/storage/bootstrap/result/shard_ranges_test.go
src/dbnode/storage/cleanup.go
src/dbnode/storage/cleanup_test.go
src/dbnode/storage/index.go
src/dbnode/storage/index_test.go
src/x/time/range_iter.go
src/x/time/range_iter_test.go

Fixes on disk index dedupe and is superset logic for shard time ranges. Deduping should be done w/in a block. 
Also grabs all fileset files paths when reading index info files.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix dedupe/superset logic

---

src/dbnode/persist/fs/persist_manager.go
src/dbnode/persist/persist_mock.go
src/dbnode/persist/types.go

Allows closing of persist manager resources.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Persist manager close resources

---

src/dbnode/storage/bootstrap/bootstrapper/peers/source.go

Decouples the index builder from the lifetime of the peers bootstrapper.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Decouple index builder from lifetime of peers bootstrapper.

---

src/dbnode/server/server.go

By default we need to be using histogram timers for anything constructed with `instrument.NewTimer` otherwise we get highly degraded performance when using Prometheus summaries for DB node.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Use histogram by default for instrument.NewTimer in DB node

---

src/dbnode/storage/bootstrap/bootstrapper/commitlog/source.go
src/dbnode/storage/bootstrap/bootstrapper/fs/source.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source.go

Fixes some zap field types to display e.g. `"took":"6m42.895234s"` vs `"took":404.830821181`

[logging] Update types on some log fields

---

src/dbnode/storage/errors/types.go
src/dbnode/storage/series/buffer.go
src/dbnode/storage/series/buffer_test.go

Adds a much more debuggable message when writing datapoints outside of retention.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Add verbose out of retention errors

---

src/dbnode/storage/series/buffer.go
src/dbnode/storage/series/buffer_test.go

Record buffer first writes as now. Also don't set if the bucket write value is zero. 
Adds tests for first write.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix first write logic

---

src/dbnode/storage/index.go
src/dbnode/storage/index/block.go
src/dbnode/storage/index/index_mock.go
src/dbnode/storage/index/mutable_segments.go
src/dbnode/storage/index/types.go
src/dbnode/storage/index_test.go
src/dbnode/storage/namespace.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go

Adds knowledge of cold mutable segs to an index block. Also exposes APIs to rotate cold segs and evict them. 
Handle both cases in namespace cold flush.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Add cold mutable segs and expose APIs to rotate/evict

---

src/dbnode/storage/index/block.go

Need to read from cold mutable segments in the read path. Also need to operate upon cold mutable segments in a few places.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Operate upon on cold mutable segments in index block

---

src/dbnode/storage/index.go
src/dbnode/storage/shard.go
src/dbnode/storage/shard_index_test.go

Removes prior optimization preventing cold writes from making it into shard index queue. Also immediately seal cold index blocks when we create them. 
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Let cold writes through and seal cold created index blocks

---

src/query/api/v1/handler/prometheus/remote/read.go

Sets the `M3-Results-Limited` header in /prom/remote/read?**format=json** responses. 
Oneliner.
NONE
NONE

[query] Set warning headers in remote read debug endpoint (json format)

---

src/dbnode/client/client_mock.go
src/dbnode/client/connection_pool.go
src/dbnode/client/connection_pool_test.go
src/dbnode/client/options.go
src/dbnode/client/session_fetch_high_concurrency_test.go
src/dbnode/client/types.go

Adds better control over tchannel clients. Allows for easier experimentation with third party plugins.

[dbnode] Add option for experimental TChannel client use

---

src/cmd/services/m3dbnode/config/bootstrap.go
src/cmd/services/m3dbnode/config/config_test.go
src/dbnode/storage/bootstrap/bootstrapper/peers/options.go

Adds ability to tweak from config the parallelism for shard concurrency from config.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Add ability to configure peer streaming shard concurrency

---

src/dbnode/integration/serve.go
src/dbnode/network/server/tchannelthrift/node/options.go
src/dbnode/network/server/tchannelthrift/node/server.go
src/dbnode/server/options.go
src/dbnode/server/server.go

Adds better control over tchannel servers. Allows for easier experimentation with third party plugins.

[dbnode] Add option for experimental TChannel server use

---

src/dbnode/storage/index/block.go
src/dbnode/storage/index/mutable_segments.go

Remove `Evict()` API from `mutableSegments` and call `Close()` instead.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Clean up mutable segment resources

---

src/query/executor/transform/exec.go
src/query/functions/aggregation/base_test.go
src/query/functions/aggregation/count_values_test.go
src/query/functions/aggregation/quantile_test.go
src/query/functions/utils/group.go
src/query/functions/utils/group_test.go
src/query/test/comparison.go

This sorts grouped aggregate outputs by tags (in a way that is Prometheus compatible).
Previously the results were ordered non deterministically.
NONE
NONE

[query] Sort grouped aggregate outputs by tags

---

src/cmd/services/m3coordinator/ingest/m3msg/ingest.go
src/cmd/services/m3coordinator/ingest/m3msg/ingest_test.go

This makes sure bad request and invalid params errors being returned for writes from ingesting aggregated metrics are always written to the log. Helps sample rate impact seeing invalid params/bad request errors.
```release-note
NONE
```
```documentation-note
NONE
```

[coordinator] Ingesting aggregated metrics with invalid params should always log error

---

src/query/api/v1/handler/graphite/find.go
src/query/api/v1/handler/graphite/render_parser.go
src/query/api/v1/handler/openapi/openapi.go
src/query/api/v1/handler/prom/common.go
src/query/api/v1/handler/prometheus/common_test.go
src/query/api/v1/handler/prometheus/native/common_test.go
src/query/api/v1/handler/prometheus/native/complete_tags.go
src/query/api/v1/handler/prometheus/native/list_tags.go
src/query/api/v1/handler/prometheus/native/read.go
src/query/api/v1/handler/prometheus/remote/match.go
src/query/api/v1/handler/prometheus/remote/read.go
src/query/api/v1/handler/prometheus/remote/read_test.go
src/query/api/v1/handler/prometheus/remote/tag_values.go
src/query/api/v1/handler/search_test.go
src/x/net/http/response.go

We had been sending the wrong Content-Type value that our middleware
inferred. With this change, we'll be able to send gzip'd responses but
browsers will know to decompress to HTML.
Before:
```
$ curl -sv -H "Accept-Encoding: gzip" http://localhost:7201/api/v1/openapi
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 7201 (#0)
> GET /api/v1/openapi HTTP/1.1
> Host: localhost:7201
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: accept, content-type, authorization
< Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
< Access-Control-Allow-Origin: *
< Content-Encoding: gzip
< Date: Thu, 11 Jun 2020 16:22:15 GMT
< Content-Length: 420
< Content-Type: application/x-gzip <<< BAD
```
After:
```
$ …
```

[query] Fix Content-Type for OpenAPI handler

---

src/query/api/v1/httpd/handler.go

A fix for:
```
{"level":"error","ts":1591814855.3818853,"msg":"register metric error","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"query_fetch_success\", help: \"query_fetch_success counter\", constLabels: {}, variableLabels: [handler]} has different label names or a different help string"}
{"level":"error","ts":1591814855.3826127,"msg":"register metric error","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"query_fetch_errors\", help: \"query_fetch_errors counter\", constLabels: {}, variableLabels: [handler code]} has different label names or a different help string"}
{"level":"error","ts":1591814855.3828459,"msg":"register metric error","error":"a …
```

[query] Fix metrics registration issue for nativePromReadInstantHandler

---

src/m3ninx/index/segment/builder/builder.go
src/m3ninx/index/segment/builder/builder_test.go

Fixes duplicate IDs causing an error when creating segments on index flush.  This would have been a transient error, still it was special cased however the error type changed and this should just be a no-op.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix duplicate ID insertions causing transient error when flushing index block

---

scripts/comparator/basic_queries/queries.json
src/query/plan/physical.go
src/query/plan/physical_test.go

Fixes 2 issues in `PhysicalPlan.shiftTime`:
1. `Offset` was not being used when computing time shift.
2. Shift alignment was not working properly, for example it could have changed the shift to zero in some cases (eg. `query=rate(multi_1[1m])&step=5m`).
NONE
NONE

[query] Fix PhysicalPlan.shiftTime

---

scripts/docker-integration-tests/prometheus/test.sh
src/dbnode/storage/index_block_test.go

This reverts commit 669609d3a18392d1c64902259e1705acf2ae7892 from PR #2412.
This was my bad, I accidentally merged a PR that was failing CI.
```release-note
NONE
```
```documentation-note
NONE
```

Revert "[dbnode] Additional require-exhaustive test cases (#2412)"

---

src/dbnode/integration/index_helpers.go
src/dbnode/integration/index_single_node_high_concurrency_test.go
src/dbnode/storage/index/block.go
src/dbnode/storage/index/block_test.go
src/dbnode/storage/index/mutable_segments.go
src/dbnode/storage/stats/query_stats_test.go
src/m3ninx/index/segment/fst/segment.go
src/m3ninx/index/segment/fst/writer_reader_test.go

During segment rotation during in-memory background compaction there is a moment where it is swapped out with the newly compacted segment and during that brief swap of acquiring lock and replacing the segments array there was the possibility a reader could reach a now closed segment which would return an error when executing an index search on that segment. 
This could sometimes be observed at sustained high levels of query concurrency.
This negates that possibility by extending the lifetime of the segment until it is finalized from the view of a segment reader.
```release-note
NONE
```
**Does this PR require updating code package or …

[dbnode] Negate possibility of point in time segment rotation returning query error 

---

docs/common/headers_optional_read_all.md
docs/m3coordinator/api/remote.md
docs/m3query/api/index.md

Adds missing example to docs.
```release-note
NONE
```
```documentation-note
NONE
```

[docs] Add M3-Restrict-By-Tags-JSON example to docs

---

src/dbnode/storage/index.go
src/dbnode/storage/index_test.go

We should always attempt to warm flush sealed blocks to disk if there doesn't already exist data on disk. 
We're checking this instead of `block.NeedsMutableSegmentsEvicted()` since bootstrap writes for cold block starts get marked as warm writes if there doesn't already exist data on disk.
We need this logic so those bootstrap writes properly go through the warm flush lifecycle or else they will never get indexed. 
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Check if data exists on disk for warm index flushes

---

docs/faqs/index.md
docs/operational_guide/bootstrapping_crash_recovery.md
docs/operational_guide/etcd.md
docs/operational_guide/repairs.md

Was looking around the docs, found a few places to improve them.
NONE
NONE

[docs] Minor documentation fixes

---

src/dbnode/storage/cluster/database.go

Fixes #2257. Allows for alerting to be done based on existing shard available/etc metrics.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Expose cluster total shards and replicas as metrics

---

src/dbnode/storage/database.go

DB nodes need to be restarted after namespace changes.
Fixes #
```release-note
[dbnode] Add a metric indicating a database restart is required after namespace changes
```
```documentation-note
```

[db] Set gauge when DB requires restart

---

src/dbnode/storage/index.go
src/dbnode/storage/shard.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go

When accumulating the docs to flush in the index, attempt to reference existing allocated docs in the shard’s series (in the shardmap). This should reduce memory spikes in cases where segments are very dense with docs from having high cardinality. 
Looks like cache hit/miss ratio is very strong based on initial testing
```release-note
```
```documentation-note
```

[dbnode] Reference existing doc in shard map on index flush

---

docs/operational_guide/mapping_rollup.md

Add simple rollup rules example.
```release-note
NONE
```
```documentation-note
NONE
```

[docs] Add simple rollup rules example

---

docs/operational_guide/mapping_rollup.md

Fixes #
```release-note
```
```documentation-note
```

[docs] Add more rollup rules docs

---

src/dbnode/storage/index_test.go

CI is failing like so:
```
--- FAIL: TestNamespaceIndexFlushSuccess (0.01s)^M
assertions.go:221: ^M                        ^M     Error Trace:    index_test.go:435^M
^M                      index_test.go:251^M
^M      Error:          Not equal: 11 (expected)^M
!= 12 (actual)^M
```
Looks like the index's view of time and the test data's view of time are out of sync, sometimes causing the index to attempt to flush an extra (non-mocked) block. 
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix namespace index flush test

---

src/dbnode/storage/index_test.go

Fixes flaky TestNamespaceIndexFlushSuccess.
It was failing with `Not equal: 11 (expected) != 12 (actual)` consistently between `hh:00` and `hh:30`, where `xx` is an even hour in UTC (so, 25% of the time). The reason was that production code was taking `idx.bufferPast` (which is 30 mins) into consideration, affecting `persistClosedTimes` and `persistCalledTimes` counters, while the test code was not taking it into consideration, thus sometimes overcounting `numBlocks`.
I'm not 100% sure if my proposed solution is the best, but at least we know the cause.
NONE …

[dbnode] Fix flaky TestNamespaceIndexFlushSuccess

---

docs/m3db/architecture/storage.md
src/dbnode/persist/fs/msgpack/decoder.go
src/dbnode/persist/fs/msgpack/decoder_test.go
src/dbnode/persist/fs/msgpack/encoder.go
src/dbnode/persist/fs/msgpack/encoder_test.go
src/dbnode/persist/fs/msgpack/roundtrip_test.go
src/dbnode/persist/fs/msgpack/schema.go
src/dbnode/persist/fs/read.go
src/dbnode/persist/fs/retriever.go
src/dbnode/persist/fs/seek.go
src/dbnode/persist/fs/write.go
src/dbnode/persist/schema/types.go

Fixes #2628
Adds IndexEntryChecksum field which can be used to validate a single entry in the index file. This PR only encodes and decodes the value. Actual validation will occur in a later PR.
```release-note
NONE
```
```documentation-note
Yes, updated 'docs/m3db/architecture/storage.md' in PR
```

[dbnode] Add IndexEntryChecksum field to entries in index file

---

src/dbnode/integration/large_tiles_test.go

An integration test to test large tiles end to end workflow.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Integration test for large tiles

---

src/query/api/v1/handler/prometheus/remote/read_test.go
src/query/storage/converter.go
src/query/storage/converter_test.go

[query] Auto-set reasonable range on remote match

---

CHANGELOG.md

Add changelog for 0.15.6 release.
```release-note
NONE
```
```documentation-note
NONE
```

[changelog] Update changelog for 0.15.6

---

src/query/api/v1/handler/prometheus/common.go
src/query/api/v1/handler/prometheus/remote/match.go
src/query/api/v1/handler/prometheus/remote/read.go
src/query/api/v1/handler/prometheus/remote/read_test.go
src/query/parser/promql/options.go

Fixes some places where parser functions were called directly rather than through options

[query] Standardize parse function logic

---

Makefile
src/query/storage/index.go
src/query/storage/index_test.go
src/query/test/compatibility/testdata/regression.test
src/query/test/compatibility/testdata/selectors.test
src/query/test/compatibility/testdata/staleness.test

Fixes a recently introduced bug where selector like `{foo=~".*bar"}` would be parsed as a FieldMatcher rather than a RegexMatcher as intended
Fixes #2503

[query] Fix to regexes with leading wildcard

---

CHANGELOG.md

[changelog] 0.15.7

---

src/dbnode/persist/fs/read.go
src/dbnode/persist/fs/types.go
src/dbnode/storage/bootstrap/bootstrapper/fs/source.go
src/dbnode/storage/bootstrap/bootstrapper/peers/source.go
src/dbnode/storage/bootstrap/bootstrapper/readers.go

Avoid sorting index entries in bootstrap paths where only reading series metadata is required. 
Also adds some debug logs and additional tracing instrumentation for enqueuing of data shard readers.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Do not unnecessarily sort index entries in bootstrap paths

---

.buildkite/scripts/docs_push.sh

PR https://github.com/m3db/m3/pull/2524 updated build steps but missed removing a parameter in the buildkite scripts, this PR removes it from there too.

Remove unused parameter from buildkite script

---

src/cluster/placement/placement_mock.go
src/cluster/placement/service/mirrored_custom_groups_test.go
src/cluster/placement/service/operator.go
src/cluster/placement/service/operator_test.go
src/cluster/placement/service/service.go
src/cluster/placement/types.go

This PR splits out some placement service functionality into a stateless `placement.Operator` class; `placement.Service` remains the same.  Currently, `placement.Service` is responsible for both performing manipulations on placement.Placement objects (node adds etc) and for storing the results back. 
This is inconvenient for certain automation cases, where you may need to perform multiple operations on a placement before storing it back. In my particular case, I'm doing:
```
curPlacement := svc.Placement()
// check with external system if placement changes are needed
// do placement changes
svc.CheckAndSet(modifiedPlacement)
``` …

[m3cluster] Split out m3cluster placement service into stateless and stateful classes

---

go.mod
go.sum

For further details see issue https://github.com/m3db/m3/issues/2534. Thanks to @BertHartm and @mmedvede for porting the vellum fix to the M3 fork of vellum that contains performance changes required by M3 that have been unable to be upstreamed.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Fix case insensitive regexp flag implementation for selectors

---

go.mod
go.sum
src/cmd/tools/docs_test/main/main.go

This diff performs some more go.mod version cleanups. Overall goal here is to impose fewer requirements on downstream projects importing M3 as a library. We're only really touching deps around the edges here; fsnotify isn't used by the project (comes through by way of viper, which itself is barely used by the project), and blackfriday (also barely used) can and should be referenced by the gopkg.in/russross/blackfriday.v2 path, to support working in projects which have both v1 and v2.

Use blackfriday.v2 to avoid version conflicts; eliminate fsnotify pin (unused)

---

src/x/pool/object.go
src/x/pool/object_test.go
src/x/unsafe/rand.go

Add rudimentary benchmarks to measure impact of any changes to pooling
Reduce instrumentation and raw get/put overhead due to contention
```
name                                                 old time/op    new time/op    delta
ObjectPoolGetPut                                       68.3ns ± 3%    58.6ns ± 3%  -14.24%  (p=0.000 n=10+10)
ObjectPoolGetPut-2                                     68.0ns ± 1%    58.5ns ± 2%  -13.95%  (p=0.000 n=10+10)
ObjectPoolGetPut-4                                     68.5ns ± 2%    58.0ns ± 1%  -15.36%  (p=0.000 n=10+9)
ObjectPoolGetPut-6                                     68.6ns ± 3%    58.2ns ± 1%  -15.16%  (p=0.000 n=10+10)
ObjectPoolGetPut-8                                     68.3ns ± 2%    58.2ns ± 2%  -14.76% …
```

Reduce ObjectPool overhead

---

src/query/graphite/native/aggregation_functions.go
src/query/graphite/native/aggregation_functions_test.go
src/query/graphite/native/builtin_functions.go
src/query/graphite/native/builtin_functions_test.go

Add graphite function support - groupByNodes
```release-note
NONE
```
```documentation-note
NONE
```

[m3query] Add graphite function support - groupByNodes

---

go.sum
src/dbnode/storage/bootstrap.go
src/dbnode/storage/database.go
src/dbnode/storage/database_bootstrapped_test.go
src/dbnode/storage/flush.go
src/dbnode/storage/flush_test.go
src/dbnode/storage/storage_mock.go
src/dbnode/storage/types.go

Fix one of the few races that are always triggering on my env with go 1.14:
```
--- FAIL: TestRoundtrip (24.25s)
testing.go:906: race detected during execution of test
```
Updates #2540
```release-note
```
```documentation-note
```

Fix races triggered by TestRoundtrip in flushManager and bootstrapManager

---

src/msg/integration/integration_test.go
src/msg/integration/setup.go
src/msg/producer/ref_counted.go
src/msg/producer/writer/message.go
src/msg/producer/writer/message_benchmark_test.go

Fixes various data races in m3msg consumer, producer tests (followup after #2583, updates #2540). 
Consumers are sharing message object pool, which makes go race detector go nuts - as a workaround, simply disabled pooling in `src/msg/integration` test suite.
Also, cleaned up some unnecessary indirection in message structs, should reduce GC overhead overall.
```
name                     old time/op    new time/op    delta
MessageAtomics-12          50.1ns ± 3%    49.8ns ± 1%     ~     (p=0.317 n=5+5)
MessageAtomicsAllocs-12     184ns ± 0%     138ns ± 0%  -25.38%  (p=0.008 n=5+5)
name                     old allocs/op  new allocs/op  delta
MessageAtomics-12            0.00           0.00          ~     (all equal)
MessageAtomicsAllocs-12      5.00 ± …
```

Fix races in m3msg consumer test code

---

src/dbnode/storage/series/buffer.go

Finalizes segment after taking ownership and only close encoder once (`encoder.Discard()` also closes the encoder).
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Finalize seg and only close encoder once

---

src/dbnode/storage/index/convert/convert.go
src/query/graphite/graphite/tags.go

This optimizes converting tags from streamed from peer to use the static pre-allocated Graphite tags they are Graphite tag names. This allows for better use of memory, since the other optimization of using the bytes backed by the ID cannot be done here since Graphite IDs don't contain the Graphite tag names representing each dimension.
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Add graphite tag pooling optimization for peer streaming 

---

src/query/graphite/native/functions.go

Without this it was very hard to trace where the binary shifter was used (since searching for "binaryContextShifterPtrType" returned no matches against where the function was actually invoked).
This also now safely returns error if type is not expected.
```release-note
NONE
```
```documentation-note
NONE
```

[query] Add explicit checking of context shifting for Graphite evaluation

---

src/dbnode/generated/thrift/rpc.thrift
src/dbnode/network/server/tchannelthrift/node/service.go
src/dbnode/network/server/tchannelthrift/node/service_test.go

Currently, if the `FetchTagged` endpoint fails while retrieving some subset of the desired data, the error is not propagated to the top-level RPC call. This means that dashboards will only show a subset of resulting metrics to users. Additionally, there's no indication given to the caller that this has happened unless the results are egregiously wrong. This PR bubbles failures up to the top-level and returns it instead of treating the RPC call as successful.
```release-note
```
```documentation-note
```

Fail if FetchTagged partially retrieves results due to error

---

src/query/graphite/native/aggregation_functions_test.go
src/query/graphite/native/compiler.go
src/query/graphite/native/compiler_test.go
src/query/graphite/native/engine.go

Exposes graphite's compile method to make it easier to check for function validity.

[query] Expose Graphite Compile method.

---

src/query/api/v1/handler/placement/set.go
src/query/api/v1/handler/placement/set_test.go

Previously `/set` required that a placement already exists in order to
set it. This hinders operations such as preemptively creating a
placement or replacing one that had been deleted via safe APIs.
This PR allows using `/set` even if a placement didn't previously exist
at that key.
Fixes #
```release-note
Placement `/set` now works if a placement previously did not exist.
```
```documentation-note
```

[m3admin] Allow /set for new placements

---

docs/operational_guide/fileset_migrations.md

Fixes #
```release-note
```
```documentation-note
```

[docs] Add documentation on fileset migrations under operational guides

---

src/cmd/services/m3dbnode/config/config.go
src/dbnode/server/server.go

When you just set `cacheBlocksOnRetrieve: false` it was default the `fetchConcurrency` to zero as a default value, then also setting to validate the min to be 1 since below 1 will break queries (as no fetch concurrency exists and no fetch loops are spun up).
```release-note
NONE
```
```documentation-note
NONE
```

[dbnode] Better defaults for block retriever config
